
CREATE ROLE dbop createdb createrole LOGIN password 'dbop';
create role geodb_admin createdb createrole login password 'geodb_admin';
create role land_office_administration;
create role db_creation createdb;
create role role_management createrole;
create role cadastre_view;
create role cadastre_update;
create role contracting_view;
create role contracting_update;
create role reporting;
create role log_view;
create role role_manager login password 'role_manager';
grant contracting_update to role_manager;
create role role_reporting login password 'role_reporting';
grant role_management to role_manager;
grant reporting to role_reporting;
create role application_view;
create role application_update;
CREATE ROLE bucardo SUPERUSER CREATEROLE LOGIN PASSWORD 'H3718*a!';

drop role if exists s04401;
drop role if exists s04404;
drop role if exists s04407;
drop role if exists s04410;
drop role if exists s04413;
drop role if exists s04416;
drop role if exists s04419;
drop role if exists s04422;
drop role if exists s04425;
drop role if exists s04428;
drop role if exists s04431;
drop role if exists s04434;
drop role if exists s04437;
drop role if exists s04440;
drop role if exists s04443;
drop role if exists s04446;
drop role if exists s04449;

create role s04401;
create role s04404;
create role s04407;
create role s04410;
create role s04413;
create role s04416;
create role s04419;
create role s04422;
create role s04425;
create role s04428;
create role s04431;
create role s04434;
create role s04437;
create role s04440;
create role s04443;
create role s04446;
create role s04449;

drop database if exists  lm_4401;
drop database if exists  lm_4404;
drop database if exists  lm_4407;
drop database if exists  lm_4410;
drop database if exists  lm_4413;
drop database if exists  lm_4416;
drop database if exists  lm_4419;
drop database if exists  lm_4422;
drop database if exists  lm_4425;
drop database if exists  lm_4428;
drop database if exists  lm_4431;
drop database if exists  lm_4434;
drop database if exists  lm_4437;
drop database if exists  lm_4440;
drop database if exists  lm_4443;
drop database if exists  lm_4446;
drop database if exists  lm_4449;

create database lm_4401 template=template_postgis owner=dbop;
create database lm_4404 template=template_postgis owner=dbop;
create database lm_4407 template=template_postgis owner=dbop;
create database lm_4410 template=template_postgis owner=dbop;
create database lm_4413 template=template_postgis owner=dbop;
create database lm_4416 template=template_postgis owner=dbop;
create database lm_4419 template=template_postgis owner=dbop;
create database lm_4422 template=template_postgis owner=dbop;
create database lm_4425 template=template_postgis owner=dbop;
create database lm_4428 template=template_postgis owner=dbop;
create database lm_4431 template=template_postgis owner=dbop;
create database lm_4434 template=template_postgis owner=dbop;
create database lm_4437 template=template_postgis owner=dbop;
create database lm_4440 template=template_postgis owner=dbop;
create database lm_4443 template=template_postgis owner=dbop;
create database lm_4446 template=template_postgis owner=dbop;
create database lm_4449 template=template_postgis owner=dbop;

GRANT CREATE ON DATABASE lm_4401 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4404 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4407 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4410 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4413 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4416 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4419 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4422 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4425 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4428 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4431 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4434 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4437 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4440 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4443 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4440 TO geodb_admin;
GRANT CREATE ON DATABASE lm_4449 TO geodb_admin;

