DATABASE_NAME = "/lm2/settings/database_name"
HOST = "/lm2/settings/host"
PORT = "/lm2/settings/port"
USER = "/lm2/settings/user"
PASSWORD = "/lm2/settings/password"
DOCUMENT_PATH = "/lm2/settings/document_path"
WEBGIS_IP = "/lm2/settings/webgis_ip"
FTP_IP = "/lm2/settings/ftp_ip"
FTP_USER = "/lm2/settings/ftp_user"

REPOSITORY_URL = "/Qgis/plugin-repos/Mongolia/url"
REPOSITORY_ENABLED = "/Qgis/plugin-repos/Mongolia/enabled"

#Print dialog

DPI = "/plugins/lm2/print_dialog/dpi"
BUFFER = "/plugins/lm2/print_dialog/buffer"
GRID_DISTANCE = "/plugins/lm2/print_dialog/grid_distance"
GRID_OFFSET_X = "/plugins/lm2/print_dialog/grid_distance_x"
GRID_OFFSET_Y = "/plugins/lm2/print_dialog/grid_distance_y"
PARCEL_ID_FIELD = "/plugins/lm2/print_dialog/parcel_id_field"
OLD_PARCEL_ID_FIELD = "/plugins/lm2/print_dialog/old_parcel_id_field"
GEO_ID_FIELD = "/plugins/lm2/print_dialog/geo_id_field"
MAP_TITLE = "/plugins/lm2/print_dialog/map_title"
DEPARTMENT = "/plugins/lm2/print_dialog/department"
DEPARTMENT_HEAD = "/plugins/lm2/print_dialog/department_head"
ORGANISATION = "/plugins/lm2/print_dialog/organisation"
NORTH_ARROW_POSITION = "/plugins/lm2/print_dialog/north_arrow_position"
LAST_FILE_PATH = "/plugins/lm2/print_dialog/last_file_path"
