delete from data_monitoring.mt_set_monitor_parcel_monitor_point;
delete from data_monitoring.mt_monitoring_parcel_map;
delete from data_monitoring.mt_monitor_point;
delete from data_monitoring.mt_verify_planned;
delete from data_monitoring.mt_monitoring_parcel_map;
delete from data_monitoring.mt_monitoring;
delete from data_monitoring.mt_monitor_parcel;
delete from data_monitoring.mt_monitor_parcel;
