alter table codelists.cl_parcel_type add column layer_type integer;

insert into codelists.cl_parcel_type (code, description, table_name, python_model_name, php_model_name, layer_type, is_insert_state_parcel) values(1, 'Кадастрын үндсэн давхарга', 'data_soums_union.ca_parcel_tbl', 'CaParcelTbl', 'parcel/Parcel', 1, false);
insert into codelists.cl_parcel_type (code, description, table_name, python_model_name, php_model_name, layer_type, is_insert_state_parcel) values(2, 'Кадастрын ажлын давхарга', 'data_soums_union.ca_tmp_parcel', 'CaTmpParcel', 'parcel/ParcelTemp', 1, false);
insert into codelists.cl_parcel_type (code, description, table_name, python_model_name, php_model_name, layer_type, is_insert_state_parcel) values(3, 'Бэлчээр/нөхөрлөлийн хил', 'data_soums_union.ca_pasture_parcel_tbl', 'CaPastureParcelTbl', 'parcel/CaPastureParcel', 1, false);
insert into codelists.cl_parcel_type (code, description, table_name, python_model_name, php_model_name, layer_type, is_insert_state_parcel) values(4, 'Газар зохион байгуулалтын төлөвлөгөө', 'data_plan.pl_project_parcel', 'PlProjectParcel', '', 1, false);
insert into codelists.cl_parcel_type (code, description, table_name, python_model_name, php_model_name, layer_type, is_insert_state_parcel) values(5, 'Төрийн өмчийн газар', 'data_soums_union.ca_state_parcel_tbl', 'CaStateParcelTbl', '', 1, true);
insert into codelists.cl_parcel_type (code, description, table_name, python_model_name, php_model_name, layer_type, is_insert_state_parcel) values(6, 'Тусгай хэрэгцээний газар', 'data_soums_union.ca_spa_parcel_tbl', 'CaSpaParcelTbl', '', 1, false);
insert into codelists.cl_parcel_type (code, description, table_name, python_model_name, php_model_name, layer_type, is_insert_state_parcel) values(7, 'Байр зүйн зургийн давхарга нэгж талбар', '', '', '', 1, false);
insert into codelists.cl_parcel_type (code, description, table_name, python_model_name, php_model_name, layer_type, is_insert_state_parcel) values(8, 'Кадастрын үндсэн давхарга барилга', 'data_soums_union.ca_building_tbl', 'CaBuildingTbl', '', 2, false);
insert into codelists.cl_parcel_type (code, description, table_name, python_model_name, php_model_name, layer_type, is_insert_state_parcel) values(9, 'Кадастрын ажлын давхарга барилга', 'data_soums_union.ca_tmp_building', 'CaTmpBuilding', '', 2, false);
insert into codelists.cl_parcel_type (code, description, table_name, python_model_name, php_model_name, layer_type, is_insert_state_parcel) values(10, 'Байр зүйн зургийн давхарга барилга', '', '', '', 2, false);
insert into codelists.cl_parcel_type (code, description, table_name, python_model_name, php_model_name, layer_type, is_insert_state_parcel) values(11, 'Хаягийн нэгж талбар', 'data_address.ca_parcel_address_view', '', '', 1, false);
insert into codelists.cl_parcel_type (code, description, table_name, python_model_name, php_model_name, layer_type, is_insert_state_parcel) values(12, 'Хаягийн барилга, байгууламж', 'data_address.ca_building_address_view', '', '', 2, false);