# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\work\LAND_MANAGER\lm2\view\PastureSettings.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(808, 538)
        self.close_button = QtGui.QPushButton(Dialog)
        self.close_button.setGeometry(QtCore.QRect(1054, 822, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 786, 416))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.documents_tab = QtGui.QWidget()
        self.documents_tab.setObjectName(_fromUtf8("documents_tab"))
        self.groupBox_12 = QtGui.QGroupBox(self.documents_tab)
        self.groupBox_12.setGeometry(QtCore.QRect(5, 10, 766, 356))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.doc_twidget = QtGui.QTableWidget(self.groupBox_12)
        self.doc_twidget.setGeometry(QtCore.QRect(20, 40, 701, 301))
        self.doc_twidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.doc_twidget.setObjectName(_fromUtf8("doc_twidget"))
        self.doc_twidget.setColumnCount(5)
        self.doc_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(4, item)
        self.doc_twidget.horizontalHeader().setCascadingSectionResizes(False)
        self.doc_twidget.horizontalHeader().setDefaultSectionSize(120)
        self.doc_twidget.horizontalHeader().setHighlightSections(False)
        self.doc_twidget.verticalHeader().setCascadingSectionResizes(False)
        self.add_document_button = QtGui.QPushButton(self.groupBox_12)
        self.add_document_button.setGeometry(QtCore.QRect(730, 150, 31, 31))
        self.add_document_button.setObjectName(_fromUtf8("add_document_button"))
        self.remove_document_button = QtGui.QPushButton(self.groupBox_12)
        self.remove_document_button.setGeometry(QtCore.QRect(730, 190, 31, 31))
        self.remove_document_button.setObjectName(_fromUtf8("remove_document_button"))
        self.load_off_document_button = QtGui.QPushButton(self.groupBox_12)
        self.load_off_document_button.setGeometry(QtCore.QRect(730, 110, 31, 31))
        self.load_off_document_button.setObjectName(_fromUtf8("load_off_document_button"))
        self.tabWidget.addTab(self.documents_tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_10.setGeometry(QtCore.QRect(6, 3, 766, 376))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_10)
        self.label_11.setGeometry(QtCore.QRect(25, 25, 300, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.select_codelist_cbox = QtGui.QComboBox(self.groupBox_10)
        self.select_codelist_cbox.setGeometry(QtCore.QRect(20, 40, 686, 22))
        self.select_codelist_cbox.setObjectName(_fromUtf8("select_codelist_cbox"))
        self.label_12 = QtGui.QLabel(self.groupBox_10)
        self.label_12.setGeometry(QtCore.QRect(20, 70, 300, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_10)
        self.label_13.setGeometry(QtCore.QRect(30, 400, 101, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.delete_button = QtGui.QPushButton(self.groupBox_10)
        self.delete_button.setGeometry(QtCore.QRect(725, 230, 31, 31))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.add_button = QtGui.QPushButton(self.groupBox_10)
        self.add_button.setGeometry(QtCore.QRect(725, 190, 31, 31))
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.table_widget = QtGui.QTableWidget(self.groupBox_10)
        self.table_widget.setGeometry(QtCore.QRect(20, 85, 691, 281))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_widget.sizePolicy().hasHeightForWidth())
        self.table_widget.setSizePolicy(sizePolicy)
        self.table_widget.setObjectName(_fromUtf8("table_widget"))
        self.table_widget.setColumnCount(2)
        self.table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_widget.setHorizontalHeaderItem(1, item)
        self.table_widget.horizontalHeader().setDefaultSectionSize(80)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.help_button = QtGui.QPushButton(Dialog)
        self.help_button.setGeometry(QtCore.QRect(874, 822, 91, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.apply_button = QtGui.QPushButton(Dialog)
        self.apply_button.setGeometry(QtCore.QRect(974, 822, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.status_label = QtGui.QLabel(Dialog)
        self.status_label.setGeometry(QtCore.QRect(354, 827, 486, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.help_button_2 = QtGui.QPushButton(Dialog)
        self.help_button_2.setGeometry(QtCore.QRect(540, 500, 91, 23))
        self.help_button_2.setObjectName(_fromUtf8("help_button_2"))
        self.close_button_2 = QtGui.QPushButton(Dialog)
        self.close_button_2.setGeometry(QtCore.QRect(720, 500, 75, 23))
        self.close_button_2.setObjectName(_fromUtf8("close_button_2"))
        self.status_label_2 = QtGui.QLabel(Dialog)
        self.status_label_2.setGeometry(QtCore.QRect(20, 500, 486, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.status_label_2.setFont(font)
        self.status_label_2.setObjectName(_fromUtf8("status_label_2"))
        self.apply_button_2 = QtGui.QPushButton(Dialog)
        self.apply_button_2.setGeometry(QtCore.QRect(640, 500, 75, 23))
        self.apply_button_2.setObjectName(_fromUtf8("apply_button_2"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.close_button.setText(_translate("Dialog", "Close", None))
        self.groupBox_12.setTitle(_translate("Dialog", "Official documents", None))
        item = self.doc_twidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Visible", None))
        item = self.doc_twidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name", None))
        item = self.doc_twidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Description", None))
        item = self.doc_twidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Open", None))
        item = self.doc_twidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "View", None))
        self.add_document_button.setToolTip(_translate("Dialog", "Add Row", None))
        self.add_document_button.setText(_translate("Dialog", "+", None))
        self.remove_document_button.setToolTip(_translate("Dialog", "Delete Row", None))
        self.remove_document_button.setText(_translate("Dialog", "-", None))
        self.load_off_document_button.setToolTip(_translate("Dialog", "Add Row", None))
        self.load_off_document_button.setText(_translate("Dialog", "Load", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documents_tab), _translate("Dialog", "Official Documents", None))
        self.groupBox_10.setTitle(_translate("Dialog", "Codelists", None))
        self.label_11.setText(_translate("Dialog", "Select Codelist", None))
        self.label_12.setText(_translate("Dialog", "Entries", None))
        self.label_13.setText(_translate("Dialog", "Messages", None))
        self.delete_button.setToolTip(_translate("Dialog", "Delete Row", None))
        self.delete_button.setText(_translate("Dialog", "-", None))
        self.add_button.setToolTip(_translate("Dialog", "Add Row", None))
        self.add_button.setText(_translate("Dialog", "+", None))
        item = self.table_widget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Code", None))
        item = self.table_widget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Description", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Codelists", None))
        self.help_button.setText(_translate("Dialog", "?", None))
        self.apply_button.setText(_translate("Dialog", "Apply", None))
        self.status_label.setText(_translate("Dialog", "Messages", None))
        self.help_button_2.setText(_translate("Dialog", "?", None))
        self.close_button_2.setText(_translate("Dialog", "Close", None))
        self.status_label_2.setText(_translate("Dialog", "Messages", None))
        self.apply_button_2.setText(_translate("Dialog", "Apply", None))

