# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ApplicationsSpaDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ApplicationsSpaDialog(object):
    def setupUi(self, ApplicationsSpaDialog):
        ApplicationsSpaDialog.setObjectName(_fromUtf8("ApplicationsSpaDialog"))
        ApplicationsSpaDialog.resize(810, 500)
        ApplicationsSpaDialog.setMinimumSize(QtCore.QSize(810, 500))
        ApplicationsSpaDialog.setMaximumSize(QtCore.QSize(810, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2_pasture/crops.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ApplicationsSpaDialog.setWindowIcon(icon)
        ApplicationsSpaDialog.setStyleSheet(_fromUtf8(""))
        self.application_tab_widget = QtGui.QTabWidget(ApplicationsSpaDialog)
        self.application_tab_widget.setGeometry(QtCore.QRect(10, 30, 796, 431))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.application_tab_widget.sizePolicy().hasHeightForWidth())
        self.application_tab_widget.setSizePolicy(sizePolicy)
        self.application_tab_widget.setMinimumSize(QtCore.QSize(200, 0))
        self.application_tab_widget.setBaseSize(QtCore.QSize(200, 0))
        self.application_tab_widget.setStyleSheet(_fromUtf8("QTabBar::tab { width: 150px; }"))
        self.application_tab_widget.setUsesScrollButtons(True)
        self.application_tab_widget.setObjectName(_fromUtf8("application_tab_widget"))
        self.application_detail_tab = QtGui.QWidget()
        self.application_detail_tab.setObjectName(_fromUtf8("application_detail_tab"))
        self.registration_group_box = QtGui.QGroupBox(self.application_detail_tab)
        self.registration_group_box.setGeometry(QtCore.QRect(3, 10, 351, 391))
        self.registration_group_box.setObjectName(_fromUtf8("registration_group_box"))
        self.date_time_date = QtGui.QDateTimeEdit(self.registration_group_box)
        self.date_time_date.setEnabled(True)
        self.date_time_date.setGeometry(QtCore.QRect(10, 40, 171, 22))
        self.date_time_date.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.date_time_date.setCalendarPopup(True)
        self.date_time_date.setObjectName(_fromUtf8("date_time_date"))
        self.application_type_cbox = QtGui.QComboBox(self.registration_group_box)
        self.application_type_cbox.setEnabled(True)
        self.application_type_cbox.setGeometry(QtCore.QRect(10, 87, 336, 22))
        self.application_type_cbox.setObjectName(_fromUtf8("application_type_cbox"))
        self.application_num_first_edit = QtGui.QLineEdit(self.registration_group_box)
        self.application_num_first_edit.setEnabled(False)
        self.application_num_first_edit.setGeometry(QtCore.QRect(11, 133, 71, 20))
        self.application_num_first_edit.setObjectName(_fromUtf8("application_num_first_edit"))
        self.application_num_middle_edit = QtGui.QLineEdit(self.registration_group_box)
        self.application_num_middle_edit.setEnabled(False)
        self.application_num_middle_edit.setGeometry(QtCore.QRect(137, 133, 71, 20))
        self.application_num_middle_edit.setObjectName(_fromUtf8("application_num_middle_edit"))
        self.application_num_last_edit = QtGui.QLineEdit(self.registration_group_box)
        self.application_num_last_edit.setEnabled(False)
        self.application_num_last_edit.setGeometry(QtCore.QRect(221, 133, 81, 20))
        self.application_num_last_edit.setObjectName(_fromUtf8("application_num_last_edit"))
        self.label_2 = QtGui.QLabel(self.registration_group_box)
        self.label_2.setGeometry(QtCore.QRect(10, 25, 271, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.registration_group_box)
        self.label_3.setGeometry(QtCore.QRect(11, 70, 291, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.registration_group_box)
        self.label_4.setGeometry(QtCore.QRect(11, 115, 281, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.duration_request_label = QtGui.QLabel(self.registration_group_box)
        self.duration_request_label.setGeometry(QtCore.QRect(10, 250, 161, 16))
        self.duration_request_label.setObjectName(_fromUtf8("duration_request_label"))
        self.duration_approved_label = QtGui.QLabel(self.registration_group_box)
        self.duration_approved_label.setGeometry(QtCore.QRect(170, 250, 151, 16))
        self.duration_approved_label.setObjectName(_fromUtf8("duration_approved_label"))
        self.label_7 = QtGui.QLabel(self.registration_group_box)
        self.label_7.setGeometry(QtCore.QRect(10, 294, 171, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.requested_land_use_type_cbox = QtGui.QComboBox(self.registration_group_box)
        self.requested_land_use_type_cbox.setGeometry(QtCore.QRect(10, 175, 336, 22))
        self.requested_land_use_type_cbox.setObjectName(_fromUtf8("requested_land_use_type_cbox"))
        self.label_8 = QtGui.QLabel(self.registration_group_box)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 271, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.approved_year_spin_box = QtGui.QSpinBox(self.registration_group_box)
        self.approved_year_spin_box.setEnabled(False)
        self.approved_year_spin_box.setGeometry(QtCore.QRect(170, 268, 141, 24))
        self.approved_year_spin_box.setMaximum(2900)
        self.approved_year_spin_box.setProperty("value", 0)
        self.approved_year_spin_box.setObjectName(_fromUtf8("approved_year_spin_box"))
        self.requested_year_spin_box = QtGui.QSpinBox(self.registration_group_box)
        self.requested_year_spin_box.setGeometry(QtCore.QRect(10, 268, 141, 24))
        self.requested_year_spin_box.setMaximum(500)
        self.requested_year_spin_box.setProperty("value", 15)
        self.requested_year_spin_box.setObjectName(_fromUtf8("requested_year_spin_box"))
        self.remarks_text_edit = QtGui.QTextEdit(self.registration_group_box)
        self.remarks_text_edit.setGeometry(QtCore.QRect(10, 311, 301, 71))
        self.remarks_text_edit.setObjectName(_fromUtf8("remarks_text_edit"))
        self.application_num_type_edit = QtGui.QLineEdit(self.registration_group_box)
        self.application_num_type_edit.setEnabled(False)
        self.application_num_type_edit.setGeometry(QtCore.QRect(94, 133, 31, 20))
        self.application_num_type_edit.setObjectName(_fromUtf8("application_num_type_edit"))
        self.label_43 = QtGui.QLabel(self.registration_group_box)
        self.label_43.setGeometry(QtCore.QRect(84, 134, 16, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_44 = QtGui.QLabel(self.registration_group_box)
        self.label_44.setGeometry(QtCore.QRect(127, 135, 16, 16))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.registration_group_box)
        self.label_45.setGeometry(QtCore.QRect(212, 135, 16, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.approved_land_use_type_cbox = QtGui.QComboBox(self.registration_group_box)
        self.approved_land_use_type_cbox.setEnabled(False)
        self.approved_land_use_type_cbox.setGeometry(QtCore.QRect(9, 219, 336, 22))
        self.approved_land_use_type_cbox.setObjectName(_fromUtf8("approved_land_use_type_cbox"))
        self.label_16 = QtGui.QLabel(self.registration_group_box)
        self.label_16.setGeometry(QtCore.QRect(9, 204, 271, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_33 = QtGui.QLabel(self.registration_group_box)
        self.label_33.setEnabled(True)
        self.label_33.setGeometry(QtCore.QRect(201, 23, 141, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.rigth_type_cbox = QtGui.QComboBox(self.registration_group_box)
        self.rigth_type_cbox.setEnabled(True)
        self.rigth_type_cbox.setGeometry(QtCore.QRect(200, 40, 146, 22))
        self.rigth_type_cbox.setObjectName(_fromUtf8("rigth_type_cbox"))
        self.application_status_group_box = QtGui.QGroupBox(self.application_detail_tab)
        self.application_status_group_box.setGeometry(QtCore.QRect(358, 10, 430, 391))
        self.application_status_group_box.setObjectName(_fromUtf8("application_status_group_box"))
        self.label_9 = QtGui.QLabel(self.application_status_group_box)
        self.label_9.setGeometry(QtCore.QRect(10, 25, 161, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.application_status_group_box)
        self.label_10.setGeometry(QtCore.QRect(215, 75, 201, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.status_date_date = QtGui.QDateEdit(self.application_status_group_box)
        self.status_date_date.setGeometry(QtCore.QRect(10, 90, 171, 22))
        self.status_date_date.setCalendarPopup(True)
        self.status_date_date.setObjectName(_fromUtf8("status_date_date"))
        self.label_11 = QtGui.QLabel(self.application_status_group_box)
        self.label_11.setGeometry(QtCore.QRect(10, 75, 171, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.add_button = QtGui.QPushButton(self.application_status_group_box)
        self.add_button.setGeometry(QtCore.QRect(30, 140, 93, 23))
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.update_button = QtGui.QPushButton(self.application_status_group_box)
        self.update_button.setGeometry(QtCore.QRect(160, 140, 93, 23))
        self.update_button.setObjectName(_fromUtf8("update_button"))
        self.delete_button = QtGui.QPushButton(self.application_status_group_box)
        self.delete_button.setGeometry(QtCore.QRect(290, 140, 93, 23))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.application_status_twidget = QtGui.QTableWidget(self.application_status_group_box)
        self.application_status_twidget.setGeometry(QtCore.QRect(5, 190, 420, 141))
        self.application_status_twidget.setObjectName(_fromUtf8("application_status_twidget"))
        self.application_status_twidget.setColumnCount(4)
        self.application_status_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_twidget.setHorizontalHeaderItem(3, item)
        self.application_status_twidget.horizontalHeader().setDefaultSectionSize(105)
        self.status_cbox = QtGui.QComboBox(self.application_status_group_box)
        self.status_cbox.setGeometry(QtCore.QRect(10, 40, 376, 22))
        self.status_cbox.setObjectName(_fromUtf8("status_cbox"))
        self.next_officer_in_charge_cbox = QtGui.QComboBox(self.application_status_group_box)
        self.next_officer_in_charge_cbox.setGeometry(QtCore.QRect(215, 90, 171, 22))
        self.next_officer_in_charge_cbox.setObjectName(_fromUtf8("next_officer_in_charge_cbox"))
        self.application_tab_widget.addTab(self.application_detail_tab, _fromUtf8(""))
        self.applicants_tab = QtGui.QWidget()
        self.applicants_tab.setObjectName(_fromUtf8("applicants_tab"))
        self.applicants_group_box = QtGui.QGroupBox(self.applicants_tab)
        self.applicants_group_box.setGeometry(QtCore.QRect(10, 2, 761, 391))
        self.applicants_group_box.setObjectName(_fromUtf8("applicants_group_box"))
        self.appliciants_remove_button = QtGui.QPushButton(self.applicants_group_box)
        self.appliciants_remove_button.setGeometry(QtCore.QRect(610, 360, 141, 23))
        self.appliciants_remove_button.setObjectName(_fromUtf8("appliciants_remove_button"))
        self.label_5 = QtGui.QLabel(self.applicants_group_box)
        self.label_5.setGeometry(QtCore.QRect(50, 50, 101, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.personal_id_edit = QtGui.QLineEdit(self.applicants_group_box)
        self.personal_id_edit.setGeometry(QtCore.QRect(160, 49, 151, 20))
        self.personal_id_edit.setObjectName(_fromUtf8("personal_id_edit"))
        self.search_person_button = QtGui.QPushButton(self.applicants_group_box)
        self.search_person_button.setGeometry(QtCore.QRect(330, 47, 100, 23))
        self.search_person_button.setObjectName(_fromUtf8("search_person_button"))
        self.accept_person_button = QtGui.QPushButton(self.applicants_group_box)
        self.accept_person_button.setGeometry(QtCore.QRect(330, 78, 100, 23))
        self.accept_person_button.setObjectName(_fromUtf8("accept_person_button"))
        self.accept_person_edit = QtGui.QLineEdit(self.applicants_group_box)
        self.accept_person_edit.setGeometry(QtCore.QRect(50, 80, 261, 20))
        self.accept_person_edit.setObjectName(_fromUtf8("accept_person_edit"))
        self.person_type_cbox = QtGui.QComboBox(self.applicants_group_box)
        self.person_type_cbox.setGeometry(QtCore.QRect(50, 20, 379, 22))
        self.person_type_cbox.setObjectName(_fromUtf8("person_type_cbox"))
        self.application_tab_widget.addTab(self.applicants_tab, _fromUtf8(""))
        self.document_tab = QtGui.QWidget()
        self.document_tab.setObjectName(_fromUtf8("document_tab"))
        self.documents_group_box = QtGui.QGroupBox(self.document_tab)
        self.documents_group_box.setGeometry(QtCore.QRect(10, 0, 751, 401))
        self.documents_group_box.setObjectName(_fromUtf8("documents_group_box"))
        self.applicant_documents_cbox = QtGui.QComboBox(self.documents_group_box)
        self.applicant_documents_cbox.setGeometry(QtCore.QRect(260, 19, 261, 22))
        self.applicant_documents_cbox.setObjectName(_fromUtf8("applicant_documents_cbox"))
        self.label_12 = QtGui.QLabel(self.documents_group_box)
        self.label_12.setGeometry(QtCore.QRect(10, 22, 251, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.load_doc_button = QtGui.QPushButton(self.documents_group_box)
        self.load_doc_button.setGeometry(QtCore.QRect(560, 19, 141, 23))
        self.load_doc_button.setObjectName(_fromUtf8("load_doc_button"))
        self.application_tab_widget.addTab(self.document_tab, _fromUtf8(""))
        self.parcel_tab = QtGui.QWidget()
        self.parcel_tab.setObjectName(_fromUtf8("parcel_tab"))
        self.search_group_box = QtGui.QGroupBox(self.parcel_tab)
        self.search_group_box.setGeometry(QtCore.QRect(20, 1, 751, 161))
        self.search_group_box.setObjectName(_fromUtf8("search_group_box"))
        self.search_parcel_num_edit = QtGui.QLineEdit(self.search_group_box)
        self.search_parcel_num_edit.setGeometry(QtCore.QRect(40, 84, 241, 22))
        self.search_parcel_num_edit.setObjectName(_fromUtf8("search_parcel_num_edit"))
        self.found_parcel_number_edit = QtGui.QLineEdit(self.search_group_box)
        self.found_parcel_number_edit.setEnabled(False)
        self.found_parcel_number_edit.setGeometry(QtCore.QRect(40, 125, 241, 22))
        self.found_parcel_number_edit.setObjectName(_fromUtf8("found_parcel_number_edit"))
        self.search_parcel_number_button = QtGui.QPushButton(self.search_group_box)
        self.search_parcel_number_button.setGeometry(QtCore.QRect(330, 80, 93, 23))
        self.search_parcel_number_button.setObjectName(_fromUtf8("search_parcel_number_button"))
        self.accept_parcel_number_button = QtGui.QPushButton(self.search_group_box)
        self.accept_parcel_number_button.setGeometry(QtCore.QRect(330, 124, 93, 23))
        self.accept_parcel_number_button.setObjectName(_fromUtf8("accept_parcel_number_button"))
        self.label_13 = QtGui.QLabel(self.search_group_box)
        self.label_13.setGeometry(QtCore.QRect(40, 68, 241, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.search_group_box)
        self.label_14.setGeometry(QtCore.QRect(40, 108, 241, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_19 = QtGui.QLabel(self.search_group_box)
        self.label_19.setGeometry(QtCore.QRect(40, 25, 381, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.parcel_type_cbox = QtGui.QComboBox(self.search_group_box)
        self.parcel_type_cbox.setGeometry(QtCore.QRect(40, 43, 381, 22))
        self.parcel_type_cbox.setObjectName(_fromUtf8("parcel_type_cbox"))
        self.assigned_group_box = QtGui.QGroupBox(self.parcel_tab)
        self.assigned_group_box.setGeometry(QtCore.QRect(20, 164, 751, 81))
        self.assigned_group_box.setObjectName(_fromUtf8("assigned_group_box"))
        self.parcel_edit = QtGui.QLineEdit(self.assigned_group_box)
        self.parcel_edit.setEnabled(False)
        self.parcel_edit.setGeometry(QtCore.QRect(40, 40, 241, 22))
        self.parcel_edit.setObjectName(_fromUtf8("parcel_edit"))
        self.parcel_area_edit = QtGui.QLineEdit(self.assigned_group_box)
        self.parcel_area_edit.setEnabled(False)
        self.parcel_area_edit.setGeometry(QtCore.QRect(330, 40, 141, 22))
        self.parcel_area_edit.setObjectName(_fromUtf8("parcel_area_edit"))
        self.unassign_button = QtGui.QPushButton(self.assigned_group_box)
        self.unassign_button.setGeometry(QtCore.QRect(490, 40, 251, 23))
        self.unassign_button.setObjectName(_fromUtf8("unassign_button"))
        self.label_15 = QtGui.QLabel(self.assigned_group_box)
        self.label_15.setGeometry(QtCore.QRect(40, 23, 241, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_17 = QtGui.QLabel(self.assigned_group_box)
        self.label_17.setGeometry(QtCore.QRect(330, 23, 171, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.spa_gbox = QtGui.QGroupBox(self.parcel_tab)
        self.spa_gbox.setGeometry(QtCore.QRect(20, 248, 751, 121))
        self.spa_gbox.setObjectName(_fromUtf8("spa_gbox"))
        self.spa_type_cbox = QtGui.QComboBox(self.spa_gbox)
        self.spa_type_cbox.setGeometry(QtCore.QRect(40, 40, 241, 22))
        self.spa_type_cbox.setObjectName(_fromUtf8("spa_type_cbox"))
        self.label_6 = QtGui.QLabel(self.spa_gbox)
        self.label_6.setGeometry(QtCore.QRect(40, 23, 241, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_18 = QtGui.QLabel(self.spa_gbox)
        self.label_18.setGeometry(QtCore.QRect(40, 66, 241, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.spa_mood_cbox = QtGui.QComboBox(self.spa_gbox)
        self.spa_mood_cbox.setGeometry(QtCore.QRect(40, 83, 241, 22))
        self.spa_mood_cbox.setObjectName(_fromUtf8("spa_mood_cbox"))
        self.application_tab_widget.addTab(self.parcel_tab, _fromUtf8(""))
        self.tab_print = QtGui.QWidget()
        self.tab_print.setObjectName(_fromUtf8("tab_print"))
        self.groupBox_14 = QtGui.QGroupBox(self.tab_print)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 10, 751, 331))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.reg_receipt_print_button = QtGui.QPushButton(self.groupBox_14)
        self.reg_receipt_print_button.setGeometry(QtCore.QRect(80, 80, 101, 23))
        self.reg_receipt_print_button.setObjectName(_fromUtf8("reg_receipt_print_button"))
        self.app_return_button = QtGui.QPushButton(self.groupBox_14)
        self.app_return_button.setGeometry(QtCore.QRect(80, 115, 176, 23))
        self.app_return_button.setObjectName(_fromUtf8("app_return_button"))
        self.application_tab_widget.addTab(self.tab_print, _fromUtf8(""))
        self.line = QtGui.QFrame(ApplicationsSpaDialog)
        self.line.setGeometry(QtCore.QRect(0, 20, 800, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(ApplicationsSpaDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 481, 801, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label = QtGui.QLabel(ApplicationsSpaDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 236, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.help_button = QtGui.QPushButton(ApplicationsSpaDialog)
        self.help_button.setGeometry(QtCore.QRect(489, 460, 111, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.apply_button = QtGui.QPushButton(ApplicationsSpaDialog)
        self.apply_button.setGeometry(QtCore.QRect(620, 460, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.close_button = QtGui.QPushButton(ApplicationsSpaDialog)
        self.close_button.setGeometry(QtCore.QRect(710, 460, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.error_label = QtGui.QLabel(ApplicationsSpaDialog)
        self.error_label.setGeometry(QtCore.QRect(10, 463, 461, 20))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.status_label = QtGui.QLabel(ApplicationsSpaDialog)
        self.status_label.setGeometry(QtCore.QRect(10, 466, 361, 16))
        self.status_label.setText(_fromUtf8(""))
        self.status_label.setObjectName(_fromUtf8("status_label"))

        self.retranslateUi(ApplicationsSpaDialog)
        self.application_tab_widget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(ApplicationsSpaDialog)
        ApplicationsSpaDialog.setTabOrder(self.application_tab_widget, self.date_time_date)
        ApplicationsSpaDialog.setTabOrder(self.date_time_date, self.application_type_cbox)
        ApplicationsSpaDialog.setTabOrder(self.application_type_cbox, self.application_num_first_edit)
        ApplicationsSpaDialog.setTabOrder(self.application_num_first_edit, self.application_num_middle_edit)
        ApplicationsSpaDialog.setTabOrder(self.application_num_middle_edit, self.application_num_last_edit)
        ApplicationsSpaDialog.setTabOrder(self.application_num_last_edit, self.requested_land_use_type_cbox)
        ApplicationsSpaDialog.setTabOrder(self.requested_land_use_type_cbox, self.status_cbox)
        ApplicationsSpaDialog.setTabOrder(self.status_cbox, self.status_date_date)
        ApplicationsSpaDialog.setTabOrder(self.status_date_date, self.next_officer_in_charge_cbox)
        ApplicationsSpaDialog.setTabOrder(self.next_officer_in_charge_cbox, self.add_button)
        ApplicationsSpaDialog.setTabOrder(self.add_button, self.update_button)
        ApplicationsSpaDialog.setTabOrder(self.update_button, self.delete_button)
        ApplicationsSpaDialog.setTabOrder(self.delete_button, self.application_status_twidget)
        ApplicationsSpaDialog.setTabOrder(self.application_status_twidget, self.help_button)
        ApplicationsSpaDialog.setTabOrder(self.help_button, self.apply_button)
        ApplicationsSpaDialog.setTabOrder(self.apply_button, self.close_button)
        ApplicationsSpaDialog.setTabOrder(self.close_button, self.appliciants_remove_button)
        ApplicationsSpaDialog.setTabOrder(self.appliciants_remove_button, self.applicant_documents_cbox)
        ApplicationsSpaDialog.setTabOrder(self.applicant_documents_cbox, self.reg_receipt_print_button)

    def retranslateUi(self, ApplicationsSpaDialog):
        ApplicationsSpaDialog.setWindowTitle(_translate("ApplicationsSpaDialog", "Applications SPA Parcel Dialog", None))
        self.registration_group_box.setTitle(_translate("ApplicationsSpaDialog", "Registration", None))
        self.date_time_date.setDisplayFormat(_translate("ApplicationsSpaDialog", "yyyy-MM-dd, hh:mm", None))
        self.label_2.setText(_translate("ApplicationsSpaDialog", "Date,Time", None))
        self.label_3.setText(_translate("ApplicationsSpaDialog", "Application Type", None))
        self.label_4.setText(_translate("ApplicationsSpaDialog", "Application Number", None))
        self.duration_request_label.setText(_translate("ApplicationsSpaDialog", "Requested duration [year]", None))
        self.duration_approved_label.setText(_translate("ApplicationsSpaDialog", "Approved duration [year]", None))
        self.label_7.setText(_translate("ApplicationsSpaDialog", "Remarks", None))
        self.label_8.setText(_translate("ApplicationsSpaDialog", "Requested Land Use Type", None))
        self.label_43.setText(_translate("ApplicationsSpaDialog", "-", None))
        self.label_44.setText(_translate("ApplicationsSpaDialog", "-", None))
        self.label_45.setText(_translate("ApplicationsSpaDialog", "-", None))
        self.label_16.setText(_translate("ApplicationsSpaDialog", "Approved Land Use Type", None))
        self.label_33.setText(_translate("ApplicationsSpaDialog", "Rigth Type", None))
        self.application_status_group_box.setTitle(_translate("ApplicationsSpaDialog", "Application Status", None))
        self.label_9.setText(_translate("ApplicationsSpaDialog", "Status", None))
        self.label_10.setText(_translate("ApplicationsSpaDialog", "Next Officer In Charge", None))
        self.status_date_date.setDisplayFormat(_translate("ApplicationsSpaDialog", "yyyy-MM-dd", None))
        self.label_11.setText(_translate("ApplicationsSpaDialog", "Status Date", None))
        self.add_button.setText(_translate("ApplicationsSpaDialog", "Add", None))
        self.update_button.setText(_translate("ApplicationsSpaDialog", "Update", None))
        self.delete_button.setText(_translate("ApplicationsSpaDialog", "Delete", None))
        item = self.application_status_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsSpaDialog", "Status", None))
        item = self.application_status_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsSpaDialog", "Date", None))
        item = self.application_status_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsSpaDialog", "Officer in Charge", None))
        item = self.application_status_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ApplicationsSpaDialog", "Next Officer in Charge", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.application_detail_tab), _translate("ApplicationsSpaDialog", "Application Details", None))
        self.applicants_group_box.setTitle(_translate("ApplicationsSpaDialog", "Applicants", None))
        self.appliciants_remove_button.setText(_translate("ApplicationsSpaDialog", "Remove", None))
        self.label_5.setText(_translate("ApplicationsSpaDialog", "Register Number", None))
        self.search_person_button.setText(_translate("ApplicationsSpaDialog", "Find", None))
        self.accept_person_button.setText(_translate("ApplicationsSpaDialog", "Accept", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.applicants_tab), _translate("ApplicationsSpaDialog", "Applicants", None))
        self.documents_group_box.setTitle(_translate("ApplicationsSpaDialog", "Documents", None))
        self.label_12.setText(_translate("ApplicationsSpaDialog", "Select Applicants", None))
        self.load_doc_button.setText(_translate("ApplicationsSpaDialog", "Load Document", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.document_tab), _translate("ApplicationsSpaDialog", "Documents", None))
        self.search_group_box.setTitle(_translate("ApplicationsSpaDialog", "Search", None))
        self.search_parcel_number_button.setText(_translate("ApplicationsSpaDialog", "Search", None))
        self.accept_parcel_number_button.setText(_translate("ApplicationsSpaDialog", "Accept", None))
        self.label_13.setText(_translate("ApplicationsSpaDialog", "Enter Parcel Number", None))
        self.label_14.setText(_translate("ApplicationsSpaDialog", "Found:", None))
        self.label_19.setText(_translate("ApplicationsSpaDialog", "Parcel Type", None))
        self.assigned_group_box.setTitle(_translate("ApplicationsSpaDialog", "Assigned Parcel", None))
        self.unassign_button.setText(_translate("ApplicationsSpaDialog", "Unassign", None))
        self.label_15.setText(_translate("ApplicationsSpaDialog", "Parcel", None))
        self.label_17.setText(_translate("ApplicationsSpaDialog", "Parcel Area/m2/", None))
        self.spa_gbox.setTitle(_translate("ApplicationsSpaDialog", "SPA", None))
        self.label_6.setText(_translate("ApplicationsSpaDialog", "SPA Type", None))
        self.label_18.setText(_translate("ApplicationsSpaDialog", "SPA Mood", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.parcel_tab), _translate("ApplicationsSpaDialog", "Parcel", None))
        self.groupBox_14.setTitle(_translate("ApplicationsSpaDialog", "Registration Receipt", None))
        self.reg_receipt_print_button.setText(_translate("ApplicationsSpaDialog", "Print", None))
        self.app_return_button.setText(_translate("ApplicationsSpaDialog", "Response by governor", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.tab_print), _translate("ApplicationsSpaDialog", "Print", None))
        self.label.setText(_translate("ApplicationsSpaDialog", "Application", None))
        self.help_button.setText(_translate("ApplicationsSpaDialog", "?", None))
        self.apply_button.setText(_translate("ApplicationsSpaDialog", "Apply", None))
        self.close_button.setText(_translate("ApplicationsSpaDialog", "Close", None))

import resources_pasture_rc
import resources_rc
