# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ApplicationsDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ApplicationsDialog(object):
    def setupUi(self, ApplicationsDialog):
        ApplicationsDialog.setObjectName(_fromUtf8("ApplicationsDialog"))
        ApplicationsDialog.resize(810, 500)
        ApplicationsDialog.setMinimumSize(QtCore.QSize(810, 500))
        ApplicationsDialog.setMaximumSize(QtCore.QSize(810, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/application.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ApplicationsDialog.setWindowIcon(icon)
        ApplicationsDialog.setStyleSheet(_fromUtf8(""))
        self.application_tab_widget = QtGui.QTabWidget(ApplicationsDialog)
        self.application_tab_widget.setGeometry(QtCore.QRect(10, 30, 796, 431))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.application_tab_widget.sizePolicy().hasHeightForWidth())
        self.application_tab_widget.setSizePolicy(sizePolicy)
        self.application_tab_widget.setMinimumSize(QtCore.QSize(200, 0))
        self.application_tab_widget.setBaseSize(QtCore.QSize(200, 0))
        self.application_tab_widget.setStyleSheet(_fromUtf8("QTabBar::tab { width: 150px; }"))
        self.application_tab_widget.setUsesScrollButtons(True)
        self.application_tab_widget.setObjectName(_fromUtf8("application_tab_widget"))
        self.application_detail_tab = QtGui.QWidget()
        self.application_detail_tab.setObjectName(_fromUtf8("application_detail_tab"))
        self.registration_group_box = QtGui.QGroupBox(self.application_detail_tab)
        self.registration_group_box.setGeometry(QtCore.QRect(3, 10, 351, 391))
        self.registration_group_box.setObjectName(_fromUtf8("registration_group_box"))
        self.date_time_date = QtGui.QDateTimeEdit(self.registration_group_box)
        self.date_time_date.setEnabled(True)
        self.date_time_date.setGeometry(QtCore.QRect(10, 30, 181, 22))
        self.date_time_date.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.date_time_date.setCalendarPopup(True)
        self.date_time_date.setObjectName(_fromUtf8("date_time_date"))
        self.application_type_cbox = QtGui.QComboBox(self.registration_group_box)
        self.application_type_cbox.setEnabled(True)
        self.application_type_cbox.setGeometry(QtCore.QRect(10, 72, 336, 22))
        self.application_type_cbox.setObjectName(_fromUtf8("application_type_cbox"))
        self.application_num_first_edit = QtGui.QLineEdit(self.registration_group_box)
        self.application_num_first_edit.setEnabled(False)
        self.application_num_first_edit.setGeometry(QtCore.QRect(11, 117, 71, 20))
        self.application_num_first_edit.setObjectName(_fromUtf8("application_num_first_edit"))
        self.application_num_middle_edit = QtGui.QLineEdit(self.registration_group_box)
        self.application_num_middle_edit.setEnabled(False)
        self.application_num_middle_edit.setGeometry(QtCore.QRect(137, 117, 71, 20))
        self.application_num_middle_edit.setObjectName(_fromUtf8("application_num_middle_edit"))
        self.application_num_last_edit = QtGui.QLineEdit(self.registration_group_box)
        self.application_num_last_edit.setEnabled(False)
        self.application_num_last_edit.setGeometry(QtCore.QRect(221, 117, 81, 20))
        self.application_num_last_edit.setObjectName(_fromUtf8("application_num_last_edit"))
        self.label_2 = QtGui.QLabel(self.registration_group_box)
        self.label_2.setGeometry(QtCore.QRect(10, 15, 181, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.registration_group_box)
        self.label_3.setGeometry(QtCore.QRect(11, 55, 291, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.registration_group_box)
        self.label_4.setGeometry(QtCore.QRect(11, 99, 281, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.duration_request_label = QtGui.QLabel(self.registration_group_box)
        self.duration_request_label.setGeometry(QtCore.QRect(10, 234, 161, 16))
        self.duration_request_label.setObjectName(_fromUtf8("duration_request_label"))
        self.duration_approved_label = QtGui.QLabel(self.registration_group_box)
        self.duration_approved_label.setGeometry(QtCore.QRect(170, 234, 151, 16))
        self.duration_approved_label.setObjectName(_fromUtf8("duration_approved_label"))
        self.label_7 = QtGui.QLabel(self.registration_group_box)
        self.label_7.setGeometry(QtCore.QRect(10, 280, 171, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.requested_land_use_type_cbox = QtGui.QComboBox(self.registration_group_box)
        self.requested_land_use_type_cbox.setGeometry(QtCore.QRect(10, 159, 336, 22))
        self.requested_land_use_type_cbox.setObjectName(_fromUtf8("requested_land_use_type_cbox"))
        self.label_8 = QtGui.QLabel(self.registration_group_box)
        self.label_8.setGeometry(QtCore.QRect(10, 144, 271, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.approved_year_spin_box = QtGui.QSpinBox(self.registration_group_box)
        self.approved_year_spin_box.setEnabled(False)
        self.approved_year_spin_box.setGeometry(QtCore.QRect(170, 252, 141, 24))
        self.approved_year_spin_box.setMaximum(2900)
        self.approved_year_spin_box.setProperty("value", 0)
        self.approved_year_spin_box.setObjectName(_fromUtf8("approved_year_spin_box"))
        self.requested_year_spin_box = QtGui.QSpinBox(self.registration_group_box)
        self.requested_year_spin_box.setGeometry(QtCore.QRect(10, 252, 141, 24))
        self.requested_year_spin_box.setMaximum(500)
        self.requested_year_spin_box.setProperty("value", 15)
        self.requested_year_spin_box.setObjectName(_fromUtf8("requested_year_spin_box"))
        self.remarks_text_edit = QtGui.QTextEdit(self.registration_group_box)
        self.remarks_text_edit.setGeometry(QtCore.QRect(10, 301, 331, 81))
        self.remarks_text_edit.setObjectName(_fromUtf8("remarks_text_edit"))
        self.application_num_type_edit = QtGui.QLineEdit(self.registration_group_box)
        self.application_num_type_edit.setEnabled(False)
        self.application_num_type_edit.setGeometry(QtCore.QRect(94, 117, 31, 20))
        self.application_num_type_edit.setObjectName(_fromUtf8("application_num_type_edit"))
        self.label_43 = QtGui.QLabel(self.registration_group_box)
        self.label_43.setGeometry(QtCore.QRect(84, 118, 16, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_44 = QtGui.QLabel(self.registration_group_box)
        self.label_44.setGeometry(QtCore.QRect(127, 119, 16, 16))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.registration_group_box)
        self.label_45.setGeometry(QtCore.QRect(212, 119, 16, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.approved_land_use_type_cbox = QtGui.QComboBox(self.registration_group_box)
        self.approved_land_use_type_cbox.setEnabled(False)
        self.approved_land_use_type_cbox.setGeometry(QtCore.QRect(9, 203, 336, 22))
        self.approved_land_use_type_cbox.setObjectName(_fromUtf8("approved_land_use_type_cbox"))
        self.label_16 = QtGui.QLabel(self.registration_group_box)
        self.label_16.setGeometry(QtCore.QRect(9, 188, 271, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.rigth_type_cbox = QtGui.QComboBox(self.registration_group_box)
        self.rigth_type_cbox.setEnabled(True)
        self.rigth_type_cbox.setGeometry(QtCore.QRect(200, 30, 146, 22))
        self.rigth_type_cbox.setObjectName(_fromUtf8("rigth_type_cbox"))
        self.label_32 = QtGui.QLabel(self.registration_group_box)
        self.label_32.setGeometry(QtCore.QRect(201, 13, 141, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.application_status_group_box = QtGui.QGroupBox(self.application_detail_tab)
        self.application_status_group_box.setGeometry(QtCore.QRect(358, 10, 430, 391))
        self.application_status_group_box.setObjectName(_fromUtf8("application_status_group_box"))
        self.label_9 = QtGui.QLabel(self.application_status_group_box)
        self.label_9.setGeometry(QtCore.QRect(10, 15, 161, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.application_status_group_box)
        self.label_10.setGeometry(QtCore.QRect(130, 57, 251, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.status_date_date = QtGui.QDateEdit(self.application_status_group_box)
        self.status_date_date.setGeometry(QtCore.QRect(10, 72, 91, 22))
        self.status_date_date.setCalendarPopup(True)
        self.status_date_date.setObjectName(_fromUtf8("status_date_date"))
        self.label_11 = QtGui.QLabel(self.application_status_group_box)
        self.label_11.setGeometry(QtCore.QRect(10, 57, 171, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.add_button = QtGui.QPushButton(self.application_status_group_box)
        self.add_button.setGeometry(QtCore.QRect(30, 100, 93, 23))
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.update_button = QtGui.QPushButton(self.application_status_group_box)
        self.update_button.setGeometry(QtCore.QRect(160, 100, 93, 23))
        self.update_button.setObjectName(_fromUtf8("update_button"))
        self.delete_button = QtGui.QPushButton(self.application_status_group_box)
        self.delete_button.setGeometry(QtCore.QRect(290, 100, 93, 23))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.application_status_twidget = QtGui.QTableWidget(self.application_status_group_box)
        self.application_status_twidget.setGeometry(QtCore.QRect(5, 161, 420, 221))
        self.application_status_twidget.setObjectName(_fromUtf8("application_status_twidget"))
        self.application_status_twidget.setColumnCount(4)
        self.application_status_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_twidget.setHorizontalHeaderItem(3, item)
        self.application_status_twidget.horizontalHeader().setDefaultSectionSize(105)
        self.status_cbox = QtGui.QComboBox(self.application_status_group_box)
        self.status_cbox.setGeometry(QtCore.QRect(10, 30, 401, 22))
        self.status_cbox.setObjectName(_fromUtf8("status_cbox"))
        self.next_officer_in_charge_cbox = QtGui.QComboBox(self.application_status_group_box)
        self.next_officer_in_charge_cbox.setGeometry(QtCore.QRect(130, 72, 281, 22))
        self.next_officer_in_charge_cbox.setObjectName(_fromUtf8("next_officer_in_charge_cbox"))
        self.status_desc_lbl = QtGui.QLabel(self.application_status_group_box)
        self.status_desc_lbl.setGeometry(QtCore.QRect(10, 124, 411, 37))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.status_desc_lbl.setFont(font)
        self.status_desc_lbl.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 0);"))
        self.status_desc_lbl.setWordWrap(True)
        self.status_desc_lbl.setObjectName(_fromUtf8("status_desc_lbl"))
        self.application_tab_widget.addTab(self.application_detail_tab, _fromUtf8(""))
        self.applicants_tab = QtGui.QWidget()
        self.applicants_tab.setObjectName(_fromUtf8("applicants_tab"))
        self.applicants_group_box = QtGui.QGroupBox(self.applicants_tab)
        self.applicants_group_box.setGeometry(QtCore.QRect(10, 10, 761, 371))
        self.applicants_group_box.setObjectName(_fromUtf8("applicants_group_box"))
        self.appliciants_remove_button = QtGui.QPushButton(self.applicants_group_box)
        self.appliciants_remove_button.setGeometry(QtCore.QRect(610, 330, 141, 23))
        self.appliciants_remove_button.setObjectName(_fromUtf8("appliciants_remove_button"))
        self.application_tab_widget.addTab(self.applicants_tab, _fromUtf8(""))
        self.legal_representative_tab = QtGui.QWidget()
        self.legal_representative_tab.setObjectName(_fromUtf8("legal_representative_tab"))
        self.legal_representative_group_box = QtGui.QGroupBox(self.legal_representative_tab)
        self.legal_representative_group_box.setGeometry(QtCore.QRect(10, 10, 751, 381))
        self.legal_representative_group_box.setObjectName(_fromUtf8("legal_representative_group_box"))
        self.representatives_remove_button = QtGui.QPushButton(self.legal_representative_group_box)
        self.representatives_remove_button.setGeometry(QtCore.QRect(600, 350, 141, 23))
        self.representatives_remove_button.setObjectName(_fromUtf8("representatives_remove_button"))
        self.application_tab_widget.addTab(self.legal_representative_tab, _fromUtf8(""))
        self.document_tab = QtGui.QWidget()
        self.document_tab.setObjectName(_fromUtf8("document_tab"))
        self.documents_group_box = QtGui.QGroupBox(self.document_tab)
        self.documents_group_box.setGeometry(QtCore.QRect(10, 0, 771, 401))
        self.documents_group_box.setObjectName(_fromUtf8("documents_group_box"))
        self.applicant_documents_cbox = QtGui.QComboBox(self.documents_group_box)
        self.applicant_documents_cbox.setGeometry(QtCore.QRect(220, 20, 241, 22))
        self.applicant_documents_cbox.setObjectName(_fromUtf8("applicant_documents_cbox"))
        self.label_12 = QtGui.QLabel(self.documents_group_box)
        self.label_12.setGeometry(QtCore.QRect(20, 24, 181, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.load_doc_button = QtGui.QPushButton(self.documents_group_box)
        self.load_doc_button.setGeometry(QtCore.QRect(490, 20, 141, 23))
        self.load_doc_button.setObjectName(_fromUtf8("load_doc_button"))
        self.application_tab_widget.addTab(self.document_tab, _fromUtf8(""))
        self.parcel_tab = QtGui.QWidget()
        self.parcel_tab.setObjectName(_fromUtf8("parcel_tab"))
        self.search_group_box = QtGui.QGroupBox(self.parcel_tab)
        self.search_group_box.setGeometry(QtCore.QRect(10, 70, 751, 112))
        self.search_group_box.setObjectName(_fromUtf8("search_group_box"))
        self.search_parcel_num_edit = QtGui.QLineEdit(self.search_group_box)
        self.search_parcel_num_edit.setGeometry(QtCore.QRect(40, 40, 241, 22))
        self.search_parcel_num_edit.setObjectName(_fromUtf8("search_parcel_num_edit"))
        self.found_parcel_number_edit = QtGui.QLineEdit(self.search_group_box)
        self.found_parcel_number_edit.setEnabled(False)
        self.found_parcel_number_edit.setGeometry(QtCore.QRect(40, 81, 241, 22))
        self.found_parcel_number_edit.setObjectName(_fromUtf8("found_parcel_number_edit"))
        self.search_parcel_number_button = QtGui.QPushButton(self.search_group_box)
        self.search_parcel_number_button.setGeometry(QtCore.QRect(330, 36, 93, 23))
        self.search_parcel_number_button.setObjectName(_fromUtf8("search_parcel_number_button"))
        self.accept_parcel_number_button = QtGui.QPushButton(self.search_group_box)
        self.accept_parcel_number_button.setGeometry(QtCore.QRect(330, 80, 93, 23))
        self.accept_parcel_number_button.setObjectName(_fromUtf8("accept_parcel_number_button"))
        self.label_13 = QtGui.QLabel(self.search_group_box)
        self.label_13.setGeometry(QtCore.QRect(40, 25, 241, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.search_group_box)
        self.label_14.setGeometry(QtCore.QRect(40, 65, 241, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.assigned_group_box = QtGui.QGroupBox(self.parcel_tab)
        self.assigned_group_box.setGeometry(QtCore.QRect(10, 180, 751, 115))
        self.assigned_group_box.setObjectName(_fromUtf8("assigned_group_box"))
        self.parcel_edit = QtGui.QLineEdit(self.assigned_group_box)
        self.parcel_edit.setEnabled(False)
        self.parcel_edit.setGeometry(QtCore.QRect(40, 50, 241, 22))
        self.parcel_edit.setObjectName(_fromUtf8("parcel_edit"))
        self.parcel_area_edit = QtGui.QLineEdit(self.assigned_group_box)
        self.parcel_area_edit.setEnabled(False)
        self.parcel_area_edit.setGeometry(QtCore.QRect(330, 50, 141, 22))
        self.parcel_area_edit.setObjectName(_fromUtf8("parcel_area_edit"))
        self.unassign_button = QtGui.QPushButton(self.assigned_group_box)
        self.unassign_button.setGeometry(QtCore.QRect(490, 50, 251, 23))
        self.unassign_button.setObjectName(_fromUtf8("unassign_button"))
        self.label_15 = QtGui.QLabel(self.assigned_group_box)
        self.label_15.setGeometry(QtCore.QRect(40, 35, 241, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_17 = QtGui.QLabel(self.assigned_group_box)
        self.label_17.setGeometry(QtCore.QRect(330, 35, 171, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.first_time_ownership_group_box = QtGui.QGroupBox(self.parcel_tab)
        self.first_time_ownership_group_box.setGeometry(QtCore.QRect(10, 290, 751, 101))
        self.first_time_ownership_group_box.setObjectName(_fromUtf8("first_time_ownership_group_box"))
        self.paid_by_applicant_check_box = QtGui.QCheckBox(self.first_time_ownership_group_box)
        self.paid_by_applicant_check_box.setGeometry(QtCore.QRect(530, 50, 211, 20))
        self.paid_by_applicant_check_box.setObjectName(_fromUtf8("paid_by_applicant_check_box"))
        self.label_18 = QtGui.QLabel(self.first_time_ownership_group_box)
        self.label_18.setGeometry(QtCore.QRect(40, 35, 241, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.first_time_ownership_group_box)
        self.label_19.setGeometry(QtCore.QRect(330, 35, 141, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.excess_area_spin_box = QtGui.QSpinBox(self.first_time_ownership_group_box)
        self.excess_area_spin_box.setGeometry(QtCore.QRect(40, 50, 221, 24))
        self.excess_area_spin_box.setMaximum(999999)
        self.excess_area_spin_box.setSingleStep(1)
        self.excess_area_spin_box.setObjectName(_fromUtf8("excess_area_spin_box"))
        self.price_to_be_paid_spin_box = QtGui.QSpinBox(self.first_time_ownership_group_box)
        self.price_to_be_paid_spin_box.setGeometry(QtCore.QRect(330, 50, 131, 24))
        self.price_to_be_paid_spin_box.setMaximum(999999999)
        self.price_to_be_paid_spin_box.setObjectName(_fromUtf8("price_to_be_paid_spin_box"))
        self.groupBox = QtGui.QGroupBox(self.parcel_tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 751, 72))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_47 = QtGui.QLabel(self.groupBox)
        self.label_47.setGeometry(QtCore.QRect(40, 29, 250, 13))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.maintenance_case_edit = QtGui.QLineEdit(self.groupBox)
        self.maintenance_case_edit.setEnabled(False)
        self.maintenance_case_edit.setGeometry(QtCore.QRect(40, 44, 250, 20))
        self.maintenance_case_edit.setObjectName(_fromUtf8("maintenance_case_edit"))
        self.application_tab_widget.addTab(self.parcel_tab, _fromUtf8(""))
        self.change_of_co_ownership_tab = QtGui.QWidget()
        self.change_of_co_ownership_tab.setObjectName(_fromUtf8("change_of_co_ownership_tab"))
        self.groupBox_8 = QtGui.QGroupBox(self.change_of_co_ownership_tab)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 10, 771, 341))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.owners_remaining_twidget = QtGui.QTableWidget(self.groupBox_8)
        self.owners_remaining_twidget.setGeometry(QtCore.QRect(10, 40, 750, 121))
        self.owners_remaining_twidget.setMaximumSize(QtCore.QSize(751, 16777215))
        self.owners_remaining_twidget.setObjectName(_fromUtf8("owners_remaining_twidget"))
        self.owners_remaining_twidget.setColumnCount(4)
        self.owners_remaining_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.owners_remaining_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.owners_remaining_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.owners_remaining_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.owners_remaining_twidget.setHorizontalHeaderItem(3, item)
        self.owners_remaining_twidget.horizontalHeader().setDefaultSectionSize(250)
        self.owners_remaining_twidget.horizontalHeader().setMinimumSectionSize(3)
        self.owners_giving_twidget = QtGui.QTableWidget(self.groupBox_8)
        self.owners_giving_twidget.setGeometry(QtCore.QRect(10, 210, 750, 121))
        self.owners_giving_twidget.setColumnCount(3)
        self.owners_giving_twidget.setObjectName(_fromUtf8("owners_giving_twidget"))
        self.owners_giving_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.owners_giving_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.owners_giving_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.owners_giving_twidget.setHorizontalHeaderItem(2, item)
        self.owners_giving_twidget.horizontalHeader().setDefaultSectionSize(250)
        self.label_20 = QtGui.QLabel(self.groupBox_8)
        self.label_20.setGeometry(QtCore.QRect(10, 25, 491, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.groupBox_8)
        self.label_21.setGeometry(QtCore.QRect(10, 195, 411, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.down_button = QtGui.QPushButton(self.groupBox_8)
        self.down_button.setGeometry(QtCore.QRect(280, 170, 75, 23))
        self.down_button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/down_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.down_button.setIcon(icon1)
        self.down_button.setObjectName(_fromUtf8("down_button"))
        self.up_button = QtGui.QPushButton(self.groupBox_8)
        self.up_button.setGeometry(QtCore.QRect(390, 170, 75, 23))
        self.up_button.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/up_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.up_button.setIcon(icon2)
        self.up_button.setObjectName(_fromUtf8("up_button"))
        self.application_tab_widget.addTab(self.change_of_co_ownership_tab, _fromUtf8(""))
        self.mortgage_tab = QtGui.QWidget()
        self.mortgage_tab.setObjectName(_fromUtf8("mortgage_tab"))
        self.mortgage_group_box = QtGui.QGroupBox(self.mortgage_tab)
        self.mortgage_group_box.setGeometry(QtCore.QRect(10, 10, 771, 381))
        self.mortgage_group_box.setObjectName(_fromUtf8("mortgage_group_box"))
        self.mortgagee_remove_button = QtGui.QPushButton(self.mortgage_group_box)
        self.mortgagee_remove_button.setGeometry(QtCore.QRect(620, 350, 141, 23))
        self.mortgagee_remove_button.setObjectName(_fromUtf8("mortgagee_remove_button"))
        self.mortgage_start_date_edit = QtGui.QDateEdit(self.mortgage_group_box)
        self.mortgage_start_date_edit.setGeometry(QtCore.QRect(200, 22, 110, 24))
        self.mortgage_start_date_edit.setCalendarPopup(True)
        self.mortgage_start_date_edit.setObjectName(_fromUtf8("mortgage_start_date_edit"))
        self.mortgage_end_date_edit = QtGui.QDateEdit(self.mortgage_group_box)
        self.mortgage_end_date_edit.setGeometry(QtCore.QRect(200, 50, 110, 24))
        self.mortgage_end_date_edit.setCalendarPopup(True)
        self.mortgage_end_date_edit.setObjectName(_fromUtf8("mortgage_end_date_edit"))
        self.label_40 = QtGui.QLabel(self.mortgage_group_box)
        self.label_40.setGeometry(QtCore.QRect(67, 24, 124, 17))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.mortgage_group_box)
        self.label_41.setGeometry(QtCore.QRect(100, 52, 90, 17))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.mortgage_type_cbox = QtGui.QComboBox(self.mortgage_group_box)
        self.mortgage_type_cbox.setGeometry(QtCore.QRect(450, 22, 313, 22))
        self.mortgage_type_cbox.setObjectName(_fromUtf8("mortgage_type_cbox"))
        self.label_42 = QtGui.QLabel(self.mortgage_group_box)
        self.label_42.setGeometry(QtCore.QRect(327, 24, 114, 17))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.mortgage_status_cbox = QtGui.QComboBox(self.mortgage_group_box)
        self.mortgage_status_cbox.setGeometry(QtCore.QRect(450, 50, 311, 23))
        self.mortgage_status_cbox.setObjectName(_fromUtf8("mortgage_status_cbox"))
        self.label_46 = QtGui.QLabel(self.mortgage_group_box)
        self.label_46.setGeometry(QtCore.QRect(401, 53, 39, 17))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.mortgage_twidget = QtGui.QTableWidget(self.mortgage_group_box)
        self.mortgage_twidget.setGeometry(QtCore.QRect(10, 150, 751, 192))
        self.mortgage_twidget.setAcceptDrops(True)
        self.mortgage_twidget.setDragEnabled(True)
        self.mortgage_twidget.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.mortgage_twidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.mortgage_twidget.setObjectName(_fromUtf8("mortgage_twidget"))
        self.mortgage_twidget.setColumnCount(4)
        self.mortgage_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mortgage_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mortgage_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mortgage_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.mortgage_twidget.setHorizontalHeaderItem(3, item)
        self.mortgage_twidget.horizontalHeader().setMinimumSectionSize(44)
        self.mortgage_twidget.verticalHeader().setDefaultSectionSize(30)
        self.mortgage_twidget.verticalHeader().setMinimumSectionSize(25)
        self.label_35 = QtGui.QLabel(self.mortgage_group_box)
        self.label_35.setGeometry(QtCore.QRect(27, 111, 164, 17))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.mortgage_contract_no_edit = QtGui.QLineEdit(self.mortgage_group_box)
        self.mortgage_contract_no_edit.setGeometry(QtCore.QRect(200, 83, 113, 23))
        self.mortgage_contract_no_edit.setObjectName(_fromUtf8("mortgage_contract_no_edit"))
        self.label_6 = QtGui.QLabel(self.mortgage_group_box)
        self.label_6.setGeometry(QtCore.QRect(10, 85, 181, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.loan_contract_no_edit = QtGui.QLineEdit(self.mortgage_group_box)
        self.loan_contract_no_edit.setGeometry(QtCore.QRect(200, 110, 113, 23))
        self.loan_contract_no_edit.setObjectName(_fromUtf8("loan_contract_no_edit"))
        self.label_48 = QtGui.QLabel(self.mortgage_group_box)
        self.label_48.setGeometry(QtCore.QRect(341, 86, 99, 17))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.mortgage_unit_type_cbox = QtGui.QComboBox(self.mortgage_group_box)
        self.mortgage_unit_type_cbox.setGeometry(QtCore.QRect(450, 83, 311, 23))
        self.mortgage_unit_type_cbox.setObjectName(_fromUtf8("mortgage_unit_type_cbox"))
        self.label_36 = QtGui.QLabel(self.mortgage_group_box)
        self.label_36.setGeometry(QtCore.QRect(344, 111, 97, 17))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.mortgage_unit_value_sbox = QtGui.QDoubleSpinBox(self.mortgage_group_box)
        self.mortgage_unit_value_sbox.setGeometry(QtCore.QRect(450, 110, 151, 23))
        self.mortgage_unit_value_sbox.setMaximum(999999999.0)
        self.mortgage_unit_value_sbox.setObjectName(_fromUtf8("mortgage_unit_value_sbox"))
        self.label_41.raise_()
        self.mortgagee_remove_button.raise_()
        self.mortgage_start_date_edit.raise_()
        self.mortgage_end_date_edit.raise_()
        self.label_40.raise_()
        self.mortgage_type_cbox.raise_()
        self.label_42.raise_()
        self.mortgage_status_cbox.raise_()
        self.label_46.raise_()
        self.mortgage_twidget.raise_()
        self.label_35.raise_()
        self.mortgage_contract_no_edit.raise_()
        self.label_6.raise_()
        self.loan_contract_no_edit.raise_()
        self.label_48.raise_()
        self.mortgage_unit_type_cbox.raise_()
        self.label_36.raise_()
        self.mortgage_unit_value_sbox.raise_()
        self.application_tab_widget.addTab(self.mortgage_tab, _fromUtf8(""))
        self.cancel_contract_tab = QtGui.QWidget()
        self.cancel_contract_tab.setObjectName(_fromUtf8("cancel_contract_tab"))
        self.groupBox_10 = QtGui.QGroupBox(self.cancel_contract_tab)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 10, 751, 331))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.contract_to_be_cancelled_edit = QtGui.QLineEdit(self.groupBox_10)
        self.contract_to_be_cancelled_edit.setEnabled(False)
        self.contract_to_be_cancelled_edit.setGeometry(QtCore.QRect(30, 140, 250, 20))
        self.contract_to_be_cancelled_edit.setObjectName(_fromUtf8("contract_to_be_cancelled_edit"))
        self.label_22 = QtGui.QLabel(self.groupBox_10)
        self.label_22.setGeometry(QtCore.QRect(30, 40, 551, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_10)
        self.label_23.setGeometry(QtCore.QRect(30, 125, 250, 13))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox_10)
        self.label_24.setGeometry(QtCore.QRect(30, 300, 579, 13))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.contract_cancelled_num_edit = QtGui.QLineEdit(self.groupBox_10)
        self.contract_cancelled_num_edit.setEnabled(False)
        self.contract_cancelled_num_edit.setGeometry(QtCore.QRect(30, 60, 250, 20))
        self.contract_cancelled_num_edit.setObjectName(_fromUtf8("contract_cancelled_num_edit"))
        self.application_tab_widget.addTab(self.cancel_contract_tab, _fromUtf8(""))
        self.record_cancelled_tab = QtGui.QWidget()
        self.record_cancelled_tab.setObjectName(_fromUtf8("record_cancelled_tab"))
        self.record_cancelled_groupbox = QtGui.QGroupBox(self.record_cancelled_tab)
        self.record_cancelled_groupbox.setGeometry(QtCore.QRect(10, 20, 751, 331))
        self.record_cancelled_groupbox.setObjectName(_fromUtf8("record_cancelled_groupbox"))
        self.record_to_be_cancelled_edit = QtGui.QLineEdit(self.record_cancelled_groupbox)
        self.record_to_be_cancelled_edit.setEnabled(False)
        self.record_to_be_cancelled_edit.setGeometry(QtCore.QRect(30, 140, 250, 20))
        self.record_to_be_cancelled_edit.setObjectName(_fromUtf8("record_to_be_cancelled_edit"))
        self.label_72 = QtGui.QLabel(self.record_cancelled_groupbox)
        self.label_72.setGeometry(QtCore.QRect(30, 45, 551, 16))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.label_73 = QtGui.QLabel(self.record_cancelled_groupbox)
        self.label_73.setGeometry(QtCore.QRect(30, 125, 250, 13))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.label_74 = QtGui.QLabel(self.record_cancelled_groupbox)
        self.label_74.setGeometry(QtCore.QRect(30, 300, 579, 13))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.record_cancelled_num_edit = QtGui.QLineEdit(self.record_cancelled_groupbox)
        self.record_cancelled_num_edit.setEnabled(False)
        self.record_cancelled_num_edit.setGeometry(QtCore.QRect(30, 60, 250, 20))
        self.record_cancelled_num_edit.setObjectName(_fromUtf8("record_cancelled_num_edit"))
        self.application_tab_widget.addTab(self.record_cancelled_tab, _fromUtf8(""))
        self.relating_contract_tab = QtGui.QWidget()
        self.relating_contract_tab.setObjectName(_fromUtf8("relating_contract_tab"))
        self.relating_contract_groupbox = QtGui.QGroupBox(self.relating_contract_tab)
        self.relating_contract_groupbox.setGeometry(QtCore.QRect(10, 10, 761, 331))
        self.relating_contract_groupbox.setObjectName(_fromUtf8("relating_contract_groupbox"))
        self.relating_contract_edit = QtGui.QLineEdit(self.relating_contract_groupbox)
        self.relating_contract_edit.setEnabled(False)
        self.relating_contract_edit.setGeometry(QtCore.QRect(30, 140, 191, 20))
        self.relating_contract_edit.setObjectName(_fromUtf8("relating_contract_edit"))
        self.label_25 = QtGui.QLabel(self.relating_contract_groupbox)
        self.label_25.setGeometry(QtCore.QRect(30, 40, 191, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.relating_contract_groupbox)
        self.label_26.setGeometry(QtCore.QRect(30, 120, 250, 13))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.found_contract_number_edit = QtGui.QLineEdit(self.relating_contract_groupbox)
        self.found_contract_number_edit.setEnabled(False)
        self.found_contract_number_edit.setGeometry(QtCore.QRect(30, 60, 191, 20))
        self.found_contract_number_edit.setObjectName(_fromUtf8("found_contract_number_edit"))
        self.accept_relating_contract_button = QtGui.QPushButton(self.relating_contract_groupbox)
        self.accept_relating_contract_button.setGeometry(QtCore.QRect(249, 56, 93, 23))
        self.accept_relating_contract_button.setObjectName(_fromUtf8("accept_relating_contract_button"))
        self.unassign_contract_button = QtGui.QPushButton(self.relating_contract_groupbox)
        self.unassign_contract_button.setGeometry(QtCore.QRect(250, 140, 93, 23))
        self.unassign_contract_button.setObjectName(_fromUtf8("unassign_contract_button"))
        self.label_5 = QtGui.QLabel(self.relating_contract_groupbox)
        self.label_5.setGeometry(QtCore.QRect(30, 170, 661, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.contract_court_decision_label = QtGui.QLabel(self.relating_contract_groupbox)
        self.contract_court_decision_label.setGeometry(QtCore.QRect(30, 200, 391, 16))
        self.contract_court_decision_label.setObjectName(_fromUtf8("contract_court_decision_label"))
        self.contract_court_status_cbox = QtGui.QComboBox(self.relating_contract_groupbox)
        self.contract_court_status_cbox.setGeometry(QtCore.QRect(30, 220, 390, 22))
        self.contract_court_status_cbox.setObjectName(_fromUtf8("contract_court_status_cbox"))
        self.contract_court_start_date_edit = QtGui.QDateEdit(self.relating_contract_groupbox)
        self.contract_court_start_date_edit.setGeometry(QtCore.QRect(110, 257, 110, 24))
        self.contract_court_start_date_edit.setCalendarPopup(True)
        self.contract_court_start_date_edit.setObjectName(_fromUtf8("contract_court_start_date_edit"))
        self.contract_court_end_label = QtGui.QLabel(self.relating_contract_groupbox)
        self.contract_court_end_label.setGeometry(QtCore.QRect(240, 260, 62, 16))
        self.contract_court_end_label.setObjectName(_fromUtf8("contract_court_end_label"))
        self.contract_court_start_label = QtGui.QLabel(self.relating_contract_groupbox)
        self.contract_court_start_label.setGeometry(QtCore.QRect(30, 261, 71, 16))
        self.contract_court_start_label.setObjectName(_fromUtf8("contract_court_start_label"))
        self.contract_court_end_date_edit = QtGui.QDateEdit(self.relating_contract_groupbox)
        self.contract_court_end_date_edit.setGeometry(QtCore.QRect(310, 257, 110, 24))
        self.contract_court_end_date_edit.setCalendarPopup(True)
        self.contract_court_end_date_edit.setObjectName(_fromUtf8("contract_court_end_date_edit"))
        self.label_49 = QtGui.QLabel(self.relating_contract_groupbox)
        self.label_49.setGeometry(QtCore.QRect(436, 200, 130, 17))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.contract_court_decision_no_edit = QtGui.QLineEdit(self.relating_contract_groupbox)
        self.contract_court_decision_no_edit.setGeometry(QtCore.QRect(436, 220, 221, 23))
        self.contract_court_decision_no_edit.setObjectName(_fromUtf8("contract_court_decision_no_edit"))
        self.application_tab_widget.addTab(self.relating_contract_tab, _fromUtf8(""))
        self.relating_record_tab = QtGui.QWidget()
        self.relating_record_tab.setObjectName(_fromUtf8("relating_record_tab"))
        self.relating_record_groupbox = QtGui.QGroupBox(self.relating_record_tab)
        self.relating_record_groupbox.setGeometry(QtCore.QRect(0, 20, 761, 331))
        self.relating_record_groupbox.setObjectName(_fromUtf8("relating_record_groupbox"))
        self.relating_accepted_record_edit = QtGui.QLineEdit(self.relating_record_groupbox)
        self.relating_accepted_record_edit.setEnabled(False)
        self.relating_accepted_record_edit.setGeometry(QtCore.QRect(30, 140, 191, 20))
        self.relating_accepted_record_edit.setObjectName(_fromUtf8("relating_accepted_record_edit"))
        self.label_75 = QtGui.QLabel(self.relating_record_groupbox)
        self.label_75.setGeometry(QtCore.QRect(30, 45, 461, 16))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.label_76 = QtGui.QLabel(self.relating_record_groupbox)
        self.label_76.setGeometry(QtCore.QRect(30, 125, 250, 13))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.relating_record_num_edit = QtGui.QLineEdit(self.relating_record_groupbox)
        self.relating_record_num_edit.setEnabled(False)
        self.relating_record_num_edit.setGeometry(QtCore.QRect(30, 60, 191, 20))
        self.relating_record_num_edit.setObjectName(_fromUtf8("relating_record_num_edit"))
        self.unassign_record_button = QtGui.QPushButton(self.relating_record_groupbox)
        self.unassign_record_button.setGeometry(QtCore.QRect(291, 139, 93, 23))
        self.unassign_record_button.setObjectName(_fromUtf8("unassign_record_button"))
        self.accept_relating_record_button = QtGui.QPushButton(self.relating_record_groupbox)
        self.accept_relating_record_button.setGeometry(QtCore.QRect(290, 59, 93, 23))
        self.accept_relating_record_button.setObjectName(_fromUtf8("accept_relating_record_button"))
        self.record_court_status_cbox = QtGui.QComboBox(self.relating_record_groupbox)
        self.record_court_status_cbox.setGeometry(QtCore.QRect(30, 220, 390, 22))
        self.record_court_status_cbox.setObjectName(_fromUtf8("record_court_status_cbox"))
        self.record_court_decision_label = QtGui.QLabel(self.relating_record_groupbox)
        self.record_court_decision_label.setGeometry(QtCore.QRect(30, 200, 451, 16))
        self.record_court_decision_label.setObjectName(_fromUtf8("record_court_decision_label"))
        self.record_court_start_date_edit = QtGui.QDateEdit(self.relating_record_groupbox)
        self.record_court_start_date_edit.setGeometry(QtCore.QRect(110, 260, 110, 24))
        self.record_court_start_date_edit.setCalendarPopup(True)
        self.record_court_start_date_edit.setObjectName(_fromUtf8("record_court_start_date_edit"))
        self.record_court_end_label = QtGui.QLabel(self.relating_record_groupbox)
        self.record_court_end_label.setGeometry(QtCore.QRect(240, 263, 62, 16))
        self.record_court_end_label.setObjectName(_fromUtf8("record_court_end_label"))
        self.record_court_start_label = QtGui.QLabel(self.relating_record_groupbox)
        self.record_court_start_label.setGeometry(QtCore.QRect(30, 264, 71, 16))
        self.record_court_start_label.setObjectName(_fromUtf8("record_court_start_label"))
        self.record_court_end_date_edit = QtGui.QDateEdit(self.relating_record_groupbox)
        self.record_court_end_date_edit.setGeometry(QtCore.QRect(310, 260, 110, 24))
        self.record_court_end_date_edit.setCalendarPopup(True)
        self.record_court_end_date_edit.setObjectName(_fromUtf8("record_court_end_date_edit"))
        self.record_court_decision_no_edit = QtGui.QLineEdit(self.relating_record_groupbox)
        self.record_court_decision_no_edit.setGeometry(QtCore.QRect(430, 220, 221, 23))
        self.record_court_decision_no_edit.setObjectName(_fromUtf8("record_court_decision_no_edit"))
        self.label_50 = QtGui.QLabel(self.relating_record_groupbox)
        self.label_50.setGeometry(QtCore.QRect(430, 200, 130, 17))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.application_tab_widget.addTab(self.relating_record_tab, _fromUtf8(""))
        self.new_contract_tab = QtGui.QWidget()
        self.new_contract_tab.setObjectName(_fromUtf8("new_contract_tab"))
        self.groupBox_12 = QtGui.QGroupBox(self.new_contract_tab)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 10, 761, 331))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.label_27 = QtGui.QLabel(self.groupBox_12)
        self.label_27.setGeometry(QtCore.QRect(30, 85, 250, 13))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.contract_created_edit = QtGui.QLineEdit(self.groupBox_12)
        self.contract_created_edit.setEnabled(False)
        self.contract_created_edit.setGeometry(QtCore.QRect(30, 100, 250, 20))
        self.contract_created_edit.setObjectName(_fromUtf8("contract_created_edit"))
        self.label_28 = QtGui.QLabel(self.groupBox_12)
        self.label_28.setGeometry(QtCore.QRect(30, 40, 721, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.application_tab_widget.addTab(self.new_contract_tab, _fromUtf8(""))
        self.created_record_tab = QtGui.QWidget()
        self.created_record_tab.setObjectName(_fromUtf8("created_record_tab"))
        self.groupBox_15 = QtGui.QGroupBox(self.created_record_tab)
        self.groupBox_15.setGeometry(QtCore.QRect(0, 20, 761, 331))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.label_37 = QtGui.QLabel(self.groupBox_15)
        self.label_37.setGeometry(QtCore.QRect(30, 85, 250, 13))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.record_created_edit = QtGui.QLineEdit(self.groupBox_15)
        self.record_created_edit.setEnabled(False)
        self.record_created_edit.setGeometry(QtCore.QRect(30, 100, 250, 20))
        self.record_created_edit.setObjectName(_fromUtf8("record_created_edit"))
        self.label_38 = QtGui.QLabel(self.groupBox_15)
        self.label_38.setGeometry(QtCore.QRect(30, 40, 721, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.application_tab_widget.addTab(self.created_record_tab, _fromUtf8(""))
        self.transfer_tab = QtGui.QWidget()
        self.transfer_tab.setObjectName(_fromUtf8("transfer_tab"))
        self.old_right_holders_group_box = QtGui.QGroupBox(self.transfer_tab)
        self.old_right_holders_group_box.setGeometry(QtCore.QRect(10, 20, 751, 181))
        self.old_right_holders_group_box.setObjectName(_fromUtf8("old_right_holders_group_box"))
        self.label_29 = QtGui.QLabel(self.old_right_holders_group_box)
        self.label_29.setGeometry(QtCore.QRect(20, 35, 721, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.old_right_holders_twidget = QtGui.QTableWidget(self.old_right_holders_group_box)
        self.old_right_holders_twidget.setGeometry(QtCore.QRect(16, 50, 720, 121))
        self.old_right_holders_twidget.setObjectName(_fromUtf8("old_right_holders_twidget"))
        self.old_right_holders_twidget.setColumnCount(4)
        self.old_right_holders_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.old_right_holders_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.old_right_holders_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.old_right_holders_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.old_right_holders_twidget.setHorizontalHeaderItem(3, item)
        self.old_right_holders_twidget.horizontalHeader().setDefaultSectionSize(180)
        self.new_right_holder_groupbox = QtGui.QGroupBox(self.transfer_tab)
        self.new_right_holder_groupbox.setGeometry(QtCore.QRect(10, 200, 751, 191))
        self.new_right_holder_groupbox.setObjectName(_fromUtf8("new_right_holder_groupbox"))
        self.label_31 = QtGui.QLabel(self.new_right_holder_groupbox)
        self.label_31.setGeometry(QtCore.QRect(20, 22, 721, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.remove_new_right_holder_button = QtGui.QPushButton(self.new_right_holder_groupbox)
        self.remove_new_right_holder_button.setGeometry(QtCore.QRect(670, 162, 75, 23))
        self.remove_new_right_holder_button.setObjectName(_fromUtf8("remove_new_right_holder_button"))
        self.type_of_transfer_cbox = QtGui.QComboBox(self.transfer_tab)
        self.type_of_transfer_cbox.setGeometry(QtCore.QRect(371, 5, 250, 22))
        self.type_of_transfer_cbox.setObjectName(_fromUtf8("type_of_transfer_cbox"))
        self.label_39 = QtGui.QLabel(self.transfer_tab)
        self.label_39.setGeometry(QtCore.QRect(171, 8, 171, 16))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.application_tab_widget.addTab(self.transfer_tab, _fromUtf8(""))
        self.decision_tab = QtGui.QWidget()
        self.decision_tab.setObjectName(_fromUtf8("decision_tab"))
        self.groupBox_17 = QtGui.QGroupBox(self.decision_tab)
        self.groupBox_17.setGeometry(QtCore.QRect(0, 20, 761, 361))
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.decision_date_edit = QtGui.QLineEdit(self.groupBox_17)
        self.decision_date_edit.setEnabled(False)
        self.decision_date_edit.setGeometry(QtCore.QRect(10, 70, 240, 22))
        self.decision_date_edit.setObjectName(_fromUtf8("decision_date_edit"))
        self.decision_number_edit = QtGui.QLineEdit(self.groupBox_17)
        self.decision_number_edit.setEnabled(False)
        self.decision_number_edit.setGeometry(QtCore.QRect(260, 70, 240, 22))
        self.decision_number_edit.setObjectName(_fromUtf8("decision_number_edit"))
        self.label_33 = QtGui.QLabel(self.groupBox_17)
        self.label_33.setGeometry(QtCore.QRect(10, 55, 220, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.groupBox_17)
        self.label_34.setGeometry(QtCore.QRect(260, 50, 220, 20))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_30 = QtGui.QLabel(self.groupBox_17)
        self.label_30.setGeometry(QtCore.QRect(510, 55, 241, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.decision_level_edit = QtGui.QLineEdit(self.groupBox_17)
        self.decision_level_edit.setEnabled(False)
        self.decision_level_edit.setGeometry(QtCore.QRect(510, 70, 240, 22))
        self.decision_level_edit.setObjectName(_fromUtf8("decision_level_edit"))
        self.application_tab_widget.addTab(self.decision_tab, _fromUtf8(""))
        self.tab_print = QtGui.QWidget()
        self.tab_print.setObjectName(_fromUtf8("tab_print"))
        self.groupBox_14 = QtGui.QGroupBox(self.tab_print)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 10, 751, 331))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.reg_receipt_print_button = QtGui.QPushButton(self.groupBox_14)
        self.reg_receipt_print_button.setGeometry(QtCore.QRect(80, 80, 101, 23))
        self.reg_receipt_print_button.setObjectName(_fromUtf8("reg_receipt_print_button"))
        self.app_return_button = QtGui.QPushButton(self.groupBox_14)
        self.app_return_button.setGeometry(QtCore.QRect(80, 115, 176, 23))
        self.app_return_button.setObjectName(_fromUtf8("app_return_button"))
        self.application_tab_widget.addTab(self.tab_print, _fromUtf8(""))
        self.line = QtGui.QFrame(ApplicationsDialog)
        self.line.setGeometry(QtCore.QRect(0, 20, 800, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(ApplicationsDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 481, 801, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label = QtGui.QLabel(ApplicationsDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 236, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.help_button = QtGui.QPushButton(ApplicationsDialog)
        self.help_button.setGeometry(QtCore.QRect(489, 460, 111, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.apply_button = QtGui.QPushButton(ApplicationsDialog)
        self.apply_button.setGeometry(QtCore.QRect(620, 460, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.close_button = QtGui.QPushButton(ApplicationsDialog)
        self.close_button.setGeometry(QtCore.QRect(710, 460, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.status_label = QtGui.QLabel(ApplicationsDialog)
        self.status_label.setGeometry(QtCore.QRect(10, 468, 361, 16))
        self.status_label.setText(_fromUtf8(""))
        self.status_label.setObjectName(_fromUtf8("status_label"))

        self.retranslateUi(ApplicationsDialog)
        self.application_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ApplicationsDialog)
        ApplicationsDialog.setTabOrder(self.application_tab_widget, self.date_time_date)
        ApplicationsDialog.setTabOrder(self.date_time_date, self.application_type_cbox)
        ApplicationsDialog.setTabOrder(self.application_type_cbox, self.application_num_first_edit)
        ApplicationsDialog.setTabOrder(self.application_num_first_edit, self.application_num_middle_edit)
        ApplicationsDialog.setTabOrder(self.application_num_middle_edit, self.application_num_last_edit)
        ApplicationsDialog.setTabOrder(self.application_num_last_edit, self.requested_land_use_type_cbox)
        ApplicationsDialog.setTabOrder(self.requested_land_use_type_cbox, self.status_cbox)
        ApplicationsDialog.setTabOrder(self.status_cbox, self.status_date_date)
        ApplicationsDialog.setTabOrder(self.status_date_date, self.next_officer_in_charge_cbox)
        ApplicationsDialog.setTabOrder(self.next_officer_in_charge_cbox, self.add_button)
        ApplicationsDialog.setTabOrder(self.add_button, self.update_button)
        ApplicationsDialog.setTabOrder(self.update_button, self.delete_button)
        ApplicationsDialog.setTabOrder(self.delete_button, self.application_status_twidget)
        ApplicationsDialog.setTabOrder(self.application_status_twidget, self.help_button)
        ApplicationsDialog.setTabOrder(self.help_button, self.apply_button)
        ApplicationsDialog.setTabOrder(self.apply_button, self.close_button)
        ApplicationsDialog.setTabOrder(self.close_button, self.appliciants_remove_button)
        ApplicationsDialog.setTabOrder(self.appliciants_remove_button, self.representatives_remove_button)
        ApplicationsDialog.setTabOrder(self.representatives_remove_button, self.applicant_documents_cbox)
        ApplicationsDialog.setTabOrder(self.applicant_documents_cbox, self.search_parcel_num_edit)
        ApplicationsDialog.setTabOrder(self.search_parcel_num_edit, self.search_parcel_number_button)
        ApplicationsDialog.setTabOrder(self.search_parcel_number_button, self.found_parcel_number_edit)
        ApplicationsDialog.setTabOrder(self.found_parcel_number_edit, self.accept_parcel_number_button)
        ApplicationsDialog.setTabOrder(self.accept_parcel_number_button, self.parcel_edit)
        ApplicationsDialog.setTabOrder(self.parcel_edit, self.parcel_area_edit)
        ApplicationsDialog.setTabOrder(self.parcel_area_edit, self.unassign_button)
        ApplicationsDialog.setTabOrder(self.unassign_button, self.paid_by_applicant_check_box)
        ApplicationsDialog.setTabOrder(self.paid_by_applicant_check_box, self.owners_remaining_twidget)
        ApplicationsDialog.setTabOrder(self.owners_remaining_twidget, self.down_button)
        ApplicationsDialog.setTabOrder(self.down_button, self.owners_giving_twidget)
        ApplicationsDialog.setTabOrder(self.owners_giving_twidget, self.up_button)
        ApplicationsDialog.setTabOrder(self.up_button, self.mortgagee_remove_button)
        ApplicationsDialog.setTabOrder(self.mortgagee_remove_button, self.contract_cancelled_num_edit)
        ApplicationsDialog.setTabOrder(self.contract_cancelled_num_edit, self.contract_to_be_cancelled_edit)
        ApplicationsDialog.setTabOrder(self.contract_to_be_cancelled_edit, self.found_contract_number_edit)
        ApplicationsDialog.setTabOrder(self.found_contract_number_edit, self.relating_contract_edit)
        ApplicationsDialog.setTabOrder(self.relating_contract_edit, self.contract_created_edit)
        ApplicationsDialog.setTabOrder(self.contract_created_edit, self.remove_new_right_holder_button)
        ApplicationsDialog.setTabOrder(self.remove_new_right_holder_button, self.decision_date_edit)
        ApplicationsDialog.setTabOrder(self.decision_date_edit, self.decision_number_edit)
        ApplicationsDialog.setTabOrder(self.decision_number_edit, self.decision_level_edit)
        ApplicationsDialog.setTabOrder(self.decision_level_edit, self.reg_receipt_print_button)

    def retranslateUi(self, ApplicationsDialog):
        ApplicationsDialog.setWindowTitle(_translate("ApplicationsDialog", "Applications Dialog", None))
        self.registration_group_box.setTitle(_translate("ApplicationsDialog", "Registration", None))
        self.date_time_date.setDisplayFormat(_translate("ApplicationsDialog", "yyyy-MM-dd, hh:mm", None))
        self.label_2.setText(_translate("ApplicationsDialog", "Date,Time", None))
        self.label_3.setText(_translate("ApplicationsDialog", "Application Type", None))
        self.label_4.setText(_translate("ApplicationsDialog", "Application Number", None))
        self.duration_request_label.setText(_translate("ApplicationsDialog", "Requested duration [year]", None))
        self.duration_approved_label.setText(_translate("ApplicationsDialog", "Approved duration [year]", None))
        self.label_7.setText(_translate("ApplicationsDialog", "Remarks", None))
        self.label_8.setText(_translate("ApplicationsDialog", "Requested Land Use Type", None))
        self.label_43.setText(_translate("ApplicationsDialog", "-", None))
        self.label_44.setText(_translate("ApplicationsDialog", "-", None))
        self.label_45.setText(_translate("ApplicationsDialog", "-", None))
        self.label_16.setText(_translate("ApplicationsDialog", "Approved Land Use Type", None))
        self.label_32.setText(_translate("ApplicationsDialog", "Rigth Type", None))
        self.application_status_group_box.setTitle(_translate("ApplicationsDialog", "Application Status", None))
        self.label_9.setText(_translate("ApplicationsDialog", "Status", None))
        self.label_10.setText(_translate("ApplicationsDialog", "Next Officer In Charge", None))
        self.status_date_date.setDisplayFormat(_translate("ApplicationsDialog", "yyyy-MM-dd", None))
        self.label_11.setText(_translate("ApplicationsDialog", "Status Date", None))
        self.add_button.setText(_translate("ApplicationsDialog", "Add", None))
        self.update_button.setText(_translate("ApplicationsDialog", "Update", None))
        self.delete_button.setText(_translate("ApplicationsDialog", "Delete", None))
        item = self.application_status_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsDialog", "Status", None))
        item = self.application_status_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsDialog", "Date", None))
        item = self.application_status_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsDialog", "Officer in Charge", None))
        item = self.application_status_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ApplicationsDialog", "Next Officer in Charge", None))
        self.status_desc_lbl.setText(_translate("ApplicationsDialog", "Явцын тайлбар/тухайн явц дээр дарахад энд тайлбар нь гарна/", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.application_detail_tab), _translate("ApplicationsDialog", "Application Details", None))
        self.applicants_group_box.setTitle(_translate("ApplicationsDialog", "Applicants", None))
        self.appliciants_remove_button.setText(_translate("ApplicationsDialog", "Remove", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.applicants_tab), _translate("ApplicationsDialog", "Applicants", None))
        self.legal_representative_group_box.setTitle(_translate("ApplicationsDialog", "Legal Representative", None))
        self.representatives_remove_button.setText(_translate("ApplicationsDialog", "Remove", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.legal_representative_tab), _translate("ApplicationsDialog", "Legal Representative", None))
        self.documents_group_box.setTitle(_translate("ApplicationsDialog", "Documents", None))
        self.label_12.setText(_translate("ApplicationsDialog", "Select Applicants", None))
        self.load_doc_button.setText(_translate("ApplicationsDialog", "Connect to file server", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.document_tab), _translate("ApplicationsDialog", "Documents", None))
        self.search_group_box.setTitle(_translate("ApplicationsDialog", "Search", None))
        self.search_parcel_number_button.setText(_translate("ApplicationsDialog", "Search", None))
        self.accept_parcel_number_button.setText(_translate("ApplicationsDialog", "Accept", None))
        self.label_13.setText(_translate("ApplicationsDialog", "Enter Parcel Number", None))
        self.label_14.setText(_translate("ApplicationsDialog", "Found:", None))
        self.assigned_group_box.setTitle(_translate("ApplicationsDialog", "Assigned Parcel", None))
        self.unassign_button.setText(_translate("ApplicationsDialog", "Unassign", None))
        self.label_15.setText(_translate("ApplicationsDialog", "Parcel", None))
        self.label_17.setText(_translate("ApplicationsDialog", "Parcel Area", None))
        self.first_time_ownership_group_box.setTitle(_translate("ApplicationsDialog", "First Time Ownership Only", None))
        self.paid_by_applicant_check_box.setText(_translate("ApplicationsDialog", "Paid By Applicant", None))
        self.label_18.setText(_translate("ApplicationsDialog", "Excess Area [m2]", None))
        self.label_19.setText(_translate("ApplicationsDialog", "Price To Be Paid [₮J]", None))
        self.groupBox.setTitle(_translate("ApplicationsDialog", "Maintenance Case", None))
        self.label_47.setText(_translate("ApplicationsDialog", "Maintenance Case", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.parcel_tab), _translate("ApplicationsDialog", "Parcel", None))
        self.groupBox_8.setTitle(_translate("ApplicationsDialog", "Change Of Co-Ownership", None))
        item = self.owners_remaining_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsDialog", "Main", None))
        item = self.owners_remaining_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsDialog", "Personal/Company ID", None))
        item = self.owners_remaining_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsDialog", "Surname/Company", None))
        item = self.owners_remaining_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ApplicationsDialog", "First Name", None))
        item = self.owners_giving_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsDialog", "Personal/Company ID", None))
        item = self.owners_giving_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsDialog", "Surname/Company", None))
        item = self.owners_giving_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsDialog", "First Name", None))
        self.label_20.setText(_translate("ApplicationsDialog", "Owners Remaining", None))
        self.label_21.setText(_translate("ApplicationsDialog", "Owners Giving Up Co-Ownership", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.change_of_co_ownership_tab), _translate("ApplicationsDialog", "Change Of Co-Ownership", None))
        self.mortgage_group_box.setTitle(_translate("ApplicationsDialog", "Mortgagee(s)", None))
        self.mortgagee_remove_button.setText(_translate("ApplicationsDialog", "Remove", None))
        self.mortgage_start_date_edit.setDisplayFormat(_translate("ApplicationsDialog", "dd-MM-yyyy", None))
        self.mortgage_end_date_edit.setDisplayFormat(_translate("ApplicationsDialog", "dd-MM-yyyy", None))
        self.label_40.setText(_translate("ApplicationsDialog", "Барьцаалсан огноо", None))
        self.label_41.setText(_translate("ApplicationsDialog", "Дуусах огноо", None))
        self.label_42.setText(_translate("ApplicationsDialog", "Барьцааны төрөл", None))
        self.label_46.setText(_translate("ApplicationsDialog", "Төлөв", None))
        self.mortgage_twidget.setSortingEnabled(True)
        item = self.mortgage_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsDialog", "Share (0.0-1.0)", None))
        item = self.mortgage_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsDialog", "Person/Company ID", None))
        item = self.mortgage_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsDialog", "Surname/Company", None))
        item = self.mortgage_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ApplicationsDialog", "First Name", None))
        self.label_35.setText(_translate("ApplicationsDialog", "Зээлийн гэрээний дугаар", None))
        self.label_6.setText(_translate("ApplicationsDialog", "Барьцааны гэрээний дугаар", None))
        self.label_48.setText(_translate("ApplicationsDialog", "Мөнгөний нэгж", None))
        self.label_36.setText(_translate("ApplicationsDialog", "Барьцааны дүн", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.mortgage_tab), _translate("ApplicationsDialog", "Mortgagee", None))
        self.groupBox_10.setTitle(_translate("ApplicationsDialog", "Contract Cancelled", None))
        self.label_22.setText(_translate("ApplicationsDialog", "This application will cause the following contract to be cancelled", None))
        self.label_23.setText(_translate("ApplicationsDialog", "Contract To Be Cancelled", None))
        self.label_24.setText(_translate("ApplicationsDialog", "Note: The contract will only be tagged/referenced, actual cancellation needs to be done in the \"Contract\" dialog window!", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.cancel_contract_tab), _translate("ApplicationsDialog", "Contract Cancelled", None))
        self.record_cancelled_groupbox.setTitle(_translate("ApplicationsDialog", "Ownership Record Cancelled", None))
        self.label_72.setText(_translate("ApplicationsDialog", "This application will cause the following ownership record to be cancelled", None))
        self.label_73.setText(_translate("ApplicationsDialog", "Ownership Record To Be Cancelled", None))
        self.label_74.setText(_translate("ApplicationsDialog", "Note: The ownership record will only be tagged/referenced, actual cancellation needs to be done in the \"Ownership Record\" dialog window!", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.record_cancelled_tab), _translate("ApplicationsDialog", "Record Cancelled", None))
        self.relating_contract_groupbox.setTitle(_translate("ApplicationsDialog", "Relating Contract", None))
        self.label_25.setText(_translate("ApplicationsDialog", "Found Contract", None))
        self.label_26.setText(_translate("ApplicationsDialog", "Relating Contract", None))
        self.accept_relating_contract_button.setText(_translate("ApplicationsDialog", "Accept", None))
        self.unassign_contract_button.setText(_translate("ApplicationsDialog", "Unassign", None))
        self.label_5.setText(_translate("ApplicationsDialog", "Note: Contracts can be added after the assignment of the parcel", None))
        self.contract_court_decision_label.setText(_translate("ApplicationsDialog", "Court Decision", None))
        self.contract_court_start_date_edit.setDisplayFormat(_translate("ApplicationsDialog", "dd-MM-yyyy", None))
        self.contract_court_end_label.setText(_translate("ApplicationsDialog", "End", None))
        self.contract_court_start_label.setText(_translate("ApplicationsDialog", "Start", None))
        self.contract_court_end_date_edit.setDisplayFormat(_translate("ApplicationsDialog", "dd-MM-yyyy", None))
        self.label_49.setText(_translate("ApplicationsDialog", "Шийдвэрийн дугаар", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.relating_contract_tab), _translate("ApplicationsDialog", "Relating Contract", None))
        self.relating_record_groupbox.setTitle(_translate("ApplicationsDialog", "Relating Ownership Record", None))
        self.label_75.setText(_translate("ApplicationsDialog", "This application relates to the following ownership record", None))
        self.label_76.setText(_translate("ApplicationsDialog", "Relating Ownership Record", None))
        self.unassign_record_button.setText(_translate("ApplicationsDialog", "Unassign", None))
        self.accept_relating_record_button.setText(_translate("ApplicationsDialog", "Accept", None))
        self.record_court_decision_label.setText(_translate("ApplicationsDialog", "Court Decision", None))
        self.record_court_start_date_edit.setDisplayFormat(_translate("ApplicationsDialog", "dd-MM-yyyy", None))
        self.record_court_end_label.setText(_translate("ApplicationsDialog", "End", None))
        self.record_court_start_label.setText(_translate("ApplicationsDialog", "Start", None))
        self.record_court_end_date_edit.setDisplayFormat(_translate("ApplicationsDialog", "dd-MM-yyyy", None))
        self.label_50.setText(_translate("ApplicationsDialog", "Шийдвэрийн дугаар", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.relating_record_tab), _translate("ApplicationsDialog", "Relating Record", None))
        self.groupBox_12.setTitle(_translate("ApplicationsDialog", "Created Contract", None))
        self.label_27.setText(_translate("ApplicationsDialog", "Contract Created", None))
        self.label_28.setText(_translate("ApplicationsDialog", "This application will result in a new contract that is shown here for reference once created", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.new_contract_tab), _translate("ApplicationsDialog", "Contract Created", None))
        self.groupBox_15.setTitle(_translate("ApplicationsDialog", "Created Ownership Record", None))
        self.label_37.setText(_translate("ApplicationsDialog", "Ownership Record Created", None))
        self.label_38.setText(_translate("ApplicationsDialog", "This application will result in a new ownership record that is shown here for reference once created", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.created_record_tab), _translate("ApplicationsDialog", "Created Record", None))
        self.old_right_holders_group_box.setTitle(_translate("ApplicationsDialog", "From", None))
        self.label_29.setText(_translate("ApplicationsDialog", "Old Right Holder(s)", None))
        item = self.old_right_holders_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsDialog", "Share (0.0 - 1.0)", None))
        item = self.old_right_holders_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsDialog", "Personal/Company ID", None))
        item = self.old_right_holders_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsDialog", "Surname/Company", None))
        item = self.old_right_holders_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ApplicationsDialog", "First Name", None))
        self.new_right_holder_groupbox.setTitle(_translate("ApplicationsDialog", "To", None))
        self.label_31.setText(_translate("ApplicationsDialog", "New Right Holder(s)", None))
        self.remove_new_right_holder_button.setText(_translate("ApplicationsDialog", "Remove", None))
        self.label_39.setText(_translate("ApplicationsDialog", "Type Of Transfer", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.transfer_tab), _translate("ApplicationsDialog", "Transfer Of Right", None))
        self.groupBox_17.setTitle(_translate("ApplicationsDialog", "Decision", None))
        self.label_33.setText(_translate("ApplicationsDialog", "Decision Date", None))
        self.label_34.setText(_translate("ApplicationsDialog", "Decision Number", None))
        self.label_30.setText(_translate("ApplicationsDialog", "Decision Level", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.decision_tab), _translate("ApplicationsDialog", "Decision", None))
        self.groupBox_14.setTitle(_translate("ApplicationsDialog", "Registration Receipt", None))
        self.reg_receipt_print_button.setText(_translate("ApplicationsDialog", "Print", None))
        self.app_return_button.setText(_translate("ApplicationsDialog", "Response by governor", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.tab_print), _translate("ApplicationsDialog", "Print", None))
        self.label.setText(_translate("ApplicationsDialog", "Application", None))
        self.help_button.setText(_translate("ApplicationsDialog", "?", None))
        self.apply_button.setText(_translate("ApplicationsDialog", "Apply", None))
        self.close_button.setText(_translate("ApplicationsDialog", "Close", None))

import resources_rc
