# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddressNavigatorWidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AddressNavigatorWidget(object):
    def setupUi(self, AddressNavigatorWidget):
        AddressNavigatorWidget.setObjectName(_fromUtf8("AddressNavigatorWidget"))
        AddressNavigatorWidget.resize(500, 758)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddressNavigatorWidget.sizePolicy().hasHeightForWidth())
        AddressNavigatorWidget.setSizePolicy(sizePolicy)
        AddressNavigatorWidget.setMinimumSize(QtCore.QSize(500, 620))
        AddressNavigatorWidget.setMaximumSize(QtCore.QSize(500, 524287))
        AddressNavigatorWidget.setBaseSize(QtCore.QSize(440, 665))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setGeometry(QtCore.QRect(1, 0, 498, 700))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 650))
        self.scrollArea.setMaximumSize(QtCore.QSize(500, 700))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 500, 750))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 650))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 800))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.working_l1_cbox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.working_l1_cbox.setGeometry(QtCore.QRect(4, 4, 170, 22))
        self.working_l1_cbox.setObjectName(_fromUtf8("working_l1_cbox"))
        self.working_l2_cbox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.working_l2_cbox.setGeometry(QtCore.QRect(184, 4, 170, 22))
        self.working_l2_cbox.setObjectName(_fromUtf8("working_l2_cbox"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(6, 34, 466, 521))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.parcel_tab = QtGui.QWidget()
        self.parcel_tab.setObjectName(_fromUtf8("parcel_tab"))
        self.selected_parcel_load_button = QtGui.QPushButton(self.parcel_tab)
        self.selected_parcel_load_button.setGeometry(QtCore.QRect(9, 50, 221, 23))
        self.selected_parcel_load_button.setObjectName(_fromUtf8("selected_parcel_load_button"))
        self.geographic_name_edit = QtGui.QLineEdit(self.parcel_tab)
        self.geographic_name_edit.setGeometry(QtCore.QRect(10, 260, 441, 20))
        self.geographic_name_edit.setObjectName(_fromUtf8("geographic_name_edit"))
        self.label = QtGui.QLabel(self.parcel_tab)
        self.label.setGeometry(QtCore.QRect(10, 243, 74, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.khashaa_no_edit = QtGui.QLineEdit(self.parcel_tab)
        self.khashaa_no_edit.setGeometry(QtCore.QRect(10, 382, 441, 20))
        self.khashaa_no_edit.setObjectName(_fromUtf8("khashaa_no_edit"))
        self.label_2 = QtGui.QLabel(self.parcel_tab)
        self.label_2.setGeometry(QtCore.QRect(10, 365, 85, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.parcel_tab)
        self.label_3.setGeometry(QtCore.QRect(10, 291, 74, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.streets_cbox = QtGui.QComboBox(self.parcel_tab)
        self.streets_cbox.setGeometry(QtCore.QRect(10, 310, 387, 22))
        self.streets_cbox.setObjectName(_fromUtf8("streets_cbox"))
        self.str_count_sbox = QtGui.QSpinBox(self.parcel_tab)
        self.str_count_sbox.setGeometry(QtCore.QRect(403, 310, 48, 22))
        self.str_count_sbox.setProperty("value", 2)
        self.str_count_sbox.setObjectName(_fromUtf8("str_count_sbox"))
        self.layer_type_cbox = QtGui.QComboBox(self.parcel_tab)
        self.layer_type_cbox.setGeometry(QtCore.QRect(10, 20, 281, 22))
        self.layer_type_cbox.setObjectName(_fromUtf8("layer_type_cbox"))
        self.address_parcel_twidget = QtGui.QTableWidget(self.parcel_tab)
        self.address_parcel_twidget.setGeometry(QtCore.QRect(10, 80, 441, 157))
        self.address_parcel_twidget.setObjectName(_fromUtf8("address_parcel_twidget"))
        self.address_parcel_twidget.setColumnCount(3)
        self.address_parcel_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.address_parcel_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.address_parcel_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.address_parcel_twidget.setHorizontalHeaderItem(2, item)
        self.address_parcel_twidget.horizontalHeader().setDefaultSectionSize(140)
        self.selected_parcel_remove_button = QtGui.QPushButton(self.parcel_tab)
        self.selected_parcel_remove_button.setGeometry(QtCore.QRect(250, 50, 201, 23))
        self.selected_parcel_remove_button.setObjectName(_fromUtf8("selected_parcel_remove_button"))
        self.str_txt_lbl = QtGui.QLabel(self.parcel_tab)
        self.str_txt_lbl.setGeometry(QtCore.QRect(10, 351, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.str_txt_lbl.setFont(font)
        self.str_txt_lbl.setText(_fromUtf8(""))
        self.str_txt_lbl.setObjectName(_fromUtf8("str_txt_lbl"))
        self.str_txt_lbl_2 = QtGui.QLabel(self.parcel_tab)
        self.str_txt_lbl_2.setGeometry(QtCore.QRect(10, 340, 90, 13))
        self.str_txt_lbl_2.setObjectName(_fromUtf8("str_txt_lbl_2"))
        self.str_type_lbl = QtGui.QLabel(self.parcel_tab)
        self.str_type_lbl.setGeometry(QtCore.QRect(110, 339, 341, 16))
        self.str_type_lbl.setText(_fromUtf8(""))
        self.str_type_lbl.setObjectName(_fromUtf8("str_type_lbl"))
        self.str_count_lbl_3 = QtGui.QLabel(self.parcel_tab)
        self.str_count_lbl_3.setGeometry(QtCore.QRect(10, 471, 95, 13))
        self.str_count_lbl_3.setObjectName(_fromUtf8("str_count_lbl_3"))
        self.parcel_progressBar = QtGui.QProgressBar(self.parcel_tab)
        self.parcel_progressBar.setGeometry(QtCore.QRect(10, 440, 441, 23))
        self.parcel_progressBar.setProperty("value", 0)
        self.parcel_progressBar.setObjectName(_fromUtf8("parcel_progressBar"))
        self.parcel_count_lbl = QtGui.QLabel(self.parcel_tab)
        self.parcel_count_lbl.setGeometry(QtCore.QRect(110, 470, 181, 20))
        self.parcel_count_lbl.setText(_fromUtf8(""))
        self.parcel_count_lbl.setObjectName(_fromUtf8("parcel_count_lbl"))
        self.is_selected_parcels_chbox = QtGui.QCheckBox(self.parcel_tab)
        self.is_selected_parcels_chbox.setGeometry(QtCore.QRect(10, 413, 121, 17))
        self.is_selected_parcels_chbox.setObjectName(_fromUtf8("is_selected_parcels_chbox"))
        self.get_entry_parcels_button = QtGui.QPushButton(self.parcel_tab)
        self.get_entry_parcels_button.setGeometry(QtCore.QRect(130, 410, 286, 23))
        self.get_entry_parcels_button.setObjectName(_fromUtf8("get_entry_parcels_button"))
        self.tabWidget.addTab(self.parcel_tab, _fromUtf8(""))
        self.building_tab = QtGui.QWidget()
        self.building_tab.setObjectName(_fromUtf8("building_tab"))
        self.building_streets_cbox = QtGui.QComboBox(self.building_tab)
        self.building_streets_cbox.setGeometry(QtCore.QRect(10, 340, 387, 22))
        self.building_streets_cbox.setObjectName(_fromUtf8("building_streets_cbox"))
        self.building_str_count_sbox = QtGui.QSpinBox(self.building_tab)
        self.building_str_count_sbox.setGeometry(QtCore.QRect(403, 340, 48, 22))
        self.building_str_count_sbox.setProperty("value", 2)
        self.building_str_count_sbox.setObjectName(_fromUtf8("building_str_count_sbox"))
        self.str_txt_lbl_3 = QtGui.QLabel(self.building_tab)
        self.str_txt_lbl_3.setGeometry(QtCore.QRect(10, 370, 90, 13))
        self.str_txt_lbl_3.setObjectName(_fromUtf8("str_txt_lbl_3"))
        self.building_str_txt_lbl = QtGui.QLabel(self.building_tab)
        self.building_str_txt_lbl.setGeometry(QtCore.QRect(10, 381, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.building_str_txt_lbl.setFont(font)
        self.building_str_txt_lbl.setText(_fromUtf8(""))
        self.building_str_txt_lbl.setObjectName(_fromUtf8("building_str_txt_lbl"))
        self.selected_building_remove_button = QtGui.QPushButton(self.building_tab)
        self.selected_building_remove_button.setGeometry(QtCore.QRect(250, 50, 201, 23))
        self.selected_building_remove_button.setObjectName(_fromUtf8("selected_building_remove_button"))
        self.geographic_building_name_edit = QtGui.QLineEdit(self.building_tab)
        self.geographic_building_name_edit.setGeometry(QtCore.QRect(10, 290, 441, 20))
        self.geographic_building_name_edit.setObjectName(_fromUtf8("geographic_building_name_edit"))
        self.label_4 = QtGui.QLabel(self.building_tab)
        self.label_4.setGeometry(QtCore.QRect(10, 321, 74, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.building_tab)
        self.label_5.setGeometry(QtCore.QRect(10, 273, 74, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.building_no_edit = QtGui.QLineEdit(self.building_tab)
        self.building_no_edit.setGeometry(QtCore.QRect(10, 412, 441, 20))
        self.building_no_edit.setObjectName(_fromUtf8("building_no_edit"))
        self.building_layer_type_cbox = QtGui.QComboBox(self.building_tab)
        self.building_layer_type_cbox.setGeometry(QtCore.QRect(10, 20, 281, 22))
        self.building_layer_type_cbox.setObjectName(_fromUtf8("building_layer_type_cbox"))
        self.address_building_twidget = QtGui.QTableWidget(self.building_tab)
        self.address_building_twidget.setGeometry(QtCore.QRect(10, 80, 441, 141))
        self.address_building_twidget.setObjectName(_fromUtf8("address_building_twidget"))
        self.address_building_twidget.setColumnCount(3)
        self.address_building_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.address_building_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.address_building_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.address_building_twidget.setHorizontalHeaderItem(2, item)
        self.address_building_twidget.horizontalHeader().setDefaultSectionSize(140)
        self.label_6 = QtGui.QLabel(self.building_tab)
        self.label_6.setGeometry(QtCore.QRect(10, 395, 88, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.selected_building_load_button = QtGui.QPushButton(self.building_tab)
        self.selected_building_load_button.setGeometry(QtCore.QRect(9, 50, 221, 23))
        self.selected_building_load_button.setObjectName(_fromUtf8("selected_building_load_button"))
        self.building_str_type_lbl = QtGui.QLabel(self.building_tab)
        self.building_str_type_lbl.setGeometry(QtCore.QRect(110, 369, 341, 16))
        self.building_str_type_lbl.setText(_fromUtf8(""))
        self.building_str_type_lbl.setObjectName(_fromUtf8("building_str_type_lbl"))
        self.tabWidget.addTab(self.building_tab, _fromUtf8(""))
        self.street_tab = QtGui.QWidget()
        self.street_tab.setObjectName(_fromUtf8("street_tab"))
        self.selected_str_load_button = QtGui.QPushButton(self.street_tab)
        self.selected_str_load_button.setGeometry(QtCore.QRect(10, 20, 281, 23))
        self.selected_str_load_button.setObjectName(_fromUtf8("selected_str_load_button"))
        self.tabWidget_2 = QtGui.QTabWidget(self.street_tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 110, 441, 201))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.str_nodes_twidget = QtGui.QTableWidget(self.tab_3)
        self.str_nodes_twidget.setGeometry(QtCore.QRect(10, 10, 411, 151))
        self.str_nodes_twidget.setObjectName(_fromUtf8("str_nodes_twidget"))
        self.str_nodes_twidget.setColumnCount(3)
        self.str_nodes_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.str_nodes_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.str_nodes_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.str_nodes_twidget.setHorizontalHeaderItem(2, item)
        self.str_nodes_twidget.horizontalHeader().setDefaultSectionSize(133)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.street_tab)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 96, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.street_tab)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 92, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.street_tab)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 92, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.str_id_lbl = QtGui.QLabel(self.street_tab)
        self.str_id_lbl.setGeometry(QtCore.QRect(110, 49, 331, 16))
        self.str_id_lbl.setText(_fromUtf8(""))
        self.str_id_lbl.setObjectName(_fromUtf8("str_id_lbl"))
        self.str_code_lbl = QtGui.QLabel(self.street_tab)
        self.str_code_lbl.setGeometry(QtCore.QRect(110, 70, 331, 16))
        self.str_code_lbl.setText(_fromUtf8(""))
        self.str_code_lbl.setObjectName(_fromUtf8("str_code_lbl"))
        self.str_name_lbl = QtGui.QLabel(self.street_tab)
        self.str_name_lbl.setGeometry(QtCore.QRect(110, 90, 331, 16))
        self.str_name_lbl.setText(_fromUtf8(""))
        self.str_name_lbl.setObjectName(_fromUtf8("str_name_lbl"))
        self.get_str_start_button = QtGui.QPushButton(self.street_tab)
        self.get_str_start_button.setGeometry(QtCore.QRect(130, 330, 286, 23))
        self.get_str_start_button.setObjectName(_fromUtf8("get_str_start_button"))
        self.progressBar = QtGui.QProgressBar(self.street_tab)
        self.progressBar.setGeometry(QtCore.QRect(10, 360, 441, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.str_count_lbl = QtGui.QLabel(self.street_tab)
        self.str_count_lbl.setGeometry(QtCore.QRect(83, 390, 181, 20))
        self.str_count_lbl.setText(_fromUtf8(""))
        self.str_count_lbl.setObjectName(_fromUtf8("str_count_lbl"))
        self.str_count_lbl_2 = QtGui.QLabel(self.street_tab)
        self.str_count_lbl_2.setGeometry(QtCore.QRect(10, 390, 71, 20))
        self.str_count_lbl_2.setObjectName(_fromUtf8("str_count_lbl_2"))
        self.is_selected_str_chbox = QtGui.QCheckBox(self.street_tab)
        self.is_selected_str_chbox.setGeometry(QtCore.QRect(10, 333, 121, 17))
        self.is_selected_str_chbox.setObjectName(_fromUtf8("is_selected_str_chbox"))
        self.tabWidget.addTab(self.street_tab, _fromUtf8(""))
        self.address_layer_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.address_layer_button.setGeometry(QtCore.QRect(10, 618, 283, 23))
        self.address_layer_button.setObjectName(_fromUtf8("address_layer_button"))
        self.get_address_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.get_address_button.setGeometry(QtCore.QRect(10, 560, 283, 23))
        self.get_address_button.setObjectName(_fromUtf8("get_address_button"))
        self.apply_address_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.apply_address_button.setGeometry(QtCore.QRect(10, 588, 283, 23))
        self.apply_address_button.setObjectName(_fromUtf8("apply_address_button"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        AddressNavigatorWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(AddressNavigatorWidget)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AddressNavigatorWidget)

    def retranslateUi(self, AddressNavigatorWidget):
        AddressNavigatorWidget.setWindowTitle(_translate("AddressNavigatorWidget", "Selection / Filter", None))
        self.selected_parcel_load_button.setText(_translate("AddressNavigatorWidget", "Хаягийн мэдээллийн санд оруулах", None))
        self.label.setText(_translate("AddressNavigatorWidget", "Газар зүйн нэр", None))
        self.label_2.setText(_translate("AddressNavigatorWidget", "Хашааны дугаар", None))
        self.label_3.setText(_translate("AddressNavigatorWidget", "Гудамж", None))
        item = self.address_parcel_twidget.horizontalHeaderItem(0)
        item.setText(_translate("AddressNavigatorWidget", "Нэгж талбарын дугаар", None))
        item = self.address_parcel_twidget.horizontalHeaderItem(1)
        item.setText(_translate("AddressNavigatorWidget", "Давхаргын төрөл", None))
        item = self.address_parcel_twidget.horizontalHeaderItem(2)
        item.setText(_translate("AddressNavigatorWidget", "Хаягийн төлөв", None))
        self.selected_parcel_remove_button.setText(_translate("AddressNavigatorWidget", "Хаягийн мэдээллийн сангаас хасах", None))
        self.str_txt_lbl_2.setText(_translate("AddressNavigatorWidget", "Гудамжны төрөл:", None))
        self.str_count_lbl_3.setText(_translate("AddressNavigatorWidget", "Нийт нэгж талбар:", None))
        self.is_selected_parcels_chbox.setText(_translate("AddressNavigatorWidget", "Is Selected Parcel", None))
        self.get_entry_parcels_button.setText(_translate("AddressNavigatorWidget", "Орц, гарцыг автоматаар авах", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.parcel_tab), _translate("AddressNavigatorWidget", "Нэгж талбар", None))
        self.str_txt_lbl_3.setText(_translate("AddressNavigatorWidget", "Гудамжны төрөл:", None))
        self.selected_building_remove_button.setText(_translate("AddressNavigatorWidget", "Хаягийн мэдээллийн сангаас хасах", None))
        self.label_4.setText(_translate("AddressNavigatorWidget", "Гудамж", None))
        self.label_5.setText(_translate("AddressNavigatorWidget", "Газар зүйн нэр", None))
        item = self.address_building_twidget.horizontalHeaderItem(0)
        item.setText(_translate("AddressNavigatorWidget", "Барилгын дугаар", None))
        item = self.address_building_twidget.horizontalHeaderItem(1)
        item.setText(_translate("AddressNavigatorWidget", "Давхаргын төрөл", None))
        item = self.address_building_twidget.horizontalHeaderItem(2)
        item.setText(_translate("AddressNavigatorWidget", "Хаягийн төлөв", None))
        self.label_6.setText(_translate("AddressNavigatorWidget", "Барилгын дугаар", None))
        self.selected_building_load_button.setText(_translate("AddressNavigatorWidget", "Хаягийн мэдээллийн санд оруулах", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.building_tab), _translate("AddressNavigatorWidget", "Барилга", None))
        self.selected_str_load_button.setText(_translate("AddressNavigatorWidget", "Гудамжны мэдээлэл харах", None))
        item = self.str_nodes_twidget.horizontalHeaderItem(0)
        item.setText(_translate("AddressNavigatorWidget", "ID", None))
        item = self.str_nodes_twidget.horizontalHeaderItem(1)
        item.setText(_translate("AddressNavigatorWidget", "X", None))
        item = self.str_nodes_twidget.horizontalHeaderItem(2)
        item.setText(_translate("AddressNavigatorWidget", "Y", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("AddressNavigatorWidget", "Эхлэлийн Цэг", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("AddressNavigatorWidget", "Хамаарах Зам", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("AddressNavigatorWidget", "Хавсралт Материал", None))
        self.label_7.setText(_translate("AddressNavigatorWidget", "Гудамжны дугаар:", None))
        self.label_8.setText(_translate("AddressNavigatorWidget", "Гудамжны код:", None))
        self.label_9.setText(_translate("AddressNavigatorWidget", "Гудамжны нэр:", None))
        self.get_str_start_button.setText(_translate("AddressNavigatorWidget", "Суурьшлын төвөөс гудамжны эхлэлийг авах", None))
        self.str_count_lbl_2.setText(_translate("AddressNavigatorWidget", "Нийт гудамж:", None))
        self.is_selected_str_chbox.setText(_translate("AddressNavigatorWidget", "Is Selected Street", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.street_tab), _translate("AddressNavigatorWidget", "Гудамж", None))
        self.address_layer_button.setText(_translate("AddressNavigatorWidget", "Давхарга", None))
        self.get_address_button.setText(_translate("AddressNavigatorWidget", "Хаяг авах", None))
        self.apply_address_button.setText(_translate("AddressNavigatorWidget", "Хадгалах", None))

