# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ApplicationsPastureDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ApplicationsPastureDialog(object):
    def setupUi(self, ApplicationsPastureDialog):
        ApplicationsPastureDialog.setObjectName(_fromUtf8("ApplicationsPastureDialog"))
        ApplicationsPastureDialog.resize(810, 500)
        ApplicationsPastureDialog.setMinimumSize(QtCore.QSize(810, 500))
        ApplicationsPastureDialog.setMaximumSize(QtCore.QSize(810, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2_pasture/crops.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ApplicationsPastureDialog.setWindowIcon(icon)
        ApplicationsPastureDialog.setStyleSheet(_fromUtf8(""))
        self.application_tab_widget = QtGui.QTabWidget(ApplicationsPastureDialog)
        self.application_tab_widget.setGeometry(QtCore.QRect(10, 30, 796, 431))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.application_tab_widget.sizePolicy().hasHeightForWidth())
        self.application_tab_widget.setSizePolicy(sizePolicy)
        self.application_tab_widget.setMinimumSize(QtCore.QSize(200, 0))
        self.application_tab_widget.setBaseSize(QtCore.QSize(200, 0))
        self.application_tab_widget.setStyleSheet(_fromUtf8("QTabBar::tab { width: 150px; }"))
        self.application_tab_widget.setUsesScrollButtons(True)
        self.application_tab_widget.setObjectName(_fromUtf8("application_tab_widget"))
        self.application_detail_tab = QtGui.QWidget()
        self.application_detail_tab.setObjectName(_fromUtf8("application_detail_tab"))
        self.registration_group_box = QtGui.QGroupBox(self.application_detail_tab)
        self.registration_group_box.setGeometry(QtCore.QRect(3, 10, 351, 391))
        self.registration_group_box.setObjectName(_fromUtf8("registration_group_box"))
        self.date_time_date = QtGui.QDateTimeEdit(self.registration_group_box)
        self.date_time_date.setEnabled(True)
        self.date_time_date.setGeometry(QtCore.QRect(10, 40, 171, 22))
        self.date_time_date.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.date_time_date.setCalendarPopup(True)
        self.date_time_date.setObjectName(_fromUtf8("date_time_date"))
        self.application_type_cbox = QtGui.QComboBox(self.registration_group_box)
        self.application_type_cbox.setEnabled(True)
        self.application_type_cbox.setGeometry(QtCore.QRect(10, 87, 336, 22))
        self.application_type_cbox.setObjectName(_fromUtf8("application_type_cbox"))
        self.application_num_first_edit = QtGui.QLineEdit(self.registration_group_box)
        self.application_num_first_edit.setEnabled(False)
        self.application_num_first_edit.setGeometry(QtCore.QRect(11, 133, 71, 20))
        self.application_num_first_edit.setObjectName(_fromUtf8("application_num_first_edit"))
        self.application_num_middle_edit = QtGui.QLineEdit(self.registration_group_box)
        self.application_num_middle_edit.setEnabled(False)
        self.application_num_middle_edit.setGeometry(QtCore.QRect(137, 133, 71, 20))
        self.application_num_middle_edit.setObjectName(_fromUtf8("application_num_middle_edit"))
        self.application_num_last_edit = QtGui.QLineEdit(self.registration_group_box)
        self.application_num_last_edit.setEnabled(False)
        self.application_num_last_edit.setGeometry(QtCore.QRect(221, 133, 81, 20))
        self.application_num_last_edit.setObjectName(_fromUtf8("application_num_last_edit"))
        self.label_2 = QtGui.QLabel(self.registration_group_box)
        self.label_2.setGeometry(QtCore.QRect(10, 25, 271, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.registration_group_box)
        self.label_3.setGeometry(QtCore.QRect(11, 70, 291, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.registration_group_box)
        self.label_4.setGeometry(QtCore.QRect(11, 115, 281, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.duration_request_label = QtGui.QLabel(self.registration_group_box)
        self.duration_request_label.setGeometry(QtCore.QRect(10, 250, 161, 16))
        self.duration_request_label.setObjectName(_fromUtf8("duration_request_label"))
        self.duration_approved_label = QtGui.QLabel(self.registration_group_box)
        self.duration_approved_label.setGeometry(QtCore.QRect(170, 250, 151, 16))
        self.duration_approved_label.setObjectName(_fromUtf8("duration_approved_label"))
        self.label_7 = QtGui.QLabel(self.registration_group_box)
        self.label_7.setGeometry(QtCore.QRect(10, 294, 171, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.requested_land_use_type_cbox = QtGui.QComboBox(self.registration_group_box)
        self.requested_land_use_type_cbox.setGeometry(QtCore.QRect(10, 175, 336, 22))
        self.requested_land_use_type_cbox.setObjectName(_fromUtf8("requested_land_use_type_cbox"))
        self.label_8 = QtGui.QLabel(self.registration_group_box)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 271, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.approved_year_spin_box = QtGui.QSpinBox(self.registration_group_box)
        self.approved_year_spin_box.setEnabled(False)
        self.approved_year_spin_box.setGeometry(QtCore.QRect(170, 268, 141, 24))
        self.approved_year_spin_box.setMaximum(2900)
        self.approved_year_spin_box.setProperty("value", 0)
        self.approved_year_spin_box.setObjectName(_fromUtf8("approved_year_spin_box"))
        self.requested_year_spin_box = QtGui.QSpinBox(self.registration_group_box)
        self.requested_year_spin_box.setGeometry(QtCore.QRect(10, 268, 141, 24))
        self.requested_year_spin_box.setMaximum(500)
        self.requested_year_spin_box.setProperty("value", 15)
        self.requested_year_spin_box.setObjectName(_fromUtf8("requested_year_spin_box"))
        self.remarks_text_edit = QtGui.QTextEdit(self.registration_group_box)
        self.remarks_text_edit.setGeometry(QtCore.QRect(10, 311, 301, 71))
        self.remarks_text_edit.setObjectName(_fromUtf8("remarks_text_edit"))
        self.application_num_type_edit = QtGui.QLineEdit(self.registration_group_box)
        self.application_num_type_edit.setEnabled(False)
        self.application_num_type_edit.setGeometry(QtCore.QRect(94, 133, 31, 20))
        self.application_num_type_edit.setObjectName(_fromUtf8("application_num_type_edit"))
        self.label_43 = QtGui.QLabel(self.registration_group_box)
        self.label_43.setGeometry(QtCore.QRect(84, 134, 16, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_44 = QtGui.QLabel(self.registration_group_box)
        self.label_44.setGeometry(QtCore.QRect(127, 135, 16, 16))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.registration_group_box)
        self.label_45.setGeometry(QtCore.QRect(212, 135, 16, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.approved_land_use_type_cbox = QtGui.QComboBox(self.registration_group_box)
        self.approved_land_use_type_cbox.setEnabled(False)
        self.approved_land_use_type_cbox.setGeometry(QtCore.QRect(9, 219, 336, 22))
        self.approved_land_use_type_cbox.setObjectName(_fromUtf8("approved_land_use_type_cbox"))
        self.label_16 = QtGui.QLabel(self.registration_group_box)
        self.label_16.setGeometry(QtCore.QRect(9, 204, 271, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_33 = QtGui.QLabel(self.registration_group_box)
        self.label_33.setEnabled(True)
        self.label_33.setGeometry(QtCore.QRect(201, 23, 141, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.rigth_type_cbox = QtGui.QComboBox(self.registration_group_box)
        self.rigth_type_cbox.setEnabled(False)
        self.rigth_type_cbox.setGeometry(QtCore.QRect(200, 40, 146, 22))
        self.rigth_type_cbox.setObjectName(_fromUtf8("rigth_type_cbox"))
        self.application_status_group_box = QtGui.QGroupBox(self.application_detail_tab)
        self.application_status_group_box.setGeometry(QtCore.QRect(358, 10, 430, 391))
        self.application_status_group_box.setObjectName(_fromUtf8("application_status_group_box"))
        self.label_9 = QtGui.QLabel(self.application_status_group_box)
        self.label_9.setGeometry(QtCore.QRect(10, 25, 161, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.application_status_group_box)
        self.label_10.setGeometry(QtCore.QRect(215, 75, 201, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.status_date_date = QtGui.QDateEdit(self.application_status_group_box)
        self.status_date_date.setGeometry(QtCore.QRect(10, 90, 171, 22))
        self.status_date_date.setCalendarPopup(True)
        self.status_date_date.setObjectName(_fromUtf8("status_date_date"))
        self.label_11 = QtGui.QLabel(self.application_status_group_box)
        self.label_11.setGeometry(QtCore.QRect(10, 75, 171, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.add_button = QtGui.QPushButton(self.application_status_group_box)
        self.add_button.setGeometry(QtCore.QRect(30, 140, 93, 23))
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.update_button = QtGui.QPushButton(self.application_status_group_box)
        self.update_button.setGeometry(QtCore.QRect(160, 140, 93, 23))
        self.update_button.setObjectName(_fromUtf8("update_button"))
        self.delete_button = QtGui.QPushButton(self.application_status_group_box)
        self.delete_button.setGeometry(QtCore.QRect(290, 140, 93, 23))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.application_status_twidget = QtGui.QTableWidget(self.application_status_group_box)
        self.application_status_twidget.setGeometry(QtCore.QRect(5, 190, 420, 141))
        self.application_status_twidget.setObjectName(_fromUtf8("application_status_twidget"))
        self.application_status_twidget.setColumnCount(4)
        self.application_status_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_twidget.setHorizontalHeaderItem(3, item)
        self.application_status_twidget.horizontalHeader().setDefaultSectionSize(105)
        self.status_cbox = QtGui.QComboBox(self.application_status_group_box)
        self.status_cbox.setGeometry(QtCore.QRect(10, 40, 376, 22))
        self.status_cbox.setObjectName(_fromUtf8("status_cbox"))
        self.next_officer_in_charge_cbox = QtGui.QComboBox(self.application_status_group_box)
        self.next_officer_in_charge_cbox.setGeometry(QtCore.QRect(215, 90, 171, 22))
        self.next_officer_in_charge_cbox.setObjectName(_fromUtf8("next_officer_in_charge_cbox"))
        self.application_tab_widget.addTab(self.application_detail_tab, _fromUtf8(""))
        self.applicants_tab = QtGui.QWidget()
        self.applicants_tab.setObjectName(_fromUtf8("applicants_tab"))
        self.applicants_group_box = QtGui.QGroupBox(self.applicants_tab)
        self.applicants_group_box.setGeometry(QtCore.QRect(10, 2, 761, 391))
        self.applicants_group_box.setObjectName(_fromUtf8("applicants_group_box"))
        self.appliciants_remove_button = QtGui.QPushButton(self.applicants_group_box)
        self.appliciants_remove_button.setGeometry(QtCore.QRect(610, 360, 141, 23))
        self.appliciants_remove_button.setObjectName(_fromUtf8("appliciants_remove_button"))
        self.person_group_gbox = QtGui.QGroupBox(self.applicants_group_box)
        self.person_group_gbox.setGeometry(QtCore.QRect(20, 13, 271, 184))
        self.person_group_gbox.setObjectName(_fromUtf8("person_group_gbox"))
        self.leader_id_edit = QtGui.QLineEdit(self.person_group_gbox)
        self.leader_id_edit.setEnabled(False)
        self.leader_id_edit.setGeometry(QtCore.QRect(40, 77, 211, 20))
        self.leader_id_edit.setObjectName(_fromUtf8("leader_id_edit"))
        self.label_35 = QtGui.QLabel(self.person_group_gbox)
        self.label_35.setGeometry(QtCore.QRect(40, 99, 211, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.leader_name_edit = QtGui.QLineEdit(self.person_group_gbox)
        self.leader_name_edit.setEnabled(False)
        self.leader_name_edit.setGeometry(QtCore.QRect(40, 116, 211, 20))
        self.leader_name_edit.setObjectName(_fromUtf8("leader_name_edit"))
        self.pasture_group_cbox = QtGui.QComboBox(self.person_group_gbox)
        self.pasture_group_cbox.setEnabled(False)
        self.pasture_group_cbox.setGeometry(QtCore.QRect(40, 33, 211, 22))
        self.pasture_group_cbox.setObjectName(_fromUtf8("pasture_group_cbox"))
        self.is_group_checkbox = QtGui.QCheckBox(self.person_group_gbox)
        self.is_group_checkbox.setGeometry(QtCore.QRect(40, 13, 171, 17))
        self.is_group_checkbox.setObjectName(_fromUtf8("is_group_checkbox"))
        self.label_32 = QtGui.QLabel(self.person_group_gbox)
        self.label_32.setGeometry(QtCore.QRect(40, 60, 211, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.group_connect_button = QtGui.QPushButton(self.person_group_gbox)
        self.group_connect_button.setEnabled(False)
        self.group_connect_button.setGeometry(QtCore.QRect(100, 157, 75, 23))
        self.group_connect_button.setObjectName(_fromUtf8("group_connect_button"))
        self.person_gbox = QtGui.QGroupBox(self.applicants_group_box)
        self.person_gbox.setGeometry(QtCore.QRect(320, 13, 411, 184))
        self.person_gbox.setObjectName(_fromUtf8("person_gbox"))
        self.person_twidget = QtGui.QTableWidget(self.person_gbox)
        self.person_twidget.setEnabled(False)
        self.person_twidget.setGeometry(QtCore.QRect(30, 57, 341, 81))
        self.person_twidget.setObjectName(_fromUtf8("person_twidget"))
        self.person_twidget.setColumnCount(0)
        self.person_twidget.setRowCount(0)
        self.person_twidget.horizontalHeader().setDefaultSectionSize(100)
        self.person_twidget.verticalHeader().setDefaultSectionSize(30)
        self.person_twidget.verticalHeader().setMinimumSectionSize(19)
        self.person_find_button = QtGui.QPushButton(self.person_gbox)
        self.person_find_button.setEnabled(False)
        self.person_find_button.setGeometry(QtCore.QRect(280, 31, 91, 23))
        self.person_find_button.setObjectName(_fromUtf8("person_find_button"))
        self.person_id_edit = QtGui.QLineEdit(self.person_gbox)
        self.person_id_edit.setEnabled(False)
        self.person_id_edit.setGeometry(QtCore.QRect(30, 32, 113, 20))
        self.person_id_edit.setObjectName(_fromUtf8("person_id_edit"))
        self.firstname_edit = QtGui.QLineEdit(self.person_gbox)
        self.firstname_edit.setEnabled(False)
        self.firstname_edit.setGeometry(QtCore.QRect(150, 32, 121, 20))
        self.firstname_edit.setObjectName(_fromUtf8("firstname_edit"))
        self.label_36 = QtGui.QLabel(self.person_gbox)
        self.label_36.setGeometry(QtCore.QRect(150, 14, 113, 13))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.is_person_checkbox = QtGui.QCheckBox(self.person_gbox)
        self.is_person_checkbox.setGeometry(QtCore.QRect(30, 13, 121, 17))
        self.is_person_checkbox.setObjectName(_fromUtf8("is_person_checkbox"))
        self.person_connect_button = QtGui.QPushButton(self.person_gbox)
        self.person_connect_button.setEnabled(False)
        self.person_connect_button.setGeometry(QtCore.QRect(150, 157, 75, 23))
        self.person_connect_button.setObjectName(_fromUtf8("person_connect_button"))
        self.application_tab_widget.addTab(self.applicants_tab, _fromUtf8(""))
        self.document_tab = QtGui.QWidget()
        self.document_tab.setObjectName(_fromUtf8("document_tab"))
        self.documents_group_box = QtGui.QGroupBox(self.document_tab)
        self.documents_group_box.setGeometry(QtCore.QRect(10, 0, 751, 401))
        self.documents_group_box.setObjectName(_fromUtf8("documents_group_box"))
        self.applicant_documents_cbox = QtGui.QComboBox(self.documents_group_box)
        self.applicant_documents_cbox.setGeometry(QtCore.QRect(260, 19, 261, 22))
        self.applicant_documents_cbox.setObjectName(_fromUtf8("applicant_documents_cbox"))
        self.label_12 = QtGui.QLabel(self.documents_group_box)
        self.label_12.setGeometry(QtCore.QRect(10, 22, 251, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.load_doc_button = QtGui.QPushButton(self.documents_group_box)
        self.load_doc_button.setGeometry(QtCore.QRect(560, 19, 141, 23))
        self.load_doc_button.setObjectName(_fromUtf8("load_doc_button"))
        self.application_tab_widget.addTab(self.document_tab, _fromUtf8(""))
        self.boundary_tab = QtGui.QWidget()
        self.boundary_tab.setObjectName(_fromUtf8("boundary_tab"))
        self.search_group_box_2 = QtGui.QGroupBox(self.boundary_tab)
        self.search_group_box_2.setGeometry(QtCore.QRect(10, -1, 751, 64))
        self.search_group_box_2.setObjectName(_fromUtf8("search_group_box_2"))
        self.search_boundary_num_edit = QtGui.QLineEdit(self.search_group_box_2)
        self.search_boundary_num_edit.setGeometry(QtCore.QRect(220, 31, 191, 22))
        self.search_boundary_num_edit.setObjectName(_fromUtf8("search_boundary_num_edit"))
        self.find_boundary_number_button = QtGui.QPushButton(self.search_group_box_2)
        self.find_boundary_number_button.setGeometry(QtCore.QRect(441, 30, 101, 23))
        self.find_boundary_number_button.setObjectName(_fromUtf8("find_boundary_number_button"))
        self.label_15 = QtGui.QLabel(self.search_group_box_2)
        self.label_15.setGeometry(QtCore.QRect(220, 16, 241, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.bag_boundary_cbox = QtGui.QComboBox(self.search_group_box_2)
        self.bag_boundary_cbox.setGeometry(QtCore.QRect(10, 31, 191, 22))
        self.bag_boundary_cbox.setObjectName(_fromUtf8("bag_boundary_cbox"))
        self.label_17 = QtGui.QLabel(self.search_group_box_2)
        self.label_17.setGeometry(QtCore.QRect(10, 15, 181, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.boundary_remove_button = QtGui.QPushButton(self.boundary_tab)
        self.boundary_remove_button.setGeometry(QtCore.QRect(380, 219, 81, 31))
        self.boundary_remove_button.setObjectName(_fromUtf8("boundary_remove_button"))
        self.assigned_group_box_3 = QtGui.QGroupBox(self.boundary_tab)
        self.assigned_group_box_3.setGeometry(QtCore.QRect(10, 64, 751, 151))
        self.assigned_group_box_3.setObjectName(_fromUtf8("assigned_group_box_3"))
        self.result_boundary_twidget = QtGui.QTableWidget(self.assigned_group_box_3)
        self.result_boundary_twidget.setGeometry(QtCore.QRect(10, 20, 731, 121))
        self.result_boundary_twidget.setObjectName(_fromUtf8("result_boundary_twidget"))
        self.result_boundary_twidget.setColumnCount(3)
        self.result_boundary_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.result_boundary_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.result_boundary_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.result_boundary_twidget.setHorizontalHeaderItem(2, item)
        self.boundary_add_button = QtGui.QPushButton(self.boundary_tab)
        self.boundary_add_button.setGeometry(QtCore.QRect(280, 219, 81, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boundary_add_button.sizePolicy().hasHeightForWidth())
        self.boundary_add_button.setSizePolicy(sizePolicy)
        self.boundary_add_button.setBaseSize(QtCore.QSize(0, 0))
        self.boundary_add_button.setObjectName(_fromUtf8("boundary_add_button"))
        self.assigned_group_box_4 = QtGui.QGroupBox(self.boundary_tab)
        self.assigned_group_box_4.setGeometry(QtCore.QRect(10, 250, 751, 151))
        self.assigned_group_box_4.setObjectName(_fromUtf8("assigned_group_box_4"))
        self.assigned_boundary_twidget = QtGui.QTableWidget(self.assigned_group_box_4)
        self.assigned_boundary_twidget.setGeometry(QtCore.QRect(10, 20, 731, 121))
        self.assigned_boundary_twidget.setObjectName(_fromUtf8("assigned_boundary_twidget"))
        self.assigned_boundary_twidget.setColumnCount(3)
        self.assigned_boundary_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.assigned_boundary_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_boundary_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_boundary_twidget.setHorizontalHeaderItem(2, item)
        self.application_tab_widget.addTab(self.boundary_tab, _fromUtf8(""))
        self.parcel_tab = QtGui.QWidget()
        self.parcel_tab.setObjectName(_fromUtf8("parcel_tab"))
        self.search_group_box = QtGui.QGroupBox(self.parcel_tab)
        self.search_group_box.setGeometry(QtCore.QRect(10, 0, 771, 64))
        self.search_group_box.setObjectName(_fromUtf8("search_group_box"))
        self.search_parcel_num_edit = QtGui.QLineEdit(self.search_group_box)
        self.search_parcel_num_edit.setGeometry(QtCore.QRect(220, 31, 191, 22))
        self.search_parcel_num_edit.setObjectName(_fromUtf8("search_parcel_num_edit"))
        self.find_parcel_number_button = QtGui.QPushButton(self.search_group_box)
        self.find_parcel_number_button.setGeometry(QtCore.QRect(441, 30, 101, 23))
        self.find_parcel_number_button.setObjectName(_fromUtf8("find_parcel_number_button"))
        self.label_13 = QtGui.QLabel(self.search_group_box)
        self.label_13.setGeometry(QtCore.QRect(220, 16, 241, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.bag_parcel_cbox = QtGui.QComboBox(self.search_group_box)
        self.bag_parcel_cbox.setGeometry(QtCore.QRect(10, 31, 191, 22))
        self.bag_parcel_cbox.setObjectName(_fromUtf8("bag_parcel_cbox"))
        self.label_14 = QtGui.QLabel(self.search_group_box)
        self.label_14.setGeometry(QtCore.QRect(10, 15, 181, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.assigned_group_box = QtGui.QGroupBox(self.parcel_tab)
        self.assigned_group_box.setGeometry(QtCore.QRect(10, 65, 771, 151))
        self.assigned_group_box.setObjectName(_fromUtf8("assigned_group_box"))
        self.result_parcel_twidget = QtGui.QTableWidget(self.assigned_group_box)
        self.result_parcel_twidget.setGeometry(QtCore.QRect(10, 20, 751, 121))
        self.result_parcel_twidget.setObjectName(_fromUtf8("result_parcel_twidget"))
        self.result_parcel_twidget.setColumnCount(3)
        self.result_parcel_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.result_parcel_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.result_parcel_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.result_parcel_twidget.setHorizontalHeaderItem(2, item)
        self.parcel_add_button = QtGui.QPushButton(self.parcel_tab)
        self.parcel_add_button.setGeometry(QtCore.QRect(280, 220, 81, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parcel_add_button.sizePolicy().hasHeightForWidth())
        self.parcel_add_button.setSizePolicy(sizePolicy)
        self.parcel_add_button.setBaseSize(QtCore.QSize(0, 0))
        self.parcel_add_button.setObjectName(_fromUtf8("parcel_add_button"))
        self.parcel_remove_button = QtGui.QPushButton(self.parcel_tab)
        self.parcel_remove_button.setGeometry(QtCore.QRect(380, 220, 81, 31))
        self.parcel_remove_button.setObjectName(_fromUtf8("parcel_remove_button"))
        self.assigned_group_box_2 = QtGui.QGroupBox(self.parcel_tab)
        self.assigned_group_box_2.setGeometry(QtCore.QRect(10, 251, 771, 151))
        self.assigned_group_box_2.setObjectName(_fromUtf8("assigned_group_box_2"))
        self.assigned_parcel_twidget = QtGui.QTableWidget(self.assigned_group_box_2)
        self.assigned_parcel_twidget.setGeometry(QtCore.QRect(10, 20, 311, 121))
        self.assigned_parcel_twidget.setObjectName(_fromUtf8("assigned_parcel_twidget"))
        self.assigned_parcel_twidget.setColumnCount(3)
        self.assigned_parcel_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.assigned_parcel_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_parcel_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_parcel_twidget.setHorizontalHeaderItem(2, item)
        self.pasture_remove_button = QtGui.QPushButton(self.assigned_group_box_2)
        self.pasture_remove_button.setGeometry(QtCore.QRect(465, 57, 31, 31))
        self.pasture_remove_button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2_pasture/double_angle_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pasture_remove_button.setIcon(icon1)
        self.pasture_remove_button.setObjectName(_fromUtf8("pasture_remove_button"))
        self.pasture_type_twidget = QtGui.QTableWidget(self.assigned_group_box_2)
        self.pasture_type_twidget.setGeometry(QtCore.QRect(500, 20, 261, 121))
        self.pasture_type_twidget.setObjectName(_fromUtf8("pasture_type_twidget"))
        self.pasture_type_twidget.setColumnCount(4)
        self.pasture_type_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.pasture_type_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pasture_type_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.pasture_type_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.pasture_type_twidget.setHorizontalHeaderItem(3, item)
        self.pasture_add_button = QtGui.QPushButton(self.assigned_group_box_2)
        self.pasture_add_button.setGeometry(QtCore.QRect(465, 19, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pasture_add_button.sizePolicy().hasHeightForWidth())
        self.pasture_add_button.setSizePolicy(sizePolicy)
        self.pasture_add_button.setBaseSize(QtCore.QSize(0, 0))
        self.pasture_add_button.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2_pasture/double_angle_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pasture_add_button.setIcon(icon2)
        self.pasture_add_button.setObjectName(_fromUtf8("pasture_add_button"))
        self.pasture_type_cbox = QtGui.QComboBox(self.assigned_group_box_2)
        self.pasture_type_cbox.setGeometry(QtCore.QRect(327, 20, 131, 22))
        self.pasture_type_cbox.setObjectName(_fromUtf8("pasture_type_cbox"))
        self.application_tab_widget.addTab(self.parcel_tab, _fromUtf8(""))
        self.person_group_parcel_tab = QtGui.QWidget()
        self.person_group_parcel_tab.setObjectName(_fromUtf8("person_group_parcel_tab"))
        self.parcel_add_button_2 = QtGui.QPushButton(self.person_group_parcel_tab)
        self.parcel_add_button_2.setGeometry(QtCore.QRect(280, 220, 81, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parcel_add_button_2.sizePolicy().hasHeightForWidth())
        self.parcel_add_button_2.setSizePolicy(sizePolicy)
        self.parcel_add_button_2.setBaseSize(QtCore.QSize(0, 0))
        self.parcel_add_button_2.setObjectName(_fromUtf8("parcel_add_button_2"))
        self.assigned_group_box_5 = QtGui.QGroupBox(self.person_group_parcel_tab)
        self.assigned_group_box_5.setGeometry(QtCore.QRect(10, 251, 771, 151))
        self.assigned_group_box_5.setObjectName(_fromUtf8("assigned_group_box_5"))
        self.assigned_parcel_twidget_2 = QtGui.QTableWidget(self.assigned_group_box_5)
        self.assigned_parcel_twidget_2.setGeometry(QtCore.QRect(10, 20, 311, 121))
        self.assigned_parcel_twidget_2.setObjectName(_fromUtf8("assigned_parcel_twidget_2"))
        self.assigned_parcel_twidget_2.setColumnCount(3)
        self.assigned_parcel_twidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.assigned_parcel_twidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_parcel_twidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_parcel_twidget_2.setHorizontalHeaderItem(2, item)
        self.pasture_remove_button_2 = QtGui.QPushButton(self.assigned_group_box_5)
        self.pasture_remove_button_2.setGeometry(QtCore.QRect(465, 57, 31, 31))
        self.pasture_remove_button_2.setText(_fromUtf8(""))
        self.pasture_remove_button_2.setIcon(icon1)
        self.pasture_remove_button_2.setObjectName(_fromUtf8("pasture_remove_button_2"))
        self.pasture_type_twidget_2 = QtGui.QTableWidget(self.assigned_group_box_5)
        self.pasture_type_twidget_2.setGeometry(QtCore.QRect(500, 20, 261, 121))
        self.pasture_type_twidget_2.setObjectName(_fromUtf8("pasture_type_twidget_2"))
        self.pasture_type_twidget_2.setColumnCount(4)
        self.pasture_type_twidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.pasture_type_twidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pasture_type_twidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.pasture_type_twidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.pasture_type_twidget_2.setHorizontalHeaderItem(3, item)
        self.pasture_add_button_2 = QtGui.QPushButton(self.assigned_group_box_5)
        self.pasture_add_button_2.setGeometry(QtCore.QRect(465, 19, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pasture_add_button_2.sizePolicy().hasHeightForWidth())
        self.pasture_add_button_2.setSizePolicy(sizePolicy)
        self.pasture_add_button_2.setBaseSize(QtCore.QSize(0, 0))
        self.pasture_add_button_2.setText(_fromUtf8(""))
        self.pasture_add_button_2.setIcon(icon2)
        self.pasture_add_button_2.setObjectName(_fromUtf8("pasture_add_button_2"))
        self.pasture_type_cbox_2 = QtGui.QComboBox(self.assigned_group_box_5)
        self.pasture_type_cbox_2.setGeometry(QtCore.QRect(327, 20, 131, 22))
        self.pasture_type_cbox_2.setObjectName(_fromUtf8("pasture_type_cbox_2"))
        self.assigned_group_box_6 = QtGui.QGroupBox(self.person_group_parcel_tab)
        self.assigned_group_box_6.setGeometry(QtCore.QRect(10, 65, 771, 151))
        self.assigned_group_box_6.setObjectName(_fromUtf8("assigned_group_box_6"))
        self.result_parcel_twidget_2 = QtGui.QTableWidget(self.assigned_group_box_6)
        self.result_parcel_twidget_2.setGeometry(QtCore.QRect(10, 20, 751, 121))
        self.result_parcel_twidget_2.setObjectName(_fromUtf8("result_parcel_twidget_2"))
        self.result_parcel_twidget_2.setColumnCount(3)
        self.result_parcel_twidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.result_parcel_twidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.result_parcel_twidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.result_parcel_twidget_2.setHorizontalHeaderItem(2, item)
        self.search_group_box_3 = QtGui.QGroupBox(self.person_group_parcel_tab)
        self.search_group_box_3.setGeometry(QtCore.QRect(10, 0, 771, 64))
        self.search_group_box_3.setObjectName(_fromUtf8("search_group_box_3"))
        self.search_parcel_num_edit_2 = QtGui.QLineEdit(self.search_group_box_3)
        self.search_parcel_num_edit_2.setGeometry(QtCore.QRect(220, 31, 191, 22))
        self.search_parcel_num_edit_2.setObjectName(_fromUtf8("search_parcel_num_edit_2"))
        self.find_parcel_number_button_2 = QtGui.QPushButton(self.search_group_box_3)
        self.find_parcel_number_button_2.setGeometry(QtCore.QRect(441, 30, 101, 23))
        self.find_parcel_number_button_2.setObjectName(_fromUtf8("find_parcel_number_button_2"))
        self.label_18 = QtGui.QLabel(self.search_group_box_3)
        self.label_18.setGeometry(QtCore.QRect(220, 16, 241, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.bag_parcel_cbox_2 = QtGui.QComboBox(self.search_group_box_3)
        self.bag_parcel_cbox_2.setGeometry(QtCore.QRect(10, 31, 191, 22))
        self.bag_parcel_cbox_2.setObjectName(_fromUtf8("bag_parcel_cbox_2"))
        self.label_19 = QtGui.QLabel(self.search_group_box_3)
        self.label_19.setGeometry(QtCore.QRect(10, 15, 181, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.parcel_remove_button_2 = QtGui.QPushButton(self.person_group_parcel_tab)
        self.parcel_remove_button_2.setGeometry(QtCore.QRect(380, 220, 81, 31))
        self.parcel_remove_button_2.setObjectName(_fromUtf8("parcel_remove_button_2"))
        self.application_tab_widget.addTab(self.person_group_parcel_tab, _fromUtf8(""))
        self.tab_print = QtGui.QWidget()
        self.tab_print.setObjectName(_fromUtf8("tab_print"))
        self.groupBox_14 = QtGui.QGroupBox(self.tab_print)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 10, 751, 331))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.reg_receipt_print_button = QtGui.QPushButton(self.groupBox_14)
        self.reg_receipt_print_button.setGeometry(QtCore.QRect(80, 80, 101, 23))
        self.reg_receipt_print_button.setObjectName(_fromUtf8("reg_receipt_print_button"))
        self.app_return_button = QtGui.QPushButton(self.groupBox_14)
        self.app_return_button.setGeometry(QtCore.QRect(80, 115, 176, 23))
        self.app_return_button.setObjectName(_fromUtf8("app_return_button"))
        self.application_tab_widget.addTab(self.tab_print, _fromUtf8(""))
        self.line = QtGui.QFrame(ApplicationsPastureDialog)
        self.line.setGeometry(QtCore.QRect(0, 20, 800, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(ApplicationsPastureDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 481, 801, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label = QtGui.QLabel(ApplicationsPastureDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 236, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.help_button = QtGui.QPushButton(ApplicationsPastureDialog)
        self.help_button.setGeometry(QtCore.QRect(489, 460, 111, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.apply_button = QtGui.QPushButton(ApplicationsPastureDialog)
        self.apply_button.setGeometry(QtCore.QRect(620, 460, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.close_button = QtGui.QPushButton(ApplicationsPastureDialog)
        self.close_button.setGeometry(QtCore.QRect(710, 460, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.error_label = QtGui.QLabel(ApplicationsPastureDialog)
        self.error_label.setGeometry(QtCore.QRect(10, 463, 461, 20))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.status_label = QtGui.QLabel(ApplicationsPastureDialog)
        self.status_label.setGeometry(QtCore.QRect(10, 466, 361, 16))
        self.status_label.setText(_fromUtf8(""))
        self.status_label.setObjectName(_fromUtf8("status_label"))

        self.retranslateUi(ApplicationsPastureDialog)
        self.application_tab_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ApplicationsPastureDialog)
        ApplicationsPastureDialog.setTabOrder(self.application_tab_widget, self.date_time_date)
        ApplicationsPastureDialog.setTabOrder(self.date_time_date, self.application_type_cbox)
        ApplicationsPastureDialog.setTabOrder(self.application_type_cbox, self.application_num_first_edit)
        ApplicationsPastureDialog.setTabOrder(self.application_num_first_edit, self.application_num_middle_edit)
        ApplicationsPastureDialog.setTabOrder(self.application_num_middle_edit, self.application_num_last_edit)
        ApplicationsPastureDialog.setTabOrder(self.application_num_last_edit, self.requested_land_use_type_cbox)
        ApplicationsPastureDialog.setTabOrder(self.requested_land_use_type_cbox, self.status_cbox)
        ApplicationsPastureDialog.setTabOrder(self.status_cbox, self.status_date_date)
        ApplicationsPastureDialog.setTabOrder(self.status_date_date, self.next_officer_in_charge_cbox)
        ApplicationsPastureDialog.setTabOrder(self.next_officer_in_charge_cbox, self.add_button)
        ApplicationsPastureDialog.setTabOrder(self.add_button, self.update_button)
        ApplicationsPastureDialog.setTabOrder(self.update_button, self.delete_button)
        ApplicationsPastureDialog.setTabOrder(self.delete_button, self.application_status_twidget)
        ApplicationsPastureDialog.setTabOrder(self.application_status_twidget, self.help_button)
        ApplicationsPastureDialog.setTabOrder(self.help_button, self.apply_button)
        ApplicationsPastureDialog.setTabOrder(self.apply_button, self.close_button)
        ApplicationsPastureDialog.setTabOrder(self.close_button, self.appliciants_remove_button)
        ApplicationsPastureDialog.setTabOrder(self.appliciants_remove_button, self.applicant_documents_cbox)
        ApplicationsPastureDialog.setTabOrder(self.applicant_documents_cbox, self.search_parcel_num_edit)
        ApplicationsPastureDialog.setTabOrder(self.search_parcel_num_edit, self.find_parcel_number_button)
        ApplicationsPastureDialog.setTabOrder(self.find_parcel_number_button, self.reg_receipt_print_button)

    def retranslateUi(self, ApplicationsPastureDialog):
        ApplicationsPastureDialog.setWindowTitle(_translate("ApplicationsPastureDialog", "Applications Pasture Dialog", None))
        self.registration_group_box.setTitle(_translate("ApplicationsPastureDialog", "Registration", None))
        self.date_time_date.setDisplayFormat(_translate("ApplicationsPastureDialog", "yyyy-MM-dd, hh:mm", None))
        self.label_2.setText(_translate("ApplicationsPastureDialog", "Date,Time", None))
        self.label_3.setText(_translate("ApplicationsPastureDialog", "Application Type", None))
        self.label_4.setText(_translate("ApplicationsPastureDialog", "Application Number", None))
        self.duration_request_label.setText(_translate("ApplicationsPastureDialog", "Requested duration [year]", None))
        self.duration_approved_label.setText(_translate("ApplicationsPastureDialog", "Approved duration [year]", None))
        self.label_7.setText(_translate("ApplicationsPastureDialog", "Remarks", None))
        self.label_8.setText(_translate("ApplicationsPastureDialog", "Requested Land Use Type", None))
        self.label_43.setText(_translate("ApplicationsPastureDialog", "-", None))
        self.label_44.setText(_translate("ApplicationsPastureDialog", "-", None))
        self.label_45.setText(_translate("ApplicationsPastureDialog", "-", None))
        self.label_16.setText(_translate("ApplicationsPastureDialog", "Approved Land Use Type", None))
        self.label_33.setText(_translate("ApplicationsPastureDialog", "Rigth Type", None))
        self.application_status_group_box.setTitle(_translate("ApplicationsPastureDialog", "Application Status", None))
        self.label_9.setText(_translate("ApplicationsPastureDialog", "Status", None))
        self.label_10.setText(_translate("ApplicationsPastureDialog", "Next Officer In Charge", None))
        self.status_date_date.setDisplayFormat(_translate("ApplicationsPastureDialog", "yyyy-MM-dd", None))
        self.label_11.setText(_translate("ApplicationsPastureDialog", "Status Date", None))
        self.add_button.setText(_translate("ApplicationsPastureDialog", "Add", None))
        self.update_button.setText(_translate("ApplicationsPastureDialog", "Update", None))
        self.delete_button.setText(_translate("ApplicationsPastureDialog", "Delete", None))
        item = self.application_status_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsPastureDialog", "Status", None))
        item = self.application_status_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsPastureDialog", "Date", None))
        item = self.application_status_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsPastureDialog", "Officer in Charge", None))
        item = self.application_status_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ApplicationsPastureDialog", "Next Officer in Charge", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.application_detail_tab), _translate("ApplicationsPastureDialog", "Application Details", None))
        self.applicants_group_box.setTitle(_translate("ApplicationsPastureDialog", "Applicants", None))
        self.appliciants_remove_button.setText(_translate("ApplicationsPastureDialog", "Remove", None))
        self.person_group_gbox.setTitle(_translate("ApplicationsPastureDialog", "PUG Group", None))
        self.label_35.setText(_translate("ApplicationsPastureDialog", "Leader Name", None))
        self.is_group_checkbox.setText(_translate("ApplicationsPastureDialog", "Is Find", None))
        self.label_32.setText(_translate("ApplicationsPastureDialog", "Leader ID", None))
        self.group_connect_button.setText(_translate("ApplicationsPastureDialog", "Connect", None))
        self.person_gbox.setTitle(_translate("ApplicationsPastureDialog", "Person", None))
        self.person_find_button.setText(_translate("ApplicationsPastureDialog", "Find", None))
        self.label_36.setText(_translate("ApplicationsPastureDialog", "Firstname", None))
        self.is_person_checkbox.setText(_translate("ApplicationsPastureDialog", "Person ID", None))
        self.person_connect_button.setText(_translate("ApplicationsPastureDialog", "Connect", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.applicants_tab), _translate("ApplicationsPastureDialog", "Applicants", None))
        self.documents_group_box.setTitle(_translate("ApplicationsPastureDialog", "Documents", None))
        self.label_12.setText(_translate("ApplicationsPastureDialog", "Select Applicants", None))
        self.load_doc_button.setText(_translate("ApplicationsPastureDialog", "Load Document", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.document_tab), _translate("ApplicationsPastureDialog", "Documents", None))
        self.search_group_box_2.setTitle(_translate("ApplicationsPastureDialog", "Search", None))
        self.find_boundary_number_button.setText(_translate("ApplicationsPastureDialog", "Find", None))
        self.label_15.setText(_translate("ApplicationsPastureDialog", "Enter Parcel Number", None))
        self.label_17.setText(_translate("ApplicationsPastureDialog", "Bag", None))
        self.boundary_remove_button.setText(_translate("ApplicationsPastureDialog", "Cancel", None))
        self.assigned_group_box_3.setTitle(_translate("ApplicationsPastureDialog", "Result Parcel", None))
        item = self.result_boundary_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsPastureDialog", "Parcel ID", None))
        item = self.result_boundary_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsPastureDialog", "Group Name", None))
        item = self.result_boundary_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsPastureDialog", "Area(ga)", None))
        self.boundary_add_button.setText(_translate("ApplicationsPastureDialog", "Connect", None))
        self.assigned_group_box_4.setTitle(_translate("ApplicationsPastureDialog", "Assigned Parcel", None))
        item = self.assigned_boundary_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsPastureDialog", "Boundary ID", None))
        item = self.assigned_boundary_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsPastureDialog", "Group Name", None))
        item = self.assigned_boundary_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsPastureDialog", "Area(ga)", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.boundary_tab), _translate("ApplicationsPastureDialog", "PUG Boundary", None))
        self.search_group_box.setTitle(_translate("ApplicationsPastureDialog", "Search", None))
        self.find_parcel_number_button.setText(_translate("ApplicationsPastureDialog", "Find", None))
        self.label_13.setText(_translate("ApplicationsPastureDialog", "Enter Parcel Number", None))
        self.label_14.setText(_translate("ApplicationsPastureDialog", "Bag", None))
        self.assigned_group_box.setTitle(_translate("ApplicationsPastureDialog", "Result Parcel", None))
        item = self.result_parcel_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsPastureDialog", "Parcel ID", None))
        item = self.result_parcel_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsPastureDialog", "Land Use Type", None))
        item = self.result_parcel_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsPastureDialog", "Area(ga)", None))
        self.parcel_add_button.setText(_translate("ApplicationsPastureDialog", "Connect", None))
        self.parcel_remove_button.setText(_translate("ApplicationsPastureDialog", "Cancel", None))
        self.assigned_group_box_2.setTitle(_translate("ApplicationsPastureDialog", "Assigned Parcel", None))
        item = self.assigned_parcel_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsPastureDialog", "Parcel ID", None))
        item = self.assigned_parcel_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsPastureDialog", "Neighbourhood", None))
        item = self.assigned_parcel_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsPastureDialog", "Area(ga)", None))
        item = self.pasture_type_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsPastureDialog", "Pasture Type", None))
        item = self.pasture_type_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsPastureDialog", "Begin Month", None))
        item = self.pasture_type_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsPastureDialog", "End Month", None))
        item = self.pasture_type_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ApplicationsPastureDialog", "Days", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.parcel_tab), _translate("ApplicationsPastureDialog", "Pasture Parcel", None))
        self.parcel_add_button_2.setText(_translate("ApplicationsPastureDialog", "Connect", None))
        self.assigned_group_box_5.setTitle(_translate("ApplicationsPastureDialog", "Assigned Parcel", None))
        item = self.assigned_parcel_twidget_2.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsPastureDialog", "Parcel ID", None))
        item = self.assigned_parcel_twidget_2.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsPastureDialog", "Neighbourhood", None))
        item = self.assigned_parcel_twidget_2.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsPastureDialog", "Area(ga)", None))
        item = self.pasture_type_twidget_2.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsPastureDialog", "Pasture Type", None))
        item = self.pasture_type_twidget_2.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsPastureDialog", "Begin Month", None))
        item = self.pasture_type_twidget_2.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsPastureDialog", "End Month", None))
        item = self.pasture_type_twidget_2.horizontalHeaderItem(3)
        item.setText(_translate("ApplicationsPastureDialog", "Days", None))
        self.assigned_group_box_6.setTitle(_translate("ApplicationsPastureDialog", "Result Parcel", None))
        item = self.result_parcel_twidget_2.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationsPastureDialog", "Parcel ID", None))
        item = self.result_parcel_twidget_2.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationsPastureDialog", "Land Use Type", None))
        item = self.result_parcel_twidget_2.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationsPastureDialog", "Area(ga)", None))
        self.search_group_box_3.setTitle(_translate("ApplicationsPastureDialog", "Search", None))
        self.find_parcel_number_button_2.setText(_translate("ApplicationsPastureDialog", "Find", None))
        self.label_18.setText(_translate("ApplicationsPastureDialog", "Enter Parcel Number", None))
        self.label_19.setText(_translate("ApplicationsPastureDialog", "Bag", None))
        self.parcel_remove_button_2.setText(_translate("ApplicationsPastureDialog", "Cancel", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.person_group_parcel_tab), _translate("ApplicationsPastureDialog", "Person Group Parcel", None))
        self.groupBox_14.setTitle(_translate("ApplicationsPastureDialog", "Registration Receipt", None))
        self.reg_receipt_print_button.setText(_translate("ApplicationsPastureDialog", "Print", None))
        self.app_return_button.setText(_translate("ApplicationsPastureDialog", "Response by governor", None))
        self.application_tab_widget.setTabText(self.application_tab_widget.indexOf(self.tab_print), _translate("ApplicationsPastureDialog", "Print", None))
        self.label.setText(_translate("ApplicationsPastureDialog", "Application", None))
        self.help_button.setText(_translate("ApplicationsPastureDialog", "?", None))
        self.apply_button.setText(_translate("ApplicationsPastureDialog", "Apply", None))
        self.close_button.setText(_translate("ApplicationsPastureDialog", "Close", None))

import resources_pasture_rc
import resources_rc
