# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\CamaNavigatorWidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CamaNavigatorWidget(object):
    def setupUi(self, CamaNavigatorWidget):
        CamaNavigatorWidget.setObjectName(_fromUtf8("CamaNavigatorWidget"))
        CamaNavigatorWidget.resize(500, 758)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CamaNavigatorWidget.sizePolicy().hasHeightForWidth())
        CamaNavigatorWidget.setSizePolicy(sizePolicy)
        CamaNavigatorWidget.setMinimumSize(QtCore.QSize(500, 620))
        CamaNavigatorWidget.setMaximumSize(QtCore.QSize(500, 524287))
        CamaNavigatorWidget.setBaseSize(QtCore.QSize(440, 665))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setGeometry(QtCore.QRect(1, 0, 498, 700))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 650))
        self.scrollArea.setMaximumSize(QtCore.QSize(500, 700))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 500, 750))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 650))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 800))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.working_l1_cbox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.working_l1_cbox.setGeometry(QtCore.QRect(4, 4, 170, 22))
        self.working_l1_cbox.setObjectName(_fromUtf8("working_l1_cbox"))
        self.working_l2_cbox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.working_l2_cbox.setGeometry(QtCore.QRect(184, 4, 170, 22))
        self.working_l2_cbox.setObjectName(_fromUtf8("working_l2_cbox"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 481, 650))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(290, 64, 75, 13))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(150, 64, 86, 13))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.min_price_edit = QtGui.QLineEdit(self.tab)
        self.min_price_edit.setGeometry(QtCore.QRect(150, 84, 113, 20))
        self.min_price_edit.setObjectName(_fromUtf8("min_price_edit"))
        self.max_price_edit = QtGui.QLineEdit(self.tab)
        self.max_price_edit.setGeometry(QtCore.QRect(290, 84, 113, 20))
        self.max_price_edit.setObjectName(_fromUtf8("max_price_edit"))
        self.parcel_count_edit = QtGui.QLineEdit(self.tab)
        self.parcel_count_edit.setGeometry(QtCore.QRect(10, 84, 113, 20))
        self.parcel_count_edit.setObjectName(_fromUtf8("parcel_count_edit"))
        self.label_32 = QtGui.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(10, 64, 126, 13))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.load_button = QtGui.QPushButton(self.tab)
        self.load_button.setGeometry(QtCore.QRect(9, 35, 172, 23))
        self.load_button.setObjectName(_fromUtf8("load_button"))
        self.market_price_rbutton = QtGui.QRadioButton(self.tab)
        self.market_price_rbutton.setGeometry(QtCore.QRect(160, 10, 111, 17))
        self.market_price_rbutton.setObjectName(_fromUtf8("market_price_rbutton"))
        self.base_price_rbutton = QtGui.QRadioButton(self.tab)
        self.base_price_rbutton.setGeometry(QtCore.QRect(10, 10, 141, 17))
        self.base_price_rbutton.setChecked(True)
        self.base_price_rbutton.setObjectName(_fromUtf8("base_price_rbutton"))
        self.level_count_sbox = QtGui.QSpinBox(self.tab)
        self.level_count_sbox.setGeometry(QtCore.QRect(10, 130, 113, 22))
        self.level_count_sbox.setObjectName(_fromUtf8("level_count_sbox"))
        self.calculate_button = QtGui.QPushButton(self.tab)
        self.calculate_button.setGeometry(QtCore.QRect(290, 129, 171, 23))
        self.calculate_button.setObjectName(_fromUtf8("calculate_button"))
        self.price_interval_twidget = QtGui.QTableWidget(self.tab)
        self.price_interval_twidget.setGeometry(QtCore.QRect(10, 210, 453, 341))
        self.price_interval_twidget.setObjectName(_fromUtf8("price_interval_twidget"))
        self.price_interval_twidget.setColumnCount(4)
        self.price_interval_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.price_interval_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.price_interval_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.price_interval_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.price_interval_twidget.setHorizontalHeaderItem(3, item)
        self.view_layer_button = QtGui.QPushButton(self.tab)
        self.view_layer_button.setGeometry(QtCore.QRect(290, 179, 171, 23))
        self.view_layer_button.setObjectName(_fromUtf8("view_layer_button"))
        self.layer_button = QtGui.QPushButton(self.tab)
        self.layer_button.setGeometry(QtCore.QRect(10, 560, 141, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.layer_button.setFont(font)
        self.layer_button.setObjectName(_fromUtf8("layer_button"))
        self.label_36 = QtGui.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(10, 110, 112, 13))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.valuation_level_status_cbox = QtGui.QComboBox(self.tab)
        self.valuation_level_status_cbox.setGeometry(QtCore.QRect(10, 180, 271, 22))
        self.valuation_level_status_cbox.setObjectName(_fromUtf8("valuation_level_status_cbox"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 271, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_37 = QtGui.QLabel(self.tab)
        self.label_37.setGeometry(QtCore.QRect(150, 110, 161, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.buffer_dsbox = QtGui.QDoubleSpinBox(self.tab)
        self.buffer_dsbox.setGeometry(QtCore.QRect(150, 130, 121, 22))
        self.buffer_dsbox.setObjectName(_fromUtf8("buffer_dsbox"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.is_elevation_chbox = QtGui.QCheckBox(self.tab_9)
        self.is_elevation_chbox.setGeometry(QtCore.QRect(10, 190, 131, 17))
        self.is_elevation_chbox.setObjectName(_fromUtf8("is_elevation_chbox"))
        self.is_slope_chbox = QtGui.QCheckBox(self.tab_9)
        self.is_slope_chbox.setGeometry(QtCore.QRect(10, 210, 151, 17))
        self.is_slope_chbox.setObjectName(_fromUtf8("is_slope_chbox"))
        self.cadastre_current_twidget = QtGui.QTableWidget(self.tab_9)
        self.cadastre_current_twidget.setGeometry(QtCore.QRect(6, 230, 464, 361))
        self.cadastre_current_twidget.setObjectName(_fromUtf8("cadastre_current_twidget"))
        self.cadastre_current_twidget.setColumnCount(3)
        self.cadastre_current_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.cadastre_current_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.cadastre_current_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.cadastre_current_twidget.setHorizontalHeaderItem(2, item)
        self.cadastre_current_twidget.horizontalHeader().setDefaultSectionSize(160)
        self.cadastre_current_twidget.horizontalHeader().setMinimumSectionSize(35)
        self.cadastre_current_twidget.verticalHeader().setDefaultSectionSize(30)
        self.cadastre_current_twidget.verticalHeader().setMinimumSectionSize(19)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_9.setGeometry(QtCore.QRect(1, 0, 470, 187))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.parcel_results_label = QtGui.QLabel(self.groupBox_9)
        self.parcel_results_label.setGeometry(QtCore.QRect(10, 155, 131, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.parcel_results_label.setFont(font)
        self.parcel_results_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.parcel_results_label.setObjectName(_fromUtf8("parcel_results_label"))
        self.parcel_khashaa_edit = QtGui.QLineEdit(self.groupBox_9)
        self.parcel_khashaa_edit.setGeometry(QtCore.QRect(290, 125, 170, 20))
        self.parcel_khashaa_edit.setObjectName(_fromUtf8("parcel_khashaa_edit"))
        self.land_use_type_cbox = QtGui.QComboBox(self.groupBox_9)
        self.land_use_type_cbox.setGeometry(QtCore.QRect(10, 80, 451, 22))
        self.land_use_type_cbox.setObjectName(_fromUtf8("land_use_type_cbox"))
        self.label_34 = QtGui.QLabel(self.groupBox_9)
        self.label_34.setGeometry(QtCore.QRect(10, 60, 170, 17))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.parcel_num_edit = QtGui.QLineEdit(self.groupBox_9)
        self.parcel_num_edit.setGeometry(QtCore.QRect(290, 33, 170, 20))
        self.parcel_num_edit.setObjectName(_fromUtf8("parcel_num_edit"))
        self.parcel_streetname_edit = QtGui.QLineEdit(self.groupBox_9)
        self.parcel_streetname_edit.setGeometry(QtCore.QRect(10, 125, 271, 20))
        self.parcel_streetname_edit.setObjectName(_fromUtf8("parcel_streetname_edit"))
        self.bag_cbox = QtGui.QComboBox(self.groupBox_9)
        self.bag_cbox.setGeometry(QtCore.QRect(10, 33, 271, 22))
        self.bag_cbox.setObjectName(_fromUtf8("bag_cbox"))
        self.label_83 = QtGui.QLabel(self.groupBox_9)
        self.label_83.setGeometry(QtCore.QRect(10, 105, 170, 17))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.label_35 = QtGui.QLabel(self.groupBox_9)
        self.label_35.setGeometry(QtCore.QRect(11, 13, 170, 17))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_84 = QtGui.QLabel(self.groupBox_9)
        self.label_84.setGeometry(QtCore.QRect(290, 105, 161, 17))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.label_33 = QtGui.QLabel(self.groupBox_9)
        self.label_33.setGeometry(QtCore.QRect(290, 13, 170, 17))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.parcel_find_button = QtGui.QPushButton(self.groupBox_9)
        self.parcel_find_button.setGeometry(QtCore.QRect(386, 153, 75, 23))
        self.parcel_find_button.setDefault(True)
        self.parcel_find_button.setObjectName(_fromUtf8("parcel_find_button"))
        self.parcel_clear_button = QtGui.QPushButton(self.groupBox_9)
        self.parcel_clear_button.setGeometry(QtCore.QRect(300, 153, 75, 23))
        self.parcel_clear_button.setObjectName(_fromUtf8("parcel_clear_button"))
        self.is_no_calculate_chbox = QtGui.QCheckBox(self.groupBox_9)
        self.is_no_calculate_chbox.setGeometry(QtCore.QRect(150, 156, 141, 17))
        self.is_no_calculate_chbox.setObjectName(_fromUtf8("is_no_calculate_chbox"))
        self.slope_calculate_button = QtGui.QPushButton(self.tab_9)
        self.slope_calculate_button.setGeometry(QtCore.QRect(301, 203, 75, 23))
        self.slope_calculate_button.setObjectName(_fromUtf8("slope_calculate_button"))
        self.error_label = QtGui.QLabel(self.tab_9)
        self.error_label.setGeometry(QtCore.QRect(10, 600, 374, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet(_fromUtf8("QLabel {color : red;}\n"
"font: 75 14pt \"Helvetica\";"))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setWordWrap(True)
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.slope_apply_button = QtGui.QPushButton(self.tab_9)
        self.slope_apply_button.setGeometry(QtCore.QRect(388, 203, 75, 23))
        self.slope_apply_button.setObjectName(_fromUtf8("slope_apply_button"))
        self.print_button = QtGui.QPushButton(self.tab_9)
        self.print_button.setGeometry(QtCore.QRect(216, 203, 75, 23))
        self.print_button.setObjectName(_fromUtf8("print_button"))
        self.print_pbar = QtGui.QProgressBar(self.tab_9)
        self.print_pbar.setGeometry(QtCore.QRect(218, 190, 243, 11))
        self.print_pbar.setProperty("value", 0)
        self.print_pbar.setObjectName(_fromUtf8("print_pbar"))
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 1, 475, 155))
        self.groupBox.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: #f5f5ef; border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.parcel_id_edit = QtGui.QLineEdit(self.groupBox)
        self.parcel_id_edit.setEnabled(True)
        self.parcel_id_edit.setGeometry(QtCore.QRect(11, 53, 121, 20))
        self.parcel_id_edit.setReadOnly(True)
        self.parcel_id_edit.setObjectName(_fromUtf8("parcel_id_edit"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(11, 37, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 78, 95, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.parcel_area_edit = QtGui.QLineEdit(self.groupBox)
        self.parcel_area_edit.setEnabled(False)
        self.parcel_area_edit.setGeometry(QtCore.QRect(10, 94, 95, 20))
        self.parcel_area_edit.setObjectName(_fromUtf8("parcel_area_edit"))
        self.parcel_market_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_market_price.setEnabled(False)
        self.parcel_market_price.setGeometry(QtCore.QRect(120, 132, 95, 20))
        self.parcel_market_price.setStyleSheet(_fromUtf8("background-color: rgb(219, 242, 255);"))
        self.parcel_market_price.setObjectName(_fromUtf8("parcel_market_price"))
        self.market_price_chbox = QtGui.QCheckBox(self.groupBox)
        self.market_price_chbox.setGeometry(QtCore.QRect(120, 115, 101, 17))
        self.market_price_chbox.setObjectName(_fromUtf8("market_price_chbox"))
        self.cadastre_rbutton = QtGui.QRadioButton(self.groupBox)
        self.cadastre_rbutton.setGeometry(QtCore.QRect(10, 17, 61, 17))
        self.cadastre_rbutton.setChecked(True)
        self.cadastre_rbutton.setObjectName(_fromUtf8("cadastre_rbutton"))
        self.parcel_address_edit = QtGui.QLineEdit(self.groupBox)
        self.parcel_address_edit.setEnabled(False)
        self.parcel_address_edit.setGeometry(QtCore.QRect(140, 53, 331, 20))
        self.parcel_address_edit.setObjectName(_fromUtf8("parcel_address_edit"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(140, 37, 137, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.plan_rbutton = QtGui.QRadioButton(self.groupBox)
        self.plan_rbutton.setGeometry(QtCore.QRect(90, 17, 81, 17))
        self.plan_rbutton.setObjectName(_fromUtf8("plan_rbutton"))
        self.parcel_area_ha_edit = QtGui.QLineEdit(self.groupBox)
        self.parcel_area_ha_edit.setEnabled(False)
        self.parcel_area_ha_edit.setGeometry(QtCore.QRect(10, 132, 95, 20))
        self.parcel_area_ha_edit.setObjectName(_fromUtf8("parcel_area_ha_edit"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 116, 95, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.parcel_base_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_base_price.setGeometry(QtCore.QRect(120, 94, 95, 20))
        self.parcel_base_price.setStyleSheet(_fromUtf8("background-color: rgb(255, 224, 206);"))
        self.parcel_base_price.setObjectName(_fromUtf8("parcel_base_price"))
        self.base_price_chbox = QtGui.QCheckBox(self.groupBox)
        self.base_price_chbox.setGeometry(QtCore.QRect(120, 77, 101, 17))
        self.base_price_chbox.setChecked(True)
        self.base_price_chbox.setObjectName(_fromUtf8("base_price_chbox"))
        self.parcel_all_base_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_all_base_price.setGeometry(QtCore.QRect(220, 94, 115, 20))
        self.parcel_all_base_price.setStyleSheet(_fromUtf8("background-color: rgb(255, 224, 206);"))
        self.parcel_all_base_price.setObjectName(_fromUtf8("parcel_all_base_price"))
        self.parcel_calc_base_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_calc_base_price.setGeometry(QtCore.QRect(340, 94, 115, 20))
        self.parcel_calc_base_price.setStyleSheet(_fromUtf8("background-color: rgb(255, 224, 206);"))
        self.parcel_calc_base_price.setObjectName(_fromUtf8("parcel_calc_base_price"))
        self.parcel_all_market_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_all_market_price.setGeometry(QtCore.QRect(220, 132, 115, 20))
        self.parcel_all_market_price.setStyleSheet(_fromUtf8("background-color: rgb(219, 242, 255);"))
        self.parcel_all_market_price.setObjectName(_fromUtf8("parcel_all_market_price"))
        self.parcel_calc_market_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_calc_market_price.setGeometry(QtCore.QRect(340, 132, 115, 20))
        self.parcel_calc_market_price.setStyleSheet(_fromUtf8("background-color: rgb(219, 242, 255);"))
        self.parcel_calc_market_price.setObjectName(_fromUtf8("parcel_calc_market_price"))
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(220, 78, 111, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.groupBox)
        self.label_27.setGeometry(QtCore.QRect(340, 78, 111, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.groupBox)
        self.label_28.setGeometry(QtCore.QRect(220, 116, 111, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.groupBox)
        self.label_29.setGeometry(QtCore.QRect(340, 116, 111, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.valuation_button = QtGui.QPushButton(self.groupBox)
        self.valuation_button.setGeometry(QtCore.QRect(350, 10, 111, 23))
        self.valuation_button.setObjectName(_fromUtf8("valuation_button"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        CamaNavigatorWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(CamaNavigatorWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CamaNavigatorWidget)

    def retranslateUi(self, CamaNavigatorWidget):
        CamaNavigatorWidget.setWindowTitle(_translate("CamaNavigatorWidget", "Selection / Filter", None))
        self.label_30.setText(_translate("CamaNavigatorWidget", "Хамгийн их үнэ", None))
        self.label_31.setText(_translate("CamaNavigatorWidget", "Хамгийн бага үнэ", None))
        self.label_32.setText(_translate("CamaNavigatorWidget", "Нийт нэгж талбарын тоо", None))
        self.load_button.setText(_translate("CamaNavigatorWidget", "Тооцоолох үнийн интервал", None))
        self.market_price_rbutton.setText(_translate("CamaNavigatorWidget", "Is Market Price", None))
        self.base_price_rbutton.setText(_translate("CamaNavigatorWidget", "Is Base Price", None))
        self.calculate_button.setText(_translate("CamaNavigatorWidget", "Calculate", None))
        item = self.price_interval_twidget.horizontalHeaderItem(0)
        item.setText(_translate("CamaNavigatorWidget", "Is Check", None))
        item = self.price_interval_twidget.horizontalHeaderItem(1)
        item.setText(_translate("CamaNavigatorWidget", "zone no", None))
        item = self.price_interval_twidget.horizontalHeaderItem(2)
        item.setText(_translate("CamaNavigatorWidget", "begin", None))
        item = self.price_interval_twidget.horizontalHeaderItem(3)
        item.setText(_translate("CamaNavigatorWidget", "end", None))
        self.view_layer_button.setText(_translate("CamaNavigatorWidget", "Тооцооллын давхарга харах", None))
        self.layer_button.setText(_translate("CamaNavigatorWidget", "Давхарга", None))
        self.label_36.setText(_translate("CamaNavigatorWidget", "Тооцоолох Бүсийн тоо", None))
        self.label_5.setText(_translate("CamaNavigatorWidget", "Үнэлгээний бүсчлэлийн төлөв", None))
        self.label_37.setText(_translate("CamaNavigatorWidget", "Бүсийн хүрээ (0.0002 >)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CamaNavigatorWidget", "Бүсчлэлийн анализ", None))
        self.is_elevation_chbox.setText(_translate("CamaNavigatorWidget", "Elevation", None))
        self.is_slope_chbox.setText(_translate("CamaNavigatorWidget", "Slope", None))
        self.cadastre_current_twidget.setSortingEnabled(True)
        item = self.cadastre_current_twidget.horizontalHeaderItem(0)
        item.setText(_translate("CamaNavigatorWidget", "Cadastre Parcel Information", None))
        item = self.cadastre_current_twidget.horizontalHeaderItem(1)
        item.setText(_translate("CamaNavigatorWidget", "Elevation", None))
        item = self.cadastre_current_twidget.horizontalHeaderItem(2)
        item.setText(_translate("CamaNavigatorWidget", "Slope", None))
        self.groupBox_9.setTitle(_translate("CamaNavigatorWidget", "Criteria", None))
        self.parcel_results_label.setText(_translate("CamaNavigatorWidget", "Results:", None))
        self.label_34.setText(_translate("CamaNavigatorWidget", "Land Use Type", None))
        self.label_83.setText(_translate("CamaNavigatorWidget", "Street Name", None))
        self.label_35.setText(_translate("CamaNavigatorWidget", "Bag", None))
        self.label_84.setText(_translate("CamaNavigatorWidget", "Khashaa Number", None))
        self.label_33.setText(_translate("CamaNavigatorWidget", "Parcel Number", None))
        self.parcel_find_button.setText(_translate("CamaNavigatorWidget", "Find", None))
        self.parcel_clear_button.setText(_translate("CamaNavigatorWidget", "Clear", None))
        self.is_no_calculate_chbox.setText(_translate("CamaNavigatorWidget", "Is No Calculate", None))
        self.slope_calculate_button.setText(_translate("CamaNavigatorWidget", "Calculate", None))
        self.slope_apply_button.setText(_translate("CamaNavigatorWidget", "Apply", None))
        self.print_button.setText(_translate("CamaNavigatorWidget", "Print", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("CamaNavigatorWidget", "Ө/Н-н анализ", None))
        self.groupBox.setTitle(_translate("CamaNavigatorWidget", "Parcel Information", None))
        self.label.setText(_translate("CamaNavigatorWidget", "Нэгж талбарын дугаар", None))
        self.label_2.setText(_translate("CamaNavigatorWidget", "Талбай /м2/", None))
        self.market_price_chbox.setText(_translate("CamaNavigatorWidget", "З/З-н үнэ", None))
        self.cadastre_rbutton.setText(_translate("CamaNavigatorWidget", "Кадастр", None))
        self.label_4.setText(_translate("CamaNavigatorWidget", "Нэгж талбарын хаяг", None))
        self.plan_rbutton.setText(_translate("CamaNavigatorWidget", "Төлөвлөгөө", None))
        self.label_3.setText(_translate("CamaNavigatorWidget", "Талбай /га/", None))
        self.base_price_chbox.setText(_translate("CamaNavigatorWidget", "Суурь үнэ /м2/", None))
        self.label_26.setText(_translate("CamaNavigatorWidget", "Н/Т-н суурь үнэ/сая.т/", None))
        self.label_27.setText(_translate("CamaNavigatorWidget", "Бодогдсон үнэ/сая.т/", None))
        self.label_28.setText(_translate("CamaNavigatorWidget", "Н/Т-н суурь үнэ/сая.т/", None))
        self.label_29.setText(_translate("CamaNavigatorWidget", "Бодогдсон үнэ/сая.т/", None))
        self.valuation_button.setText(_translate("CamaNavigatorWidget", "З/З-н үнийн мэдээ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CamaNavigatorWidget", "Parcel Price", None))

