# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ContractDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ContractDialog(object):
    def setupUi(self, ContractDialog):
        ContractDialog.setObjectName(_fromUtf8("ContractDialog"))
        ContractDialog.resize(800, 470)
        ContractDialog.setMinimumSize(QtCore.QSize(800, 470))
        ContractDialog.setMaximumSize(QtCore.QSize(800, 470))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../.designer/backup/icons/contract.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ContractDialog.setWindowIcon(icon)
        self.line = QtGui.QFrame(ContractDialog)
        self.line.setGeometry(QtCore.QRect(0, 20, 801, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(ContractDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 450, 801, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label = QtGui.QLabel(ContractDialog)
        self.label.setGeometry(QtCore.QRect(10, 7, 151, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.tab_widget = QtGui.QTabWidget(ContractDialog)
        self.tab_widget.setGeometry(QtCore.QRect(10, 30, 781, 391))
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.application_groupbox = QtGui.QGroupBox(self.tab)
        self.application_groupbox.setGeometry(QtCore.QRect(10, 10, 756, 151))
        self.application_groupbox.setObjectName(_fromUtf8("application_groupbox"))
        self.enter_application_num_edit = QtGui.QLineEdit(self.application_groupbox)
        self.enter_application_num_edit.setGeometry(QtCore.QRect(40, 51, 241, 20))
        self.enter_application_num_edit.setObjectName(_fromUtf8("enter_application_num_edit"))
        self.found_edit = QtGui.QLineEdit(self.application_groupbox)
        self.found_edit.setGeometry(QtCore.QRect(40, 101, 241, 20))
        self.found_edit.setObjectName(_fromUtf8("found_edit"))
        self.search_button = QtGui.QPushButton(self.application_groupbox)
        self.search_button.setGeometry(QtCore.QRect(310, 50, 75, 23))
        self.search_button.setObjectName(_fromUtf8("search_button"))
        self.accept_button = QtGui.QPushButton(self.application_groupbox)
        self.accept_button.setGeometry(QtCore.QRect(310, 100, 75, 23))
        self.accept_button.setObjectName(_fromUtf8("accept_button"))
        self.label_2 = QtGui.QLabel(self.application_groupbox)
        self.label_2.setGeometry(QtCore.QRect(40, 35, 250, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_37 = QtGui.QLabel(self.application_groupbox)
        self.label_37.setGeometry(QtCore.QRect(40, 85, 250, 13))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.groupBox_16 = QtGui.QGroupBox(self.tab)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 180, 756, 171))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.application_this_contract_based_edit = QtGui.QLineEdit(self.groupBox_16)
        self.application_this_contract_based_edit.setEnabled(False)
        self.application_this_contract_based_edit.setGeometry(QtCore.QRect(40, 50, 291, 20))
        self.application_this_contract_based_edit.setObjectName(_fromUtf8("application_this_contract_based_edit"))
        self.unassign_button = QtGui.QPushButton(self.groupBox_16)
        self.unassign_button.setGeometry(QtCore.QRect(430, 48, 200, 23))
        self.unassign_button.setObjectName(_fromUtf8("unassign_button"))
        self.label_31 = QtGui.QLabel(self.groupBox_16)
        self.label_31.setGeometry(QtCore.QRect(40, 35, 259, 13))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.application_type_edit = QtGui.QLineEdit(self.groupBox_16)
        self.application_type_edit.setEnabled(False)
        self.application_type_edit.setGeometry(QtCore.QRect(40, 120, 691, 20))
        self.application_type_edit.setObjectName(_fromUtf8("application_type_edit"))
        self.label_40 = QtGui.QLabel(self.groupBox_16)
        self.label_40.setGeometry(QtCore.QRect(40, 105, 259, 13))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.tab_widget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 756, 341))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.id_main_edit = QtGui.QLineEdit(self.groupBox)
        self.id_main_edit.setEnabled(False)
        self.id_main_edit.setGeometry(QtCore.QRect(20, 50, 241, 20))
        self.id_main_edit.setObjectName(_fromUtf8("id_main_edit"))
        self.old_id_edit = QtGui.QLineEdit(self.groupBox)
        self.old_id_edit.setEnabled(False)
        self.old_id_edit.setGeometry(QtCore.QRect(20, 110, 241, 20))
        self.old_id_edit.setObjectName(_fromUtf8("old_id_edit"))
        self.geo_id_edit = QtGui.QLineEdit(self.groupBox)
        self.geo_id_edit.setEnabled(False)
        self.geo_id_edit.setGeometry(QtCore.QRect(20, 170, 241, 20))
        self.geo_id_edit.setObjectName(_fromUtf8("geo_id_edit"))
        self.land_use_type_edit = QtGui.QLineEdit(self.groupBox)
        self.land_use_type_edit.setEnabled(False)
        self.land_use_type_edit.setGeometry(QtCore.QRect(20, 230, 381, 20))
        self.land_use_type_edit.setObjectName(_fromUtf8("land_use_type_edit"))
        self.calculated_area_edit = QtGui.QLineEdit(self.groupBox)
        self.calculated_area_edit.setEnabled(False)
        self.calculated_area_edit.setGeometry(QtCore.QRect(300, 50, 161, 20))
        self.calculated_area_edit.setObjectName(_fromUtf8("calculated_area_edit"))
        self.documents_area_edit = QtGui.QLineEdit(self.groupBox)
        self.documents_area_edit.setEnabled(False)
        self.documents_area_edit.setGeometry(QtCore.QRect(300, 110, 161, 20))
        self.documents_area_edit.setObjectName(_fromUtf8("documents_area_edit"))
        self.aimag_edit = QtGui.QLineEdit(self.groupBox)
        self.aimag_edit.setEnabled(False)
        self.aimag_edit.setGeometry(QtCore.QRect(510, 50, 221, 20))
        self.aimag_edit.setObjectName(_fromUtf8("aimag_edit"))
        self.soum_edit = QtGui.QLineEdit(self.groupBox)
        self.soum_edit.setEnabled(False)
        self.soum_edit.setGeometry(QtCore.QRect(510, 110, 221, 20))
        self.soum_edit.setObjectName(_fromUtf8("soum_edit"))
        self.bag_edit = QtGui.QLineEdit(self.groupBox)
        self.bag_edit.setEnabled(False)
        self.bag_edit.setGeometry(QtCore.QRect(510, 160, 221, 20))
        self.bag_edit.setObjectName(_fromUtf8("bag_edit"))
        self.street_name_edit = QtGui.QLineEdit(self.groupBox)
        self.street_name_edit.setEnabled(False)
        self.street_name_edit.setGeometry(QtCore.QRect(510, 210, 221, 20))
        self.street_name_edit.setObjectName(_fromUtf8("street_name_edit"))
        self.khashaa_edit = QtGui.QLineEdit(self.groupBox)
        self.khashaa_edit.setEnabled(False)
        self.khashaa_edit.setGeometry(QtCore.QRect(510, 260, 221, 20))
        self.khashaa_edit.setObjectName(_fromUtf8("khashaa_edit"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 35, 250, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 95, 250, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 155, 250, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 215, 250, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(300, 35, 166, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(300, 95, 191, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(510, 35, 222, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(510, 95, 222, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(510, 145, 222, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(510, 195, 222, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(510, 245, 222, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(20, 300, 721, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.edit_address_chbox = QtGui.QCheckBox(self.groupBox)
        self.edit_address_chbox.setGeometry(QtCore.QRect(510, 10, 211, 17))
        self.edit_address_chbox.setObjectName(_fromUtf8("edit_address_chbox"))
        self.tab_widget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 756, 357))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.contract_num_edit = QtGui.QLineEdit(self.groupBox_2)
        self.contract_num_edit.setEnabled(False)
        self.contract_num_edit.setGeometry(QtCore.QRect(30, 40, 181, 20))
        self.contract_num_edit.setObjectName(_fromUtf8("contract_num_edit"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(30, 25, 171, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.contract_begin_edit = QtGui.QLineEdit(self.groupBox_2)
        self.contract_begin_edit.setEnabled(False)
        self.contract_begin_edit.setGeometry(QtCore.QRect(30, 100, 181, 20))
        self.contract_begin_edit.setObjectName(_fromUtf8("contract_begin_edit"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(30, 85, 241, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(230, 25, 141, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(230, 85, 161, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(590, 25, 150, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(400, 85, 151, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.contract_date = QtGui.QDateEdit(self.groupBox_2)
        self.contract_date.setGeometry(QtCore.QRect(230, 40, 91, 22))
        self.contract_date.setCalendarPopup(True)
        self.contract_date.setObjectName(_fromUtf8("contract_date"))
        self.contract_duration_edit = QtGui.QLineEdit(self.groupBox_2)
        self.contract_duration_edit.setEnabled(False)
        self.contract_duration_edit.setGeometry(QtCore.QRect(230, 100, 161, 20))
        self.contract_duration_edit.setObjectName(_fromUtf8("contract_duration_edit"))
        self.calculated_num_edit = QtGui.QLineEdit(self.groupBox_2)
        self.calculated_num_edit.setEnabled(True)
        self.calculated_num_edit.setGeometry(QtCore.QRect(590, 40, 150, 20))
        self.calculated_num_edit.setObjectName(_fromUtf8("calculated_num_edit"))
        self.status_groupbox = QtGui.QGroupBox(self.groupBox_2)
        self.status_groupbox.setGeometry(QtCore.QRect(30, 130, 191, 171))
        self.status_groupbox.setObjectName(_fromUtf8("status_groupbox"))
        self.draft_rbutton = QtGui.QRadioButton(self.status_groupbox)
        self.draft_rbutton.setGeometry(QtCore.QRect(30, 40, 151, 20))
        self.draft_rbutton.setChecked(True)
        self.draft_rbutton.setObjectName(_fromUtf8("draft_rbutton"))
        self.contract_status_groupbox = QtGui.QButtonGroup(ContractDialog)
        self.contract_status_groupbox.setObjectName(_fromUtf8("contract_status_groupbox"))
        self.contract_status_groupbox.addButton(self.draft_rbutton)
        self.active_rbutton = QtGui.QRadioButton(self.status_groupbox)
        self.active_rbutton.setGeometry(QtCore.QRect(30, 70, 200, 20))
        self.active_rbutton.setObjectName(_fromUtf8("active_rbutton"))
        self.contract_status_groupbox.addButton(self.active_rbutton)
        self.expired_rbutton = QtGui.QRadioButton(self.status_groupbox)
        self.expired_rbutton.setGeometry(QtCore.QRect(30, 100, 146, 20))
        self.expired_rbutton.setObjectName(_fromUtf8("expired_rbutton"))
        self.contract_status_groupbox.addButton(self.expired_rbutton)
        self.cancelled_rbutton = QtGui.QRadioButton(self.status_groupbox)
        self.cancelled_rbutton.setGeometry(QtCore.QRect(30, 130, 151, 20))
        self.cancelled_rbutton.setObjectName(_fromUtf8("cancelled_rbutton"))
        self.contract_status_groupbox.addButton(self.cancelled_rbutton)
        self.contract_cancellation_groupbox = QtGui.QGroupBox(self.groupBox_2)
        self.contract_cancellation_groupbox.setEnabled(False)
        self.contract_cancellation_groupbox.setGeometry(QtCore.QRect(240, 130, 511, 171))
        self.contract_cancellation_groupbox.setObjectName(_fromUtf8("contract_cancellation_groupbox"))
        self.cancelation_date = QtGui.QDateEdit(self.contract_cancellation_groupbox)
        self.cancelation_date.setEnabled(False)
        self.cancelation_date.setGeometry(QtCore.QRect(30, 50, 91, 20))
        self.cancelation_date.setCalendarPopup(True)
        self.cancelation_date.setObjectName(_fromUtf8("cancelation_date"))
        self.label_23 = QtGui.QLabel(self.contract_cancellation_groupbox)
        self.label_23.setGeometry(QtCore.QRect(30, 21, 200, 20))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.application_based_rbutton = QtGui.QRadioButton(self.contract_cancellation_groupbox)
        self.application_based_rbutton.setGeometry(QtCore.QRect(185, 20, 200, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.application_based_rbutton.sizePolicy().hasHeightForWidth())
        self.application_based_rbutton.setSizePolicy(sizePolicy)
        self.application_based_rbutton.setChecked(True)
        self.application_based_rbutton.setObjectName(_fromUtf8("application_based_rbutton"))
        self.cancellation_reason_groupbox = QtGui.QButtonGroup(ContractDialog)
        self.cancellation_reason_groupbox.setObjectName(_fromUtf8("cancellation_reason_groupbox"))
        self.cancellation_reason_groupbox.addButton(self.application_based_rbutton)
        self.app_number_cbox = QtGui.QComboBox(self.contract_cancellation_groupbox)
        self.app_number_cbox.setEnabled(False)
        self.app_number_cbox.setGeometry(QtCore.QRect(200, 50, 151, 20))
        self.app_number_cbox.setObjectName(_fromUtf8("app_number_cbox"))
        self.label_24 = QtGui.QLabel(self.contract_cancellation_groupbox)
        self.label_24.setGeometry(QtCore.QRect(130, 52, 66, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.type_edit = QtGui.QLineEdit(self.contract_cancellation_groupbox)
        self.type_edit.setEnabled(False)
        self.type_edit.setGeometry(QtCore.QRect(80, 85, 421, 20))
        self.type_edit.setObjectName(_fromUtf8("type_edit"))
        self.label_25 = QtGui.QLabel(self.contract_cancellation_groupbox)
        self.label_25.setGeometry(QtCore.QRect(10, 87, 66, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.other_reason_cbox = QtGui.QComboBox(self.contract_cancellation_groupbox)
        self.other_reason_cbox.setEnabled(False)
        self.other_reason_cbox.setGeometry(QtCore.QRect(10, 135, 491, 22))
        self.other_reason_cbox.setObjectName(_fromUtf8("other_reason_cbox"))
        self.other_reason_rbutton = QtGui.QRadioButton(self.contract_cancellation_groupbox)
        self.other_reason_rbutton.setGeometry(QtCore.QRect(10, 110, 200, 20))
        self.other_reason_rbutton.setObjectName(_fromUtf8("other_reason_rbutton"))
        self.cancellation_reason_groupbox.addButton(self.other_reason_rbutton)
        self.cancellation_date_check_box = QtGui.QCheckBox(self.contract_cancellation_groupbox)
        self.cancellation_date_check_box.setGeometry(QtCore.QRect(10, 50, 16, 16))
        self.cancellation_date_check_box.setText(_fromUtf8(""))
        self.cancellation_date_check_box.setObjectName(_fromUtf8("cancellation_date_check_box"))
        self.person_id_edit = QtGui.QLineEdit(self.contract_cancellation_groupbox)
        self.person_id_edit.setEnabled(False)
        self.person_id_edit.setGeometry(QtCore.QRect(370, 50, 131, 20))
        self.person_id_edit.setObjectName(_fromUtf8("person_id_edit"))
        self.label_30 = QtGui.QLabel(self.contract_cancellation_groupbox)
        self.label_30.setGeometry(QtCore.QRect(370, 24, 131, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(30, 305, 721, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.error_label = QtGui.QLabel(self.groupBox_2)
        self.error_label.setGeometry(QtCore.QRect(30, 325, 711, 16))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.contract_end_date = QtGui.QDateEdit(self.groupBox_2)
        self.contract_end_date.setGeometry(QtCore.QRect(400, 100, 110, 22))
        self.contract_end_date.setObjectName(_fromUtf8("contract_end_date"))
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(540, 86, 150, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.property_num_edit = QtGui.QLineEdit(self.groupBox_2)
        self.property_num_edit.setEnabled(False)
        self.property_num_edit.setGeometry(QtCore.QRect(540, 101, 131, 20))
        self.property_num_edit.setObjectName(_fromUtf8("property_num_edit"))
        self.cert_range_cbox = QtGui.QComboBox(self.groupBox_2)
        self.cert_range_cbox.setGeometry(QtCore.QRect(370, 40, 215, 22))
        self.cert_range_cbox.setObjectName(_fromUtf8("cert_range_cbox"))
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(370, 25, 215, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.property_refresh_button = QtGui.QPushButton(self.groupBox_2)
        self.property_refresh_button.setGeometry(QtCore.QRect(680, 100, 61, 23))
        self.property_refresh_button.setObjectName(_fromUtf8("property_refresh_button"))
        self.tab_widget.addTab(self.tab_3, _fromUtf8(""))
        self.contract_conditions_tab = QtGui.QWidget()
        self.contract_conditions_tab.setObjectName(_fromUtf8("contract_conditions_tab"))
        self.groupBox_5 = QtGui.QGroupBox(self.contract_conditions_tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 751, 341))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.conditions_tree = QtGui.QTreeView(self.groupBox_5)
        self.conditions_tree.setGeometry(QtCore.QRect(15, 45, 356, 281))
        self.conditions_tree.setObjectName(_fromUtf8("conditions_tree"))
        self.preview_text_edit = QtGui.QTextEdit(self.groupBox_5)
        self.preview_text_edit.setGeometry(QtCore.QRect(380, 45, 356, 281))
        self.preview_text_edit.setReadOnly(True)
        self.preview_text_edit.setObjectName(_fromUtf8("preview_text_edit"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(15, 30, 171, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(380, 30, 171, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.tab_widget.addTab(self.contract_conditions_tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 756, 131))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.base_fee_edit = QtGui.QLineEdit(self.groupBox_6)
        self.base_fee_edit.setEnabled(False)
        self.base_fee_edit.setGeometry(QtCore.QRect(40, 65, 200, 20))
        self.base_fee_edit.setObjectName(_fromUtf8("base_fee_edit"))
        self.subsidized_area_edit = QtGui.QLineEdit(self.groupBox_6)
        self.subsidized_area_edit.setEnabled(False)
        self.subsidized_area_edit.setGeometry(QtCore.QRect(278, 65, 200, 20))
        self.subsidized_area_edit.setObjectName(_fromUtf8("subsidized_area_edit"))
        self.subsidized_fee_rate_edit = QtGui.QLineEdit(self.groupBox_6)
        self.subsidized_fee_rate_edit.setEnabled(False)
        self.subsidized_fee_rate_edit.setGeometry(QtCore.QRect(510, 65, 200, 20))
        self.subsidized_fee_rate_edit.setObjectName(_fromUtf8("subsidized_fee_rate_edit"))
        self.label_27 = QtGui.QLabel(self.groupBox_6)
        self.label_27.setGeometry(QtCore.QRect(40, 50, 200, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.groupBox_6)
        self.label_28.setGeometry(QtCore.QRect(278, 50, 200, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.groupBox_6)
        self.label_29.setGeometry(QtCore.QRect(510, 50, 220, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.landfee_message_label1 = QtGui.QLabel(self.groupBox_6)
        self.landfee_message_label1.setGeometry(QtCore.QRect(15, 100, 726, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.landfee_message_label1.setFont(font)
        self.landfee_message_label1.setObjectName(_fromUtf8("landfee_message_label1"))
        self.fee_zone_cbox = QtGui.QComboBox(self.groupBox_6)
        self.fee_zone_cbox.setGeometry(QtCore.QRect(280, 20, 321, 22))
        self.fee_zone_cbox.setObjectName(_fromUtf8("fee_zone_cbox"))
        self.label_34 = QtGui.QLabel(self.groupBox_6)
        self.label_34.setGeometry(QtCore.QRect(40, 24, 200, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.refresh_fee_button = QtGui.QPushButton(self.groupBox_6)
        self.refresh_fee_button.setGeometry(QtCore.QRect(630, 20, 111, 23))
        self.refresh_fee_button.setObjectName(_fromUtf8("refresh_fee_button"))
        self.land_fee_twidget = QtGui.QTableWidget(self.tab_5)
        self.land_fee_twidget.setGeometry(QtCore.QRect(10, 150, 756, 181))
        self.land_fee_twidget.setObjectName(_fromUtf8("land_fee_twidget"))
        self.land_fee_twidget.setColumnCount(8)
        self.land_fee_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.land_fee_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.land_fee_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.land_fee_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.land_fee_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.land_fee_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.land_fee_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.land_fee_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.land_fee_twidget.setHorizontalHeaderItem(7, item)
        self.land_fee_twidget.horizontalHeader().setDefaultSectionSize(120)
        self.landfee_message_label2 = QtGui.QLabel(self.tab_5)
        self.landfee_message_label2.setGeometry(QtCore.QRect(15, 340, 746, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.landfee_message_label2.setFont(font)
        self.landfee_message_label2.setObjectName(_fromUtf8("landfee_message_label2"))
        self.tab_widget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 90, 756, 91))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.archive_base_fee_edit = QtGui.QLineEdit(self.groupBox_13)
        self.archive_base_fee_edit.setEnabled(False)
        self.archive_base_fee_edit.setGeometry(QtCore.QRect(60, 40, 200, 20))
        self.archive_base_fee_edit.setObjectName(_fromUtf8("archive_base_fee_edit"))
        self.archive_subsidized_area_edit = QtGui.QLineEdit(self.groupBox_13)
        self.archive_subsidized_area_edit.setEnabled(False)
        self.archive_subsidized_area_edit.setGeometry(QtCore.QRect(295, 40, 200, 20))
        self.archive_subsidized_area_edit.setObjectName(_fromUtf8("archive_subsidized_area_edit"))
        self.archive_subsidized_fee_rate_edit = QtGui.QLineEdit(self.groupBox_13)
        self.archive_subsidized_fee_rate_edit.setEnabled(False)
        self.archive_subsidized_fee_rate_edit.setGeometry(QtCore.QRect(530, 40, 200, 20))
        self.archive_subsidized_fee_rate_edit.setObjectName(_fromUtf8("archive_subsidized_fee_rate_edit"))
        self.label_69 = QtGui.QLabel(self.groupBox_13)
        self.label_69.setGeometry(QtCore.QRect(60, 25, 200, 16))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.label_70 = QtGui.QLabel(self.groupBox_13)
        self.label_70.setGeometry(QtCore.QRect(295, 25, 200, 16))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.label_71 = QtGui.QLabel(self.groupBox_13)
        self.label_71.setGeometry(QtCore.QRect(530, 25, 200, 16))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.archive_land_fee_twidget = QtGui.QTableWidget(self.tab_6)
        self.archive_land_fee_twidget.setGeometry(QtCore.QRect(10, 191, 756, 141))
        self.archive_land_fee_twidget.setObjectName(_fromUtf8("archive_land_fee_twidget"))
        self.archive_land_fee_twidget.setColumnCount(8)
        self.archive_land_fee_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.archive_land_fee_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.archive_land_fee_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.archive_land_fee_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.archive_land_fee_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.archive_land_fee_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.archive_land_fee_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.archive_land_fee_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.archive_land_fee_twidget.setHorizontalHeaderItem(7, item)
        self.archive_land_fee_twidget.horizontalHeader().setDefaultSectionSize(120)
        self.groupBox_14 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 10, 756, 71))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.label_72 = QtGui.QLabel(self.groupBox_14)
        self.label_72.setGeometry(QtCore.QRect(60, 25, 333, 16))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.time_period_cbox = QtGui.QComboBox(self.groupBox_14)
        self.time_period_cbox.setGeometry(QtCore.QRect(60, 40, 256, 26))
        self.time_period_cbox.setObjectName(_fromUtf8("time_period_cbox"))
        self.tab_widget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.documents_groupbox = QtGui.QGroupBox(self.tab_13)
        self.documents_groupbox.setGeometry(QtCore.QRect(10, 10, 756, 341))
        self.documents_groupbox.setObjectName(_fromUtf8("documents_groupbox"))
        self.doc_twidget = QtGui.QTableWidget(self.documents_groupbox)
        self.doc_twidget.setGeometry(QtCore.QRect(20, 59, 700, 271))
        self.doc_twidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.doc_twidget.setObjectName(_fromUtf8("doc_twidget"))
        self.doc_twidget.setColumnCount(6)
        self.doc_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(5, item)
        self.doc_twidget.horizontalHeader().setCascadingSectionResizes(False)
        self.doc_twidget.horizontalHeader().setDefaultSectionSize(120)
        self.doc_twidget.horizontalHeader().setHighlightSections(False)
        self.doc_twidget.verticalHeader().setCascadingSectionResizes(False)
        self.load_doc_button = QtGui.QPushButton(self.documents_groupbox)
        self.load_doc_button.setGeometry(QtCore.QRect(304, 29, 171, 23))
        self.load_doc_button.setObjectName(_fromUtf8("load_doc_button"))
        self.label_32 = QtGui.QLabel(self.documents_groupbox)
        self.label_32.setGeometry(QtCore.QRect(22, 14, 261, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.document_path_edit = QtGui.QLineEdit(self.documents_groupbox)
        self.document_path_edit.setGeometry(QtCore.QRect(21, 30, 261, 20))
        self.document_path_edit.setReadOnly(True)
        self.document_path_edit.setObjectName(_fromUtf8("document_path_edit"))
        self.tab_widget.addTab(self.tab_13, _fromUtf8(""))
        self.tab_app_doc = QtGui.QWidget()
        self.tab_app_doc.setObjectName(_fromUtf8("tab_app_doc"))
        self.documents_groupbox_2 = QtGui.QGroupBox(self.tab_app_doc)
        self.documents_groupbox_2.setGeometry(QtCore.QRect(5, 2, 756, 341))
        self.documents_groupbox_2.setObjectName(_fromUtf8("documents_groupbox_2"))
        self.applicant_documents_cbox = QtGui.QComboBox(self.documents_groupbox_2)
        self.applicant_documents_cbox.setGeometry(QtCore.QRect(20, 30, 311, 26))
        self.applicant_documents_cbox.setObjectName(_fromUtf8("applicant_documents_cbox"))
        self.app_doc_twidget = QtGui.QTableWidget(self.documents_groupbox_2)
        self.app_doc_twidget.setGeometry(QtCore.QRect(20, 69, 700, 251))
        self.app_doc_twidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.app_doc_twidget.setObjectName(_fromUtf8("app_doc_twidget"))
        self.app_doc_twidget.setColumnCount(4)
        self.app_doc_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.app_doc_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.app_doc_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.app_doc_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.app_doc_twidget.setHorizontalHeaderItem(3, item)
        self.app_doc_twidget.horizontalHeader().setCascadingSectionResizes(True)
        self.app_doc_twidget.horizontalHeader().setDefaultSectionSize(100)
        self.app_doc_twidget.verticalHeader().setCascadingSectionResizes(False)
        self.load_app_doc_button = QtGui.QPushButton(self.documents_groupbox_2)
        self.load_app_doc_button.setGeometry(QtCore.QRect(430, 30, 171, 23))
        self.load_app_doc_button.setObjectName(_fromUtf8("load_app_doc_button"))
        self.tab_widget.addTab(self.tab_app_doc, _fromUtf8(""))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.groupBox_20 = QtGui.QGroupBox(self.tab_14)
        self.groupBox_20.setGeometry(QtCore.QRect(10, 10, 756, 341))
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.print_contract_button = QtGui.QPushButton(self.groupBox_20)
        self.print_contract_button.setGeometry(QtCore.QRect(80, 60, 261, 23))
        self.print_contract_button.setObjectName(_fromUtf8("print_contract_button"))
        self.print_certificate_button = QtGui.QPushButton(self.groupBox_20)
        self.print_certificate_button.setGeometry(QtCore.QRect(80, 110, 261, 23))
        self.print_certificate_button.setObjectName(_fromUtf8("print_certificate_button"))
        self.print_soil_qual_pass_edit = QtGui.QPushButton(self.groupBox_20)
        self.print_soil_qual_pass_edit.setGeometry(QtCore.QRect(80, 160, 261, 23))
        self.print_soil_qual_pass_edit.setObjectName(_fromUtf8("print_soil_qual_pass_edit"))
        self.print_officer_cbox = QtGui.QComboBox(self.groupBox_20)
        self.print_officer_cbox.setGeometry(QtCore.QRect(360, 110, 211, 22))
        self.print_officer_cbox.setObjectName(_fromUtf8("print_officer_cbox"))
        self.is_sign_checkbox = QtGui.QCheckBox(self.groupBox_20)
        self.is_sign_checkbox.setGeometry(QtCore.QRect(360, 60, 361, 17))
        self.is_sign_checkbox.setObjectName(_fromUtf8("is_sign_checkbox"))
        self.pdf_checkbox = QtGui.QCheckBox(self.groupBox_20)
        self.pdf_checkbox.setGeometry(QtCore.QRect(110, 30, 161, 17))
        self.pdf_checkbox.setObjectName(_fromUtf8("pdf_checkbox"))
        self.position_lbl = QtGui.QLabel(self.groupBox_20)
        self.position_lbl.setGeometry(QtCore.QRect(360, 140, 391, 16))
        self.position_lbl.setText(_fromUtf8(""))
        self.position_lbl.setObjectName(_fromUtf8("position_lbl"))
        self.tab_widget.addTab(self.tab_14, _fromUtf8(""))
        self.apply_button = QtGui.QPushButton(ContractDialog)
        self.apply_button.setGeometry(QtCore.QRect(600, 430, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.close_button = QtGui.QPushButton(ContractDialog)
        self.close_button.setGeometry(QtCore.QRect(690, 430, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.help_button = QtGui.QPushButton(ContractDialog)
        self.help_button.setGeometry(QtCore.QRect(479, 430, 101, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.status_label = QtGui.QLabel(ContractDialog)
        self.status_label.setGeometry(QtCore.QRect(25, 430, 441, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setObjectName(_fromUtf8("status_label"))

        self.retranslateUi(ContractDialog)
        self.tab_widget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(ContractDialog)
        ContractDialog.setTabOrder(self.tab_widget, self.enter_application_num_edit)
        ContractDialog.setTabOrder(self.enter_application_num_edit, self.search_button)
        ContractDialog.setTabOrder(self.search_button, self.found_edit)
        ContractDialog.setTabOrder(self.found_edit, self.accept_button)
        ContractDialog.setTabOrder(self.accept_button, self.application_this_contract_based_edit)
        ContractDialog.setTabOrder(self.application_this_contract_based_edit, self.application_type_edit)
        ContractDialog.setTabOrder(self.application_type_edit, self.unassign_button)
        ContractDialog.setTabOrder(self.unassign_button, self.help_button)
        ContractDialog.setTabOrder(self.help_button, self.apply_button)
        ContractDialog.setTabOrder(self.apply_button, self.close_button)
        ContractDialog.setTabOrder(self.close_button, self.id_main_edit)
        ContractDialog.setTabOrder(self.id_main_edit, self.old_id_edit)
        ContractDialog.setTabOrder(self.old_id_edit, self.geo_id_edit)
        ContractDialog.setTabOrder(self.geo_id_edit, self.land_use_type_edit)
        ContractDialog.setTabOrder(self.land_use_type_edit, self.calculated_area_edit)
        ContractDialog.setTabOrder(self.calculated_area_edit, self.documents_area_edit)
        ContractDialog.setTabOrder(self.documents_area_edit, self.aimag_edit)
        ContractDialog.setTabOrder(self.aimag_edit, self.soum_edit)
        ContractDialog.setTabOrder(self.soum_edit, self.bag_edit)
        ContractDialog.setTabOrder(self.bag_edit, self.street_name_edit)
        ContractDialog.setTabOrder(self.street_name_edit, self.khashaa_edit)
        ContractDialog.setTabOrder(self.khashaa_edit, self.contract_num_edit)
        ContractDialog.setTabOrder(self.contract_num_edit, self.contract_date)
        ContractDialog.setTabOrder(self.contract_date, self.calculated_num_edit)
        ContractDialog.setTabOrder(self.calculated_num_edit, self.contract_begin_edit)
        ContractDialog.setTabOrder(self.contract_begin_edit, self.contract_duration_edit)
        ContractDialog.setTabOrder(self.contract_duration_edit, self.draft_rbutton)
        ContractDialog.setTabOrder(self.draft_rbutton, self.active_rbutton)
        ContractDialog.setTabOrder(self.active_rbutton, self.expired_rbutton)
        ContractDialog.setTabOrder(self.expired_rbutton, self.cancelled_rbutton)
        ContractDialog.setTabOrder(self.cancelled_rbutton, self.cancellation_date_check_box)
        ContractDialog.setTabOrder(self.cancellation_date_check_box, self.cancelation_date)
        ContractDialog.setTabOrder(self.cancelation_date, self.application_based_rbutton)
        ContractDialog.setTabOrder(self.application_based_rbutton, self.app_number_cbox)
        ContractDialog.setTabOrder(self.app_number_cbox, self.type_edit)
        ContractDialog.setTabOrder(self.type_edit, self.other_reason_rbutton)
        ContractDialog.setTabOrder(self.other_reason_rbutton, self.other_reason_cbox)
        ContractDialog.setTabOrder(self.other_reason_cbox, self.conditions_tree)
        ContractDialog.setTabOrder(self.conditions_tree, self.preview_text_edit)
        ContractDialog.setTabOrder(self.preview_text_edit, self.base_fee_edit)
        ContractDialog.setTabOrder(self.base_fee_edit, self.subsidized_area_edit)
        ContractDialog.setTabOrder(self.subsidized_area_edit, self.subsidized_fee_rate_edit)
        ContractDialog.setTabOrder(self.subsidized_fee_rate_edit, self.land_fee_twidget)
        ContractDialog.setTabOrder(self.land_fee_twidget, self.time_period_cbox)
        ContractDialog.setTabOrder(self.time_period_cbox, self.archive_base_fee_edit)
        ContractDialog.setTabOrder(self.archive_base_fee_edit, self.archive_subsidized_area_edit)
        ContractDialog.setTabOrder(self.archive_subsidized_area_edit, self.archive_subsidized_fee_rate_edit)
        ContractDialog.setTabOrder(self.archive_subsidized_fee_rate_edit, self.archive_land_fee_twidget)
        ContractDialog.setTabOrder(self.archive_land_fee_twidget, self.print_contract_button)
        ContractDialog.setTabOrder(self.print_contract_button, self.print_certificate_button)
        ContractDialog.setTabOrder(self.print_certificate_button, self.print_soil_qual_pass_edit)

    def retranslateUi(self, ContractDialog):
        ContractDialog.setWindowTitle(_translate("ContractDialog", "Dialog", None))
        self.label.setText(_translate("ContractDialog", "Contract", None))
        self.application_groupbox.setTitle(_translate("ContractDialog", "Search", None))
        self.search_button.setText(_translate("ContractDialog", "Search", None))
        self.accept_button.setText(_translate("ContractDialog", "Accept", None))
        self.label_2.setText(_translate("ContractDialog", "Enter Application Number", None))
        self.label_37.setText(_translate("ContractDialog", "Found:", None))
        self.groupBox_16.setTitle(_translate("ContractDialog", "Assigned Parcel", None))
        self.unassign_button.setText(_translate("ContractDialog", "Unassign", None))
        self.label_31.setText(_translate("ContractDialog", "Application this contract is based on", None))
        self.label_40.setText(_translate("ContractDialog", "Application type", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("ContractDialog", "Application", None))
        self.groupBox.setTitle(_translate("ContractDialog", "Parcel Details", None))
        self.label_3.setText(_translate("ContractDialog", "ID (Main)", None))
        self.label_4.setText(_translate("ContractDialog", "Old ID", None))
        self.label_5.setText(_translate("ContractDialog", "Geo ID", None))
        self.label_6.setText(_translate("ContractDialog", "Land Use type", None))
        self.label_7.setText(_translate("ContractDialog", "Calculated Area [m2]", None))
        self.label_8.setText(_translate("ContractDialog", "Documented Area [m2]", None))
        self.label_9.setText(_translate("ContractDialog", "Aimag", None))
        self.label_10.setText(_translate("ContractDialog", "Soum / Duureg", None))
        self.label_11.setText(_translate("ContractDialog", "Bag / Khoroo", None))
        self.label_12.setText(_translate("ContractDialog", "Street Name", None))
        self.label_13.setText(_translate("ContractDialog", "Khashaa", None))
        self.label_14.setText(_translate("ContractDialog", "Parcel details will be populated automatically once an application was selected in the previous tab.", None))
        self.edit_address_chbox.setText(_translate("ContractDialog", "Edit address", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("ContractDialog", "Parcel", None))
        self.groupBox_2.setTitle(_translate("ContractDialog", "Contract Details", None))
        self.label_15.setText(_translate("ContractDialog", "Contract Number", None))
        self.label_16.setText(_translate("ContractDialog", "Contract Begin (= Decision Date)", None))
        self.label_19.setText(_translate("ContractDialog", "Contract Date", None))
        self.label_20.setText(_translate("ContractDialog", "Contract Duration [years]", None))
        self.label_21.setText(_translate("ContractDialog", "Certificate Number", None))
        self.label_22.setText(_translate("ContractDialog", "Contract End", None))
        self.contract_date.setDisplayFormat(_translate("ContractDialog", "yyyy-MM-dd", None))
        self.status_groupbox.setTitle(_translate("ContractDialog", "Contract Status", None))
        self.draft_rbutton.setText(_translate("ContractDialog", "Draft", None))
        self.active_rbutton.setText(_translate("ContractDialog", "Active", None))
        self.expired_rbutton.setText(_translate("ContractDialog", "Expired", None))
        self.cancelled_rbutton.setText(_translate("ContractDialog", "Cancelled", None))
        self.contract_cancellation_groupbox.setTitle(_translate("ContractDialog", "Contract Cancellation", None))
        self.cancelation_date.setDisplayFormat(_translate("ContractDialog", "yyyy-MM-dd", None))
        self.label_23.setText(_translate("ContractDialog", "Cancellation Date", None))
        self.application_based_rbutton.setText(_translate("ContractDialog", "Application based", None))
        self.label_24.setText(_translate("ContractDialog", "Number", None))
        self.label_25.setText(_translate("ContractDialog", "Type", None))
        self.other_reason_rbutton.setText(_translate("ContractDialog", "Other reason", None))
        self.label_30.setText(_translate("ContractDialog", "Person/Company ID", None))
        self.label_26.setText(_translate("ContractDialog", "Contract begin and end cannot be set explicitely. They are based on decision date and contract duration.", None))
        self.label_33.setText(_translate("ContractDialog", "Property No", None))
        self.label_35.setText(_translate("ContractDialog", "Select Range", None))
        self.property_refresh_button.setText(_translate("ContractDialog", "refresh", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_3), _translate("ContractDialog", "Contract Details", None))
        self.groupBox_5.setTitle(_translate("ContractDialog", "Contract Conditions", None))
        self.label_17.setText(_translate("ContractDialog", "Conditions", None))
        self.label_18.setText(_translate("ContractDialog", "Preview", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.contract_conditions_tab), _translate("ContractDialog", "Contract Conditions", None))
        self.groupBox_6.setTitle(_translate("ContractDialog", "Base Figures", None))
        self.label_27.setText(_translate("ContractDialog", "Base Fee Per m2 [₮]", None))
        self.label_28.setText(_translate("ContractDialog", "Subsidized Area [m2]", None))
        self.label_29.setText(_translate("ContractDialog", "Subsidized Fee Rate [%]", None))
        self.landfee_message_label1.setText(_translate("ContractDialog", "XXX", None))
        self.label_34.setText(_translate("ContractDialog", "Select base fee", None))
        self.refresh_fee_button.setText(_translate("ContractDialog", "Calculate Fee", None))
        item = self.land_fee_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ContractDialog", "Contractor", None))
        item = self.land_fee_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ContractDialog", "ID", None))
        item = self.land_fee_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ContractDialog", "Share", None))
        item = self.land_fee_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ContractDialog", "Area [m2]", None))
        item = self.land_fee_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ContractDialog", "Fee [₮] (Calculated)", None))
        item = self.land_fee_twidget.horizontalHeaderItem(5)
        item.setText(_translate("ContractDialog", "Fee [₮] (Contract)", None))
        item = self.land_fee_twidget.horizontalHeaderItem(6)
        item.setText(_translate("ContractDialog", "Grace Period [days]", None))
        item = self.land_fee_twidget.horizontalHeaderItem(7)
        item.setText(_translate("ContractDialog", "Payment Frequency", None))
        self.landfee_message_label2.setText(_translate("ContractDialog", "XXX", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_5), _translate("ContractDialog", "Land Fee", None))
        self.groupBox_13.setTitle(_translate("ContractDialog", "Base Figures", None))
        self.label_69.setText(_translate("ContractDialog", "Base Fee Per m2 [₮]", None))
        self.label_70.setText(_translate("ContractDialog", "Subsidized Area [m2]", None))
        self.label_71.setText(_translate("ContractDialog", "Subsidized Fee Rate [%]", None))
        item = self.archive_land_fee_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ContractDialog", "Contractor", None))
        item = self.archive_land_fee_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ContractDialog", "ID", None))
        item = self.archive_land_fee_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ContractDialog", "Share", None))
        item = self.archive_land_fee_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ContractDialog", "Area [m2]", None))
        item = self.archive_land_fee_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ContractDialog", "Fee [₮] (Calculated)", None))
        item = self.archive_land_fee_twidget.horizontalHeaderItem(5)
        item.setText(_translate("ContractDialog", "Fee [₮] (Contract)", None))
        item = self.archive_land_fee_twidget.horizontalHeaderItem(6)
        item.setText(_translate("ContractDialog", "Grace Period [days]", None))
        item = self.archive_land_fee_twidget.horizontalHeaderItem(7)
        item.setText(_translate("ContractDialog", "Payment Frequency", None))
        self.groupBox_14.setTitle(_translate("ContractDialog", "Land Fee History", None))
        self.label_72.setText(_translate("ContractDialog", "Time Period", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_6), _translate("ContractDialog", "Land Fee History", None))
        self.documents_groupbox.setTitle(_translate("ContractDialog", "Contracts Documents", None))
        item = self.doc_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ContractDialog", "Provided", None))
        item = self.doc_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ContractDialog", "Type", None))
        item = self.doc_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ContractDialog", "Name", None))
        item = self.doc_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ContractDialog", "Open", None))
        item = self.doc_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ContractDialog", "Remove", None))
        item = self.doc_twidget.horizontalHeaderItem(5)
        item.setText(_translate("ContractDialog", "View", None))
        self.load_doc_button.setText(_translate("ContractDialog", "Load Document", None))
        self.label_32.setText(_translate("ContractDialog", "Document Path", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_13), _translate("ContractDialog", "Documents", None))
        self.documents_groupbox_2.setTitle(_translate("ContractDialog", "Application Documents", None))
        item = self.app_doc_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ContractDialog", "Provided", None))
        item = self.app_doc_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ContractDialog", "Type", None))
        item = self.app_doc_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ContractDialog", "Name", None))
        item = self.app_doc_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ContractDialog", "View", None))
        self.load_app_doc_button.setText(_translate("ContractDialog", "Load Document", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_app_doc), _translate("ContractDialog", "Application Documents", None))
        self.groupBox_20.setTitle(_translate("ContractDialog", "Print", None))
        self.print_contract_button.setText(_translate("ContractDialog", "Print Contract", None))
        self.print_certificate_button.setText(_translate("ContractDialog", "Print Certificate", None))
        self.print_soil_qual_pass_edit.setText(_translate("ContractDialog", "Print Soil Quality Passport", None))
        self.is_sign_checkbox.setText(_translate("ContractDialog", "whether to sign the chief", None))
        self.pdf_checkbox.setText(_translate("ContractDialog", "*.pdf print", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_14), _translate("ContractDialog", "Print", None))
        self.apply_button.setText(_translate("ContractDialog", "Apply", None))
        self.close_button.setText(_translate("ContractDialog", "Close", None))
        self.help_button.setText(_translate("ContractDialog", "?", None))
        self.status_label.setText(_translate("ContractDialog", "Messages", None))

