# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ContractPastureDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ContractPastureDialog(object):
    def setupUi(self, ContractPastureDialog):
        ContractPastureDialog.setObjectName(_fromUtf8("ContractPastureDialog"))
        ContractPastureDialog.resize(800, 470)
        ContractPastureDialog.setMinimumSize(QtCore.QSize(800, 470))
        ContractPastureDialog.setMaximumSize(QtCore.QSize(800, 470))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../.designer/backup/icons/contract.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ContractPastureDialog.setWindowIcon(icon)
        self.line = QtGui.QFrame(ContractPastureDialog)
        self.line.setGeometry(QtCore.QRect(0, 20, 801, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(ContractPastureDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 450, 801, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label = QtGui.QLabel(ContractPastureDialog)
        self.label.setGeometry(QtCore.QRect(10, 7, 151, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.tab_widget = QtGui.QTabWidget(ContractPastureDialog)
        self.tab_widget.setGeometry(QtCore.QRect(10, 30, 781, 397))
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.application_groupbox = QtGui.QGroupBox(self.tab)
        self.application_groupbox.setGeometry(QtCore.QRect(10, 10, 756, 151))
        self.application_groupbox.setObjectName(_fromUtf8("application_groupbox"))
        self.enter_application_num_edit = QtGui.QLineEdit(self.application_groupbox)
        self.enter_application_num_edit.setGeometry(QtCore.QRect(40, 51, 241, 20))
        self.enter_application_num_edit.setObjectName(_fromUtf8("enter_application_num_edit"))
        self.found_edit = QtGui.QLineEdit(self.application_groupbox)
        self.found_edit.setGeometry(QtCore.QRect(40, 101, 241, 20))
        self.found_edit.setObjectName(_fromUtf8("found_edit"))
        self.search_button = QtGui.QPushButton(self.application_groupbox)
        self.search_button.setGeometry(QtCore.QRect(310, 50, 75, 23))
        self.search_button.setObjectName(_fromUtf8("search_button"))
        self.accept_button = QtGui.QPushButton(self.application_groupbox)
        self.accept_button.setGeometry(QtCore.QRect(310, 100, 75, 23))
        self.accept_button.setObjectName(_fromUtf8("accept_button"))
        self.label_2 = QtGui.QLabel(self.application_groupbox)
        self.label_2.setGeometry(QtCore.QRect(40, 35, 250, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_37 = QtGui.QLabel(self.application_groupbox)
        self.label_37.setGeometry(QtCore.QRect(40, 85, 250, 13))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.groupBox_16 = QtGui.QGroupBox(self.tab)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 180, 756, 171))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.application_this_contract_based_edit = QtGui.QLineEdit(self.groupBox_16)
        self.application_this_contract_based_edit.setEnabled(False)
        self.application_this_contract_based_edit.setGeometry(QtCore.QRect(40, 50, 291, 20))
        self.application_this_contract_based_edit.setObjectName(_fromUtf8("application_this_contract_based_edit"))
        self.unassign_button = QtGui.QPushButton(self.groupBox_16)
        self.unassign_button.setGeometry(QtCore.QRect(430, 48, 200, 23))
        self.unassign_button.setObjectName(_fromUtf8("unassign_button"))
        self.label_31 = QtGui.QLabel(self.groupBox_16)
        self.label_31.setGeometry(QtCore.QRect(40, 35, 259, 13))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.application_type_edit = QtGui.QLineEdit(self.groupBox_16)
        self.application_type_edit.setEnabled(False)
        self.application_type_edit.setGeometry(QtCore.QRect(40, 120, 691, 20))
        self.application_type_edit.setObjectName(_fromUtf8("application_type_edit"))
        self.label_40 = QtGui.QLabel(self.groupBox_16)
        self.label_40.setGeometry(QtCore.QRect(40, 105, 259, 13))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.tab_widget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 756, 341))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(20, 300, 721, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.assigned_parcel_twidget = QtGui.QTableWidget(self.groupBox)
        self.assigned_parcel_twidget.setGeometry(QtCore.QRect(13, 30, 731, 221))
        self.assigned_parcel_twidget.setObjectName(_fromUtf8("assigned_parcel_twidget"))
        self.assigned_parcel_twidget.setColumnCount(3)
        self.assigned_parcel_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.assigned_parcel_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_parcel_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.assigned_parcel_twidget.setHorizontalHeaderItem(2, item)
        self.tab_widget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 756, 346))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.contract_num_edit = QtGui.QLineEdit(self.groupBox_2)
        self.contract_num_edit.setEnabled(False)
        self.contract_num_edit.setGeometry(QtCore.QRect(50, 40, 200, 20))
        self.contract_num_edit.setObjectName(_fromUtf8("contract_num_edit"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(50, 25, 171, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.contract_begin_edit = QtGui.QLineEdit(self.groupBox_2)
        self.contract_begin_edit.setEnabled(False)
        self.contract_begin_edit.setGeometry(QtCore.QRect(50, 100, 181, 20))
        self.contract_begin_edit.setObjectName(_fromUtf8("contract_begin_edit"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(50, 85, 241, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(300, 25, 200, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(300, 85, 200, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(530, 85, 200, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.contract_date = QtGui.QDateEdit(self.groupBox_2)
        self.contract_date.setGeometry(QtCore.QRect(300, 40, 161, 22))
        self.contract_date.setCalendarPopup(True)
        self.contract_date.setObjectName(_fromUtf8("contract_date"))
        self.contract_duration_edit = QtGui.QLineEdit(self.groupBox_2)
        self.contract_duration_edit.setEnabled(False)
        self.contract_duration_edit.setGeometry(QtCore.QRect(300, 100, 161, 20))
        self.contract_duration_edit.setObjectName(_fromUtf8("contract_duration_edit"))
        self.contract_end_edit = QtGui.QLineEdit(self.groupBox_2)
        self.contract_end_edit.setEnabled(False)
        self.contract_end_edit.setGeometry(QtCore.QRect(530, 100, 181, 20))
        self.contract_end_edit.setObjectName(_fromUtf8("contract_end_edit"))
        self.status_groupbox = QtGui.QGroupBox(self.groupBox_2)
        self.status_groupbox.setGeometry(QtCore.QRect(30, 130, 191, 171))
        self.status_groupbox.setObjectName(_fromUtf8("status_groupbox"))
        self.draft_rbutton = QtGui.QRadioButton(self.status_groupbox)
        self.draft_rbutton.setGeometry(QtCore.QRect(30, 40, 151, 20))
        self.draft_rbutton.setChecked(True)
        self.draft_rbutton.setObjectName(_fromUtf8("draft_rbutton"))
        self.contract_status_groupbox = QtGui.QButtonGroup(ContractPastureDialog)
        self.contract_status_groupbox.setObjectName(_fromUtf8("contract_status_groupbox"))
        self.contract_status_groupbox.addButton(self.draft_rbutton)
        self.active_rbutton = QtGui.QRadioButton(self.status_groupbox)
        self.active_rbutton.setGeometry(QtCore.QRect(30, 70, 200, 20))
        self.active_rbutton.setObjectName(_fromUtf8("active_rbutton"))
        self.contract_status_groupbox.addButton(self.active_rbutton)
        self.expired_rbutton = QtGui.QRadioButton(self.status_groupbox)
        self.expired_rbutton.setGeometry(QtCore.QRect(30, 100, 146, 20))
        self.expired_rbutton.setObjectName(_fromUtf8("expired_rbutton"))
        self.contract_status_groupbox.addButton(self.expired_rbutton)
        self.cancelled_rbutton = QtGui.QRadioButton(self.status_groupbox)
        self.cancelled_rbutton.setGeometry(QtCore.QRect(30, 130, 151, 20))
        self.cancelled_rbutton.setObjectName(_fromUtf8("cancelled_rbutton"))
        self.contract_status_groupbox.addButton(self.cancelled_rbutton)
        self.contract_cancellation_groupbox = QtGui.QGroupBox(self.groupBox_2)
        self.contract_cancellation_groupbox.setEnabled(False)
        self.contract_cancellation_groupbox.setGeometry(QtCore.QRect(240, 130, 511, 171))
        self.contract_cancellation_groupbox.setObjectName(_fromUtf8("contract_cancellation_groupbox"))
        self.cancelation_date = QtGui.QDateEdit(self.contract_cancellation_groupbox)
        self.cancelation_date.setEnabled(False)
        self.cancelation_date.setGeometry(QtCore.QRect(30, 50, 91, 20))
        self.cancelation_date.setCalendarPopup(True)
        self.cancelation_date.setObjectName(_fromUtf8("cancelation_date"))
        self.label_23 = QtGui.QLabel(self.contract_cancellation_groupbox)
        self.label_23.setGeometry(QtCore.QRect(30, 21, 200, 20))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.application_based_rbutton = QtGui.QRadioButton(self.contract_cancellation_groupbox)
        self.application_based_rbutton.setGeometry(QtCore.QRect(185, 20, 200, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.application_based_rbutton.sizePolicy().hasHeightForWidth())
        self.application_based_rbutton.setSizePolicy(sizePolicy)
        self.application_based_rbutton.setChecked(True)
        self.application_based_rbutton.setObjectName(_fromUtf8("application_based_rbutton"))
        self.cancellation_reason_groupbox = QtGui.QButtonGroup(ContractPastureDialog)
        self.cancellation_reason_groupbox.setObjectName(_fromUtf8("cancellation_reason_groupbox"))
        self.cancellation_reason_groupbox.addButton(self.application_based_rbutton)
        self.app_number_cbox = QtGui.QComboBox(self.contract_cancellation_groupbox)
        self.app_number_cbox.setEnabled(False)
        self.app_number_cbox.setGeometry(QtCore.QRect(200, 50, 151, 20))
        self.app_number_cbox.setObjectName(_fromUtf8("app_number_cbox"))
        self.label_24 = QtGui.QLabel(self.contract_cancellation_groupbox)
        self.label_24.setGeometry(QtCore.QRect(130, 52, 66, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.type_edit = QtGui.QLineEdit(self.contract_cancellation_groupbox)
        self.type_edit.setEnabled(False)
        self.type_edit.setGeometry(QtCore.QRect(80, 85, 421, 20))
        self.type_edit.setObjectName(_fromUtf8("type_edit"))
        self.label_25 = QtGui.QLabel(self.contract_cancellation_groupbox)
        self.label_25.setGeometry(QtCore.QRect(10, 87, 66, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.other_reason_cbox = QtGui.QComboBox(self.contract_cancellation_groupbox)
        self.other_reason_cbox.setEnabled(False)
        self.other_reason_cbox.setGeometry(QtCore.QRect(10, 135, 491, 22))
        self.other_reason_cbox.setObjectName(_fromUtf8("other_reason_cbox"))
        self.other_reason_rbutton = QtGui.QRadioButton(self.contract_cancellation_groupbox)
        self.other_reason_rbutton.setGeometry(QtCore.QRect(10, 110, 200, 20))
        self.other_reason_rbutton.setObjectName(_fromUtf8("other_reason_rbutton"))
        self.cancellation_reason_groupbox.addButton(self.other_reason_rbutton)
        self.cancellation_date_check_box = QtGui.QCheckBox(self.contract_cancellation_groupbox)
        self.cancellation_date_check_box.setGeometry(QtCore.QRect(10, 50, 16, 16))
        self.cancellation_date_check_box.setText(_fromUtf8(""))
        self.cancellation_date_check_box.setObjectName(_fromUtf8("cancellation_date_check_box"))
        self.person_id_edit = QtGui.QLineEdit(self.contract_cancellation_groupbox)
        self.person_id_edit.setEnabled(False)
        self.person_id_edit.setGeometry(QtCore.QRect(370, 50, 131, 20))
        self.person_id_edit.setObjectName(_fromUtf8("person_id_edit"))
        self.label_30 = QtGui.QLabel(self.contract_cancellation_groupbox)
        self.label_30.setGeometry(QtCore.QRect(370, 24, 131, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(30, 305, 721, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.error_label = QtGui.QLabel(self.groupBox_2)
        self.error_label.setGeometry(QtCore.QRect(30, 325, 711, 16))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.tab_widget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.documents_groupbox = QtGui.QGroupBox(self.tab_13)
        self.documents_groupbox.setGeometry(QtCore.QRect(10, 10, 756, 341))
        self.documents_groupbox.setObjectName(_fromUtf8("documents_groupbox"))
        self.doc_twidget = QtGui.QTableWidget(self.documents_groupbox)
        self.doc_twidget.setGeometry(QtCore.QRect(20, 59, 700, 271))
        self.doc_twidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.doc_twidget.setObjectName(_fromUtf8("doc_twidget"))
        self.doc_twidget.setColumnCount(6)
        self.doc_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(5, item)
        self.doc_twidget.horizontalHeader().setCascadingSectionResizes(False)
        self.doc_twidget.horizontalHeader().setDefaultSectionSize(120)
        self.doc_twidget.horizontalHeader().setHighlightSections(False)
        self.doc_twidget.verticalHeader().setCascadingSectionResizes(False)
        self.load_doc_button = QtGui.QPushButton(self.documents_groupbox)
        self.load_doc_button.setGeometry(QtCore.QRect(304, 29, 171, 23))
        self.load_doc_button.setObjectName(_fromUtf8("load_doc_button"))
        self.label_32 = QtGui.QLabel(self.documents_groupbox)
        self.label_32.setGeometry(QtCore.QRect(22, 14, 261, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.document_path_edit = QtGui.QLineEdit(self.documents_groupbox)
        self.document_path_edit.setGeometry(QtCore.QRect(21, 30, 261, 20))
        self.document_path_edit.setReadOnly(True)
        self.document_path_edit.setObjectName(_fromUtf8("document_path_edit"))
        self.tab_widget.addTab(self.tab_13, _fromUtf8(""))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.groupBox_20 = QtGui.QGroupBox(self.tab_14)
        self.groupBox_20.setGeometry(QtCore.QRect(10, 10, 756, 341))
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.print_contract_button = QtGui.QPushButton(self.groupBox_20)
        self.print_contract_button.setGeometry(QtCore.QRect(80, 60, 261, 23))
        self.print_contract_button.setObjectName(_fromUtf8("print_contract_button"))
        self.print_certificate_button = QtGui.QPushButton(self.groupBox_20)
        self.print_certificate_button.setGeometry(QtCore.QRect(80, 110, 261, 23))
        self.print_certificate_button.setObjectName(_fromUtf8("print_certificate_button"))
        self.print_soil_qual_pass_edit = QtGui.QPushButton(self.groupBox_20)
        self.print_soil_qual_pass_edit.setGeometry(QtCore.QRect(80, 160, 261, 23))
        self.print_soil_qual_pass_edit.setObjectName(_fromUtf8("print_soil_qual_pass_edit"))
        self.print_officer_cbox = QtGui.QComboBox(self.groupBox_20)
        self.print_officer_cbox.setGeometry(QtCore.QRect(360, 110, 211, 22))
        self.print_officer_cbox.setObjectName(_fromUtf8("print_officer_cbox"))
        self.is_sign_checkbox = QtGui.QCheckBox(self.groupBox_20)
        self.is_sign_checkbox.setGeometry(QtCore.QRect(360, 60, 361, 17))
        self.is_sign_checkbox.setObjectName(_fromUtf8("is_sign_checkbox"))
        self.pdf_checkbox = QtGui.QCheckBox(self.groupBox_20)
        self.pdf_checkbox.setGeometry(QtCore.QRect(110, 30, 161, 17))
        self.pdf_checkbox.setObjectName(_fromUtf8("pdf_checkbox"))
        self.tab_widget.addTab(self.tab_14, _fromUtf8(""))
        self.apply_button = QtGui.QPushButton(ContractPastureDialog)
        self.apply_button.setGeometry(QtCore.QRect(600, 430, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.close_button = QtGui.QPushButton(ContractPastureDialog)
        self.close_button.setGeometry(QtCore.QRect(690, 430, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.help_button = QtGui.QPushButton(ContractPastureDialog)
        self.help_button.setGeometry(QtCore.QRect(479, 430, 101, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.status_label = QtGui.QLabel(ContractPastureDialog)
        self.status_label.setGeometry(QtCore.QRect(25, 430, 441, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setObjectName(_fromUtf8("status_label"))

        self.retranslateUi(ContractPastureDialog)
        self.tab_widget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(ContractPastureDialog)
        ContractPastureDialog.setTabOrder(self.tab_widget, self.enter_application_num_edit)
        ContractPastureDialog.setTabOrder(self.enter_application_num_edit, self.search_button)
        ContractPastureDialog.setTabOrder(self.search_button, self.found_edit)
        ContractPastureDialog.setTabOrder(self.found_edit, self.accept_button)
        ContractPastureDialog.setTabOrder(self.accept_button, self.application_this_contract_based_edit)
        ContractPastureDialog.setTabOrder(self.application_this_contract_based_edit, self.application_type_edit)
        ContractPastureDialog.setTabOrder(self.application_type_edit, self.unassign_button)
        ContractPastureDialog.setTabOrder(self.unassign_button, self.help_button)
        ContractPastureDialog.setTabOrder(self.help_button, self.apply_button)
        ContractPastureDialog.setTabOrder(self.apply_button, self.close_button)
        ContractPastureDialog.setTabOrder(self.close_button, self.contract_num_edit)
        ContractPastureDialog.setTabOrder(self.contract_num_edit, self.contract_date)
        ContractPastureDialog.setTabOrder(self.contract_date, self.contract_begin_edit)
        ContractPastureDialog.setTabOrder(self.contract_begin_edit, self.contract_duration_edit)
        ContractPastureDialog.setTabOrder(self.contract_duration_edit, self.contract_end_edit)
        ContractPastureDialog.setTabOrder(self.contract_end_edit, self.draft_rbutton)
        ContractPastureDialog.setTabOrder(self.draft_rbutton, self.active_rbutton)
        ContractPastureDialog.setTabOrder(self.active_rbutton, self.expired_rbutton)
        ContractPastureDialog.setTabOrder(self.expired_rbutton, self.cancelled_rbutton)
        ContractPastureDialog.setTabOrder(self.cancelled_rbutton, self.cancellation_date_check_box)
        ContractPastureDialog.setTabOrder(self.cancellation_date_check_box, self.cancelation_date)
        ContractPastureDialog.setTabOrder(self.cancelation_date, self.application_based_rbutton)
        ContractPastureDialog.setTabOrder(self.application_based_rbutton, self.app_number_cbox)
        ContractPastureDialog.setTabOrder(self.app_number_cbox, self.type_edit)
        ContractPastureDialog.setTabOrder(self.type_edit, self.other_reason_rbutton)
        ContractPastureDialog.setTabOrder(self.other_reason_rbutton, self.other_reason_cbox)
        ContractPastureDialog.setTabOrder(self.other_reason_cbox, self.print_contract_button)
        ContractPastureDialog.setTabOrder(self.print_contract_button, self.print_certificate_button)
        ContractPastureDialog.setTabOrder(self.print_certificate_button, self.print_soil_qual_pass_edit)

    def retranslateUi(self, ContractPastureDialog):
        ContractPastureDialog.setWindowTitle(_translate("ContractPastureDialog", "Dialog", None))
        self.label.setText(_translate("ContractPastureDialog", "Contract", None))
        self.application_groupbox.setTitle(_translate("ContractPastureDialog", "Search", None))
        self.search_button.setText(_translate("ContractPastureDialog", "Search", None))
        self.accept_button.setText(_translate("ContractPastureDialog", "Accept", None))
        self.label_2.setText(_translate("ContractPastureDialog", "Enter Application Number", None))
        self.label_37.setText(_translate("ContractPastureDialog", "Found:", None))
        self.groupBox_16.setTitle(_translate("ContractPastureDialog", "Assigned Parcel", None))
        self.unassign_button.setText(_translate("ContractPastureDialog", "Unassign", None))
        self.label_31.setText(_translate("ContractPastureDialog", "Application this contract is based on", None))
        self.label_40.setText(_translate("ContractPastureDialog", "Application type", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("ContractPastureDialog", "Application", None))
        self.groupBox.setTitle(_translate("ContractPastureDialog", "Parcel Details", None))
        self.label_14.setText(_translate("ContractPastureDialog", "Parcel details will be populated automatically once an application was selected in the previous tab.", None))
        item = self.assigned_parcel_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ContractPastureDialog", "Parcel ID", None))
        item = self.assigned_parcel_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ContractPastureDialog", "Pasture Type", None))
        item = self.assigned_parcel_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ContractPastureDialog", "Area(ga)", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("ContractPastureDialog", "Parcel", None))
        self.groupBox_2.setTitle(_translate("ContractPastureDialog", "Contract Details", None))
        self.label_15.setText(_translate("ContractPastureDialog", "Contract Number", None))
        self.label_16.setText(_translate("ContractPastureDialog", "Contract Begin (= Decision Date)", None))
        self.label_19.setText(_translate("ContractPastureDialog", "Contract Date", None))
        self.label_20.setText(_translate("ContractPastureDialog", "Contract Duration [years]", None))
        self.label_22.setText(_translate("ContractPastureDialog", "Contract End", None))
        self.contract_date.setDisplayFormat(_translate("ContractPastureDialog", "yyyy-MM-dd", None))
        self.status_groupbox.setTitle(_translate("ContractPastureDialog", "Contract Status", None))
        self.draft_rbutton.setText(_translate("ContractPastureDialog", "Draft", None))
        self.active_rbutton.setText(_translate("ContractPastureDialog", "Active", None))
        self.expired_rbutton.setText(_translate("ContractPastureDialog", "Expired", None))
        self.cancelled_rbutton.setText(_translate("ContractPastureDialog", "Cancelled", None))
        self.contract_cancellation_groupbox.setTitle(_translate("ContractPastureDialog", "Contract Cancellation", None))
        self.cancelation_date.setDisplayFormat(_translate("ContractPastureDialog", "yyyy-MM-dd", None))
        self.label_23.setText(_translate("ContractPastureDialog", "Cancellation Date", None))
        self.application_based_rbutton.setText(_translate("ContractPastureDialog", "Application based", None))
        self.label_24.setText(_translate("ContractPastureDialog", "Number", None))
        self.label_25.setText(_translate("ContractPastureDialog", "Type", None))
        self.other_reason_rbutton.setText(_translate("ContractPastureDialog", "Other reason", None))
        self.label_30.setText(_translate("ContractPastureDialog", "Person/Company ID", None))
        self.label_26.setText(_translate("ContractPastureDialog", "Contract begin and end cannot be set explicitely. They are based on decision date and contract duration.", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_3), _translate("ContractPastureDialog", "Contract Details", None))
        self.documents_groupbox.setTitle(_translate("ContractPastureDialog", "Contracts Documents", None))
        item = self.doc_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ContractPastureDialog", "Provided", None))
        item = self.doc_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ContractPastureDialog", "Type", None))
        item = self.doc_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ContractPastureDialog", "Name", None))
        item = self.doc_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ContractPastureDialog", "Open", None))
        item = self.doc_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ContractPastureDialog", "Remove", None))
        item = self.doc_twidget.horizontalHeaderItem(5)
        item.setText(_translate("ContractPastureDialog", "View", None))
        self.load_doc_button.setText(_translate("ContractPastureDialog", "Load Document", None))
        self.label_32.setText(_translate("ContractPastureDialog", "Document Path", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_13), _translate("ContractPastureDialog", "Documents", None))
        self.groupBox_20.setTitle(_translate("ContractPastureDialog", "Print", None))
        self.print_contract_button.setText(_translate("ContractPastureDialog", "Print Contract", None))
        self.print_certificate_button.setText(_translate("ContractPastureDialog", "Print Certificate", None))
        self.print_soil_qual_pass_edit.setText(_translate("ContractPastureDialog", "Print Soil Quality Passport", None))
        self.is_sign_checkbox.setText(_translate("ContractPastureDialog", "whether to sign the chief", None))
        self.pdf_checkbox.setText(_translate("ContractPastureDialog", "*.pdf print", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_14), _translate("ContractPastureDialog", "Print", None))
        self.apply_button.setText(_translate("ContractPastureDialog", "Apply", None))
        self.close_button.setText(_translate("ContractPastureDialog", "Close", None))
        self.help_button.setText(_translate("ContractPastureDialog", "?", None))
        self.status_label.setText(_translate("ContractPastureDialog", "Messages", None))

import resources_pasture_rc
