# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\CamaNavigatorWidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CamaNavigatorWidget(object):
    def setupUi(self, CamaNavigatorWidget):
        CamaNavigatorWidget.setObjectName(_fromUtf8("CamaNavigatorWidget"))
        CamaNavigatorWidget.resize(500, 758)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CamaNavigatorWidget.sizePolicy().hasHeightForWidth())
        CamaNavigatorWidget.setSizePolicy(sizePolicy)
        CamaNavigatorWidget.setMinimumSize(QtCore.QSize(500, 620))
        CamaNavigatorWidget.setMaximumSize(QtCore.QSize(500, 524287))
        CamaNavigatorWidget.setBaseSize(QtCore.QSize(440, 665))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setGeometry(QtCore.QRect(1, 0, 498, 700))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 650))
        self.scrollArea.setMaximumSize(QtCore.QSize(500, 700))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 500, 750))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 650))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 800))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.working_l1_cbox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.working_l1_cbox.setGeometry(QtCore.QRect(4, 4, 170, 22))
        self.working_l1_cbox.setObjectName(_fromUtf8("working_l1_cbox"))
        self.working_l2_cbox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.working_l2_cbox.setGeometry(QtCore.QRect(184, 4, 170, 22))
        self.working_l2_cbox.setObjectName(_fromUtf8("working_l2_cbox"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 481, 650))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(270, 64, 61, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(140, 64, 61, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.min_price_edit = QtGui.QLineEdit(self.tab)
        self.min_price_edit.setGeometry(QtCore.QRect(140, 84, 113, 20))
        self.min_price_edit.setObjectName(_fromUtf8("min_price_edit"))
        self.max_price_edit = QtGui.QLineEdit(self.tab)
        self.max_price_edit.setGeometry(QtCore.QRect(270, 84, 113, 20))
        self.max_price_edit.setObjectName(_fromUtf8("max_price_edit"))
        self.parcel_count_edit = QtGui.QLineEdit(self.tab)
        self.parcel_count_edit.setGeometry(QtCore.QRect(10, 84, 113, 20))
        self.parcel_count_edit.setObjectName(_fromUtf8("parcel_count_edit"))
        self.label_32 = QtGui.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(10, 64, 111, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.load_button = QtGui.QPushButton(self.tab)
        self.load_button.setGeometry(QtCore.QRect(9, 40, 172, 23))
        self.load_button.setObjectName(_fromUtf8("load_button"))
        self.market_price_rbutton = QtGui.QRadioButton(self.tab)
        self.market_price_rbutton.setGeometry(QtCore.QRect(160, 10, 111, 17))
        self.market_price_rbutton.setObjectName(_fromUtf8("market_price_rbutton"))
        self.base_price_rbutton = QtGui.QRadioButton(self.tab)
        self.base_price_rbutton.setGeometry(QtCore.QRect(10, 10, 141, 17))
        self.base_price_rbutton.setChecked(True)
        self.base_price_rbutton.setObjectName(_fromUtf8("base_price_rbutton"))
        self.level_count_sbox = QtGui.QSpinBox(self.tab)
        self.level_count_sbox.setGeometry(QtCore.QRect(10, 120, 71, 22))
        self.level_count_sbox.setObjectName(_fromUtf8("level_count_sbox"))
        self.calculate_button = QtGui.QPushButton(self.tab)
        self.calculate_button.setGeometry(QtCore.QRect(100, 120, 81, 23))
        self.calculate_button.setObjectName(_fromUtf8("calculate_button"))
        self.price_interval_twidget = QtGui.QTableWidget(self.tab)
        self.price_interval_twidget.setGeometry(QtCore.QRect(10, 150, 453, 251))
        self.price_interval_twidget.setObjectName(_fromUtf8("price_interval_twidget"))
        self.price_interval_twidget.setColumnCount(3)
        self.price_interval_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.price_interval_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.price_interval_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.price_interval_twidget.setHorizontalHeaderItem(2, item)
        self.view_layer_button = QtGui.QPushButton(self.tab)
        self.view_layer_button.setGeometry(QtCore.QRect(200, 120, 171, 23))
        self.view_layer_button.setObjectName(_fromUtf8("view_layer_button"))
        self.layer_button = QtGui.QPushButton(self.tab)
        self.layer_button.setGeometry(QtCore.QRect(10, 410, 141, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.layer_button.setFont(font)
        self.layer_button.setObjectName(_fromUtf8("layer_button"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 161, 478, 461))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(2, 1, 469, 133))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: #f5f5ef; border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.elevation_edit = QtGui.QLineEdit(self.groupBox_2)
        self.elevation_edit.setGeometry(QtCore.QRect(8, 30, 110, 20))
        self.elevation_edit.setText(_fromUtf8(""))
        self.elevation_edit.setObjectName(_fromUtf8("elevation_edit"))
        self.slopy_edit = QtGui.QLineEdit(self.groupBox_2)
        self.slopy_edit.setGeometry(QtCore.QRect(163, 30, 110, 20))
        self.slopy_edit.setText(_fromUtf8(""))
        self.slopy_edit.setObjectName(_fromUtf8("slopy_edit"))
        self.earthquake_edit = QtGui.QLineEdit(self.groupBox_2)
        self.earthquake_edit.setGeometry(QtCore.QRect(163, 65, 110, 20))
        self.earthquake_edit.setText(_fromUtf8(""))
        self.earthquake_edit.setObjectName(_fromUtf8("earthquake_edit"))
        self.rain_replicate_edit = QtGui.QLineEdit(self.groupBox_2)
        self.rain_replicate_edit.setGeometry(QtCore.QRect(320, 30, 110, 20))
        self.rain_replicate_edit.setText(_fromUtf8(""))
        self.rain_replicate_edit.setObjectName(_fromUtf8("rain_replicate_edit"))
        self.air_quality_edit = QtGui.QLineEdit(self.groupBox_2)
        self.air_quality_edit.setGeometry(QtCore.QRect(164, 103, 110, 20))
        self.air_quality_edit.setText(_fromUtf8(""))
        self.air_quality_edit.setObjectName(_fromUtf8("air_quality_edit"))
        self.soil_quality_edit = QtGui.QLineEdit(self.groupBox_2)
        self.soil_quality_edit.setGeometry(QtCore.QRect(320, 68, 110, 20))
        self.soil_quality_edit.setText(_fromUtf8(""))
        self.soil_quality_edit.setObjectName(_fromUtf8("soil_quality_edit"))
        self.permafrost_cbox = QtGui.QComboBox(self.groupBox_2)
        self.permafrost_cbox.setGeometry(QtCore.QRect(8, 65, 110, 22))
        self.permafrost_cbox.setObjectName(_fromUtf8("permafrost_cbox"))
        self.water_quality_cbox = QtGui.QComboBox(self.groupBox_2)
        self.water_quality_cbox.setGeometry(QtCore.QRect(8, 103, 110, 22))
        self.water_quality_cbox.setObjectName(_fromUtf8("water_quality_cbox"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(8, 49, 110, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(9, 14, 110, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(8, 87, 110, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(164, 14, 110, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(163, 49, 110, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(320, 14, 110, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(164, 87, 141, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(320, 52, 110, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.elevation_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.elevation_value_edit.setEnabled(False)
        self.elevation_value_edit.setGeometry(QtCore.QRect(126, 30, 25, 20))
        self.elevation_value_edit.setObjectName(_fromUtf8("elevation_value_edit"))
        self.permafrost_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.permafrost_value_edit.setEnabled(False)
        self.permafrost_value_edit.setGeometry(QtCore.QRect(126, 65, 25, 20))
        self.permafrost_value_edit.setObjectName(_fromUtf8("permafrost_value_edit"))
        self.water_quality_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.water_quality_value_edit.setEnabled(False)
        self.water_quality_value_edit.setGeometry(QtCore.QRect(126, 103, 25, 20))
        self.water_quality_value_edit.setObjectName(_fromUtf8("water_quality_value_edit"))
        self.slopy_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.slopy_value_edit.setEnabled(False)
        self.slopy_value_edit.setGeometry(QtCore.QRect(281, 30, 25, 20))
        self.slopy_value_edit.setObjectName(_fromUtf8("slopy_value_edit"))
        self.earthquake_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.earthquake_value_edit.setEnabled(False)
        self.earthquake_value_edit.setGeometry(QtCore.QRect(281, 65, 25, 20))
        self.earthquake_value_edit.setObjectName(_fromUtf8("earthquake_value_edit"))
        self.air_quality_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.air_quality_value_edit.setEnabled(False)
        self.air_quality_value_edit.setGeometry(QtCore.QRect(281, 103, 25, 20))
        self.air_quality_value_edit.setObjectName(_fromUtf8("air_quality_value_edit"))
        self.soil_quality_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.soil_quality_value_edit.setEnabled(False)
        self.soil_quality_value_edit.setGeometry(QtCore.QRect(437, 68, 25, 20))
        self.soil_quality_value_edit.setObjectName(_fromUtf8("soil_quality_value_edit"))
        self.rain_replicate_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.rain_replicate_value_edit.setEnabled(False)
        self.rain_replicate_value_edit.setGeometry(QtCore.QRect(437, 30, 25, 20))
        self.rain_replicate_value_edit.setObjectName(_fromUtf8("rain_replicate_value_edit"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(2, 136, 469, 95))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: rgb(255, 242, 231); border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 50, 110, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.heat_line_edit = QtGui.QLineEdit(self.groupBox_3)
        self.heat_line_edit.setGeometry(QtCore.QRect(10, 31, 110, 20))
        self.heat_line_edit.setText(_fromUtf8(""))
        self.heat_line_edit.setObjectName(_fromUtf8("heat_line_edit"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(11, 15, 110, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.power_line_edit = QtGui.QLineEdit(self.groupBox_3)
        self.power_line_edit.setGeometry(QtCore.QRect(10, 66, 110, 20))
        self.power_line_edit.setText(_fromUtf8(""))
        self.power_line_edit.setObjectName(_fromUtf8("power_line_edit"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(164, 15, 111, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.water_line_edit = QtGui.QLineEdit(self.groupBox_3)
        self.water_line_edit.setGeometry(QtCore.QRect(164, 31, 110, 20))
        self.water_line_edit.setText(_fromUtf8(""))
        self.water_line_edit.setObjectName(_fromUtf8("water_line_edit"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(320, 15, 111, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.disinfect_line_edit = QtGui.QLineEdit(self.groupBox_3)
        self.disinfect_line_edit.setGeometry(QtCore.QRect(320, 31, 110, 20))
        self.disinfect_line_edit.setText(_fromUtf8(""))
        self.disinfect_line_edit.setObjectName(_fromUtf8("disinfect_line_edit"))
        self.route_edit = QtGui.QLineEdit(self.groupBox_3)
        self.route_edit.setGeometry(QtCore.QRect(164, 66, 110, 20))
        self.route_edit.setText(_fromUtf8(""))
        self.route_edit.setObjectName(_fromUtf8("route_edit"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(164, 50, 110, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(320, 50, 110, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.parking_edit = QtGui.QLineEdit(self.groupBox_3)
        self.parking_edit.setGeometry(QtCore.QRect(320, 66, 110, 20))
        self.parking_edit.setText(_fromUtf8(""))
        self.parking_edit.setObjectName(_fromUtf8("parking_edit"))
        self.power_line_value_edit = QtGui.QLineEdit(self.groupBox_3)
        self.power_line_value_edit.setEnabled(False)
        self.power_line_value_edit.setGeometry(QtCore.QRect(127, 66, 25, 20))
        self.power_line_value_edit.setObjectName(_fromUtf8("power_line_value_edit"))
        self.heat_line_value_edit = QtGui.QLineEdit(self.groupBox_3)
        self.heat_line_value_edit.setEnabled(False)
        self.heat_line_value_edit.setGeometry(QtCore.QRect(127, 31, 25, 20))
        self.heat_line_value_edit.setObjectName(_fromUtf8("heat_line_value_edit"))
        self.route_value_edit = QtGui.QLineEdit(self.groupBox_3)
        self.route_value_edit.setEnabled(False)
        self.route_value_edit.setGeometry(QtCore.QRect(282, 66, 25, 20))
        self.route_value_edit.setObjectName(_fromUtf8("route_value_edit"))
        self.water_line_value_edit = QtGui.QLineEdit(self.groupBox_3)
        self.water_line_value_edit.setEnabled(False)
        self.water_line_value_edit.setGeometry(QtCore.QRect(282, 31, 25, 20))
        self.water_line_value_edit.setObjectName(_fromUtf8("water_line_value_edit"))
        self.disinfect_line_value_edit = QtGui.QLineEdit(self.groupBox_3)
        self.disinfect_line_value_edit.setEnabled(False)
        self.disinfect_line_value_edit.setGeometry(QtCore.QRect(437, 31, 25, 20))
        self.disinfect_line_value_edit.setObjectName(_fromUtf8("disinfect_line_value_edit"))
        self.parking_value_edit = QtGui.QLineEdit(self.groupBox_3)
        self.parking_value_edit.setEnabled(False)
        self.parking_value_edit.setGeometry(QtCore.QRect(437, 66, 25, 20))
        self.parking_value_edit.setObjectName(_fromUtf8("parking_value_edit"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(2, 233, 469, 95))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: #f5f5ef; border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(320, 14, 141, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(10, 49, 110, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.medical_edit = QtGui.QLineEdit(self.groupBox_4)
        self.medical_edit.setGeometry(QtCore.QRect(320, 30, 110, 20))
        self.medical_edit.setText(_fromUtf8(""))
        self.medical_edit.setObjectName(_fromUtf8("medical_edit"))
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(164, 14, 141, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(11, 14, 110, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.house_service_edit = QtGui.QLineEdit(self.groupBox_4)
        self.house_service_edit.setGeometry(QtCore.QRect(164, 65, 110, 20))
        self.house_service_edit.setText(_fromUtf8(""))
        self.house_service_edit.setObjectName(_fromUtf8("house_service_edit"))
        self.shcool_edit = QtGui.QLineEdit(self.groupBox_4)
        self.shcool_edit.setGeometry(QtCore.QRect(10, 30, 110, 20))
        self.shcool_edit.setText(_fromUtf8(""))
        self.shcool_edit.setObjectName(_fromUtf8("shcool_edit"))
        self.kindergarten_edit = QtGui.QLineEdit(self.groupBox_4)
        self.kindergarten_edit.setGeometry(QtCore.QRect(164, 30, 110, 20))
        self.kindergarten_edit.setText(_fromUtf8(""))
        self.kindergarten_edit.setObjectName(_fromUtf8("kindergarten_edit"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(164, 49, 110, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.admin_edit = QtGui.QLineEdit(self.groupBox_4)
        self.admin_edit.setGeometry(QtCore.QRect(10, 65, 110, 20))
        self.admin_edit.setText(_fromUtf8(""))
        self.admin_edit.setObjectName(_fromUtf8("admin_edit"))
        self.shcool_value_edit = QtGui.QLineEdit(self.groupBox_4)
        self.shcool_value_edit.setEnabled(False)
        self.shcool_value_edit.setGeometry(QtCore.QRect(128, 30, 25, 20))
        self.shcool_value_edit.setObjectName(_fromUtf8("shcool_value_edit"))
        self.admin_value_edit = QtGui.QLineEdit(self.groupBox_4)
        self.admin_value_edit.setEnabled(False)
        self.admin_value_edit.setGeometry(QtCore.QRect(128, 65, 25, 20))
        self.admin_value_edit.setObjectName(_fromUtf8("admin_value_edit"))
        self.house_service_value_edit = QtGui.QLineEdit(self.groupBox_4)
        self.house_service_value_edit.setEnabled(False)
        self.house_service_value_edit.setGeometry(QtCore.QRect(283, 65, 25, 20))
        self.house_service_value_edit.setObjectName(_fromUtf8("house_service_value_edit"))
        self.kindergarten_value_edit = QtGui.QLineEdit(self.groupBox_4)
        self.kindergarten_value_edit.setEnabled(False)
        self.kindergarten_value_edit.setGeometry(QtCore.QRect(283, 30, 25, 20))
        self.kindergarten_value_edit.setObjectName(_fromUtf8("kindergarten_value_edit"))
        self.medical_value_edit = QtGui.QLineEdit(self.groupBox_4)
        self.medical_value_edit.setEnabled(False)
        self.medical_value_edit.setGeometry(QtCore.QRect(437, 30, 25, 20))
        self.medical_value_edit.setObjectName(_fromUtf8("medical_value_edit"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(2, 330, 469, 63))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: rgb(255, 242, 231); border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.service_center_edit = QtGui.QLineEdit(self.groupBox_5)
        self.service_center_edit.setGeometry(QtCore.QRect(165, 30, 110, 20))
        self.service_center_edit.setText(_fromUtf8(""))
        self.service_center_edit.setObjectName(_fromUtf8("service_center_edit"))
        self.shop_center_edit = QtGui.QLineEdit(self.groupBox_5)
        self.shop_center_edit.setGeometry(QtCore.QRect(9, 30, 110, 20))
        self.shop_center_edit.setText(_fromUtf8(""))
        self.shop_center_edit.setObjectName(_fromUtf8("shop_center_edit"))
        self.label_25 = QtGui.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(10, 14, 110, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(165, 14, 141, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.shop_center_value_edit = QtGui.QLineEdit(self.groupBox_5)
        self.shop_center_value_edit.setEnabled(False)
        self.shop_center_value_edit.setGeometry(QtCore.QRect(127, 30, 25, 20))
        self.shop_center_value_edit.setObjectName(_fromUtf8("shop_center_value_edit"))
        self.service_center_value_edit = QtGui.QLineEdit(self.groupBox_5)
        self.service_center_value_edit.setEnabled(False)
        self.service_center_value_edit.setGeometry(QtCore.QRect(283, 30, 25, 20))
        self.service_center_value_edit.setObjectName(_fromUtf8("service_center_value_edit"))
        self.distinct_calc_button = QtGui.QPushButton(self.tab_3)
        self.distinct_calc_button.setGeometry(QtCore.QRect(168, 398, 141, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.distinct_calc_button.setFont(font)
        self.distinct_calc_button.setObjectName(_fromUtf8("distinct_calc_button"))
        self.price_calc_button = QtGui.QPushButton(self.tab_3)
        self.price_calc_button.setGeometry(QtCore.QRect(328, 398, 141, 23))
        self.price_calc_button.setObjectName(_fromUtf8("price_calc_button"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 1, 475, 155))
        self.groupBox.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: #f5f5ef; border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.parcel_id_edit = QtGui.QLineEdit(self.groupBox)
        self.parcel_id_edit.setEnabled(True)
        self.parcel_id_edit.setGeometry(QtCore.QRect(11, 53, 121, 20))
        self.parcel_id_edit.setReadOnly(True)
        self.parcel_id_edit.setObjectName(_fromUtf8("parcel_id_edit"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(11, 37, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 78, 95, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.parcel_area_edit = QtGui.QLineEdit(self.groupBox)
        self.parcel_area_edit.setEnabled(False)
        self.parcel_area_edit.setGeometry(QtCore.QRect(10, 94, 95, 20))
        self.parcel_area_edit.setObjectName(_fromUtf8("parcel_area_edit"))
        self.parcel_market_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_market_price.setEnabled(False)
        self.parcel_market_price.setGeometry(QtCore.QRect(120, 132, 95, 20))
        self.parcel_market_price.setStyleSheet(_fromUtf8("background-color: rgb(219, 242, 255);"))
        self.parcel_market_price.setObjectName(_fromUtf8("parcel_market_price"))
        self.market_price_chbox = QtGui.QCheckBox(self.groupBox)
        self.market_price_chbox.setGeometry(QtCore.QRect(120, 115, 101, 17))
        self.market_price_chbox.setObjectName(_fromUtf8("market_price_chbox"))
        self.cadastre_rbutton = QtGui.QRadioButton(self.groupBox)
        self.cadastre_rbutton.setGeometry(QtCore.QRect(10, 17, 61, 17))
        self.cadastre_rbutton.setChecked(True)
        self.cadastre_rbutton.setObjectName(_fromUtf8("cadastre_rbutton"))
        self.parcel_address_edit = QtGui.QLineEdit(self.groupBox)
        self.parcel_address_edit.setEnabled(False)
        self.parcel_address_edit.setGeometry(QtCore.QRect(140, 53, 331, 20))
        self.parcel_address_edit.setObjectName(_fromUtf8("parcel_address_edit"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(140, 37, 137, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.plan_rbutton = QtGui.QRadioButton(self.groupBox)
        self.plan_rbutton.setGeometry(QtCore.QRect(90, 17, 81, 17))
        self.plan_rbutton.setObjectName(_fromUtf8("plan_rbutton"))
        self.parcel_area_ha_edit = QtGui.QLineEdit(self.groupBox)
        self.parcel_area_ha_edit.setEnabled(False)
        self.parcel_area_ha_edit.setGeometry(QtCore.QRect(10, 132, 95, 20))
        self.parcel_area_ha_edit.setObjectName(_fromUtf8("parcel_area_ha_edit"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 116, 95, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.parcel_base_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_base_price.setGeometry(QtCore.QRect(120, 94, 95, 20))
        self.parcel_base_price.setStyleSheet(_fromUtf8("background-color: rgb(255, 224, 206);"))
        self.parcel_base_price.setObjectName(_fromUtf8("parcel_base_price"))
        self.base_price_chbox = QtGui.QCheckBox(self.groupBox)
        self.base_price_chbox.setGeometry(QtCore.QRect(120, 77, 101, 17))
        self.base_price_chbox.setChecked(True)
        self.base_price_chbox.setObjectName(_fromUtf8("base_price_chbox"))
        self.parcel_all_base_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_all_base_price.setGeometry(QtCore.QRect(220, 94, 115, 20))
        self.parcel_all_base_price.setStyleSheet(_fromUtf8("background-color: rgb(255, 224, 206);"))
        self.parcel_all_base_price.setObjectName(_fromUtf8("parcel_all_base_price"))
        self.parcel_calc_base_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_calc_base_price.setGeometry(QtCore.QRect(340, 94, 115, 20))
        self.parcel_calc_base_price.setStyleSheet(_fromUtf8("background-color: rgb(255, 224, 206);"))
        self.parcel_calc_base_price.setObjectName(_fromUtf8("parcel_calc_base_price"))
        self.parcel_all_market_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_all_market_price.setGeometry(QtCore.QRect(220, 132, 115, 20))
        self.parcel_all_market_price.setStyleSheet(_fromUtf8("background-color: rgb(219, 242, 255);"))
        self.parcel_all_market_price.setObjectName(_fromUtf8("parcel_all_market_price"))
        self.parcel_calc_market_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_calc_market_price.setGeometry(QtCore.QRect(340, 132, 115, 20))
        self.parcel_calc_market_price.setStyleSheet(_fromUtf8("background-color: rgb(219, 242, 255);"))
        self.parcel_calc_market_price.setObjectName(_fromUtf8("parcel_calc_market_price"))
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(220, 78, 111, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.groupBox)
        self.label_27.setGeometry(QtCore.QRect(340, 78, 111, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.groupBox)
        self.label_28.setGeometry(QtCore.QRect(220, 116, 111, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.groupBox)
        self.label_29.setGeometry(QtCore.QRect(340, 116, 111, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.valuation_button = QtGui.QPushButton(self.groupBox)
        self.valuation_button.setGeometry(QtCore.QRect(350, 10, 111, 23))
        self.valuation_button.setObjectName(_fromUtf8("valuation_button"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.is_elevation_chbox = QtGui.QCheckBox(self.tab_9)
        self.is_elevation_chbox.setGeometry(QtCore.QRect(10, 190, 131, 17))
        self.is_elevation_chbox.setObjectName(_fromUtf8("is_elevation_chbox"))
        self.is_slope_chbox = QtGui.QCheckBox(self.tab_9)
        self.is_slope_chbox.setGeometry(QtCore.QRect(10, 210, 151, 17))
        self.is_slope_chbox.setObjectName(_fromUtf8("is_slope_chbox"))
        self.cadastre_current_twidget = QtGui.QTableWidget(self.tab_9)
        self.cadastre_current_twidget.setGeometry(QtCore.QRect(6, 230, 464, 361))
        self.cadastre_current_twidget.setObjectName(_fromUtf8("cadastre_current_twidget"))
        self.cadastre_current_twidget.setColumnCount(3)
        self.cadastre_current_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.cadastre_current_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.cadastre_current_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.cadastre_current_twidget.setHorizontalHeaderItem(2, item)
        self.cadastre_current_twidget.horizontalHeader().setDefaultSectionSize(160)
        self.cadastre_current_twidget.horizontalHeader().setMinimumSectionSize(35)
        self.cadastre_current_twidget.verticalHeader().setDefaultSectionSize(30)
        self.cadastre_current_twidget.verticalHeader().setMinimumSectionSize(19)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_9.setGeometry(QtCore.QRect(1, 0, 470, 187))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.parcel_results_label = QtGui.QLabel(self.groupBox_9)
        self.parcel_results_label.setGeometry(QtCore.QRect(10, 155, 131, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.parcel_results_label.setFont(font)
        self.parcel_results_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.parcel_results_label.setObjectName(_fromUtf8("parcel_results_label"))
        self.parcel_khashaa_edit = QtGui.QLineEdit(self.groupBox_9)
        self.parcel_khashaa_edit.setGeometry(QtCore.QRect(290, 125, 170, 20))
        self.parcel_khashaa_edit.setObjectName(_fromUtf8("parcel_khashaa_edit"))
        self.land_use_type_cbox = QtGui.QComboBox(self.groupBox_9)
        self.land_use_type_cbox.setGeometry(QtCore.QRect(10, 80, 451, 22))
        self.land_use_type_cbox.setObjectName(_fromUtf8("land_use_type_cbox"))
        self.label_34 = QtGui.QLabel(self.groupBox_9)
        self.label_34.setGeometry(QtCore.QRect(10, 60, 170, 17))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.parcel_num_edit = QtGui.QLineEdit(self.groupBox_9)
        self.parcel_num_edit.setGeometry(QtCore.QRect(290, 33, 170, 20))
        self.parcel_num_edit.setObjectName(_fromUtf8("parcel_num_edit"))
        self.parcel_streetname_edit = QtGui.QLineEdit(self.groupBox_9)
        self.parcel_streetname_edit.setGeometry(QtCore.QRect(10, 125, 271, 20))
        self.parcel_streetname_edit.setObjectName(_fromUtf8("parcel_streetname_edit"))
        self.bag_cbox = QtGui.QComboBox(self.groupBox_9)
        self.bag_cbox.setGeometry(QtCore.QRect(10, 33, 271, 22))
        self.bag_cbox.setObjectName(_fromUtf8("bag_cbox"))
        self.label_83 = QtGui.QLabel(self.groupBox_9)
        self.label_83.setGeometry(QtCore.QRect(10, 105, 170, 17))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.label_35 = QtGui.QLabel(self.groupBox_9)
        self.label_35.setGeometry(QtCore.QRect(11, 13, 170, 17))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_84 = QtGui.QLabel(self.groupBox_9)
        self.label_84.setGeometry(QtCore.QRect(290, 105, 161, 17))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.label_33 = QtGui.QLabel(self.groupBox_9)
        self.label_33.setGeometry(QtCore.QRect(290, 13, 170, 17))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.parcel_find_button = QtGui.QPushButton(self.groupBox_9)
        self.parcel_find_button.setGeometry(QtCore.QRect(386, 153, 75, 23))
        self.parcel_find_button.setDefault(True)
        self.parcel_find_button.setObjectName(_fromUtf8("parcel_find_button"))
        self.parcel_clear_button = QtGui.QPushButton(self.groupBox_9)
        self.parcel_clear_button.setGeometry(QtCore.QRect(300, 153, 75, 23))
        self.parcel_clear_button.setObjectName(_fromUtf8("parcel_clear_button"))
        self.is_no_calculate_chbox = QtGui.QCheckBox(self.groupBox_9)
        self.is_no_calculate_chbox.setGeometry(QtCore.QRect(150, 156, 141, 17))
        self.is_no_calculate_chbox.setObjectName(_fromUtf8("is_no_calculate_chbox"))
        self.slope_calculate_button = QtGui.QPushButton(self.tab_9)
        self.slope_calculate_button.setGeometry(QtCore.QRect(301, 203, 75, 23))
        self.slope_calculate_button.setObjectName(_fromUtf8("slope_calculate_button"))
        self.error_label = QtGui.QLabel(self.tab_9)
        self.error_label.setGeometry(QtCore.QRect(10, 600, 374, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet(_fromUtf8("QLabel {color : red;}\n"
"font: 75 14pt \"Helvetica\";"))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setWordWrap(True)
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.slope_apply_button = QtGui.QPushButton(self.tab_9)
        self.slope_apply_button.setGeometry(QtCore.QRect(388, 203, 75, 23))
        self.slope_apply_button.setObjectName(_fromUtf8("slope_apply_button"))
        self.print_button = QtGui.QPushButton(self.tab_9)
        self.print_button.setGeometry(QtCore.QRect(216, 203, 75, 23))
        self.print_button.setObjectName(_fromUtf8("print_button"))
        self.print_pbar = QtGui.QProgressBar(self.tab_9)
        self.print_pbar.setGeometry(QtCore.QRect(218, 190, 243, 11))
        self.print_pbar.setProperty("value", 0)
        self.print_pbar.setObjectName(_fromUtf8("print_pbar"))
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.pasture_values_twidget = QtGui.QTableWidget(self.tab_10)
        self.pasture_values_twidget.setGeometry(QtCore.QRect(3, 90, 468, 371))
        self.pasture_values_twidget.setObjectName(_fromUtf8("pasture_values_twidget"))
        self.pasture_values_twidget.setColumnCount(0)
        self.pasture_values_twidget.setRowCount(0)
        self.tabWidget.addTab(self.tab_10, _fromUtf8(""))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        CamaNavigatorWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(CamaNavigatorWidget)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CamaNavigatorWidget)

    def retranslateUi(self, CamaNavigatorWidget):
        CamaNavigatorWidget.setWindowTitle(_translate("CamaNavigatorWidget", "Selection / Filter", None))
        self.label_30.setText(_translate("CamaNavigatorWidget", "Max Limit", None))
        self.label_31.setText(_translate("CamaNavigatorWidget", "Min Limit", None))
        self.label_32.setText(_translate("CamaNavigatorWidget", "Parcel Count", None))
        self.load_button.setText(_translate("CamaNavigatorWidget", "Тооцоолох үнийн интервал", None))
        self.market_price_rbutton.setText(_translate("CamaNavigatorWidget", "Is Market Price", None))
        self.base_price_rbutton.setText(_translate("CamaNavigatorWidget", "Is Base Price", None))
        self.calculate_button.setText(_translate("CamaNavigatorWidget", "Calculate", None))
        item = self.price_interval_twidget.horizontalHeaderItem(0)
        item.setText(_translate("CamaNavigatorWidget", "zone no", None))
        item = self.price_interval_twidget.horizontalHeaderItem(1)
        item.setText(_translate("CamaNavigatorWidget", "begin", None))
        item = self.price_interval_twidget.horizontalHeaderItem(2)
        item.setText(_translate("CamaNavigatorWidget", "end", None))
        self.view_layer_button.setText(_translate("CamaNavigatorWidget", "Тооцооллын давхарга харах", None))
        self.layer_button.setText(_translate("CamaNavigatorWidget", "Давхарга", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CamaNavigatorWidget", "Бүсчлэлийн анализ", None))
        self.groupBox_2.setTitle(_translate("CamaNavigatorWidget", "Хүрээлэн буй орчин", None))
        self.elevation_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Өндөршил", None))
        self.slopy_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Гадаргын налуу", None))
        self.earthquake_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Газар хөдлөлийн бүс", None))
        self.rain_replicate_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Үер, усны давтамж", None))
        self.air_quality_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Агаарын чанарын индекс", None))
        self.soil_quality_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Хөрсний бохирдлын зэрэг", None))
        self.label_5.setText(_translate("CamaNavigatorWidget", "Цэвдэгтэй эсэх", None))
        self.label_6.setText(_translate("CamaNavigatorWidget", "Өндөршил", None))
        self.label_7.setText(_translate("CamaNavigatorWidget", "Усны чанарын зэрэг", None))
        self.label_8.setText(_translate("CamaNavigatorWidget", "Гадаргын налуу", None))
        self.label_9.setText(_translate("CamaNavigatorWidget", "Газар хөдлөлийн бүс", None))
        self.label_10.setText(_translate("CamaNavigatorWidget", "Үер, усны давтамж", None))
        self.label_11.setText(_translate("CamaNavigatorWidget", "Агаар/чанарын индекс", None))
        self.label_12.setText(_translate("CamaNavigatorWidget", "Хөрсний бохирдол", None))
        self.groupBox_3.setTitle(_translate("CamaNavigatorWidget", "Инженерийн дэд бүтэц", None))
        self.label_15.setText(_translate("CamaNavigatorWidget", "Цахилгаан", None))
        self.heat_line_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Дулааны шугам", None))
        self.label_13.setText(_translate("CamaNavigatorWidget", "Дулаан", None))
        self.power_line_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Цахилгааны шугам", None))
        self.label_14.setText(_translate("CamaNavigatorWidget", "Усан хангамж", None))
        self.water_line_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Цэвэр усны шугам", None))
        self.label_16.setText(_translate("CamaNavigatorWidget", "Ариутгал", None))
        self.disinfect_line_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Ариутгалын шугам", None))
        self.route_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Хатуу хучилттай шугам", None))
        self.label_17.setText(_translate("CamaNavigatorWidget", "Зам", None))
        self.label_23.setText(_translate("CamaNavigatorWidget", "Зогсоол", None))
        self.parking_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Авто зогсоол", None))
        self.groupBox_4.setTitle(_translate("CamaNavigatorWidget", "Нийгмийн дэд бүтэц", None))
        self.label_19.setText(_translate("CamaNavigatorWidget", "Эмнэлэг", None))
        self.label_21.setText(_translate("CamaNavigatorWidget", "Төрийн захиргаа", None))
        self.medical_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Эмнэлэг", None))
        self.label_22.setText(_translate("CamaNavigatorWidget", "Цэцэрлэг", None))
        self.label_18.setText(_translate("CamaNavigatorWidget", "Сургууль", None))
        self.house_service_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Ахуйн үйлчилгээ", None))
        self.shcool_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Сургууль", None))
        self.kindergarten_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Цэцэрлэг", None))
        self.label_20.setText(_translate("CamaNavigatorWidget", "Ахуйн үйлчилгээ", None))
        self.admin_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Төрийн захиргааны байгууллага", None))
        self.groupBox_5.setTitle(_translate("CamaNavigatorWidget", "Үйлчилгээ", None))
        self.service_center_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Үйлчилгээний төв", None))
        self.shop_center_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Худалдааны төв", None))
        self.label_25.setText(_translate("CamaNavigatorWidget", "Худалдааны төв/зах/", None))
        self.label_24.setText(_translate("CamaNavigatorWidget", "Үйлчилгээний төв", None))
        self.distinct_calc_button.setText(_translate("CamaNavigatorWidget", "Зай тооцох", None))
        self.price_calc_button.setText(_translate("CamaNavigatorWidget", "Тооцоолох", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("CamaNavigatorWidget", "Хот, Суурин", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("CamaNavigatorWidget", "ХАА", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("CamaNavigatorWidget", "Зам, Ш/С", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("CamaNavigatorWidget", "Ойн Сан", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("CamaNavigatorWidget", "Усан Сан", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("CamaNavigatorWidget", "Тусгай Хэрэгцээ", None))
        self.groupBox.setTitle(_translate("CamaNavigatorWidget", "Parcel Information", None))
        self.label.setText(_translate("CamaNavigatorWidget", "Нэгж талбарын дугаар", None))
        self.label_2.setText(_translate("CamaNavigatorWidget", "Талбай /м2/", None))
        self.market_price_chbox.setText(_translate("CamaNavigatorWidget", "З/З-н үнэ", None))
        self.cadastre_rbutton.setText(_translate("CamaNavigatorWidget", "Кадастр", None))
        self.label_4.setText(_translate("CamaNavigatorWidget", "Нэгж талбарын хаяг", None))
        self.plan_rbutton.setText(_translate("CamaNavigatorWidget", "Төлөвлөгөө", None))
        self.label_3.setText(_translate("CamaNavigatorWidget", "Талбай /га/", None))
        self.base_price_chbox.setText(_translate("CamaNavigatorWidget", "Суурь үнэ /м2/", None))
        self.label_26.setText(_translate("CamaNavigatorWidget", "Н/Т-н суурь үнэ/сая.т/", None))
        self.label_27.setText(_translate("CamaNavigatorWidget", "Бодогдсон үнэ/сая.т/", None))
        self.label_28.setText(_translate("CamaNavigatorWidget", "Н/Т-н суурь үнэ/сая.т/", None))
        self.label_29.setText(_translate("CamaNavigatorWidget", "Бодогдсон үнэ/сая.т/", None))
        self.valuation_button.setText(_translate("CamaNavigatorWidget", "З/З-н үнийн мэдээ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CamaNavigatorWidget", "Parcel Price", None))
        self.is_elevation_chbox.setText(_translate("CamaNavigatorWidget", "Elevation", None))
        self.is_slope_chbox.setText(_translate("CamaNavigatorWidget", "Slope", None))
        self.cadastre_current_twidget.setSortingEnabled(True)
        item = self.cadastre_current_twidget.horizontalHeaderItem(0)
        item.setText(_translate("CamaNavigatorWidget", "Cadastre Parcel Information", None))
        item = self.cadastre_current_twidget.horizontalHeaderItem(1)
        item.setText(_translate("CamaNavigatorWidget", "Elevation", None))
        item = self.cadastre_current_twidget.horizontalHeaderItem(2)
        item.setText(_translate("CamaNavigatorWidget", "Slope", None))
        self.groupBox_9.setTitle(_translate("CamaNavigatorWidget", "Criteria", None))
        self.parcel_results_label.setText(_translate("CamaNavigatorWidget", "Results:", None))
        self.label_34.setText(_translate("CamaNavigatorWidget", "Land Use Type", None))
        self.label_83.setText(_translate("CamaNavigatorWidget", "Street Name", None))
        self.label_35.setText(_translate("CamaNavigatorWidget", "Bag", None))
        self.label_84.setText(_translate("CamaNavigatorWidget", "Khashaa Number", None))
        self.label_33.setText(_translate("CamaNavigatorWidget", "Parcel Number", None))
        self.parcel_find_button.setText(_translate("CamaNavigatorWidget", "Find", None))
        self.parcel_clear_button.setText(_translate("CamaNavigatorWidget", "Clear", None))
        self.is_no_calculate_chbox.setText(_translate("CamaNavigatorWidget", "Is No Calculate", None))
        self.slope_calculate_button.setText(_translate("CamaNavigatorWidget", "Calculate", None))
        self.slope_apply_button.setText(_translate("CamaNavigatorWidget", "Apply", None))
        self.print_button.setText(_translate("CamaNavigatorWidget", "Print", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("CamaNavigatorWidget", "Ө/Н-н анализ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("CamaNavigatorWidget", "Орон Зайн анализ", None))

