# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\CamaNavigatorWidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CamaNavigatorWidget(object):
    def setupUi(self, CamaNavigatorWidget):
        CamaNavigatorWidget.setObjectName(_fromUtf8("CamaNavigatorWidget"))
        CamaNavigatorWidget.resize(500, 713)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CamaNavigatorWidget.sizePolicy().hasHeightForWidth())
        CamaNavigatorWidget.setSizePolicy(sizePolicy)
        CamaNavigatorWidget.setMinimumSize(QtCore.QSize(500, 620))
        CamaNavigatorWidget.setMaximumSize(QtCore.QSize(500, 524287))
        CamaNavigatorWidget.setBaseSize(QtCore.QSize(440, 665))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setGeometry(QtCore.QRect(1, 0, 498, 650))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 600))
        self.scrollArea.setMaximumSize(QtCore.QSize(500, 650))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 500, 664))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.working_l1_cbox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.working_l1_cbox.setGeometry(QtCore.QRect(4, 4, 170, 22))
        self.working_l1_cbox.setObjectName(_fromUtf8("working_l1_cbox"))
        self.working_l2_cbox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.working_l2_cbox.setGeometry(QtCore.QRect(184, 4, 170, 22))
        self.working_l2_cbox.setObjectName(_fromUtf8("working_l2_cbox"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(2, 30, 475, 99))
        self.groupBox.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: #f5f5ef; border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.parcel_id_edit = QtGui.QLineEdit(self.groupBox)
        self.parcel_id_edit.setEnabled(True)
        self.parcel_id_edit.setGeometry(QtCore.QRect(110, 33, 135, 20))
        self.parcel_id_edit.setReadOnly(True)
        self.parcel_id_edit.setObjectName(_fromUtf8("parcel_id_edit"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(110, 17, 141, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(260, 17, 95, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.parcel_area_edit = QtGui.QLineEdit(self.groupBox)
        self.parcel_area_edit.setEnabled(False)
        self.parcel_area_edit.setGeometry(QtCore.QRect(260, 33, 95, 20))
        self.parcel_area_edit.setObjectName(_fromUtf8("parcel_area_edit"))
        self.parcel_base_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_base_price.setGeometry(QtCore.QRect(370, 33, 95, 20))
        self.parcel_base_price.setObjectName(_fromUtf8("parcel_base_price"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(110, 55, 141, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.parcel_address_edit = QtGui.QLineEdit(self.groupBox)
        self.parcel_address_edit.setEnabled(False)
        self.parcel_address_edit.setGeometry(QtCore.QRect(110, 71, 245, 20))
        self.parcel_address_edit.setObjectName(_fromUtf8("parcel_address_edit"))
        self.parcel_market_price = QtGui.QLineEdit(self.groupBox)
        self.parcel_market_price.setEnabled(False)
        self.parcel_market_price.setGeometry(QtCore.QRect(370, 71, 95, 20))
        self.parcel_market_price.setObjectName(_fromUtf8("parcel_market_price"))
        self.base_price_chbox = QtGui.QCheckBox(self.groupBox)
        self.base_price_chbox.setGeometry(QtCore.QRect(370, 16, 101, 17))
        self.base_price_chbox.setChecked(True)
        self.base_price_chbox.setObjectName(_fromUtf8("base_price_chbox"))
        self.market_price_chbox = QtGui.QCheckBox(self.groupBox)
        self.market_price_chbox.setGeometry(QtCore.QRect(370, 54, 101, 17))
        self.market_price_chbox.setObjectName(_fromUtf8("market_price_chbox"))
        self.cadastre_rbutton = QtGui.QRadioButton(self.groupBox)
        self.cadastre_rbutton.setGeometry(QtCore.QRect(10, 30, 101, 17))
        self.cadastre_rbutton.setChecked(True)
        self.cadastre_rbutton.setObjectName(_fromUtf8("cadastre_rbutton"))
        self.plan_rbutton = QtGui.QRadioButton(self.groupBox)
        self.plan_rbutton.setGeometry(QtCore.QRect(10, 50, 101, 17))
        self.plan_rbutton.setObjectName(_fromUtf8("plan_rbutton"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(2, 131, 478, 491))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(2, 1, 469, 133))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: #f5f5ef; border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.elevation_edit = QtGui.QLineEdit(self.groupBox_2)
        self.elevation_edit.setGeometry(QtCore.QRect(8, 30, 110, 20))
        self.elevation_edit.setText(_fromUtf8(""))
        self.elevation_edit.setObjectName(_fromUtf8("elevation_edit"))
        self.slopy_edit = QtGui.QLineEdit(self.groupBox_2)
        self.slopy_edit.setGeometry(QtCore.QRect(163, 30, 110, 20))
        self.slopy_edit.setText(_fromUtf8(""))
        self.slopy_edit.setObjectName(_fromUtf8("slopy_edit"))
        self.earthquake_edit = QtGui.QLineEdit(self.groupBox_2)
        self.earthquake_edit.setGeometry(QtCore.QRect(163, 65, 110, 20))
        self.earthquake_edit.setText(_fromUtf8(""))
        self.earthquake_edit.setObjectName(_fromUtf8("earthquake_edit"))
        self.rain_replicate_edit = QtGui.QLineEdit(self.groupBox_2)
        self.rain_replicate_edit.setGeometry(QtCore.QRect(320, 30, 110, 20))
        self.rain_replicate_edit.setText(_fromUtf8(""))
        self.rain_replicate_edit.setObjectName(_fromUtf8("rain_replicate_edit"))
        self.air_quality_edit = QtGui.QLineEdit(self.groupBox_2)
        self.air_quality_edit.setGeometry(QtCore.QRect(164, 103, 110, 20))
        self.air_quality_edit.setText(_fromUtf8(""))
        self.air_quality_edit.setObjectName(_fromUtf8("air_quality_edit"))
        self.soil_quality_edit = QtGui.QLineEdit(self.groupBox_2)
        self.soil_quality_edit.setGeometry(QtCore.QRect(320, 68, 110, 20))
        self.soil_quality_edit.setText(_fromUtf8(""))
        self.soil_quality_edit.setObjectName(_fromUtf8("soil_quality_edit"))
        self.permafrost_cbox = QtGui.QComboBox(self.groupBox_2)
        self.permafrost_cbox.setGeometry(QtCore.QRect(8, 65, 110, 22))
        self.permafrost_cbox.setObjectName(_fromUtf8("permafrost_cbox"))
        self.water_quality_cbox = QtGui.QComboBox(self.groupBox_2)
        self.water_quality_cbox.setGeometry(QtCore.QRect(8, 103, 110, 22))
        self.water_quality_cbox.setObjectName(_fromUtf8("water_quality_cbox"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(8, 49, 110, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(9, 14, 110, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(8, 87, 110, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(164, 14, 110, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(163, 49, 110, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(320, 14, 110, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(164, 87, 141, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(320, 52, 110, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.elevation_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.elevation_value_edit.setEnabled(False)
        self.elevation_value_edit.setGeometry(QtCore.QRect(126, 30, 25, 20))
        self.elevation_value_edit.setObjectName(_fromUtf8("elevation_value_edit"))
        self.permafrost_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.permafrost_value_edit.setEnabled(False)
        self.permafrost_value_edit.setGeometry(QtCore.QRect(126, 65, 25, 20))
        self.permafrost_value_edit.setObjectName(_fromUtf8("permafrost_value_edit"))
        self.water_quality_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.water_quality_value_edit.setEnabled(False)
        self.water_quality_value_edit.setGeometry(QtCore.QRect(126, 103, 25, 20))
        self.water_quality_value_edit.setObjectName(_fromUtf8("water_quality_value_edit"))
        self.slopy_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.slopy_value_edit.setEnabled(False)
        self.slopy_value_edit.setGeometry(QtCore.QRect(281, 30, 25, 20))
        self.slopy_value_edit.setObjectName(_fromUtf8("slopy_value_edit"))
        self.earthquake_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.earthquake_value_edit.setEnabled(False)
        self.earthquake_value_edit.setGeometry(QtCore.QRect(281, 65, 25, 20))
        self.earthquake_value_edit.setObjectName(_fromUtf8("earthquake_value_edit"))
        self.air_quality_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.air_quality_value_edit.setEnabled(False)
        self.air_quality_value_edit.setGeometry(QtCore.QRect(281, 103, 25, 20))
        self.air_quality_value_edit.setObjectName(_fromUtf8("air_quality_value_edit"))
        self.soil_quality_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.soil_quality_value_edit.setEnabled(False)
        self.soil_quality_value_edit.setGeometry(QtCore.QRect(437, 68, 25, 20))
        self.soil_quality_value_edit.setObjectName(_fromUtf8("soil_quality_value_edit"))
        self.rain_replicate_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.rain_replicate_value_edit.setEnabled(False)
        self.rain_replicate_value_edit.setGeometry(QtCore.QRect(437, 30, 25, 20))
        self.rain_replicate_value_edit.setObjectName(_fromUtf8("rain_replicate_value_edit"))
        self.environment_calc_button = QtGui.QPushButton(self.groupBox_2)
        self.environment_calc_button.setGeometry(QtCore.QRect(320, 101, 141, 23))
        self.environment_calc_button.setObjectName(_fromUtf8("environment_calc_button"))
        self.elevation_edit.raise_()
        self.slopy_edit.raise_()
        self.earthquake_edit.raise_()
        self.rain_replicate_edit.raise_()
        self.air_quality_edit.raise_()
        self.soil_quality_edit.raise_()
        self.permafrost_cbox.raise_()
        self.water_quality_cbox.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.elevation_value_edit.raise_()
        self.permafrost_value_edit.raise_()
        self.water_quality_value_edit.raise_()
        self.slopy_value_edit.raise_()
        self.earthquake_value_edit.raise_()
        self.air_quality_value_edit.raise_()
        self.soil_quality_value_edit.raise_()
        self.rain_replicate_value_edit.raise_()
        self.environment_calc_button.raise_()
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(2, 136, 469, 95))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: rgb(255, 242, 231); border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 50, 110, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.heat_line_edit = QtGui.QLineEdit(self.groupBox_3)
        self.heat_line_edit.setGeometry(QtCore.QRect(10, 31, 110, 20))
        self.heat_line_edit.setText(_fromUtf8(""))
        self.heat_line_edit.setObjectName(_fromUtf8("heat_line_edit"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(11, 15, 110, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.power_line_edit = QtGui.QLineEdit(self.groupBox_3)
        self.power_line_edit.setGeometry(QtCore.QRect(10, 66, 110, 20))
        self.power_line_edit.setText(_fromUtf8(""))
        self.power_line_edit.setObjectName(_fromUtf8("power_line_edit"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(164, 15, 111, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.water_line_edit = QtGui.QLineEdit(self.groupBox_3)
        self.water_line_edit.setGeometry(QtCore.QRect(164, 31, 110, 20))
        self.water_line_edit.setText(_fromUtf8(""))
        self.water_line_edit.setObjectName(_fromUtf8("water_line_edit"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(320, 15, 111, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.disinfect_line_edit = QtGui.QLineEdit(self.groupBox_3)
        self.disinfect_line_edit.setGeometry(QtCore.QRect(320, 31, 110, 20))
        self.disinfect_line_edit.setText(_fromUtf8(""))
        self.disinfect_line_edit.setObjectName(_fromUtf8("disinfect_line_edit"))
        self.route_edit = QtGui.QLineEdit(self.groupBox_3)
        self.route_edit.setGeometry(QtCore.QRect(164, 66, 110, 20))
        self.route_edit.setText(_fromUtf8(""))
        self.route_edit.setObjectName(_fromUtf8("route_edit"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(164, 50, 110, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(320, 50, 110, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.parking_edit = QtGui.QLineEdit(self.groupBox_3)
        self.parking_edit.setGeometry(QtCore.QRect(320, 66, 110, 20))
        self.parking_edit.setText(_fromUtf8(""))
        self.parking_edit.setObjectName(_fromUtf8("parking_edit"))
        self.power_line_value_edit = QtGui.QLineEdit(self.groupBox_3)
        self.power_line_value_edit.setEnabled(False)
        self.power_line_value_edit.setGeometry(QtCore.QRect(127, 66, 25, 20))
        self.power_line_value_edit.setObjectName(_fromUtf8("power_line_value_edit"))
        self.heat_line_value_edit = QtGui.QLineEdit(self.groupBox_3)
        self.heat_line_value_edit.setEnabled(False)
        self.heat_line_value_edit.setGeometry(QtCore.QRect(127, 31, 25, 20))
        self.heat_line_value_edit.setObjectName(_fromUtf8("heat_line_value_edit"))
        self.route_value_edit = QtGui.QLineEdit(self.groupBox_3)
        self.route_value_edit.setEnabled(False)
        self.route_value_edit.setGeometry(QtCore.QRect(282, 66, 25, 20))
        self.route_value_edit.setObjectName(_fromUtf8("route_value_edit"))
        self.water_line_value_edit = QtGui.QLineEdit(self.groupBox_3)
        self.water_line_value_edit.setEnabled(False)
        self.water_line_value_edit.setGeometry(QtCore.QRect(282, 31, 25, 20))
        self.water_line_value_edit.setObjectName(_fromUtf8("water_line_value_edit"))
        self.disinfect_line_value_edit = QtGui.QLineEdit(self.groupBox_3)
        self.disinfect_line_value_edit.setEnabled(False)
        self.disinfect_line_value_edit.setGeometry(QtCore.QRect(437, 31, 25, 20))
        self.disinfect_line_value_edit.setObjectName(_fromUtf8("disinfect_line_value_edit"))
        self.parking_value_edit = QtGui.QLineEdit(self.groupBox_3)
        self.parking_value_edit.setEnabled(False)
        self.parking_value_edit.setGeometry(QtCore.QRect(437, 66, 25, 20))
        self.parking_value_edit.setObjectName(_fromUtf8("parking_value_edit"))
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_17.raise_()
        self.label_13.raise_()
        self.label_16.raise_()
        self.label_15.raise_()
        self.heat_line_edit.raise_()
        self.label_13.raise_()
        self.power_line_edit.raise_()
        self.label_14.raise_()
        self.water_line_edit.raise_()
        self.label_16.raise_()
        self.disinfect_line_edit.raise_()
        self.route_edit.raise_()
        self.label_17.raise_()
        self.label_23.raise_()
        self.parking_edit.raise_()
        self.power_line_value_edit.raise_()
        self.heat_line_value_edit.raise_()
        self.route_value_edit.raise_()
        self.water_line_value_edit.raise_()
        self.disinfect_line_value_edit.raise_()
        self.parking_value_edit.raise_()
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(2, 233, 469, 95))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: #f5f5ef; border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(320, 14, 141, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(10, 49, 110, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.medical_edit = QtGui.QLineEdit(self.groupBox_4)
        self.medical_edit.setGeometry(QtCore.QRect(320, 30, 110, 20))
        self.medical_edit.setText(_fromUtf8(""))
        self.medical_edit.setObjectName(_fromUtf8("medical_edit"))
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(164, 14, 141, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(11, 14, 110, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.house_service_edit = QtGui.QLineEdit(self.groupBox_4)
        self.house_service_edit.setGeometry(QtCore.QRect(164, 65, 110, 20))
        self.house_service_edit.setText(_fromUtf8(""))
        self.house_service_edit.setObjectName(_fromUtf8("house_service_edit"))
        self.shcool_edit = QtGui.QLineEdit(self.groupBox_4)
        self.shcool_edit.setGeometry(QtCore.QRect(10, 30, 110, 20))
        self.shcool_edit.setText(_fromUtf8(""))
        self.shcool_edit.setObjectName(_fromUtf8("shcool_edit"))
        self.kindergarten_edit = QtGui.QLineEdit(self.groupBox_4)
        self.kindergarten_edit.setGeometry(QtCore.QRect(164, 30, 110, 20))
        self.kindergarten_edit.setText(_fromUtf8(""))
        self.kindergarten_edit.setObjectName(_fromUtf8("kindergarten_edit"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(164, 49, 110, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.admin_edit = QtGui.QLineEdit(self.groupBox_4)
        self.admin_edit.setGeometry(QtCore.QRect(10, 65, 110, 20))
        self.admin_edit.setText(_fromUtf8(""))
        self.admin_edit.setObjectName(_fromUtf8("admin_edit"))
        self.shcool_value_edit = QtGui.QLineEdit(self.groupBox_4)
        self.shcool_value_edit.setEnabled(False)
        self.shcool_value_edit.setGeometry(QtCore.QRect(128, 30, 25, 20))
        self.shcool_value_edit.setObjectName(_fromUtf8("shcool_value_edit"))
        self.admin_value_edit = QtGui.QLineEdit(self.groupBox_4)
        self.admin_value_edit.setEnabled(False)
        self.admin_value_edit.setGeometry(QtCore.QRect(128, 65, 25, 20))
        self.admin_value_edit.setObjectName(_fromUtf8("admin_value_edit"))
        self.house_service_value_edit = QtGui.QLineEdit(self.groupBox_4)
        self.house_service_value_edit.setEnabled(False)
        self.house_service_value_edit.setGeometry(QtCore.QRect(283, 65, 25, 20))
        self.house_service_value_edit.setObjectName(_fromUtf8("house_service_value_edit"))
        self.kindergarten_value_edit = QtGui.QLineEdit(self.groupBox_4)
        self.kindergarten_value_edit.setEnabled(False)
        self.kindergarten_value_edit.setGeometry(QtCore.QRect(283, 30, 25, 20))
        self.kindergarten_value_edit.setObjectName(_fromUtf8("kindergarten_value_edit"))
        self.medical_value_edit = QtGui.QLineEdit(self.groupBox_4)
        self.medical_value_edit.setEnabled(False)
        self.medical_value_edit.setGeometry(QtCore.QRect(437, 30, 25, 20))
        self.medical_value_edit.setObjectName(_fromUtf8("medical_value_edit"))
        self.label_20.raise_()
        self.label_19.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_21.raise_()
        self.medical_edit.raise_()
        self.label_22.raise_()
        self.label_18.raise_()
        self.house_service_edit.raise_()
        self.shcool_edit.raise_()
        self.kindergarten_edit.raise_()
        self.label_20.raise_()
        self.admin_edit.raise_()
        self.shcool_value_edit.raise_()
        self.admin_value_edit.raise_()
        self.house_service_value_edit.raise_()
        self.kindergarten_value_edit.raise_()
        self.medical_value_edit.raise_()
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(2, 330, 469, 63))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: rgb(255, 242, 231); border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.service_center_edit = QtGui.QLineEdit(self.groupBox_5)
        self.service_center_edit.setGeometry(QtCore.QRect(165, 30, 110, 20))
        self.service_center_edit.setText(_fromUtf8(""))
        self.service_center_edit.setObjectName(_fromUtf8("service_center_edit"))
        self.shop_center_edit = QtGui.QLineEdit(self.groupBox_5)
        self.shop_center_edit.setGeometry(QtCore.QRect(9, 30, 110, 20))
        self.shop_center_edit.setText(_fromUtf8(""))
        self.shop_center_edit.setObjectName(_fromUtf8("shop_center_edit"))
        self.label_25 = QtGui.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(10, 14, 110, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(165, 14, 141, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.shop_center_value_edit = QtGui.QLineEdit(self.groupBox_5)
        self.shop_center_value_edit.setEnabled(False)
        self.shop_center_value_edit.setGeometry(QtCore.QRect(127, 30, 25, 20))
        self.shop_center_value_edit.setObjectName(_fromUtf8("shop_center_value_edit"))
        self.service_center_value_edit = QtGui.QLineEdit(self.groupBox_5)
        self.service_center_value_edit.setEnabled(False)
        self.service_center_value_edit.setGeometry(QtCore.QRect(283, 30, 25, 20))
        self.service_center_value_edit.setObjectName(_fromUtf8("service_center_value_edit"))
        self.distinct_calc_button = QtGui.QPushButton(self.groupBox_5)
        self.distinct_calc_button.setGeometry(QtCore.QRect(320, 28, 141, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.distinct_calc_button.setFont(font)
        self.distinct_calc_button.setObjectName(_fromUtf8("distinct_calc_button"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        CamaNavigatorWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(CamaNavigatorWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CamaNavigatorWidget)

    def retranslateUi(self, CamaNavigatorWidget):
        CamaNavigatorWidget.setWindowTitle(_translate("CamaNavigatorWidget", "Selection / Filter", None))
        self.groupBox.setTitle(_translate("CamaNavigatorWidget", "Parcel Information", None))
        self.label.setText(_translate("CamaNavigatorWidget", "Нэгж талбарын дугаар", None))
        self.label_2.setText(_translate("CamaNavigatorWidget", "Талбай", None))
        self.label_4.setText(_translate("CamaNavigatorWidget", "Address", None))
        self.base_price_chbox.setText(_translate("CamaNavigatorWidget", "Суурь үнэ", None))
        self.market_price_chbox.setText(_translate("CamaNavigatorWidget", "З/З-н үнэ", None))
        self.cadastre_rbutton.setText(_translate("CamaNavigatorWidget", "Кадастр", None))
        self.plan_rbutton.setText(_translate("CamaNavigatorWidget", "Төлөвлөгөө", None))
        self.groupBox_2.setTitle(_translate("CamaNavigatorWidget", "Хүрээлэн буй орчин", None))
        self.elevation_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Өндөршил", None))
        self.slopy_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Гадаргын налуу", None))
        self.earthquake_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Газар хөдлөлийн бүс", None))
        self.rain_replicate_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Үер, усны давтамж", None))
        self.air_quality_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Агаарын чанарын индекс", None))
        self.soil_quality_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Хөрсний бохирдлын зэрэг", None))
        self.label_5.setText(_translate("CamaNavigatorWidget", "Цэвдэгтэй эсэх", None))
        self.label_6.setText(_translate("CamaNavigatorWidget", "Өндөршил", None))
        self.label_7.setText(_translate("CamaNavigatorWidget", "Усны чанарын зэрэг", None))
        self.label_8.setText(_translate("CamaNavigatorWidget", "Гадаргын налуу", None))
        self.label_9.setText(_translate("CamaNavigatorWidget", "Газар хөдлөлийн бүс", None))
        self.label_10.setText(_translate("CamaNavigatorWidget", "Үер, усны давтамж", None))
        self.label_11.setText(_translate("CamaNavigatorWidget", "Агаар/чанарын индекс", None))
        self.label_12.setText(_translate("CamaNavigatorWidget", "Хөрсний бохирдол", None))
        self.environment_calc_button.setText(_translate("CamaNavigatorWidget", "Тооцоолох", None))
        self.groupBox_3.setTitle(_translate("CamaNavigatorWidget", "Инженерийн дэд бүтэц", None))
        self.label_15.setText(_translate("CamaNavigatorWidget", "Цахилгаан", None))
        self.heat_line_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Дулааны шугам", None))
        self.label_13.setText(_translate("CamaNavigatorWidget", "Дулаан", None))
        self.power_line_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Цахилгааны шугам", None))
        self.label_14.setText(_translate("CamaNavigatorWidget", "Усан хангамж", None))
        self.water_line_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Цэвэр усны шугам", None))
        self.label_16.setText(_translate("CamaNavigatorWidget", "Ариутгал", None))
        self.disinfect_line_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Ариутгалын шугам", None))
        self.route_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Хатуу хучилттай шугам", None))
        self.label_17.setText(_translate("CamaNavigatorWidget", "Зам", None))
        self.label_23.setText(_translate("CamaNavigatorWidget", "Зогсоол", None))
        self.parking_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Авто зогсоол", None))
        self.groupBox_4.setTitle(_translate("CamaNavigatorWidget", "Нийгмийн дэд бүтэц", None))
        self.label_19.setText(_translate("CamaNavigatorWidget", "Эмнэлэг", None))
        self.label_21.setText(_translate("CamaNavigatorWidget", "Төрийн захиргаа", None))
        self.medical_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Эмнэлэг", None))
        self.label_22.setText(_translate("CamaNavigatorWidget", "Цэцэрлэг", None))
        self.label_18.setText(_translate("CamaNavigatorWidget", "Сургууль", None))
        self.house_service_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Ахуйн үйлчилгээ", None))
        self.shcool_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Сургууль", None))
        self.kindergarten_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Цэцэрлэг", None))
        self.label_20.setText(_translate("CamaNavigatorWidget", "Ахуйн үйлчилгээ", None))
        self.admin_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Төрийн захиргааны байгууллага", None))
        self.groupBox_5.setTitle(_translate("CamaNavigatorWidget", "Үйлчилгээ", None))
        self.service_center_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Үйлчилгээний төв", None))
        self.shop_center_edit.setPlaceholderText(_translate("CamaNavigatorWidget", "Худалдааны төв", None))
        self.label_25.setText(_translate("CamaNavigatorWidget", "Худалдааны төв/зах/", None))
        self.label_24.setText(_translate("CamaNavigatorWidget", "Үйлчилгээний төв", None))
        self.distinct_calc_button.setText(_translate("CamaNavigatorWidget", "Зай тооцох", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("CamaNavigatorWidget", "Хот, Суурин", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("CamaNavigatorWidget", "ХАА", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("CamaNavigatorWidget", "Зам, Ш/С", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("CamaNavigatorWidget", "Ойн Сан", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("CamaNavigatorWidget", "Усан Сан", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("CamaNavigatorWidget", "Тусгай Хэрэгцээ", None))

