# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\CreateCaseDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CreateCaseDialog(object):
    def setupUi(self, CreateCaseDialog):
        CreateCaseDialog.setObjectName(_fromUtf8("CreateCaseDialog"))
        CreateCaseDialog.resize(800, 550)
        CreateCaseDialog.setMinimumSize(QtCore.QSize(800, 550))
        CreateCaseDialog.setMaximumSize(QtCore.QSize(800, 550))
        CreateCaseDialog.setBaseSize(QtCore.QSize(335, 480))
        self.line = QtGui.QFrame(CreateCaseDialog)
        self.line.setGeometry(QtCore.QRect(0, 17, 800, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(CreateCaseDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 508, 801, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.close_button = QtGui.QPushButton(CreateCaseDialog)
        self.close_button.setGeometry(QtCore.QRect(710, 521, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.apply_button = QtGui.QPushButton(CreateCaseDialog)
        self.apply_button.setGeometry(QtCore.QRect(620, 521, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.label_6 = QtGui.QLabel(CreateCaseDialog)
        self.label_6.setGeometry(QtCore.QRect(10, 3, 311, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.help_button = QtGui.QPushButton(CreateCaseDialog)
        self.help_button.setGeometry(QtCore.QRect(531, 520, 75, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.status_label = QtGui.QLabel(CreateCaseDialog)
        self.status_label.setGeometry(QtCore.QRect(20, 530, 341, 16))
        self.status_label.setText(_fromUtf8(""))
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.tabWidget = QtGui.QTabWidget(CreateCaseDialog)
        self.tabWidget.setGeometry(QtCore.QRect(6, 29, 791, 481))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(570, 54, 121, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.created_by_edit = QtGui.QLineEdit(self.tab)
        self.created_by_edit.setGeometry(QtCore.QRect(374, 30, 190, 20))
        self.created_by_edit.setReadOnly(True)
        self.created_by_edit.setObjectName(_fromUtf8("created_by_edit"))
        self.delete_button = QtGui.QPushButton(self.tab)
        self.delete_button.setEnabled(False)
        self.delete_button.setGeometry(QtCore.QRect(298, 100, 31, 31))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.start_date = QtGui.QDateEdit(self.tab)
        self.start_date.setGeometry(QtCore.QRect(570, 29, 190, 22))
        self.start_date.setCalendarPopup(True)
        self.start_date.setObjectName(_fromUtf8("start_date"))
        self.add_button = QtGui.QPushButton(self.tab)
        self.add_button.setEnabled(False)
        self.add_button.setGeometry(QtCore.QRect(298, 60, 31, 31))
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.person_id_label = QtGui.QLabel(self.tab)
        self.person_id_label.setEnabled(False)
        self.person_id_label.setGeometry(QtCore.QRect(24, 167, 101, 16))
        self.person_id_label.setObjectName(_fromUtf8("person_id_label"))
        self.survey_date_edit = QtGui.QLineEdit(self.tab)
        self.survey_date_edit.setEnabled(False)
        self.survey_date_edit.setGeometry(QtCore.QRect(374, 113, 190, 21))
        self.survey_date_edit.setObjectName(_fromUtf8("survey_date_edit"))
        self.completed_by_edit = QtGui.QLineEdit(self.tab)
        self.completed_by_edit.setEnabled(False)
        self.completed_by_edit.setGeometry(QtCore.QRect(570, 70, 190, 21))
        self.completed_by_edit.setObjectName(_fromUtf8("completed_by_edit"))
        self.import_groupbox = QtGui.QGroupBox(self.tab)
        self.import_groupbox.setEnabled(False)
        self.import_groupbox.setGeometry(QtCore.QRect(374, 207, 381, 101))
        self.import_groupbox.setObjectName(_fromUtf8("import_groupbox"))
        self.building_shape_edit = QtGui.QLineEdit(self.import_groupbox)
        self.building_shape_edit.setGeometry(QtCore.QRect(127, 62, 200, 21))
        self.building_shape_edit.setReadOnly(True)
        self.building_shape_edit.setObjectName(_fromUtf8("building_shape_edit"))
        self.parcel_shape_edit = QtGui.QLineEdit(self.import_groupbox)
        self.parcel_shape_edit.setGeometry(QtCore.QRect(126, 32, 200, 21))
        self.parcel_shape_edit.setReadOnly(True)
        self.parcel_shape_edit.setObjectName(_fromUtf8("parcel_shape_edit"))
        self.label_3 = QtGui.QLabel(self.import_groupbox)
        self.label_3.setGeometry(QtCore.QRect(6, 64, 111, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label = QtGui.QLabel(self.import_groupbox)
        self.label.setGeometry(QtCore.QRect(8, 34, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.open_parcel_file_button = QtGui.QPushButton(self.import_groupbox)
        self.open_parcel_file_button.setGeometry(QtCore.QRect(330, 30, 40, 25))
        self.open_parcel_file_button.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_parcel_file_button.setIcon(icon)
        self.open_parcel_file_button.setObjectName(_fromUtf8("open_parcel_file_button"))
        self.open_building_file_button = QtGui.QPushButton(self.import_groupbox)
        self.open_building_file_button.setGeometry(QtCore.QRect(330, 58, 40, 25))
        self.open_building_file_button.setText(_fromUtf8(""))
        self.open_building_file_button.setIcon(icon)
        self.open_building_file_button.setObjectName(_fromUtf8("open_building_file_button"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(374, 307, 381, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(11, 57, 71, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(11, 30, 71, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.building_no_label_2 = QtGui.QLabel(self.groupBox)
        self.building_no_label_2.setGeometry(QtCore.QRect(11, 77, 141, 20))
        self.building_no_label_2.setObjectName(_fromUtf8("building_no_label_2"))
        self.khashaa_label = QtGui.QLabel(self.groupBox)
        self.khashaa_label.setGeometry(QtCore.QRect(101, 27, 211, 20))
        self.khashaa_label.setText(_fromUtf8(""))
        self.khashaa_label.setObjectName(_fromUtf8("khashaa_label"))
        self.parcel_count_label = QtGui.QLabel(self.groupBox)
        self.parcel_count_label.setGeometry(QtCore.QRect(161, 77, 51, 20))
        self.parcel_count_label.setText(_fromUtf8(""))
        self.parcel_count_label.setObjectName(_fromUtf8("parcel_count_label"))
        self.street_label = QtGui.QLabel(self.groupBox)
        self.street_label.setGeometry(QtCore.QRect(101, 54, 211, 20))
        self.street_label.setText(_fromUtf8(""))
        self.street_label.setObjectName(_fromUtf8("street_label"))
        self.building_count_label = QtGui.QLabel(self.groupBox)
        self.building_count_label.setGeometry(QtCore.QRect(161, 107, 51, 20))
        self.building_count_label.setText(_fromUtf8(""))
        self.building_count_label.setObjectName(_fromUtf8("building_count_label"))
        self.khashaa_address_label_2 = QtGui.QLabel(self.groupBox)
        self.khashaa_address_label_2.setGeometry(QtCore.QRect(11, 107, 141, 20))
        self.khashaa_address_label_2.setObjectName(_fromUtf8("khashaa_address_label_2"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(374, 12, 101, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.result_twidget = QtGui.QTreeWidget(self.tab)
        self.result_twidget.setGeometry(QtCore.QRect(14, 217, 331, 231))
        self.result_twidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.result_twidget.setObjectName(_fromUtf8("result_twidget"))
        self.result_twidget.header().setDefaultSectionSize(100)
        self.connect_app_checkbox = QtGui.QCheckBox(self.tab)
        self.connect_app_checkbox.setGeometry(QtCore.QRect(14, 0, 281, 17))
        self.connect_app_checkbox.setObjectName(_fromUtf8("connect_app_checkbox"))
        self.surveyed_by_land_office_edit = QtGui.QLineEdit(self.tab)
        self.surveyed_by_land_office_edit.setEnabled(False)
        self.surveyed_by_land_office_edit.setGeometry(QtCore.QRect(374, 157, 190, 21))
        self.surveyed_by_land_office_edit.setObjectName(_fromUtf8("surveyed_by_land_office_edit"))
        self.applications_twidget = QtGui.QTableWidget(self.tab)
        self.applications_twidget.setEnabled(False)
        self.applications_twidget.setGeometry(QtCore.QRect(14, 21, 280, 141))
        self.applications_twidget.setObjectName(_fromUtf8("applications_twidget"))
        self.applications_twidget.setColumnCount(1)
        self.applications_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.applications_twidget.setHorizontalHeaderItem(0, item)
        self.applications_twidget.horizontalHeader().setDefaultSectionSize(262)
        self.completion_date_edit = QtGui.QLineEdit(self.tab)
        self.completion_date_edit.setEnabled(False)
        self.completion_date_edit.setGeometry(QtCore.QRect(374, 70, 190, 21))
        self.completion_date_edit.setObjectName(_fromUtf8("completion_date_edit"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(570, 137, 141, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(374, 139, 161, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(374, 96, 121, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(570, 12, 101, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(374, 54, 121, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.app_person_id = QtGui.QLineEdit(self.tab)
        self.app_person_id.setEnabled(False)
        self.app_person_id.setGeometry(QtCore.QRect(24, 185, 190, 20))
        self.app_person_id.setDragEnabled(False)
        self.app_person_id.setReadOnly(False)
        self.app_person_id.setObjectName(_fromUtf8("app_person_id"))
        self.surveyed_by_surveyor_edit = QtGui.QLineEdit(self.tab)
        self.surveyed_by_surveyor_edit.setEnabled(False)
        self.surveyed_by_surveyor_edit.setGeometry(QtCore.QRect(570, 157, 190, 21))
        self.surveyed_by_surveyor_edit.setObjectName(_fromUtf8("surveyed_by_surveyor_edit"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(CreateCaseDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CreateCaseDialog)
        CreateCaseDialog.setTabOrder(self.apply_button, self.close_button)

    def retranslateUi(self, CreateCaseDialog):
        CreateCaseDialog.setWindowTitle(_translate("CreateCaseDialog", "Create Maintenance Case", None))
        self.close_button.setText(_translate("CreateCaseDialog", "Close", None))
        self.apply_button.setText(_translate("CreateCaseDialog", "Apply", None))
        self.label_6.setText(_translate("CreateCaseDialog", "Maintenance", None))
        self.help_button.setText(_translate("CreateCaseDialog", "?", None))
        self.label_9.setText(_translate("CreateCaseDialog", "Completed by:", None))
        self.delete_button.setText(_translate("CreateCaseDialog", "-", None))
        self.start_date.setDisplayFormat(_translate("CreateCaseDialog", "yyyy-MM-dd", None))
        self.add_button.setText(_translate("CreateCaseDialog", "+", None))
        self.person_id_label.setText(_translate("CreateCaseDialog", "person id", None))
        self.import_groupbox.setTitle(_translate("CreateCaseDialog", "Import", None))
        self.label_3.setText(_translate("CreateCaseDialog", "Building Shapefile", None))
        self.label.setText(_translate("CreateCaseDialog", "Parcel Shapefile", None))
        self.groupBox.setTitle(_translate("CreateCaseDialog", "Summary", None))
        self.label_8.setText(_translate("CreateCaseDialog", "Street:", None))
        self.label_7.setText(_translate("CreateCaseDialog", "Khashaa:", None))
        self.building_no_label_2.setText(_translate("CreateCaseDialog", "Number of Parcels:", None))
        self.khashaa_address_label_2.setText(_translate("CreateCaseDialog", "Number of Buildings:", None))
        self.label_4.setText(_translate("CreateCaseDialog", "User:", None))
        self.result_twidget.headerItem().setText(0, _translate("CreateCaseDialog", "Maintenance Case Objects", None))
        self.connect_app_checkbox.setText(_translate("CreateCaseDialog", "Is application to connect", None))
        item = self.applications_twidget.horizontalHeaderItem(0)
        item.setText(_translate("CreateCaseDialog", "Applications", None))
        self.label_11.setText(_translate("CreateCaseDialog", "Surveyed by surveyor:", None))
        self.label_12.setText(_translate("CreateCaseDialog", "Surveyed by land office:", None))
        self.label_10.setText(_translate("CreateCaseDialog", "Survey date:", None))
        self.label_2.setText(_translate("CreateCaseDialog", "Creation Date:", None))
        self.label_5.setText(_translate("CreateCaseDialog", "Completion date:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CreateCaseDialog", "Кадастрын өөрчлөлт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CreateCaseDialog", "Гудамжны өөрчлөлт", None))

import resources_rc
