# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\FinalizeCaseDialog.ui'
#
# Created: Fri Jul 03 14:15:39 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FinalizeCaseDialog(object):
    def setupUi(self, FinalizeCaseDialog):
        FinalizeCaseDialog.setObjectName(_fromUtf8("FinalizeCaseDialog"))
        FinalizeCaseDialog.resize(335, 600)
        FinalizeCaseDialog.setMinimumSize(QtCore.QSize(335, 600))
        FinalizeCaseDialog.setMaximumSize(QtCore.QSize(335, 600))
        FinalizeCaseDialog.setBaseSize(QtCore.QSize(335, 600))
        self.label_6 = QtGui.QLabel(FinalizeCaseDialog)
        self.label_6.setGeometry(QtCore.QRect(10, 8, 321, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line = QtGui.QFrame(FinalizeCaseDialog)
        self.line.setGeometry(QtCore.QRect(0, 25, 335, 3))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.cancel_button = QtGui.QPushButton(FinalizeCaseDialog)
        self.cancel_button.setGeometry(QtCore.QRect(250, 568, 75, 23))
        self.cancel_button.setObjectName(_fromUtf8("cancel_button"))
        self.line_2 = QtGui.QFrame(FinalizeCaseDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 567, 335, 3))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.ok_button = QtGui.QPushButton(FinalizeCaseDialog)
        self.ok_button.setGeometry(QtCore.QRect(165, 568, 75, 23))
        self.ok_button.setObjectName(_fromUtf8("ok_button"))
        self.groupBox = QtGui.QGroupBox(FinalizeCaseDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 96, 313, 142))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.company_rbutton = QtGui.QRadioButton(self.groupBox)
        self.company_rbutton.setGeometry(QtCore.QRect(22, 40, 96, 21))
        self.company_rbutton.setChecked(True)
        self.company_rbutton.setObjectName(_fromUtf8("company_rbutton"))
        self.land_office_rbutton = QtGui.QRadioButton(self.groupBox)
        self.land_office_rbutton.setGeometry(QtCore.QRect(172, 41, 101, 21))
        self.land_office_rbutton.setObjectName(_fromUtf8("land_office_rbutton"))
        self.company_cbox = QtGui.QComboBox(self.groupBox)
        self.company_cbox.setGeometry(QtCore.QRect(20, 78, 130, 20))
        self.company_cbox.setObjectName(_fromUtf8("company_cbox"))
        self.land_office_cbox = QtGui.QComboBox(self.groupBox)
        self.land_office_cbox.setEnabled(False)
        self.land_office_cbox.setGeometry(QtCore.QRect(170, 78, 130, 20))
        self.land_office_cbox.setObjectName(_fromUtf8("land_office_cbox"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(22, 61, 131, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(175, 61, 126, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.surveyor_cbox = QtGui.QComboBox(self.groupBox)
        self.surveyor_cbox.setGeometry(QtCore.QRect(20, 114, 130, 20))
        self.surveyor_cbox.setObjectName(_fromUtf8("surveyor_cbox"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(22, 98, 131, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(23, 18, 73, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.survey_date_edit = QtGui.QDateEdit(self.groupBox)
        self.survey_date_edit.setGeometry(QtCore.QRect(139, 16, 161, 20))
        self.survey_date_edit.setCalendarPopup(True)
        self.survey_date_edit.setObjectName(_fromUtf8("survey_date_edit"))
        self.groupBox_2 = QtGui.QGroupBox(FinalizeCaseDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 313, 67))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 15, 71, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.created_by_edit = QtGui.QLineEdit(self.groupBox_2)
        self.created_by_edit.setGeometry(QtCore.QRect(139, 13, 161, 20))
        self.created_by_edit.setReadOnly(True)
        self.created_by_edit.setObjectName(_fromUtf8("created_by_edit"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.creation_date_line_edit = QtGui.QLineEdit(self.groupBox_2)
        self.creation_date_line_edit.setGeometry(QtCore.QRect(139, 38, 161, 20))
        self.creation_date_line_edit.setReadOnly(True)
        self.creation_date_line_edit.setObjectName(_fromUtf8("creation_date_line_edit"))
        self.groupBox_3 = QtGui.QGroupBox(FinalizeCaseDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 240, 313, 65))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.user_name_edit = QtGui.QLineEdit(self.groupBox_3)
        self.user_name_edit.setGeometry(QtCore.QRect(140, 38, 161, 20))
        self.user_name_edit.setReadOnly(True)
        self.user_name_edit.setObjectName(_fromUtf8("user_name_edit"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(21, 40, 70, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.completion_date_edit = QtGui.QDateEdit(self.groupBox_3)
        self.completion_date_edit.setGeometry(QtCore.QRect(140, 13, 161, 20))
        self.completion_date_edit.setCalendarPopup(True)
        self.completion_date_edit.setObjectName(_fromUtf8("completion_date_edit"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(20, 16, 121, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(FinalizeCaseDialog)
        self.label_11.setGeometry(QtCore.QRect(25, 437, 111, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(FinalizeCaseDialog)
        self.label_12.setGeometry(QtCore.QRect(185, 439, 71, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.number_of_parcel_lbl = QtGui.QLabel(FinalizeCaseDialog)
        self.number_of_parcel_lbl.setGeometry(QtCore.QRect(130, 436, 38, 20))
        self.number_of_parcel_lbl.setText(_fromUtf8(""))
        self.number_of_parcel_lbl.setObjectName(_fromUtf8("number_of_parcel_lbl"))
        self.number_of_building_lbl = QtGui.QLabel(FinalizeCaseDialog)
        self.number_of_building_lbl.setGeometry(QtCore.QRect(255, 434, 61, 21))
        self.number_of_building_lbl.setText(_fromUtf8(""))
        self.number_of_building_lbl.setObjectName(_fromUtf8("number_of_building_lbl"))
        self.help_button = QtGui.QPushButton(FinalizeCaseDialog)
        self.help_button.setGeometry(QtCore.QRect(81, 568, 75, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.maintenance_objects_twidget = QtGui.QTreeWidget(FinalizeCaseDialog)
        self.maintenance_objects_twidget.setGeometry(QtCore.QRect(10, 310, 311, 127))
        self.maintenance_objects_twidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.maintenance_objects_twidget.setObjectName(_fromUtf8("maintenance_objects_twidget"))
        self.groupBox_4 = QtGui.QGroupBox(FinalizeCaseDialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 454, 311, 111))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(13, 15, 81, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(13, 34, 81, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.street_name_edit = QtGui.QLineEdit(self.groupBox_4)
        self.street_name_edit.setGeometry(QtCore.QRect(140, 11, 162, 20))
        self.street_name_edit.setObjectName(_fromUtf8("street_name_edit"))
        self.khashaa_edit = QtGui.QLineEdit(self.groupBox_4)
        self.khashaa_edit.setGeometry(QtCore.QRect(140, 35, 162, 20))
        self.khashaa_edit.setObjectName(_fromUtf8("khashaa_edit"))
        self.address_insert_button = QtGui.QPushButton(self.groupBox_4)
        self.address_insert_button.setGeometry(QtCore.QRect(140, 60, 161, 23))
        self.address_insert_button.setObjectName(_fromUtf8("address_insert_button"))
        self.error_label = QtGui.QLabel(self.groupBox_4)
        self.error_label.setGeometry(QtCore.QRect(14, 88, 291, 16))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setObjectName(_fromUtf8("error_label"))

        self.retranslateUi(FinalizeCaseDialog)
        QtCore.QMetaObject.connectSlotsByName(FinalizeCaseDialog)
        FinalizeCaseDialog.setTabOrder(self.created_by_edit, self.company_rbutton)
        FinalizeCaseDialog.setTabOrder(self.company_rbutton, self.company_cbox)
        FinalizeCaseDialog.setTabOrder(self.company_cbox, self.surveyor_cbox)
        FinalizeCaseDialog.setTabOrder(self.surveyor_cbox, self.land_office_rbutton)
        FinalizeCaseDialog.setTabOrder(self.land_office_rbutton, self.land_office_cbox)
        FinalizeCaseDialog.setTabOrder(self.land_office_cbox, self.user_name_edit)
        FinalizeCaseDialog.setTabOrder(self.user_name_edit, self.ok_button)
        FinalizeCaseDialog.setTabOrder(self.ok_button, self.cancel_button)

    def retranslateUi(self, FinalizeCaseDialog):
        FinalizeCaseDialog.setWindowTitle(_translate("FinalizeCaseDialog", "Finalize Maintenance Case", None))
        self.label_6.setText(_translate("FinalizeCaseDialog", "Finalize Maintenance Case", None))
        self.cancel_button.setText(_translate("FinalizeCaseDialog", "Close", None))
        self.ok_button.setText(_translate("FinalizeCaseDialog", "Finalize", None))
        self.groupBox.setTitle(_translate("FinalizeCaseDialog", "Surveyed By", None))
        self.company_rbutton.setText(_translate("FinalizeCaseDialog", "Company", None))
        self.land_office_rbutton.setText(_translate("FinalizeCaseDialog", "Land Office", None))
        self.label_4.setText(_translate("FinalizeCaseDialog", "Company Name", None))
        self.label_5.setText(_translate("FinalizeCaseDialog", "Name", None))
        self.label_7.setText(_translate("FinalizeCaseDialog", "Surveyor Name", None))
        self.label_8.setText(_translate("FinalizeCaseDialog", "Survey Date:", None))
        self.survey_date_edit.setDisplayFormat(_translate("FinalizeCaseDialog", "yyyy-MM-dd", None))
        self.groupBox_2.setTitle(_translate("FinalizeCaseDialog", "Creation", None))
        self.label_3.setText(_translate("FinalizeCaseDialog", "Created By:", None))
        self.label_9.setText(_translate("FinalizeCaseDialog", "Creation Date:", None))
        self.groupBox_3.setTitle(_translate("FinalizeCaseDialog", "Completion", None))
        self.label.setText(_translate("FinalizeCaseDialog", "Completed by:", None))
        self.completion_date_edit.setDisplayFormat(_translate("FinalizeCaseDialog", "yyyy-MM-dd", None))
        self.label_10.setText(_translate("FinalizeCaseDialog", "Completion Date:", None))
        self.label_11.setText(_translate("FinalizeCaseDialog", "Parcels:", None))
        self.label_12.setText(_translate("FinalizeCaseDialog", "Buildings:", None))
        self.help_button.setText(_translate("FinalizeCaseDialog", "?", None))
        self.maintenance_objects_twidget.headerItem().setText(0, _translate("FinalizeCaseDialog", "Maintenance Objects", None))
        self.groupBox_4.setTitle(_translate("FinalizeCaseDialog", "Address", None))
        self.label_2.setText(_translate("FinalizeCaseDialog", "Street name:", None))
        self.label_13.setText(_translate("FinalizeCaseDialog", "Khashaa:", None))
        self.address_insert_button.setText(_translate("FinalizeCaseDialog", "address insert", None))

