# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ImportDecisionDialog.ui'
#
# Created: Fri Sep 16 16:25:18 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImportDecisionDialog(object):
    def setupUi(self, ImportDecisionDialog):
        ImportDecisionDialog.setObjectName(_fromUtf8("ImportDecisionDialog"))
        ImportDecisionDialog.resize(800, 497)
        ImportDecisionDialog.setMinimumSize(QtCore.QSize(800, 497))
        ImportDecisionDialog.setMaximumSize(QtCore.QSize(800, 497))
        self.line = QtGui.QFrame(ImportDecisionDialog)
        self.line.setGeometry(QtCore.QRect(0, 26, 800, 3))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(ImportDecisionDialog)
        self.label.setGeometry(QtCore.QRect(10, 8, 300, 12))
        self.label.setObjectName(_fromUtf8("label"))
        self.line_2 = QtGui.QFrame(ImportDecisionDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 480, 800, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.tabWidget = QtGui.QTabWidget(ImportDecisionDialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 796, 451))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.close_button = QtGui.QPushButton(self.tab)
        self.close_button.setGeometry(QtCore.QRect(684, 395, 73, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.import_button = QtGui.QPushButton(self.tab)
        self.import_button.setGeometry(QtCore.QRect(594, 395, 73, 23))
        self.import_button.setObjectName(_fromUtf8("import_button"))
        self.Landownershiptranspor = QtGui.QGroupBox(self.tab)
        self.Landownershiptranspor.setGeometry(QtCore.QRect(604, 0, 178, 380))
        self.Landownershiptranspor.setObjectName(_fromUtf8("Landownershiptranspor"))
        self.contract_date = QtGui.QDateEdit(self.Landownershiptranspor)
        self.contract_date.setEnabled(False)
        self.contract_date.setGeometry(QtCore.QRect(10, 160, 126, 22))
        self.contract_date.setObjectName(_fromUtf8("contract_date"))
        self.label_7 = QtGui.QLabel(self.Landownershiptranspor)
        self.label_7.setGeometry(QtCore.QRect(10, 53, 155, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.Landownershiptranspor)
        self.label_8.setGeometry(QtCore.QRect(10, 97, 155, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_10 = QtGui.QLabel(self.Landownershiptranspor)
        self.label_10.setGeometry(QtCore.QRect(10, 140, 155, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.contract_id_edit = QtGui.QLineEdit(self.Landownershiptranspor)
        self.contract_id_edit.setEnabled(False)
        self.contract_id_edit.setGeometry(QtCore.QRect(10, 246, 127, 20))
        self.contract_id_edit.setObjectName(_fromUtf8("contract_id_edit"))
        self.seller_buyer_checkbox = QtGui.QCheckBox(self.Landownershiptranspor)
        self.seller_buyer_checkbox.setGeometry(QtCore.QRect(13, 25, 161, 17))
        self.seller_buyer_checkbox.setObjectName(_fromUtf8("seller_buyer_checkbox"))
        self.label_9 = QtGui.QLabel(self.Landownershiptranspor)
        self.label_9.setGeometry(QtCore.QRect(10, 226, 155, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.application_cbox = QtGui.QComboBox(self.Landownershiptranspor)
        self.application_cbox.setEnabled(False)
        self.application_cbox.setGeometry(QtCore.QRect(10, 117, 155, 22))
        self.application_cbox.setObjectName(_fromUtf8("application_cbox"))
        self.decision_save_button = QtGui.QPushButton(self.Landownershiptranspor)
        self.decision_save_button.setEnabled(False)
        self.decision_save_button.setGeometry(QtCore.QRect(20, 320, 141, 23))
        self.decision_save_button.setObjectName(_fromUtf8("decision_save_button"))
        self.person_id_edit = QtGui.QLineEdit(self.Landownershiptranspor)
        self.person_id_edit.setEnabled(False)
        self.person_id_edit.setGeometry(QtCore.QRect(10, 73, 127, 20))
        self.person_id_edit.setObjectName(_fromUtf8("person_id_edit"))
        self.notary_decision_edit = QtGui.QLineEdit(self.Landownershiptranspor)
        self.notary_decision_edit.setGeometry(QtCore.QRect(10, 289, 155, 20))
        self.notary_decision_edit.setReadOnly(True)
        self.notary_decision_edit.setObjectName(_fromUtf8("notary_decision_edit"))
        self.label_11 = QtGui.QLabel(self.Landownershiptranspor)
        self.label_11.setGeometry(QtCore.QRect(10, 269, 155, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.notary_number_edit = QtGui.QLineEdit(self.Landownershiptranspor)
        self.notary_number_edit.setEnabled(False)
        self.notary_number_edit.setGeometry(QtCore.QRect(10, 204, 127, 20))
        self.notary_number_edit.setObjectName(_fromUtf8("notary_number_edit"))
        self.label_12 = QtGui.QLabel(self.Landownershiptranspor)
        self.label_12.setGeometry(QtCore.QRect(10, 184, 155, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(4, 0, 589, 381))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 23, 300, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.decision_file_edit = QtGui.QLineEdit(self.groupBox)
        self.decision_file_edit.setGeometry(QtCore.QRect(30, 43, 231, 20))
        self.decision_file_edit.setObjectName(_fromUtf8("decision_file_edit"))
        self.select_file_button = QtGui.QPushButton(self.groupBox)
        self.select_file_button.setGeometry(QtCore.QRect(280, 42, 100, 23))
        self.select_file_button.setObjectName(_fromUtf8("select_file_button"))
        self.decision_no_edit = QtGui.QLineEdit(self.groupBox)
        self.decision_no_edit.setEnabled(False)
        self.decision_no_edit.setGeometry(QtCore.QRect(30, 94, 111, 21))
        self.decision_no_edit.setObjectName(_fromUtf8("decision_no_edit"))
        self.decision_date_edit = QtGui.QLineEdit(self.groupBox)
        self.decision_date_edit.setEnabled(False)
        self.decision_date_edit.setGeometry(QtCore.QRect(160, 94, 101, 21))
        self.decision_date_edit.setObjectName(_fromUtf8("decision_date_edit"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 74, 131, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(160, 74, 93, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.level_cbox = QtGui.QComboBox(self.groupBox)
        self.level_cbox.setEnabled(False)
        self.level_cbox.setGeometry(QtCore.QRect(280, 91, 281, 26))
        self.level_cbox.setObjectName(_fromUtf8("level_cbox"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(280, 71, 256, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.documents_groupbox = QtGui.QGroupBox(self.groupBox)
        self.documents_groupbox.setGeometry(QtCore.QRect(270, 170, 301, 181))
        self.documents_groupbox.setObjectName(_fromUtf8("documents_groupbox"))
        self.document_twidget = QtGui.QListWidget(self.documents_groupbox)
        self.document_twidget.setGeometry(QtCore.QRect(10, 30, 196, 141))
        self.document_twidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.document_twidget.setObjectName(_fromUtf8("document_twidget"))
        self.add_document_button = QtGui.QPushButton(self.documents_groupbox)
        self.add_document_button.setEnabled(False)
        self.add_document_button.setGeometry(QtCore.QRect(213, 65, 81, 32))
        self.add_document_button.setObjectName(_fromUtf8("add_document_button"))
        self.delete_document_button = QtGui.QPushButton(self.documents_groupbox)
        self.delete_document_button.setEnabled(False)
        self.delete_document_button.setGeometry(QtCore.QRect(213, 130, 81, 32))
        self.delete_document_button.setObjectName(_fromUtf8("delete_document_button"))
        self.view_document_button = QtGui.QPushButton(self.documents_groupbox)
        self.view_document_button.setEnabled(False)
        self.view_document_button.setGeometry(QtCore.QRect(213, 98, 81, 32))
        self.view_document_button.setObjectName(_fromUtf8("view_document_button"))
        self.load_document_button = QtGui.QPushButton(self.documents_groupbox)
        self.load_document_button.setEnabled(False)
        self.load_document_button.setGeometry(QtCore.QRect(213, 32, 81, 32))
        self.load_document_button.setObjectName(_fromUtf8("load_document_button"))
        self.result_tree_widget = QtGui.QTreeWidget(self.groupBox)
        self.result_tree_widget.setGeometry(QtCore.QRect(30, 131, 231, 221))
        self.result_tree_widget.setObjectName(_fromUtf8("result_tree_widget"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(280, 121, 91, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.import_by_edit = QtGui.QLineEdit(self.groupBox)
        self.import_by_edit.setEnabled(False)
        self.import_by_edit.setGeometry(QtCore.QRect(280, 141, 197, 21))
        self.import_by_edit.setObjectName(_fromUtf8("import_by_edit"))
        self.error_details_button = QtGui.QPushButton(self.groupBox)
        self.error_details_button.setEnabled(False)
        self.error_details_button.setGeometry(QtCore.QRect(27, 350, 151, 23))
        self.error_details_button.setObjectName(_fromUtf8("error_details_button"))
        self.help_button = QtGui.QPushButton(self.tab)
        self.help_button.setGeometry(QtCore.QRect(483, 395, 89, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.status_label = QtGui.QLabel(self.tab)
        self.status_label.setGeometry(QtCore.QRect(10, 390, 461, 21))
        self.status_label.setText(_fromUtf8(""))
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(4, 0, 281, 421))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 56, 131, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.decision_no_search_edit = QtGui.QLineEdit(self.groupBox_2)
        self.decision_no_search_edit.setGeometry(QtCore.QRect(10, 33, 259, 20))
        self.decision_no_search_edit.setObjectName(_fromUtf8("decision_no_search_edit"))
        self.decision_date_result_edit = QtGui.QLineEdit(self.groupBox_2)
        self.decision_date_result_edit.setEnabled(False)
        self.decision_date_result_edit.setGeometry(QtCore.QRect(148, 76, 121, 21))
        self.decision_date_result_edit.setObjectName(_fromUtf8("decision_date_result_edit"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 99, 256, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.decision_result_twidget = QtGui.QTableWidget(self.groupBox_2)
        self.decision_result_twidget.setGeometry(QtCore.QRect(10, 216, 261, 191))
        self.decision_result_twidget.setObjectName(_fromUtf8("decision_result_twidget"))
        self.decision_result_twidget.setColumnCount(1)
        self.decision_result_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.decision_result_twidget.setHorizontalHeaderItem(0, item)
        self.decision_result_twidget.horizontalHeader().setDefaultSectionSize(250)
        self.decision_no_result_edit = QtGui.QLineEdit(self.groupBox_2)
        self.decision_no_result_edit.setEnabled(False)
        self.decision_no_result_edit.setGeometry(QtCore.QRect(10, 76, 121, 21))
        self.decision_no_result_edit.setObjectName(_fromUtf8("decision_no_result_edit"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(148, 56, 121, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.application_type_edit = QtGui.QLineEdit(self.groupBox_2)
        self.application_type_edit.setEnabled(False)
        self.application_type_edit.setGeometry(QtCore.QRect(10, 169, 261, 21))
        self.application_type_edit.setObjectName(_fromUtf8("application_type_edit"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 149, 261, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 13, 201, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(11, 196, 201, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.level_result_edit = QtGui.QLineEdit(self.groupBox_2)
        self.level_result_edit.setEnabled(False)
        self.level_result_edit.setGeometry(QtCore.QRect(10, 120, 261, 21))
        self.level_result_edit.setObjectName(_fromUtf8("level_result_edit"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(300, 0, 481, 421))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.person_id_find_edit = QtGui.QLineEdit(self.groupBox_3)
        self.person_id_find_edit.setGeometry(QtCore.QRect(10, 33, 121, 20))
        self.person_id_find_edit.setObjectName(_fromUtf8("person_id_find_edit"))
        self.app_cancel_button = QtGui.QPushButton(self.groupBox_3)
        self.app_cancel_button.setGeometry(QtCore.QRect(148, 241, 60, 23))
        self.app_cancel_button.setObjectName(_fromUtf8("app_cancel_button"))
        self.app_join_button = QtGui.QPushButton(self.groupBox_3)
        self.app_join_button.setGeometry(QtCore.QRect(78, 241, 60, 23))
        self.app_join_button.setObjectName(_fromUtf8("app_join_button"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(11, 14, 121, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.result_app_twidget = QtGui.QTableWidget(self.groupBox_3)
        self.result_app_twidget.setGeometry(QtCore.QRect(10, 104, 261, 131))
        self.result_app_twidget.setObjectName(_fromUtf8("result_app_twidget"))
        self.result_app_twidget.setColumnCount(1)
        self.result_app_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.result_app_twidget.setHorizontalHeaderItem(0, item)
        self.result_app_twidget.horizontalHeader().setDefaultSectionSize(250)
        self.join_app_twidget = QtGui.QTableWidget(self.groupBox_3)
        self.join_app_twidget.setGeometry(QtCore.QRect(10, 270, 261, 137))
        self.join_app_twidget.setObjectName(_fromUtf8("join_app_twidget"))
        self.join_app_twidget.setColumnCount(1)
        self.join_app_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.join_app_twidget.setHorizontalHeaderItem(0, item)
        self.join_app_twidget.horizontalHeader().setDefaultSectionSize(250)
        self.app_no_find_edit = QtGui.QLineEdit(self.groupBox_3)
        self.app_no_find_edit.setGeometry(QtCore.QRect(139, 33, 132, 20))
        self.app_no_find_edit.setObjectName(_fromUtf8("app_no_find_edit"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(140, 13, 131, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(280, 13, 191, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.officer_by_find_cbox = QtGui.QComboBox(self.groupBox_3)
        self.officer_by_find_cbox.setGeometry(QtCore.QRect(280, 33, 193, 22))
        self.officer_by_find_cbox.setObjectName(_fromUtf8("officer_by_find_cbox"))
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(10, 56, 261, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.app_find_button = QtGui.QPushButton(self.groupBox_3)
        self.app_find_button.setGeometry(QtCore.QRect(279, 73, 91, 23))
        self.app_find_button.setObjectName(_fromUtf8("app_find_button"))
        self.parcel_id_find_edit = QtGui.QLineEdit(self.groupBox_3)
        self.parcel_id_find_edit.setGeometry(QtCore.QRect(10, 75, 261, 20))
        self.parcel_id_find_edit.setObjectName(_fromUtf8("parcel_id_find_edit"))
        self.clear_button = QtGui.QPushButton(self.groupBox_3)
        self.clear_button.setGeometry(QtCore.QRect(382, 73, 91, 23))
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.save_button = QtGui.QPushButton(self.groupBox_3)
        self.save_button.setGeometry(QtCore.QRect(279, 385, 194, 23))
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(280, 110, 191, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.surname_edit = QtGui.QLineEdit(self.groupBox_3)
        self.surname_edit.setGeometry(QtCore.QRect(280, 130, 191, 20))
        self.surname_edit.setObjectName(_fromUtf8("surname_edit"))
        self.firstname_edit = QtGui.QLineEdit(self.groupBox_3)
        self.firstname_edit.setGeometry(QtCore.QRect(280, 173, 191, 20))
        self.firstname_edit.setObjectName(_fromUtf8("firstname_edit"))
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(280, 153, 191, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(280, 195, 191, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.streetname_edit = QtGui.QLineEdit(self.groupBox_3)
        self.streetname_edit.setGeometry(QtCore.QRect(280, 215, 191, 20))
        self.streetname_edit.setObjectName(_fromUtf8("streetname_edit"))
        self.label_26 = QtGui.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(280, 240, 191, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.khashaa_edit = QtGui.QLineEdit(self.groupBox_3)
        self.khashaa_edit.setGeometry(QtCore.QRect(280, 260, 191, 20))
        self.khashaa_edit.setObjectName(_fromUtf8("khashaa_edit"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(ImportDecisionDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ImportDecisionDialog)

    def retranslateUi(self, ImportDecisionDialog):
        ImportDecisionDialog.setWindowTitle(_translate("ImportDecisionDialog", "Import / View Decisions", None))
        self.label.setText(_translate("ImportDecisionDialog", "ImportDecisions", None))
        self.close_button.setText(_translate("ImportDecisionDialog", "Close", None))
        self.import_button.setText(_translate("ImportDecisionDialog", "Import", None))
        self.Landownershiptranspor.setTitle(_translate("ImportDecisionDialog", "Transfer right for ownership", None))
        self.label_7.setText(_translate("ImportDecisionDialog", "Person Id", None))
        self.label_8.setText(_translate("ImportDecisionDialog", "Application List", None))
        self.label_10.setText(_translate("ImportDecisionDialog", "Contract Date", None))
        self.seller_buyer_checkbox.setText(_translate("ImportDecisionDialog", "Seller/Buyer", None))
        self.label_9.setText(_translate("ImportDecisionDialog", "Notary Contract Id", None))
        self.decision_save_button.setText(_translate("ImportDecisionDialog", "Natory Decision Save", None))
        self.label_11.setText(_translate("ImportDecisionDialog", "Notary Decision Number", None))
        self.label_12.setText(_translate("ImportDecisionDialog", "Notary Number", None))
        self.groupBox.setTitle(_translate("ImportDecisionDialog", "Import", None))
        self.label_2.setText(_translate("ImportDecisionDialog", "Decision File", None))
        self.select_file_button.setText(_translate("ImportDecisionDialog", "Select File", None))
        self.label_3.setText(_translate("ImportDecisionDialog", "Decision Number", None))
        self.label_4.setText(_translate("ImportDecisionDialog", "Decision Date", None))
        self.label_5.setText(_translate("ImportDecisionDialog", "Level", None))
        self.documents_groupbox.setTitle(_translate("ImportDecisionDialog", "Attached Document(s)", None))
        self.add_document_button.setText(_translate("ImportDecisionDialog", "Add", None))
        self.delete_document_button.setText(_translate("ImportDecisionDialog", "Delete", None))
        self.view_document_button.setText(_translate("ImportDecisionDialog", "View", None))
        self.load_document_button.setText(_translate("ImportDecisionDialog", "Load", None))
        self.result_tree_widget.headerItem().setText(0, _translate("ImportDecisionDialog", "Result Log", None))
        self.label_6.setText(_translate("ImportDecisionDialog", "Imported by", None))
        self.error_details_button.setText(_translate("ImportDecisionDialog", "Error Details", None))
        self.help_button.setText(_translate("ImportDecisionDialog", "?", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ImportDecisionDialog", "Import", None))
        self.groupBox_2.setTitle(_translate("ImportDecisionDialog", "Decision", None))
        self.label_17.setText(_translate("ImportDecisionDialog", "Decision Number", None))
        self.label_16.setText(_translate("ImportDecisionDialog", "Level", None))
        item = self.decision_result_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ImportDecisionDialog", "Decision_No", None))
        self.label_15.setText(_translate("ImportDecisionDialog", "Decision Date", None))
        self.label_18.setText(_translate("ImportDecisionDialog", "Application Type", None))
        self.label_13.setText(_translate("ImportDecisionDialog", "Decision Number", None))
        self.label_14.setText(_translate("ImportDecisionDialog", "Decision List", None))
        self.groupBox_3.setTitle(_translate("ImportDecisionDialog", "Application", None))
        self.app_cancel_button.setText(_translate("ImportDecisionDialog", "Up", None))
        self.app_join_button.setText(_translate("ImportDecisionDialog", "Down", None))
        self.label_19.setText(_translate("ImportDecisionDialog", "Person Id", None))
        item = self.result_app_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ImportDecisionDialog", "Application Number", None))
        item = self.join_app_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ImportDecisionDialog", "Application Number", None))
        self.label_20.setText(_translate("ImportDecisionDialog", "Application Number", None))
        self.label_21.setText(_translate("ImportDecisionDialog", "Officer by", None))
        self.label_22.setText(_translate("ImportDecisionDialog", "Parcel Id", None))
        self.app_find_button.setText(_translate("ImportDecisionDialog", "Find", None))
        self.clear_button.setText(_translate("ImportDecisionDialog", "Clear", None))
        self.save_button.setText(_translate("ImportDecisionDialog", "Save", None))
        self.label_23.setText(_translate("ImportDecisionDialog", "Surname", None))
        self.label_24.setText(_translate("ImportDecisionDialog", "First name", None))
        self.label_25.setText(_translate("ImportDecisionDialog", "Street name", None))
        self.label_26.setText(_translate("ImportDecisionDialog", "Khashaa", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ImportDecisionDialog", "Join application", None))

