# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MemberGroupDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MemberGroupDialog(object):
    def setupUi(self, MemberGroupDialog):
        MemberGroupDialog.setObjectName(_fromUtf8("MemberGroupDialog"))
        MemberGroupDialog.resize(698, 465)
        MemberGroupDialog.setMinimumSize(QtCore.QSize(698, 465))
        MemberGroupDialog.setMaximumSize(QtCore.QSize(698, 465))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/crops.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MemberGroupDialog.setWindowIcon(icon)
        self.line = QtGui.QFrame(MemberGroupDialog)
        self.line.setGeometry(QtCore.QRect(0, 20, 693, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(MemberGroupDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(MemberGroupDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 331, 391))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.group_twidget = QtGui.QTableWidget(self.groupBox)
        self.group_twidget.setGeometry(QtCore.QRect(10, 90, 311, 174))
        self.group_twidget.setObjectName(_fromUtf8("group_twidget"))
        self.group_twidget.setColumnCount(3)
        self.group_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.group_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.group_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.group_twidget.setHorizontalHeaderItem(2, item)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 14, 113, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.group_id_edit = QtGui.QLineEdit(self.groupBox)
        self.group_id_edit.setGeometry(QtCore.QRect(10, 34, 113, 20))
        self.group_id_edit.setReadOnly(True)
        self.group_id_edit.setObjectName(_fromUtf8("group_id_edit"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(130, 14, 113, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.group_name_edit = QtGui.QLineEdit(self.groupBox)
        self.group_name_edit.setGeometry(QtCore.QRect(130, 34, 191, 20))
        self.group_name_edit.setObjectName(_fromUtf8("group_name_edit"))
        self.group_add_button = QtGui.QPushButton(self.groupBox)
        self.group_add_button.setGeometry(QtCore.QRect(78, 60, 51, 23))
        self.group_add_button.setObjectName(_fromUtf8("group_add_button"))
        self.group_edit_button = QtGui.QPushButton(self.groupBox)
        self.group_edit_button.setGeometry(QtCore.QRect(138, 60, 51, 23))
        self.group_edit_button.setObjectName(_fromUtf8("group_edit_button"))
        self.group_delete_button = QtGui.QPushButton(self.groupBox)
        self.group_delete_button.setGeometry(QtCore.QRect(198, 60, 51, 23))
        self.group_delete_button.setObjectName(_fromUtf8("group_delete_button"))
        self.bag_cbox = QtGui.QComboBox(self.groupBox)
        self.bag_cbox.setGeometry(QtCore.QRect(10, 290, 113, 22))
        self.bag_cbox.setObjectName(_fromUtf8("bag_cbox"))
        self.bag_add_button = QtGui.QPushButton(self.groupBox)
        self.bag_add_button.setGeometry(QtCore.QRect(147, 281, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bag_add_button.sizePolicy().hasHeightForWidth())
        self.bag_add_button.setSizePolicy(sizePolicy)
        self.bag_add_button.setBaseSize(QtCore.QSize(0, 0))
        self.bag_add_button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2_pasture/double_angle_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bag_add_button.setIcon(icon1)
        self.bag_add_button.setObjectName(_fromUtf8("bag_add_button"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 111, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.bag_remove_button = QtGui.QPushButton(self.groupBox)
        self.bag_remove_button.setGeometry(QtCore.QRect(147, 319, 31, 31))
        self.bag_remove_button.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2_pasture/double_angle_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bag_remove_button.setIcon(icon2)
        self.bag_remove_button.setObjectName(_fromUtf8("bag_remove_button"))
        self.bag_twidget = QtGui.QTableWidget(self.groupBox)
        self.bag_twidget.setGeometry(QtCore.QRect(200, 270, 121, 114))
        self.bag_twidget.setObjectName(_fromUtf8("bag_twidget"))
        self.bag_twidget.setColumnCount(1)
        self.bag_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.bag_twidget.setHorizontalHeaderItem(0, item)
        self.group_new_button = QtGui.QPushButton(self.groupBox)
        self.group_new_button.setGeometry(QtCore.QRect(9, 60, 51, 23))
        self.group_new_button.setObjectName(_fromUtf8("group_new_button"))
        self.groupBox_2 = QtGui.QGroupBox(MemberGroupDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(349, 30, 341, 391))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.person_id_edit = QtGui.QLineEdit(self.groupBox_2)
        self.person_id_edit.setGeometry(QtCore.QRect(10, 34, 113, 20))
        self.person_id_edit.setObjectName(_fromUtf8("person_id_edit"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 14, 113, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(130, 14, 113, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.firstname_edit = QtGui.QLineEdit(self.groupBox_2)
        self.firstname_edit.setGeometry(QtCore.QRect(130, 34, 121, 20))
        self.firstname_edit.setObjectName(_fromUtf8("firstname_edit"))
        self.person_find_button = QtGui.QPushButton(self.groupBox_2)
        self.person_find_button.setGeometry(QtCore.QRect(260, 33, 75, 23))
        self.person_find_button.setObjectName(_fromUtf8("person_find_button"))
        self.person_twidget = QtGui.QTableWidget(self.groupBox_2)
        self.person_twidget.setGeometry(QtCore.QRect(10, 60, 321, 114))
        self.person_twidget.setObjectName(_fromUtf8("person_twidget"))
        self.person_twidget.setColumnCount(0)
        self.person_twidget.setRowCount(0)
        self.person_twidget.horizontalHeader().setDefaultSectionSize(100)
        self.person_twidget.verticalHeader().setDefaultSectionSize(30)
        self.person_twidget.verticalHeader().setMinimumSectionSize(19)
        self.member_twidget = QtGui.QTableWidget(self.groupBox_2)
        self.member_twidget.setGeometry(QtCore.QRect(10, 210, 321, 174))
        self.member_twidget.setObjectName(_fromUtf8("member_twidget"))
        self.member_twidget.setColumnCount(2)
        self.member_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.member_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.member_twidget.setHorizontalHeaderItem(1, item)
        self.member_twidget.horizontalHeader().setDefaultSectionSize(165)
        self.member_twidget.horizontalHeader().setMinimumSectionSize(33)
        self.pug_add_person_button = QtGui.QPushButton(self.groupBox_2)
        self.pug_add_person_button.setGeometry(QtCore.QRect(110, 180, 41, 23))
        self.pug_add_person_button.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/down_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pug_add_person_button.setIcon(icon3)
        self.pug_add_person_button.setObjectName(_fromUtf8("pug_add_person_button"))
        self.pug_remove_person_button = QtGui.QPushButton(self.groupBox_2)
        self.pug_remove_person_button.setGeometry(QtCore.QRect(170, 180, 41, 23))
        self.pug_remove_person_button.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/up_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pug_remove_person_button.setIcon(icon4)
        self.pug_remove_person_button.setObjectName(_fromUtf8("pug_remove_person_button"))
        self.close_button = QtGui.QPushButton(MemberGroupDialog)
        self.close_button.setGeometry(QtCore.QRect(610, 430, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.apply_button = QtGui.QPushButton(MemberGroupDialog)
        self.apply_button.setGeometry(QtCore.QRect(520, 430, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.error_label = QtGui.QLabel(MemberGroupDialog)
        self.error_label.setGeometry(QtCore.QRect(10, 430, 501, 21))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.status_label = QtGui.QLabel(MemberGroupDialog)
        self.status_label.setGeometry(QtCore.QRect(10, 430, 211, 20))
        self.status_label.setText(_fromUtf8(""))
        self.status_label.setObjectName(_fromUtf8("status_label"))

        self.retranslateUi(MemberGroupDialog)
        QtCore.QMetaObject.connectSlotsByName(MemberGroupDialog)

    def retranslateUi(self, MemberGroupDialog):
        MemberGroupDialog.setWindowTitle(_translate("MemberGroupDialog", "Dialog", None))
        self.label.setText(_translate("MemberGroupDialog", "Pasture use group", None))
        self.groupBox.setTitle(_translate("MemberGroupDialog", "Group Register", None))
        item = self.group_twidget.horizontalHeaderItem(0)
        item.setText(_translate("MemberGroupDialog", "PUG ID", None))
        item = self.group_twidget.horizontalHeaderItem(1)
        item.setText(_translate("MemberGroupDialog", "PUG Name", None))
        item = self.group_twidget.horizontalHeaderItem(2)
        item.setText(_translate("MemberGroupDialog", "Is Contract (№)", None))
        self.label_2.setText(_translate("MemberGroupDialog", "Group ID (only number)", None))
        self.label_3.setText(_translate("MemberGroupDialog", "Pasture use group", None))
        self.group_add_button.setText(_translate("MemberGroupDialog", "add", None))
        self.group_edit_button.setText(_translate("MemberGroupDialog", "edit", None))
        self.group_delete_button.setText(_translate("MemberGroupDialog", "delete", None))
        self.label_4.setText(_translate("MemberGroupDialog", "Bag", None))
        item = self.bag_twidget.horizontalHeaderItem(0)
        item.setText(_translate("MemberGroupDialog", "Bag name", None))
        self.group_new_button.setText(_translate("MemberGroupDialog", "new", None))
        self.groupBox_2.setTitle(_translate("MemberGroupDialog", "Member register", None))
        self.label_5.setText(_translate("MemberGroupDialog", "Person ID", None))
        self.label_6.setText(_translate("MemberGroupDialog", "Firstname", None))
        self.person_find_button.setText(_translate("MemberGroupDialog", "Find", None))
        item = self.member_twidget.horizontalHeaderItem(0)
        item.setText(_translate("MemberGroupDialog", "Person Info", None))
        item = self.member_twidget.horizontalHeaderItem(1)
        item.setText(_translate("MemberGroupDialog", "Group", None))
        self.close_button.setText(_translate("MemberGroupDialog", "Close", None))
        self.apply_button.setText(_translate("MemberGroupDialog", "Apply", None))

import resources_pasture_rc
import resources_rc
