# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\OwnRecordDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OwnRecordDialog(object):
    def setupUi(self, OwnRecordDialog):
        OwnRecordDialog.setObjectName(_fromUtf8("OwnRecordDialog"))
        OwnRecordDialog.resize(800, 470)
        self.label = QtGui.QLabel(OwnRecordDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 400, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.line = QtGui.QFrame(OwnRecordDialog)
        self.line.setGeometry(QtCore.QRect(0, 20, 800, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(OwnRecordDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 440, 800, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.help_button = QtGui.QPushButton(OwnRecordDialog)
        self.help_button.setGeometry(QtCore.QRect(489, 417, 91, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.apply_button = QtGui.QPushButton(OwnRecordDialog)
        self.apply_button.setGeometry(QtCore.QRect(600, 417, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.close_button = QtGui.QPushButton(OwnRecordDialog)
        self.close_button.setGeometry(QtCore.QRect(690, 417, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.tabWidget = QtGui.QTabWidget(OwnRecordDialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 781, 381))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.application_tab = QtGui.QWidget()
        self.application_tab.setObjectName(_fromUtf8("application_tab"))
        self.application_groupbox = QtGui.QGroupBox(self.application_tab)
        self.application_groupbox.setGeometry(QtCore.QRect(7, 4, 761, 170))
        self.application_groupbox.setObjectName(_fromUtf8("application_groupbox"))
        self.label_27 = QtGui.QLabel(self.application_groupbox)
        self.label_27.setGeometry(QtCore.QRect(50, 35, 200, 13))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.enter_application_edit = QtGui.QLineEdit(self.application_groupbox)
        self.enter_application_edit.setGeometry(QtCore.QRect(50, 50, 200, 20))
        self.enter_application_edit.setObjectName(_fromUtf8("enter_application_edit"))
        self.found_edit = QtGui.QLineEdit(self.application_groupbox)
        self.found_edit.setGeometry(QtCore.QRect(50, 100, 200, 20))
        self.found_edit.setObjectName(_fromUtf8("found_edit"))
        self.label_30 = QtGui.QLabel(self.application_groupbox)
        self.label_30.setGeometry(QtCore.QRect(50, 85, 200, 13))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.search_button = QtGui.QPushButton(self.application_groupbox)
        self.search_button.setGeometry(QtCore.QRect(290, 48, 75, 23))
        self.search_button.setObjectName(_fromUtf8("search_button"))
        self.accept_button = QtGui.QPushButton(self.application_groupbox)
        self.accept_button.setGeometry(QtCore.QRect(290, 98, 75, 23))
        self.accept_button.setObjectName(_fromUtf8("accept_button"))
        self.groupBox_12 = QtGui.QGroupBox(self.application_tab)
        self.groupBox_12.setGeometry(QtCore.QRect(7, 176, 761, 170))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.label_32 = QtGui.QLabel(self.groupBox_12)
        self.label_32.setGeometry(QtCore.QRect(50, 35, 330, 13))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.application_based_edit = QtGui.QLineEdit(self.groupBox_12)
        self.application_based_edit.setEnabled(False)
        self.application_based_edit.setGeometry(QtCore.QRect(50, 50, 300, 20))
        self.application_based_edit.setObjectName(_fromUtf8("application_based_edit"))
        self.application_type_edit = QtGui.QLineEdit(self.groupBox_12)
        self.application_type_edit.setEnabled(False)
        self.application_type_edit.setGeometry(QtCore.QRect(50, 100, 551, 20))
        self.application_type_edit.setObjectName(_fromUtf8("application_type_edit"))
        self.label_33 = QtGui.QLabel(self.groupBox_12)
        self.label_33.setGeometry(QtCore.QRect(50, 85, 330, 13))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.unassign_button = QtGui.QPushButton(self.groupBox_12)
        self.unassign_button.setGeometry(QtCore.QRect(400, 48, 200, 23))
        self.unassign_button.setObjectName(_fromUtf8("unassign_button"))
        self.tabWidget.addTab(self.application_tab, _fromUtf8(""))
        self.parcel_tab = QtGui.QWidget()
        self.parcel_tab.setObjectName(_fromUtf8("parcel_tab"))
        self.groupBox_4 = QtGui.QGroupBox(self.parcel_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(7, 4, 761, 341))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(30, 35, 220, 13))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.id_main_edit = QtGui.QLineEdit(self.groupBox_4)
        self.id_main_edit.setEnabled(False)
        self.id_main_edit.setGeometry(QtCore.QRect(30, 50, 200, 20))
        self.id_main_edit.setObjectName(_fromUtf8("id_main_edit"))
        self.calculated_area_edit = QtGui.QLineEdit(self.groupBox_4)
        self.calculated_area_edit.setEnabled(False)
        self.calculated_area_edit.setGeometry(QtCore.QRect(280, 50, 200, 20))
        self.calculated_area_edit.setObjectName(_fromUtf8("calculated_area_edit"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(280, 35, 220, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.aimag_edit = QtGui.QLineEdit(self.groupBox_4)
        self.aimag_edit.setEnabled(False)
        self.aimag_edit.setGeometry(QtCore.QRect(530, 50, 200, 20))
        self.aimag_edit.setObjectName(_fromUtf8("aimag_edit"))
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(530, 35, 220, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.old_id_edit = QtGui.QLineEdit(self.groupBox_4)
        self.old_id_edit.setEnabled(False)
        self.old_id_edit.setGeometry(QtCore.QRect(30, 100, 200, 20))
        self.old_id_edit.setObjectName(_fromUtf8("old_id_edit"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(30, 85, 220, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.geo_id_edit = QtGui.QLineEdit(self.groupBox_4)
        self.geo_id_edit.setEnabled(False)
        self.geo_id_edit.setGeometry(QtCore.QRect(30, 150, 200, 20))
        self.geo_id_edit.setObjectName(_fromUtf8("geo_id_edit"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(30, 135, 220, 13))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.land_use_type_edit = QtGui.QLineEdit(self.groupBox_4)
        self.land_use_type_edit.setEnabled(False)
        self.land_use_type_edit.setGeometry(QtCore.QRect(30, 200, 400, 20))
        self.land_use_type_edit.setObjectName(_fromUtf8("land_use_type_edit"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(30, 185, 444, 13))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.documented_area_edit = QtGui.QLineEdit(self.groupBox_4)
        self.documented_area_edit.setEnabled(False)
        self.documented_area_edit.setGeometry(QtCore.QRect(280, 100, 200, 20))
        self.documented_area_edit.setObjectName(_fromUtf8("documented_area_edit"))
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(280, 85, 220, 13))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(530, 85, 220, 13))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.soum_edit = QtGui.QLineEdit(self.groupBox_4)
        self.soum_edit.setEnabled(False)
        self.soum_edit.setGeometry(QtCore.QRect(530, 100, 200, 20))
        self.soum_edit.setObjectName(_fromUtf8("soum_edit"))
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(530, 135, 220, 13))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.bag_edit = QtGui.QLineEdit(self.groupBox_4)
        self.bag_edit.setEnabled(False)
        self.bag_edit.setGeometry(QtCore.QRect(530, 150, 200, 20))
        self.bag_edit.setObjectName(_fromUtf8("bag_edit"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(530, 185, 220, 13))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.street_name_edit = QtGui.QLineEdit(self.groupBox_4)
        self.street_name_edit.setEnabled(False)
        self.street_name_edit.setGeometry(QtCore.QRect(530, 200, 200, 20))
        self.street_name_edit.setObjectName(_fromUtf8("street_name_edit"))
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(530, 235, 220, 13))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.khashaa_edit = QtGui.QLineEdit(self.groupBox_4)
        self.khashaa_edit.setEnabled(False)
        self.khashaa_edit.setGeometry(QtCore.QRect(530, 250, 200, 20))
        self.khashaa_edit.setObjectName(_fromUtf8("khashaa_edit"))
        self.edit_address_chbox = QtGui.QCheckBox(self.groupBox_4)
        self.edit_address_chbox.setGeometry(QtCore.QRect(530, 14, 211, 17))
        self.edit_address_chbox.setObjectName(_fromUtf8("edit_address_chbox"))
        self.tabWidget.addTab(self.parcel_tab, _fromUtf8(""))
        self.record_details_tab = QtGui.QWidget()
        self.record_details_tab.setObjectName(_fromUtf8("record_details_tab"))
        self.groupBox_7 = QtGui.QGroupBox(self.record_details_tab)
        self.groupBox_7.setGeometry(QtCore.QRect(7, 4, 761, 341))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_22 = QtGui.QLabel(self.groupBox_7)
        self.label_22.setGeometry(QtCore.QRect(30, 35, 180, 13))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.record_number_edit = QtGui.QLineEdit(self.groupBox_7)
        self.record_number_edit.setEnabled(False)
        self.record_number_edit.setGeometry(QtCore.QRect(30, 50, 180, 20))
        self.record_number_edit.setObjectName(_fromUtf8("record_number_edit"))
        self.record_date_date = QtGui.QDateEdit(self.groupBox_7)
        self.record_date_date.setGeometry(QtCore.QRect(250, 50, 180, 20))
        self.record_date_date.setCalendarPopup(True)
        self.record_date_date.setObjectName(_fromUtf8("record_date_date"))
        self.label_23 = QtGui.QLabel(self.groupBox_7)
        self.label_23.setGeometry(QtCore.QRect(30, 85, 180, 13))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.record_status_groupbox = QtGui.QGroupBox(self.groupBox_7)
        self.record_status_groupbox.setGeometry(QtCore.QRect(30, 140, 165, 93))
        self.record_status_groupbox.setObjectName(_fromUtf8("record_status_groupbox"))
        self.draft_rbutton = QtGui.QRadioButton(self.record_status_groupbox)
        self.draft_rbutton.setGeometry(QtCore.QRect(10, 20, 146, 26))
        self.draft_rbutton.setObjectName(_fromUtf8("draft_rbutton"))
        self.buttonGroup = QtGui.QButtonGroup(OwnRecordDialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.draft_rbutton)
        self.active_rbutton = QtGui.QRadioButton(self.record_status_groupbox)
        self.active_rbutton.setGeometry(QtCore.QRect(10, 45, 151, 21))
        self.active_rbutton.setChecked(True)
        self.active_rbutton.setObjectName(_fromUtf8("active_rbutton"))
        self.buttonGroup.addButton(self.active_rbutton)
        self.cancelled_rbutton = QtGui.QRadioButton(self.record_status_groupbox)
        self.cancelled_rbutton.setGeometry(QtCore.QRect(10, 65, 146, 21))
        self.cancelled_rbutton.setObjectName(_fromUtf8("cancelled_rbutton"))
        self.buttonGroup.addButton(self.cancelled_rbutton)
        self.right_groupbox = QtGui.QGroupBox(self.groupBox_7)
        self.right_groupbox.setGeometry(QtCore.QRect(30, 230, 165, 83))
        self.right_groupbox.setObjectName(_fromUtf8("right_groupbox"))
        self.standard_right_rbutton = QtGui.QRadioButton(self.right_groupbox)
        self.standard_right_rbutton.setGeometry(QtCore.QRect(10, 30, 131, 21))
        self.standard_right_rbutton.setChecked(True)
        self.standard_right_rbutton.setObjectName(_fromUtf8("standard_right_rbutton"))
        self.buttonGroup_2 = QtGui.QButtonGroup(OwnRecordDialog)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.standard_right_rbutton)
        self.advanced_right_rbutton = QtGui.QRadioButton(self.right_groupbox)
        self.advanced_right_rbutton.setGeometry(QtCore.QRect(10, 55, 136, 21))
        self.advanced_right_rbutton.setObjectName(_fromUtf8("advanced_right_rbutton"))
        self.buttonGroup_2.addButton(self.advanced_right_rbutton)
        self.ownership_end_groupbox = QtGui.QGroupBox(self.groupBox_7)
        self.ownership_end_groupbox.setGeometry(QtCore.QRect(200, 140, 551, 171))
        self.ownership_end_groupbox.setObjectName(_fromUtf8("ownership_end_groupbox"))
        self.label_24 = QtGui.QLabel(self.ownership_end_groupbox)
        self.label_24.setGeometry(QtCore.QRect(15, 30, 161, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.ownership_end_date = QtGui.QDateEdit(self.ownership_end_groupbox)
        self.ownership_end_date.setEnabled(False)
        self.ownership_end_date.setGeometry(QtCore.QRect(50, 53, 96, 22))
        self.ownership_end_date.setCalendarPopup(True)
        self.ownership_end_date.setObjectName(_fromUtf8("ownership_end_date"))
        self.cancellation_date_check_box = QtGui.QCheckBox(self.ownership_end_groupbox)
        self.cancellation_date_check_box.setGeometry(QtCore.QRect(20, 57, 21, 16))
        self.cancellation_date_check_box.setText(_fromUtf8(""))
        self.cancellation_date_check_box.setObjectName(_fromUtf8("cancellation_date_check_box"))
        self.application_based_rbutton = QtGui.QRadioButton(self.ownership_end_groupbox)
        self.application_based_rbutton.setEnabled(False)
        self.application_based_rbutton.setGeometry(QtCore.QRect(175, 27, 180, 21))
        self.application_based_rbutton.setChecked(True)
        self.application_based_rbutton.setObjectName(_fromUtf8("application_based_rbutton"))
        self.buttonGroup_3 = QtGui.QButtonGroup(OwnRecordDialog)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.application_based_rbutton)
        self.label_25 = QtGui.QLabel(self.ownership_end_groupbox)
        self.label_25.setGeometry(QtCore.QRect(155, 55, 88, 13))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.ownership_end_groupbox)
        self.label_26.setGeometry(QtCore.QRect(13, 88, 88, 13))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.app_number_cbox = QtGui.QComboBox(self.ownership_end_groupbox)
        self.app_number_cbox.setEnabled(False)
        self.app_number_cbox.setGeometry(QtCore.QRect(220, 52, 157, 22))
        self.app_number_cbox.setObjectName(_fromUtf8("app_number_cbox"))
        self.type_edit = QtGui.QLineEdit(self.ownership_end_groupbox)
        self.type_edit.setEnabled(False)
        self.type_edit.setGeometry(QtCore.QRect(70, 85, 471, 20))
        self.type_edit.setObjectName(_fromUtf8("type_edit"))
        self.other_reason_rbutton = QtGui.QRadioButton(self.ownership_end_groupbox)
        self.other_reason_rbutton.setEnabled(False)
        self.other_reason_rbutton.setGeometry(QtCore.QRect(10, 107, 266, 21))
        self.other_reason_rbutton.setObjectName(_fromUtf8("other_reason_rbutton"))
        self.buttonGroup_3.addButton(self.other_reason_rbutton)
        self.other_reason_cbox = QtGui.QComboBox(self.ownership_end_groupbox)
        self.other_reason_cbox.setEnabled(False)
        self.other_reason_cbox.setGeometry(QtCore.QRect(10, 135, 531, 22))
        self.other_reason_cbox.setObjectName(_fromUtf8("other_reason_cbox"))
        self.person_id_edit = QtGui.QLineEdit(self.ownership_end_groupbox)
        self.person_id_edit.setGeometry(QtCore.QRect(390, 52, 151, 20))
        self.person_id_edit.setObjectName(_fromUtf8("person_id_edit"))
        self.label_31 = QtGui.QLabel(self.ownership_end_groupbox)
        self.label_31.setGeometry(QtCore.QRect(391, 31, 149, 13))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.messages_label = QtGui.QLabel(self.groupBox_7)
        self.messages_label.setGeometry(QtCore.QRect(30, 318, 721, 16))
        self.messages_label.setText(_fromUtf8(""))
        self.messages_label.setObjectName(_fromUtf8("messages_label"))
        self.label_28 = QtGui.QLabel(self.groupBox_7)
        self.label_28.setGeometry(QtCore.QRect(255, 34, 180, 15))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.certificate_number_edit = QtGui.QLineEdit(self.groupBox_7)
        self.certificate_number_edit.setEnabled(False)
        self.certificate_number_edit.setGeometry(QtCore.QRect(450, 50, 180, 20))
        self.certificate_number_edit.setObjectName(_fromUtf8("certificate_number_edit"))
        self.label_29 = QtGui.QLabel(self.groupBox_7)
        self.label_29.setGeometry(QtCore.QRect(450, 35, 180, 13))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.ownership_begin_edit = QtGui.QDateEdit(self.groupBox_7)
        self.ownership_begin_edit.setEnabled(False)
        self.ownership_begin_edit.setGeometry(QtCore.QRect(30, 100, 181, 24))
        self.ownership_begin_edit.setCalendarPopup(True)
        self.ownership_begin_edit.setObjectName(_fromUtf8("ownership_begin_edit"))
        self.tabWidget.addTab(self.record_details_tab, _fromUtf8(""))
        self.price_and_land_tax_tab = QtGui.QWidget()
        self.price_and_land_tax_tab.setObjectName(_fromUtf8("price_and_land_tax_tab"))
        self.groupBox = QtGui.QGroupBox(self.price_and_land_tax_tab)
        self.groupBox.setGeometry(QtCore.QRect(7, 4, 761, 116))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 35, 150, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.base_value_edit = QtGui.QLineEdit(self.groupBox)
        self.base_value_edit.setEnabled(False)
        self.base_value_edit.setGeometry(QtCore.QRect(40, 50, 150, 20))
        self.base_value_edit.setReadOnly(True)
        self.base_value_edit.setObjectName(_fromUtf8("base_value_edit"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(230, 35, 150, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.base_tax_rate_edit = QtGui.QLineEdit(self.groupBox)
        self.base_tax_rate_edit.setEnabled(False)
        self.base_tax_rate_edit.setGeometry(QtCore.QRect(230, 50, 150, 20))
        self.base_tax_rate_edit.setReadOnly(True)
        self.base_tax_rate_edit.setObjectName(_fromUtf8("base_tax_rate_edit"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(410, 35, 150, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.subsidized_area_edit = QtGui.QLineEdit(self.groupBox)
        self.subsidized_area_edit.setEnabled(False)
        self.subsidized_area_edit.setGeometry(QtCore.QRect(410, 50, 150, 20))
        self.subsidized_area_edit.setReadOnly(True)
        self.subsidized_area_edit.setObjectName(_fromUtf8("subsidized_area_edit"))
        self.subsidized_tax_rate_edit = QtGui.QLineEdit(self.groupBox)
        self.subsidized_tax_rate_edit.setEnabled(False)
        self.subsidized_tax_rate_edit.setGeometry(QtCore.QRect(590, 50, 150, 20))
        self.subsidized_tax_rate_edit.setReadOnly(True)
        self.subsidized_tax_rate_edit.setObjectName(_fromUtf8("subsidized_tax_rate_edit"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(590, 35, 150, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.landtax_message_label1 = QtGui.QLabel(self.groupBox)
        self.landtax_message_label1.setGeometry(QtCore.QRect(15, 85, 726, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.landtax_message_label1.setFont(font)
        self.landtax_message_label1.setObjectName(_fromUtf8("landtax_message_label1"))
        self.land_tax_twidget = QtGui.QTableWidget(self.price_and_land_tax_tab)
        self.land_tax_twidget.setGeometry(QtCore.QRect(7, 144, 760, 181))
        self.land_tax_twidget.setObjectName(_fromUtf8("land_tax_twidget"))
        self.land_tax_twidget.setColumnCount(9)
        self.land_tax_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.land_tax_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.land_tax_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.land_tax_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.land_tax_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.land_tax_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.land_tax_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.land_tax_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.land_tax_twidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.land_tax_twidget.setHorizontalHeaderItem(8, item)
        self.land_tax_twidget.horizontalHeader().setDefaultSectionSize(95)
        self.landtax_message_label2 = QtGui.QLabel(self.price_and_land_tax_tab)
        self.landtax_message_label2.setGeometry(QtCore.QRect(20, 330, 746, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.landtax_message_label2.setFont(font)
        self.landtax_message_label2.setObjectName(_fromUtf8("landtax_message_label2"))
        self.tabWidget.addTab(self.price_and_land_tax_tab, _fromUtf8(""))
        self.land_tax_hisotry_tab = QtGui.QWidget()
        self.land_tax_hisotry_tab.setObjectName(_fromUtf8("land_tax_hisotry_tab"))
        self.archive_land_tax_twidget = QtGui.QTableWidget(self.land_tax_hisotry_tab)
        self.archive_land_tax_twidget.setGeometry(QtCore.QRect(7, 160, 760, 180))
        self.archive_land_tax_twidget.setObjectName(_fromUtf8("archive_land_tax_twidget"))
        self.archive_land_tax_twidget.setColumnCount(9)
        self.archive_land_tax_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.archive_land_tax_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.archive_land_tax_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.archive_land_tax_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.archive_land_tax_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.archive_land_tax_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.archive_land_tax_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.archive_land_tax_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.archive_land_tax_twidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.archive_land_tax_twidget.setHorizontalHeaderItem(8, item)
        self.archive_land_tax_twidget.horizontalHeader().setDefaultSectionSize(125)
        self.groupBox_2 = QtGui.QGroupBox(self.land_tax_hisotry_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(7, 80, 761, 71))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 25, 150, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.archive_base_value_edit = QtGui.QLineEdit(self.groupBox_2)
        self.archive_base_value_edit.setEnabled(False)
        self.archive_base_value_edit.setGeometry(QtCore.QRect(30, 40, 150, 20))
        self.archive_base_value_edit.setReadOnly(True)
        self.archive_base_value_edit.setObjectName(_fromUtf8("archive_base_value_edit"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(220, 25, 150, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.archive_base_tax_rate_edit = QtGui.QLineEdit(self.groupBox_2)
        self.archive_base_tax_rate_edit.setEnabled(False)
        self.archive_base_tax_rate_edit.setGeometry(QtCore.QRect(220, 40, 150, 20))
        self.archive_base_tax_rate_edit.setReadOnly(True)
        self.archive_base_tax_rate_edit.setObjectName(_fromUtf8("archive_base_tax_rate_edit"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(400, 25, 150, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.archive_subsidized_area_edit = QtGui.QLineEdit(self.groupBox_2)
        self.archive_subsidized_area_edit.setEnabled(False)
        self.archive_subsidized_area_edit.setGeometry(QtCore.QRect(400, 40, 150, 20))
        self.archive_subsidized_area_edit.setReadOnly(True)
        self.archive_subsidized_area_edit.setObjectName(_fromUtf8("archive_subsidized_area_edit"))
        self.archive_subsidized_tax_rate_edit = QtGui.QLineEdit(self.groupBox_2)
        self.archive_subsidized_tax_rate_edit.setEnabled(False)
        self.archive_subsidized_tax_rate_edit.setGeometry(QtCore.QRect(580, 40, 150, 20))
        self.archive_subsidized_tax_rate_edit.setReadOnly(True)
        self.archive_subsidized_tax_rate_edit.setObjectName(_fromUtf8("archive_subsidized_tax_rate_edit"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(580, 25, 150, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.groupBox_3 = QtGui.QGroupBox(self.land_tax_hisotry_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(7, 5, 761, 76))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(40, 30, 200, 13))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.time_period_cbox = QtGui.QComboBox(self.groupBox_3)
        self.time_period_cbox.setGeometry(QtCore.QRect(40, 40, 200, 22))
        self.time_period_cbox.setObjectName(_fromUtf8("time_period_cbox"))
        self.tabWidget.addTab(self.land_tax_hisotry_tab, _fromUtf8(""))
        self.documents_tab = QtGui.QWidget()
        self.documents_tab.setObjectName(_fromUtf8("documents_tab"))
        self.documents_groupbox = QtGui.QGroupBox(self.documents_tab)
        self.documents_groupbox.setGeometry(QtCore.QRect(10, 0, 756, 341))
        self.documents_groupbox.setObjectName(_fromUtf8("documents_groupbox"))
        self.doc_twidget = QtGui.QTableWidget(self.documents_groupbox)
        self.doc_twidget.setGeometry(QtCore.QRect(20, 69, 700, 261))
        self.doc_twidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.doc_twidget.setObjectName(_fromUtf8("doc_twidget"))
        self.doc_twidget.setColumnCount(6)
        self.doc_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(5, item)
        self.doc_twidget.horizontalHeader().setCascadingSectionResizes(False)
        self.doc_twidget.horizontalHeader().setDefaultSectionSize(120)
        self.doc_twidget.horizontalHeader().setHighlightSections(False)
        self.doc_twidget.verticalHeader().setCascadingSectionResizes(False)
        self.document_path_edit = QtGui.QLineEdit(self.documents_groupbox)
        self.document_path_edit.setGeometry(QtCore.QRect(19, 36, 261, 20))
        self.document_path_edit.setReadOnly(True)
        self.document_path_edit.setObjectName(_fromUtf8("document_path_edit"))
        self.label_34 = QtGui.QLabel(self.documents_groupbox)
        self.label_34.setGeometry(QtCore.QRect(20, 20, 261, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.load_doc_button = QtGui.QPushButton(self.documents_groupbox)
        self.load_doc_button.setGeometry(QtCore.QRect(302, 35, 171, 23))
        self.load_doc_button.setObjectName(_fromUtf8("load_doc_button"))
        self.tabWidget.addTab(self.documents_tab, _fromUtf8(""))
        self.app_doc_tab = QtGui.QWidget()
        self.app_doc_tab.setObjectName(_fromUtf8("app_doc_tab"))
        self.documents_groupbox_2 = QtGui.QGroupBox(self.app_doc_tab)
        self.documents_groupbox_2.setGeometry(QtCore.QRect(10, 0, 756, 341))
        self.documents_groupbox_2.setObjectName(_fromUtf8("documents_groupbox_2"))
        self.applicant_documents_cbox = QtGui.QComboBox(self.documents_groupbox_2)
        self.applicant_documents_cbox.setGeometry(QtCore.QRect(20, 30, 311, 26))
        self.applicant_documents_cbox.setObjectName(_fromUtf8("applicant_documents_cbox"))
        self.app_doc_twidget = QtGui.QTableWidget(self.documents_groupbox_2)
        self.app_doc_twidget.setGeometry(QtCore.QRect(20, 69, 681, 251))
        self.app_doc_twidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.app_doc_twidget.setObjectName(_fromUtf8("app_doc_twidget"))
        self.app_doc_twidget.setColumnCount(4)
        self.app_doc_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.app_doc_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.app_doc_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.app_doc_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.app_doc_twidget.setHorizontalHeaderItem(3, item)
        self.app_doc_twidget.horizontalHeader().setCascadingSectionResizes(True)
        self.app_doc_twidget.horizontalHeader().setDefaultSectionSize(100)
        self.app_doc_twidget.verticalHeader().setCascadingSectionResizes(False)
        self.load_app_doc_button = QtGui.QPushButton(self.documents_groupbox_2)
        self.load_app_doc_button.setGeometry(QtCore.QRect(425, 33, 171, 23))
        self.load_app_doc_button.setObjectName(_fromUtf8("load_app_doc_button"))
        self.tabWidget.addTab(self.app_doc_tab, _fromUtf8(""))
        self.print_tab = QtGui.QWidget()
        self.print_tab.setObjectName(_fromUtf8("print_tab"))
        self.groupBox_5 = QtGui.QGroupBox(self.print_tab)
        self.groupBox_5.setGeometry(QtCore.QRect(7, 4, 761, 341))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.land_tax_summary_button = QtGui.QPushButton(self.groupBox_5)
        self.land_tax_summary_button.setGeometry(QtCore.QRect(50, 40, 250, 23))
        self.land_tax_summary_button.setObjectName(_fromUtf8("land_tax_summary_button"))
        self.decision_page_print_button = QtGui.QPushButton(self.groupBox_5)
        self.decision_page_print_button.setGeometry(QtCore.QRect(50, 80, 251, 23))
        self.decision_page_print_button.setObjectName(_fromUtf8("decision_page_print_button"))
        self.tabWidget.addTab(self.print_tab, _fromUtf8(""))
        self.status_label = QtGui.QLabel(OwnRecordDialog)
        self.status_label.setGeometry(QtCore.QRect(20, 420, 441, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setText(_fromUtf8(""))
        self.status_label.setObjectName(_fromUtf8("status_label"))

        self.retranslateUi(OwnRecordDialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(OwnRecordDialog)

    def retranslateUi(self, OwnRecordDialog):
        OwnRecordDialog.setWindowTitle(_translate("OwnRecordDialog", "Dialog", None))
        self.label.setText(_translate("OwnRecordDialog", "Ownership Record", None))
        self.help_button.setText(_translate("OwnRecordDialog", "?", None))
        self.apply_button.setText(_translate("OwnRecordDialog", "Apply", None))
        self.close_button.setText(_translate("OwnRecordDialog", "Close", None))
        self.application_groupbox.setTitle(_translate("OwnRecordDialog", "Search", None))
        self.label_27.setText(_translate("OwnRecordDialog", "Enter Application Number", None))
        self.label_30.setText(_translate("OwnRecordDialog", "Found", None))
        self.search_button.setText(_translate("OwnRecordDialog", "Search", None))
        self.accept_button.setText(_translate("OwnRecordDialog", "Accept", None))
        self.groupBox_12.setTitle(_translate("OwnRecordDialog", "Assigned Application", None))
        self.label_32.setText(_translate("OwnRecordDialog", "Application this ownership record is based on", None))
        self.label_33.setText(_translate("OwnRecordDialog", "Application Type", None))
        self.unassign_button.setText(_translate("OwnRecordDialog", "Unassign", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.application_tab), _translate("OwnRecordDialog", "Application", None))
        self.groupBox_4.setTitle(_translate("OwnRecordDialog", "Parcel Details", None))
        self.label_11.setText(_translate("OwnRecordDialog", "ID (Main ID)", None))
        self.label_12.setText(_translate("OwnRecordDialog", "Calculated Area [m2]", None))
        self.label_13.setText(_translate("OwnRecordDialog", "Aimag", None))
        self.label_14.setText(_translate("OwnRecordDialog", "Old ID", None))
        self.label_15.setText(_translate("OwnRecordDialog", "Geo ID", None))
        self.label_16.setText(_translate("OwnRecordDialog", "Land Use Type", None))
        self.label_17.setText(_translate("OwnRecordDialog", "Documented Area [m2]", None))
        self.label_18.setText(_translate("OwnRecordDialog", "Soum / Duureg", None))
        self.label_19.setText(_translate("OwnRecordDialog", "Bag / Khoroo", None))
        self.label_20.setText(_translate("OwnRecordDialog", "Street Name", None))
        self.label_21.setText(_translate("OwnRecordDialog", "Khashaa", None))
        self.edit_address_chbox.setText(_translate("OwnRecordDialog", "Edit address", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.parcel_tab), _translate("OwnRecordDialog", "Parcel", None))
        self.groupBox_7.setTitle(_translate("OwnRecordDialog", "Record Details", None))
        self.label_22.setText(_translate("OwnRecordDialog", "Record Number", None))
        self.record_date_date.setDisplayFormat(_translate("OwnRecordDialog", "yyyy-MM-dd", None))
        self.label_23.setText(_translate("OwnRecordDialog", "Ownership Begin", None))
        self.record_status_groupbox.setTitle(_translate("OwnRecordDialog", "Record Status", None))
        self.draft_rbutton.setText(_translate("OwnRecordDialog", "Draft", None))
        self.active_rbutton.setText(_translate("OwnRecordDialog", "Active", None))
        self.cancelled_rbutton.setText(_translate("OwnRecordDialog", "Cancelled", None))
        self.right_groupbox.setTitle(_translate("OwnRecordDialog", "Right", None))
        self.standard_right_rbutton.setText(_translate("OwnRecordDialog", "Standard Right", None))
        self.advanced_right_rbutton.setText(_translate("OwnRecordDialog", "Advanced Right", None))
        self.ownership_end_groupbox.setTitle(_translate("OwnRecordDialog", "Ownership End (Cancellation)", None))
        self.label_24.setText(_translate("OwnRecordDialog", "Ownership End", None))
        self.ownership_end_date.setDisplayFormat(_translate("OwnRecordDialog", "yyyy-MM-dd", None))
        self.application_based_rbutton.setText(_translate("OwnRecordDialog", "Application Based", None))
        self.label_25.setText(_translate("OwnRecordDialog", "Number", None))
        self.label_26.setText(_translate("OwnRecordDialog", "Type", None))
        self.other_reason_rbutton.setText(_translate("OwnRecordDialog", "Other Reason", None))
        self.label_31.setText(_translate("OwnRecordDialog", "Person/Company ID", None))
        self.label_28.setText(_translate("OwnRecordDialog", "Record Date", None))
        self.label_29.setText(_translate("OwnRecordDialog", "Certificate Number", None))
        self.ownership_begin_edit.setDisplayFormat(_translate("OwnRecordDialog", "yyyy-MM-dd", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.record_details_tab), _translate("OwnRecordDialog", "Record Details", None))
        self.groupBox.setTitle(_translate("OwnRecordDialog", "Base Figures", None))
        self.label_2.setText(_translate("OwnRecordDialog", "Base Value Per m2 [₮]", None))
        self.label_3.setText(_translate("OwnRecordDialog", "Base Tax Rate [%]", None))
        self.label_4.setText(_translate("OwnRecordDialog", "Subsidized Area [m2]", None))
        self.label_5.setText(_translate("OwnRecordDialog", "Subsidized Tax Rate [%]", None))
        self.landtax_message_label1.setText(_translate("OwnRecordDialog", "XXX", None))
        item = self.land_tax_twidget.horizontalHeaderItem(0)
        item.setText(_translate("OwnRecordDialog", "Owner", None))
        item = self.land_tax_twidget.horizontalHeaderItem(1)
        item.setText(_translate("OwnRecordDialog", "ID", None))
        item = self.land_tax_twidget.horizontalHeaderItem(2)
        item.setText(_translate("OwnRecordDialog", "Share", None))
        item = self.land_tax_twidget.horizontalHeaderItem(3)
        item.setText(_translate("OwnRecordDialog", "Area [m2]", None))
        item = self.land_tax_twidget.horizontalHeaderItem(4)
        item.setText(_translate("OwnRecordDialog", "Value Calculated [₮]", None))
        item = self.land_tax_twidget.horizontalHeaderItem(5)
        item.setText(_translate("OwnRecordDialog", "Price Paid [₮]", None))
        item = self.land_tax_twidget.horizontalHeaderItem(6)
        item.setText(_translate("OwnRecordDialog", "Land Tax [₮]", None))
        item = self.land_tax_twidget.horizontalHeaderItem(7)
        item.setText(_translate("OwnRecordDialog", "Grace Priod [days]", None))
        item = self.land_tax_twidget.horizontalHeaderItem(8)
        item.setText(_translate("OwnRecordDialog", "Payment", None))
        self.landtax_message_label2.setText(_translate("OwnRecordDialog", "XXX", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.price_and_land_tax_tab), _translate("OwnRecordDialog", "Price And Land Tax", None))
        item = self.archive_land_tax_twidget.horizontalHeaderItem(0)
        item.setText(_translate("OwnRecordDialog", "Owner", None))
        item = self.archive_land_tax_twidget.horizontalHeaderItem(1)
        item.setText(_translate("OwnRecordDialog", "ID", None))
        item = self.archive_land_tax_twidget.horizontalHeaderItem(2)
        item.setText(_translate("OwnRecordDialog", "Share", None))
        item = self.archive_land_tax_twidget.horizontalHeaderItem(3)
        item.setText(_translate("OwnRecordDialog", "Area [m2]", None))
        item = self.archive_land_tax_twidget.horizontalHeaderItem(4)
        item.setText(_translate("OwnRecordDialog", "Value Calculated [₮] ", None))
        item = self.archive_land_tax_twidget.horizontalHeaderItem(5)
        item.setText(_translate("OwnRecordDialog", "Price Paid [₮]", None))
        item = self.archive_land_tax_twidget.horizontalHeaderItem(6)
        item.setText(_translate("OwnRecordDialog", "Land Tax [₮]", None))
        item = self.archive_land_tax_twidget.horizontalHeaderItem(7)
        item.setText(_translate("OwnRecordDialog", "Grace Period [days]", None))
        item = self.archive_land_tax_twidget.horizontalHeaderItem(8)
        item.setText(_translate("OwnRecordDialog", "Payment Frequency", None))
        self.groupBox_2.setTitle(_translate("OwnRecordDialog", "Base Figures", None))
        self.label_6.setText(_translate("OwnRecordDialog", "Base Value Per m2 [₮]", None))
        self.label_7.setText(_translate("OwnRecordDialog", "Base Tax Rate [%]", None))
        self.label_8.setText(_translate("OwnRecordDialog", "Subsidized Area [m2]", None))
        self.label_9.setText(_translate("OwnRecordDialog", "Subsidized Tax Rate [%]", None))
        self.groupBox_3.setTitle(_translate("OwnRecordDialog", "Land Tax History", None))
        self.label_10.setText(_translate("OwnRecordDialog", "Time Period", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.land_tax_hisotry_tab), _translate("OwnRecordDialog", "Land Tax History", None))
        self.documents_groupbox.setTitle(_translate("OwnRecordDialog", "Ownership Record Documents", None))
        item = self.doc_twidget.horizontalHeaderItem(0)
        item.setText(_translate("OwnRecordDialog", "Provided", None))
        item = self.doc_twidget.horizontalHeaderItem(1)
        item.setText(_translate("OwnRecordDialog", "Type", None))
        item = self.doc_twidget.horizontalHeaderItem(2)
        item.setText(_translate("OwnRecordDialog", "Name", None))
        item = self.doc_twidget.horizontalHeaderItem(3)
        item.setText(_translate("OwnRecordDialog", "Open", None))
        item = self.doc_twidget.horizontalHeaderItem(4)
        item.setText(_translate("OwnRecordDialog", "Remove", None))
        item = self.doc_twidget.horizontalHeaderItem(5)
        item.setText(_translate("OwnRecordDialog", "View", None))
        self.label_34.setText(_translate("OwnRecordDialog", "Document Path", None))
        self.load_doc_button.setText(_translate("OwnRecordDialog", "Load Document", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documents_tab), _translate("OwnRecordDialog", "Documents", None))
        self.documents_groupbox_2.setTitle(_translate("OwnRecordDialog", "Application Documents", None))
        item = self.app_doc_twidget.horizontalHeaderItem(0)
        item.setText(_translate("OwnRecordDialog", "Provided", None))
        item = self.app_doc_twidget.horizontalHeaderItem(1)
        item.setText(_translate("OwnRecordDialog", "Type", None))
        item = self.app_doc_twidget.horizontalHeaderItem(2)
        item.setText(_translate("OwnRecordDialog", "Name", None))
        item = self.app_doc_twidget.horizontalHeaderItem(3)
        item.setText(_translate("OwnRecordDialog", "View", None))
        self.load_app_doc_button.setText(_translate("OwnRecordDialog", "Load Document", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.app_doc_tab), _translate("OwnRecordDialog", "Application Documents", None))
        self.groupBox_5.setTitle(_translate("OwnRecordDialog", "Print", None))
        self.land_tax_summary_button.setText(_translate("OwnRecordDialog", "Land Tax Summary", None))
        self.decision_page_print_button.setText(_translate("OwnRecordDialog", "Decision Page Pring", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.print_tab), _translate("OwnRecordDialog", "Print", None))

