# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PlanCaseDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PlanCaseDialog(object):
    def setupUi(self, PlanCaseDialog):
        PlanCaseDialog.setObjectName(_fromUtf8("PlanCaseDialog"))
        PlanCaseDialog.resize(785, 486)
        self.import_groupbox = QtGui.QGroupBox(PlanCaseDialog)
        self.import_groupbox.setEnabled(True)
        self.import_groupbox.setGeometry(QtCore.QRect(20, 75, 381, 90))
        self.import_groupbox.setObjectName(_fromUtf8("import_groupbox"))
        self.parcel_shape_edit = QtGui.QLineEdit(self.import_groupbox)
        self.parcel_shape_edit.setGeometry(QtCore.QRect(109, 58, 211, 21))
        self.parcel_shape_edit.setReadOnly(True)
        self.parcel_shape_edit.setObjectName(_fromUtf8("parcel_shape_edit"))
        self.label = QtGui.QLabel(self.import_groupbox)
        self.label.setGeometry(QtCore.QRect(110, 39, 112, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.open_parcel_file_button = QtGui.QPushButton(self.import_groupbox)
        self.open_parcel_file_button.setGeometry(QtCore.QRect(330, 56, 42, 25))
        self.open_parcel_file_button.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_parcel_file_button.setIcon(icon)
        self.open_parcel_file_button.setObjectName(_fromUtf8("open_parcel_file_button"))
        self.point_rbutton = QtGui.QRadioButton(self.import_groupbox)
        self.point_rbutton.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.point_rbutton.setObjectName(_fromUtf8("point_rbutton"))
        self.line_rbutton = QtGui.QRadioButton(self.import_groupbox)
        self.line_rbutton.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.line_rbutton.setObjectName(_fromUtf8("line_rbutton"))
        self.polygon_rbutton = QtGui.QRadioButton(self.import_groupbox)
        self.polygon_rbutton.setEnabled(True)
        self.polygon_rbutton.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.polygon_rbutton.setObjectName(_fromUtf8("polygon_rbutton"))
        self.result_twidget = QtGui.QTreeWidget(PlanCaseDialog)
        self.result_twidget.setGeometry(QtCore.QRect(410, 30, 361, 361))
        self.result_twidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.result_twidget.setObjectName(_fromUtf8("result_twidget"))
        self.result_twidget.header().setDefaultSectionSize(100)
        self.groupBox = QtGui.QGroupBox(PlanCaseDialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 168, 381, 224))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 167, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.type_edit = QtGui.QLineEdit(self.groupBox)
        self.type_edit.setGeometry(QtCore.QRect(10, 74, 361, 20))
        self.type_edit.setReadOnly(True)
        self.type_edit.setObjectName(_fromUtf8("type_edit"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 57, 81, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.date_edit = QtGui.QLineEdit(self.groupBox)
        self.date_edit.setGeometry(QtCore.QRect(10, 36, 91, 20))
        self.date_edit.setReadOnly(True)
        self.date_edit.setObjectName(_fromUtf8("date_edit"))
        self.plan_num_edit = QtGui.QLineEdit(self.groupBox)
        self.plan_num_edit.setGeometry(QtCore.QRect(110, 36, 170, 20))
        self.plan_num_edit.setReadOnly(True)
        self.plan_num_edit.setObjectName(_fromUtf8("plan_num_edit"))
        self.status_edit = QtGui.QLineEdit(self.groupBox)
        self.status_edit.setGeometry(QtCore.QRect(10, 112, 361, 20))
        self.status_edit.setReadOnly(True)
        self.status_edit.setObjectName(_fromUtf8("status_edit"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 96, 81, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.message_label = QtGui.QLabel(self.groupBox)
        self.message_label.setGeometry(QtCore.QRect(10, 145, 361, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.message_label.setFont(font)
        self.message_label.setObjectName(_fromUtf8("message_label"))
        self.line = QtGui.QFrame(PlanCaseDialog)
        self.line.setGeometry(QtCore.QRect(0, 18, 785, 7))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(PlanCaseDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 460, 785, 7))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.help_button = QtGui.QPushButton(PlanCaseDialog)
        self.help_button.setGeometry(QtCore.QRect(518, 430, 75, 23))
        self.help_button.setStyleSheet(_fromUtf8("image: url(:/plugins/lm2/help_button.png);"))
        self.help_button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/help_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_button.setIcon(icon1)
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.close_button = QtGui.QPushButton(PlanCaseDialog)
        self.close_button.setGeometry(QtCore.QRect(697, 430, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.apply_button = QtGui.QPushButton(PlanCaseDialog)
        self.apply_button.setGeometry(QtCore.QRect(607, 430, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.groupBox_2 = QtGui.QGroupBox(PlanCaseDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 24, 381, 48))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.zone_parcel_rbutton = QtGui.QRadioButton(self.groupBox_2)
        self.zone_parcel_rbutton.setGeometry(QtCore.QRect(10, 18, 120, 17))
        self.zone_parcel_rbutton.setObjectName(_fromUtf8("zone_parcel_rbutton"))
        self.zone_sub_rbutton = QtGui.QRadioButton(self.groupBox_2)
        self.zone_sub_rbutton.setGeometry(QtCore.QRect(130, 18, 120, 17))
        self.zone_sub_rbutton.setObjectName(_fromUtf8("zone_sub_rbutton"))
        self.zone_main_rbutton = QtGui.QRadioButton(self.groupBox_2)
        self.zone_main_rbutton.setGeometry(QtCore.QRect(250, 18, 120, 17))
        self.zone_main_rbutton.setObjectName(_fromUtf8("zone_main_rbutton"))
        self.status_label = QtGui.QLabel(PlanCaseDialog)
        self.status_label.setGeometry(QtCore.QRect(20, 430, 341, 16))
        self.status_label.setText(_fromUtf8(""))
        self.status_label.setObjectName(_fromUtf8("status_label"))

        self.retranslateUi(PlanCaseDialog)
        QtCore.QMetaObject.connectSlotsByName(PlanCaseDialog)

    def retranslateUi(self, PlanCaseDialog):
        PlanCaseDialog.setWindowTitle(_translate("PlanCaseDialog", "Dialog", None))
        self.import_groupbox.setTitle(_translate("PlanCaseDialog", "Import", None))
        self.label.setText(_translate("PlanCaseDialog", "Parcel Shapefile", None))
        self.point_rbutton.setText(_translate("PlanCaseDialog", "Point", None))
        self.line_rbutton.setText(_translate("PlanCaseDialog", "Line", None))
        self.polygon_rbutton.setText(_translate("PlanCaseDialog", "Polygon", None))
        self.result_twidget.headerItem().setText(0, _translate("PlanCaseDialog", "Maintenance Case Objects", None))
        self.groupBox.setTitle(_translate("PlanCaseDialog", "General information", None))
        self.label_2.setText(_translate("PlanCaseDialog", "Date & Number", None))
        self.label_3.setText(_translate("PlanCaseDialog", "Type", None))
        self.label_4.setText(_translate("PlanCaseDialog", "Status", None))
        self.message_label.setText(_translate("PlanCaseDialog", "Message Information", None))
        self.close_button.setText(_translate("PlanCaseDialog", "Close", None))
        self.apply_button.setText(_translate("PlanCaseDialog", "Apply", None))
        self.groupBox_2.setTitle(_translate("PlanCaseDialog", "Type", None))
        self.zone_parcel_rbutton.setText(_translate("PlanCaseDialog", "Parcel", None))
        self.zone_sub_rbutton.setText(_translate("PlanCaseDialog", "Sub", None))
        self.zone_main_rbutton.setText(_translate("PlanCaseDialog", "Main", None))

import resources_rc
