# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PastureMonitoringValueDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PastureMonitoringValueDialog(object):
    def setupUi(self, PastureMonitoringValueDialog):
        PastureMonitoringValueDialog.setObjectName(_fromUtf8("PastureMonitoringValueDialog"))
        PastureMonitoringValueDialog.resize(840, 536)
        self.pasture_value_tab = QtGui.QTabWidget(PastureMonitoringValueDialog)
        self.pasture_value_tab.setGeometry(QtCore.QRect(346, 64, 491, 441))
        self.pasture_value_tab.setObjectName(_fromUtf8("pasture_value_tab"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_5.setGeometry(QtCore.QRect(4, 0, 471, 451))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_27 = QtGui.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(10, 90, 41, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.x_gradus_edit = QtGui.QLineEdit(self.groupBox_5)
        self.x_gradus_edit.setGeometry(QtCore.QRect(10, 106, 45, 20))
        self.x_gradus_edit.setObjectName(_fromUtf8("x_gradus_edit"))
        self.y_gradus_edit = QtGui.QLineEdit(self.groupBox_5)
        self.y_gradus_edit.setGeometry(QtCore.QRect(10, 142, 45, 20))
        self.y_gradus_edit.setObjectName(_fromUtf8("y_gradus_edit"))
        self.label_28 = QtGui.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(10, 126, 41, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.point_twidget = QtGui.QTableWidget(self.groupBox_5)
        self.point_twidget.setGeometry(QtCore.QRect(10, 210, 451, 131))
        self.point_twidget.setObjectName(_fromUtf8("point_twidget"))
        self.point_twidget.setColumnCount(3)
        self.point_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.point_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.point_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.point_twidget.setHorizontalHeaderItem(2, item)
        self.edit_point_button = QtGui.QPushButton(self.groupBox_5)
        self.edit_point_button.setGeometry(QtCore.QRect(130, 166, 50, 23))
        self.edit_point_button.setObjectName(_fromUtf8("edit_point_button"))
        self.add_point_button = QtGui.QPushButton(self.groupBox_5)
        self.add_point_button.setEnabled(False)
        self.add_point_button.setGeometry(QtCore.QRect(70, 166, 50, 23))
        self.add_point_button.setObjectName(_fromUtf8("add_point_button"))
        self.delet_point_button = QtGui.QPushButton(self.groupBox_5)
        self.delet_point_button.setGeometry(QtCore.QRect(190, 166, 50, 23))
        self.delet_point_button.setObjectName(_fromUtf8("delet_point_button"))
        self.x_minute_edit = QtGui.QLineEdit(self.groupBox_5)
        self.x_minute_edit.setGeometry(QtCore.QRect(60, 106, 45, 20))
        self.x_minute_edit.setObjectName(_fromUtf8("x_minute_edit"))
        self.x_second_edit = QtGui.QLineEdit(self.groupBox_5)
        self.x_second_edit.setGeometry(QtCore.QRect(110, 106, 45, 20))
        self.x_second_edit.setObjectName(_fromUtf8("x_second_edit"))
        self.y_minute_edit = QtGui.QLineEdit(self.groupBox_5)
        self.y_minute_edit.setGeometry(QtCore.QRect(60, 142, 45, 20))
        self.y_minute_edit.setObjectName(_fromUtf8("y_minute_edit"))
        self.y_second_edit = QtGui.QLineEdit(self.groupBox_5)
        self.y_second_edit.setGeometry(QtCore.QRect(110, 142, 45, 20))
        self.y_second_edit.setObjectName(_fromUtf8("y_second_edit"))
        self.label_35 = QtGui.QLabel(self.groupBox_5)
        self.label_35.setGeometry(QtCore.QRect(60, 90, 41, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.groupBox_5)
        self.label_36.setGeometry(QtCore.QRect(110, 90, 51, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_38 = QtGui.QLabel(self.groupBox_5)
        self.label_38.setGeometry(QtCore.QRect(60, 126, 41, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.groupBox_5)
        self.label_39.setGeometry(QtCore.QRect(110, 126, 51, 16))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.all_point_chbox = QtGui.QCheckBox(self.groupBox_5)
        self.all_point_chbox.setGeometry(QtCore.QRect(10, 190, 451, 17))
        self.all_point_chbox.setObjectName(_fromUtf8("all_point_chbox"))
        self.new_point_button = QtGui.QPushButton(self.groupBox_5)
        self.new_point_button.setEnabled(False)
        self.new_point_button.setGeometry(QtCore.QRect(10, 166, 50, 23))
        self.new_point_button.setObjectName(_fromUtf8("new_point_button"))
        self.label_42 = QtGui.QLabel(self.groupBox_5)
        self.label_42.setGeometry(QtCore.QRect(10, 54, 141, 16))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.point_id_edit = QtGui.QLineEdit(self.groupBox_5)
        self.point_id_edit.setEnabled(False)
        self.point_id_edit.setGeometry(QtCore.QRect(10, 70, 141, 20))
        self.point_id_edit.setObjectName(_fromUtf8("point_id_edit"))
        self.label_43 = QtGui.QLabel(self.groupBox_5)
        self.label_43.setGeometry(QtCore.QRect(160, 90, 51, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.x_utm_edit = QtGui.QLineEdit(self.groupBox_5)
        self.x_utm_edit.setEnabled(False)
        self.x_utm_edit.setGeometry(QtCore.QRect(160, 106, 81, 20))
        self.x_utm_edit.setObjectName(_fromUtf8("x_utm_edit"))
        self.label_44 = QtGui.QLabel(self.groupBox_5)
        self.label_44.setGeometry(QtCore.QRect(160, 126, 51, 16))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.y_utm_edit = QtGui.QLineEdit(self.groupBox_5)
        self.y_utm_edit.setEnabled(False)
        self.y_utm_edit.setGeometry(QtCore.QRect(160, 142, 81, 20))
        self.y_utm_edit.setObjectName(_fromUtf8("y_utm_edit"))
        self.single_point_scale_sbox = QtGui.QSpinBox(self.groupBox_5)
        self.single_point_scale_sbox.setGeometry(QtCore.QRect(10, 388, 54, 22))
        self.single_point_scale_sbox.setObjectName(_fromUtf8("single_point_scale_sbox"))
        self.single_point_zoom_button = QtGui.QPushButton(self.groupBox_5)
        self.single_point_zoom_button.setGeometry(QtCore.QRect(75, 388, 131, 23))
        self.single_point_zoom_button.setObjectName(_fromUtf8("single_point_zoom_button"))
        self.natural_zone_edit = QtGui.QLineEdit(self.groupBox_5)
        self.natural_zone_edit.setEnabled(False)
        self.natural_zone_edit.setGeometry(QtCore.QRect(160, 70, 290, 20))
        self.natural_zone_edit.setObjectName(_fromUtf8("natural_zone_edit"))
        self.label_46 = QtGui.QLabel(self.groupBox_5)
        self.label_46.setGeometry(QtCore.QRect(160, 54, 171, 16))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.area_ga_edit = QtGui.QLineEdit(self.groupBox_5)
        self.area_ga_edit.setEnabled(False)
        self.area_ga_edit.setGeometry(QtCore.QRect(320, 122, 101, 20))
        self.area_ga_edit.setObjectName(_fromUtf8("area_ga_edit"))
        self.parcel_id_edit = QtGui.QLineEdit(self.groupBox_5)
        self.parcel_id_edit.setEnabled(False)
        self.parcel_id_edit.setGeometry(QtCore.QRect(8, 28, 131, 20))
        self.parcel_id_edit.setObjectName(_fromUtf8("parcel_id_edit"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(9, 13, 131, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.input_area_chbox = QtGui.QCheckBox(self.groupBox_5)
        self.input_area_chbox.setEnabled(True)
        self.input_area_chbox.setGeometry(QtCore.QRect(320, 104, 101, 17))
        self.input_area_chbox.setObjectName(_fromUtf8("input_area_chbox"))
        self.duration_days_edit = QtGui.QLineEdit(self.groupBox_5)
        self.duration_days_edit.setEnabled(False)
        self.duration_days_edit.setGeometry(QtCore.QRect(320, 168, 101, 20))
        self.duration_days_edit.setObjectName(_fromUtf8("duration_days_edit"))
        self.input_duration_chbox = QtGui.QCheckBox(self.groupBox_5)
        self.input_duration_chbox.setEnabled(True)
        self.input_duration_chbox.setGeometry(QtCore.QRect(320, 150, 101, 17))
        self.input_duration_chbox.setObjectName(_fromUtf8("input_duration_chbox"))
        self.label_29 = QtGui.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(10, 344, 361, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.land_form_cbox = QtGui.QComboBox(self.groupBox_5)
        self.land_form_cbox.setGeometry(QtCore.QRect(10, 360, 451, 20))
        self.land_form_cbox.setObjectName(_fromUtf8("land_form_cbox"))
        self.parcel_neighbourhood_edit = QtGui.QLineEdit(self.groupBox_5)
        self.parcel_neighbourhood_edit.setEnabled(False)
        self.parcel_neighbourhood_edit.setGeometry(QtCore.QRect(160, 28, 290, 20))
        self.parcel_neighbourhood_edit.setObjectName(_fromUtf8("parcel_neighbourhood_edit"))
        self.label_57 = QtGui.QLabel(self.groupBox_5)
        self.label_57.setGeometry(QtCore.QRect(160, 13, 291, 16))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.pasture_value_tab.addTab(self.tab_6, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.photos_group_box = QtGui.QGroupBox(self.tab)
        self.photos_group_box.setGeometry(QtCore.QRect(0, 0, 481, 411))
        self.photos_group_box.setObjectName(_fromUtf8("photos_group_box"))
        self.photo_load_button = QtGui.QPushButton(self.photos_group_box)
        self.photo_load_button.setGeometry(QtCore.QRect(320, 17, 101, 23))
        self.photo_load_button.setObjectName(_fromUtf8("photo_load_button"))
        self.around_photo_rbutton = QtGui.QRadioButton(self.photos_group_box)
        self.around_photo_rbutton.setGeometry(QtCore.QRect(10, 20, 121, 17))
        self.around_photo_rbutton.setObjectName(_fromUtf8("around_photo_rbutton"))
        self.cover_photo_rbutton = QtGui.QRadioButton(self.photos_group_box)
        self.cover_photo_rbutton.setGeometry(QtCore.QRect(140, 20, 111, 17))
        self.cover_photo_rbutton.setObjectName(_fromUtf8("cover_photo_rbutton"))
        self.photos_twidget = QtGui.QTableWidget(self.photos_group_box)
        self.photos_twidget.setGeometry(QtCore.QRect(10, 50, 461, 353))
        self.photos_twidget.setObjectName(_fromUtf8("photos_twidget"))
        self.photos_twidget.setColumnCount(6)
        self.photos_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.photos_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.photos_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.photos_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.photos_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.photos_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.photos_twidget.setHorizontalHeaderItem(5, item)
        self.pasture_value_tab.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.pasture_values_twidget = QtGui.QTableWidget(self.tab_5)
        self.pasture_values_twidget.setGeometry(QtCore.QRect(8, 26, 473, 371))
        self.pasture_values_twidget.setObjectName(_fromUtf8("pasture_values_twidget"))
        self.pasture_values_twidget.setColumnCount(0)
        self.pasture_values_twidget.setRowCount(0)
        self.pushButton = QtGui.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(680, 266, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pasture_value_save_button = QtGui.QPushButton(self.tab_5)
        self.pasture_value_save_button.setGeometry(QtCore.QRect(680, 230, 75, 23))
        self.pasture_value_save_button.setObjectName(_fromUtf8("pasture_value_save_button"))
        self.label_2 = QtGui.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(10, 6, 391, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cover_calc_button = QtGui.QPushButton(self.tab_5)
        self.cover_calc_button.setGeometry(QtCore.QRect(400, 0, 81, 23))
        self.cover_calc_button.setObjectName(_fromUtf8("cover_calc_button"))
        self.pasture_value_tab.addTab(self.tab_5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.live_stock_twidget = QtGui.QTableWidget(self.tab_2)
        self.live_stock_twidget.setGeometry(QtCore.QRect(8, 26, 473, 201))
        self.live_stock_twidget.setObjectName(_fromUtf8("live_stock_twidget"))
        self.live_stock_twidget.setColumnCount(0)
        self.live_stock_twidget.setRowCount(0)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(7, 7, 451, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.sheep_unit_button = QtGui.QPushButton(self.tab_2)
        self.sheep_unit_button.setGeometry(QtCore.QRect(10, 240, 141, 23))
        self.sheep_unit_button.setObjectName(_fromUtf8("sheep_unit_button"))
        self.sheep_unit_twidget = QtGui.QTableWidget(self.tab_2)
        self.sheep_unit_twidget.setGeometry(QtCore.QRect(10, 270, 473, 91))
        self.sheep_unit_twidget.setObjectName(_fromUtf8("sheep_unit_twidget"))
        self.sheep_unit_twidget.setColumnCount(0)
        self.sheep_unit_twidget.setRowCount(0)
        self.pasture_value_tab.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.urgats_twidget = QtGui.QTableWidget(self.tab_3)
        self.urgats_twidget.setGeometry(QtCore.QRect(10, 160, 473, 131))
        self.urgats_twidget.setObjectName(_fromUtf8("urgats_twidget"))
        self.urgats_twidget.setColumnCount(9)
        self.urgats_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.urgats_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.urgats_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.urgats_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.urgats_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.urgats_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.urgats_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.urgats_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.urgats_twidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.urgats_twidget.setHorizontalHeaderItem(8, item)
        self.urgats_twidget.horizontalHeader().setDefaultSectionSize(70)
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(10, 140, 461, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.biomass_type_cbox = QtGui.QComboBox(self.tab_3)
        self.biomass_type_cbox.setGeometry(QtCore.QRect(10, 30, 171, 22))
        self.biomass_type_cbox.setObjectName(_fromUtf8("biomass_type_cbox"))
        self.m_1_sbox = QtGui.QSpinBox(self.tab_3)
        self.m_1_sbox.setGeometry(QtCore.QRect(10, 80, 47, 20))
        self.m_1_sbox.setMinimum(1)
        self.m_1_sbox.setMaximum(25)
        self.m_1_sbox.setProperty("value", 15)
        self.m_1_sbox.setObjectName(_fromUtf8("m_1_sbox"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.m_2_sbox = QtGui.QSpinBox(self.tab_3)
        self.m_2_sbox.setGeometry(QtCore.QRect(170, 80, 47, 20))
        self.m_2_sbox.setMinimum(25)
        self.m_2_sbox.setMaximum(35)
        self.m_2_sbox.setObjectName(_fromUtf8("m_2_sbox"))
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(170, 60, 51, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.m_3_sbox = QtGui.QSpinBox(self.tab_3)
        self.m_3_sbox.setGeometry(QtCore.QRect(330, 79, 47, 20))
        self.m_3_sbox.setMinimum(35)
        self.m_3_sbox.setMaximum(49)
        self.m_3_sbox.setObjectName(_fromUtf8("m_3_sbox"))
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(330, 59, 51, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(70, 60, 81, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(230, 59, 71, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(390, 59, 81, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.delete_biomass_button = QtGui.QPushButton(self.tab_3)
        self.delete_biomass_button.setGeometry(QtCore.QRect(250, 114, 71, 23))
        self.delete_biomass_button.setObjectName(_fromUtf8("delete_biomass_button"))
        self.add_biomass_button = QtGui.QPushButton(self.tab_3)
        self.add_biomass_button.setEnabled(True)
        self.add_biomass_button.setGeometry(QtCore.QRect(98, 114, 71, 23))
        self.add_biomass_button.setObjectName(_fromUtf8("add_biomass_button"))
        self.edit_biomass_button = QtGui.QPushButton(self.tab_3)
        self.edit_biomass_button.setGeometry(QtCore.QRect(174, 114, 71, 23))
        self.edit_biomass_button.setObjectName(_fromUtf8("edit_biomass_button"))
        self.label_55 = QtGui.QLabel(self.tab_3)
        self.label_55.setGeometry(QtCore.QRect(10, 300, 471, 16))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.missed_evaluation_cbox = QtGui.QComboBox(self.tab_3)
        self.missed_evaluation_cbox.setGeometry(QtCore.QRect(10, 320, 471, 22))
        self.missed_evaluation_cbox.setObjectName(_fromUtf8("missed_evaluation_cbox"))
        self.label_56 = QtGui.QLabel(self.tab_3)
        self.label_56.setGeometry(QtCore.QRect(10, 345, 471, 16))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.soil_evaluation_cbox = QtGui.QComboBox(self.tab_3)
        self.soil_evaluation_cbox.setGeometry(QtCore.QRect(10, 366, 471, 22))
        self.soil_evaluation_cbox.setObjectName(_fromUtf8("soil_evaluation_cbox"))
        self.m_1_value_sbox = QtGui.QDoubleSpinBox(self.tab_3)
        self.m_1_value_sbox.setGeometry(QtCore.QRect(70, 80, 67, 22))
        self.m_1_value_sbox.setMaximum(999.99)
        self.m_1_value_sbox.setObjectName(_fromUtf8("m_1_value_sbox"))
        self.m_2_value_sbox = QtGui.QDoubleSpinBox(self.tab_3)
        self.m_2_value_sbox.setGeometry(QtCore.QRect(230, 80, 67, 22))
        self.m_2_value_sbox.setMaximum(999.99)
        self.m_2_value_sbox.setObjectName(_fromUtf8("m_2_value_sbox"))
        self.m_3_value_sbox = QtGui.QDoubleSpinBox(self.tab_3)
        self.m_3_value_sbox.setGeometry(QtCore.QRect(390, 80, 67, 22))
        self.m_3_value_sbox.setMaximum(999.99)
        self.m_3_value_sbox.setObjectName(_fromUtf8("m_3_value_sbox"))
        self.pasture_value_tab.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox = QtGui.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(1, 230, 481, 168))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_49 = QtGui.QLabel(self.groupBox)
        self.label_49.setGeometry(QtCore.QRect(220, 110, 241, 16))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_40 = QtGui.QLabel(self.groupBox)
        self.label_40.setGeometry(QtCore.QRect(220, 21, 241, 16))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_31 = QtGui.QLabel(self.groupBox)
        self.label_31.setGeometry(QtCore.QRect(10, 81, 46, 13))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.calc_d1_100ga_edit = QtGui.QLineEdit(self.groupBox)
        self.calc_d1_100ga_edit.setGeometry(QtCore.QRect(90, 50, 120, 20))
        self.calc_d1_100ga_edit.setReadOnly(True)
        self.calc_d1_100ga_edit.setObjectName(_fromUtf8("calc_d1_100ga_edit"))
        self.calc_unelgee_edit = QtGui.QLineEdit(self.groupBox)
        self.calc_unelgee_edit.setGeometry(QtCore.QRect(90, 139, 120, 20))
        self.calc_unelgee_edit.setReadOnly(True)
        self.calc_unelgee_edit.setObjectName(_fromUtf8("calc_unelgee_edit"))
        self.label_47 = QtGui.QLabel(self.groupBox)
        self.label_47.setGeometry(QtCore.QRect(220, 51, 241, 16))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.calc_d1_edit = QtGui.QLineEdit(self.groupBox)
        self.calc_d1_edit.setGeometry(QtCore.QRect(90, 20, 120, 20))
        self.calc_d1_edit.setReadOnly(True)
        self.calc_d1_edit.setObjectName(_fromUtf8("calc_d1_edit"))
        self.label_32 = QtGui.QLabel(self.groupBox)
        self.label_32.setGeometry(QtCore.QRect(10, 111, 46, 13))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_37 = QtGui.QLabel(self.groupBox)
        self.label_37.setGeometry(QtCore.QRect(10, 140, 46, 13))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.calc_d2_edit = QtGui.QLineEdit(self.groupBox)
        self.calc_d2_edit.setGeometry(QtCore.QRect(90, 80, 120, 20))
        self.calc_d2_edit.setReadOnly(True)
        self.calc_d2_edit.setObjectName(_fromUtf8("calc_d2_edit"))
        self.label_51 = QtGui.QLabel(self.groupBox)
        self.label_51.setGeometry(QtCore.QRect(220, 140, 241, 16))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(10, 24, 46, 13))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_48 = QtGui.QLabel(self.groupBox)
        self.label_48.setGeometry(QtCore.QRect(220, 80, 241, 16))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.label_30 = QtGui.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(10, 51, 81, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.calc_d3_edit = QtGui.QLineEdit(self.groupBox)
        self.calc_d3_edit.setGeometry(QtCore.QRect(90, 110, 120, 20))
        self.calc_d3_edit.setReadOnly(True)
        self.calc_d3_edit.setObjectName(_fromUtf8("calc_d3_edit"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(1, 0, 481, 231))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_52 = QtGui.QLabel(self.groupBox_2)
        self.label_52.setGeometry(QtCore.QRect(10, 17, 91, 16))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.calc_date_edit = QtGui.QDateEdit(self.groupBox_2)
        self.calc_date_edit.setGeometry(QtCore.QRect(10, 37, 91, 22))
        self.calc_date_edit.setObjectName(_fromUtf8("calc_date_edit"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(110, 17, 81, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.calc_area_sbox = QtGui.QSpinBox(self.groupBox_2)
        self.calc_area_sbox.setEnabled(True)
        self.calc_area_sbox.setGeometry(QtCore.QRect(110, 37, 91, 22))
        self.calc_area_sbox.setReadOnly(False)
        self.calc_area_sbox.setMaximum(1000000000)
        self.calc_area_sbox.setObjectName(_fromUtf8("calc_area_sbox"))
        self.label_54 = QtGui.QLabel(self.groupBox_2)
        self.label_54.setGeometry(QtCore.QRect(210, 17, 61, 16))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.calc_duration_sbox = QtGui.QSpinBox(self.groupBox_2)
        self.calc_duration_sbox.setEnabled(True)
        self.calc_duration_sbox.setGeometry(QtCore.QRect(210, 37, 63, 22))
        self.calc_duration_sbox.setReadOnly(False)
        self.calc_duration_sbox.setMaximum(1000000000)
        self.calc_duration_sbox.setObjectName(_fromUtf8("calc_duration_sbox"))
        self.calc_biomass_sbox = QtGui.QSpinBox(self.groupBox_2)
        self.calc_biomass_sbox.setEnabled(True)
        self.calc_biomass_sbox.setGeometry(QtCore.QRect(210, 81, 64, 22))
        self.calc_biomass_sbox.setReadOnly(True)
        self.calc_biomass_sbox.setMaximum(1000000000)
        self.calc_biomass_sbox.setObjectName(_fromUtf8("calc_biomass_sbox"))
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(210, 61, 65, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(110, 61, 90, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.calc_rc_edit = QtGui.QLineEdit(self.groupBox_2)
        self.calc_rc_edit.setEnabled(True)
        self.calc_rc_edit.setGeometry(QtCore.QRect(10, 81, 91, 20))
        self.calc_rc_edit.setObjectName(_fromUtf8("calc_rc_edit"))
        self.calc_rc_precent_sbox = QtGui.QSpinBox(self.groupBox_2)
        self.calc_rc_precent_sbox.setEnabled(True)
        self.calc_rc_precent_sbox.setGeometry(QtCore.QRect(110, 81, 90, 22))
        self.calc_rc_precent_sbox.setReadOnly(True)
        self.calc_rc_precent_sbox.setMaximum(1000000000)
        self.calc_rc_precent_sbox.setObjectName(_fromUtf8("calc_rc_precent_sbox"))
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(10, 61, 61, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.biomass_present_edit = QtGui.QLineEdit(self.groupBox_2)
        self.biomass_present_edit.setEnabled(True)
        self.biomass_present_edit.setGeometry(QtCore.QRect(284, 81, 99, 20))
        self.biomass_present_edit.setObjectName(_fromUtf8("biomass_present_edit"))
        self.label_58 = QtGui.QLabel(self.groupBox_2)
        self.label_58.setGeometry(QtCore.QRect(284, 61, 109, 16))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(284, 17, 89, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.calc_sheep_unit_plant_sbox = QtGui.QSpinBox(self.groupBox_2)
        self.calc_sheep_unit_plant_sbox.setEnabled(True)
        self.calc_sheep_unit_plant_sbox.setGeometry(QtCore.QRect(283, 37, 99, 22))
        self.calc_sheep_unit_plant_sbox.setReadOnly(True)
        self.calc_sheep_unit_plant_sbox.setMaximum(1000000000)
        self.calc_sheep_unit_plant_sbox.setObjectName(_fromUtf8("calc_sheep_unit_plant_sbox"))
        self.calc_sheep_unit_sbox = QtGui.QSpinBox(self.groupBox_2)
        self.calc_sheep_unit_sbox.setEnabled(True)
        self.calc_sheep_unit_sbox.setGeometry(QtCore.QRect(390, 37, 80, 22))
        self.calc_sheep_unit_sbox.setReadOnly(True)
        self.calc_sheep_unit_sbox.setMaximum(1000000000)
        self.calc_sheep_unit_sbox.setObjectName(_fromUtf8("calc_sheep_unit_sbox"))
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(390, 17, 81, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.calc_refresh_button = QtGui.QPushButton(self.groupBox_2)
        self.calc_refresh_button.setGeometry(QtCore.QRect(330, 190, 141, 23))
        self.calc_refresh_button.setObjectName(_fromUtf8("calc_refresh_button"))
        self.begin_month_date = QtGui.QDateEdit(self.groupBox_2)
        self.begin_month_date.setGeometry(QtCore.QRect(10, 125, 91, 22))
        self.begin_month_date.setCalendarPopup(True)
        self.begin_month_date.setObjectName(_fromUtf8("begin_month_date"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 105, 91, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(110, 105, 91, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.end_month_date = QtGui.QDateEdit(self.groupBox_2)
        self.end_month_date.setGeometry(QtCore.QRect(110, 125, 91, 22))
        self.end_month_date.setCalendarPopup(True)
        self.end_month_date.setObjectName(_fromUtf8("end_month_date"))
        self.calc_load_button = QtGui.QPushButton(self.groupBox_2)
        self.calc_load_button.setGeometry(QtCore.QRect(331, 120, 141, 23))
        self.calc_load_button.setObjectName(_fromUtf8("calc_load_button"))
        self.calc_present_rbutton = QtGui.QRadioButton(self.groupBox_2)
        self.calc_present_rbutton.setGeometry(QtCore.QRect(330, 150, 141, 17))
        self.calc_present_rbutton.setObjectName(_fromUtf8("calc_present_rbutton"))
        self.calc_comparison_rbutton = QtGui.QRadioButton(self.groupBox_2)
        self.calc_comparison_rbutton.setGeometry(QtCore.QRect(330, 170, 141, 17))
        self.calc_comparison_rbutton.setObjectName(_fromUtf8("calc_comparison_rbutton"))
        self.pasture_value_tab.addTab(self.tab_4, _fromUtf8(""))
        self.line = QtGui.QFrame(PastureMonitoringValueDialog)
        self.line.setGeometry(QtCore.QRect(0, 13, 801, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(PastureMonitoringValueDialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 151, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox_3 = QtGui.QGroupBox(PastureMonitoringValueDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(7, 21, 331, 484))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_33 = QtGui.QLabel(self.groupBox_3)
        self.label_33.setGeometry(QtCore.QRect(10, 192, 71, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.point_detail_twidget = QtGui.QTableWidget(self.groupBox_3)
        self.point_detail_twidget.setGeometry(QtCore.QRect(10, 275, 311, 171))
        self.point_detail_twidget.setObjectName(_fromUtf8("point_detail_twidget"))
        self.point_detail_twidget.setColumnCount(5)
        self.point_detail_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.point_detail_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.point_detail_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.point_detail_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.point_detail_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.point_detail_twidget.setHorizontalHeaderItem(4, item)
        self.elevation_sbox = QtGui.QSpinBox(self.groupBox_3)
        self.elevation_sbox.setGeometry(QtCore.QRect(10, 208, 81, 20))
        self.elevation_sbox.setMinimum(10)
        self.elevation_sbox.setMaximum(4000)
        self.elevation_sbox.setObjectName(_fromUtf8("elevation_sbox"))
        self.point_detail_date = QtGui.QDateEdit(self.groupBox_3)
        self.point_detail_date.setGeometry(QtCore.QRect(10, 172, 81, 20))
        self.point_detail_date.setObjectName(_fromUtf8("point_detail_date"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 157, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.delete_detail_button = QtGui.QPushButton(self.groupBox_3)
        self.delete_detail_button.setGeometry(QtCore.QRect(238, 232, 71, 23))
        self.delete_detail_button.setObjectName(_fromUtf8("delete_detail_button"))
        self.new_detail_button = QtGui.QPushButton(self.groupBox_3)
        self.new_detail_button.setGeometry(QtCore.QRect(10, 232, 71, 23))
        self.new_detail_button.setObjectName(_fromUtf8("new_detail_button"))
        self.add_detail_button = QtGui.QPushButton(self.groupBox_3)
        self.add_detail_button.setEnabled(False)
        self.add_detail_button.setGeometry(QtCore.QRect(86, 232, 71, 23))
        self.add_detail_button.setObjectName(_fromUtf8("add_detail_button"))
        self.edit_detail_button = QtGui.QPushButton(self.groupBox_3)
        self.edit_detail_button.setGeometry(QtCore.QRect(162, 232, 71, 23))
        self.edit_detail_button.setObjectName(_fromUtf8("edit_detail_button"))
        self.all_point_details_chbox = QtGui.QCheckBox(self.groupBox_3)
        self.all_point_details_chbox.setGeometry(QtCore.QRect(10, 255, 311, 17))
        self.all_point_details_chbox.setObjectName(_fromUtf8("all_point_details_chbox"))
        self.label_41 = QtGui.QLabel(self.groupBox_3)
        self.label_41.setGeometry(QtCore.QRect(110, 120, 211, 16))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.pug_boundary_cbox = QtGui.QComboBox(self.groupBox_3)
        self.pug_boundary_cbox.setGeometry(QtCore.QRect(10, 56, 221, 22))
        self.pug_boundary_cbox.setObjectName(_fromUtf8("pug_boundary_cbox"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 231, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.parcel_cbox = QtGui.QComboBox(self.groupBox_3)
        self.parcel_cbox.setGeometry(QtCore.QRect(10, 96, 221, 22))
        self.parcel_cbox.setObjectName(_fromUtf8("parcel_cbox"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 221, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.value_load_button = QtGui.QPushButton(self.groupBox_3)
        self.value_load_button.setGeometry(QtCore.QRect(240, 96, 81, 23))
        self.value_load_button.setObjectName(_fromUtf8("value_load_button"))
        self.land_name_text_edit = QtGui.QTextEdit(self.groupBox_3)
        self.land_name_text_edit.setGeometry(QtCore.QRect(110, 136, 208, 91))
        self.land_name_text_edit.setObjectName(_fromUtf8("land_name_text_edit"))
        self.point_detail_id_edit = QtGui.QLineEdit(self.groupBox_3)
        self.point_detail_id_edit.setEnabled(False)
        self.point_detail_id_edit.setGeometry(QtCore.QRect(10, 137, 81, 20))
        self.point_detail_id_edit.setObjectName(_fromUtf8("point_detail_id_edit"))
        self.label_45 = QtGui.QLabel(self.groupBox_3)
        self.label_45.setGeometry(QtCore.QRect(10, 120, 87, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.point_zoom_button = QtGui.QPushButton(self.groupBox_3)
        self.point_zoom_button.setGeometry(QtCore.QRect(55, 452, 161, 23))
        self.point_zoom_button.setObjectName(_fromUtf8("point_zoom_button"))
        self.point_scale_sbox = QtGui.QSpinBox(self.groupBox_3)
        self.point_scale_sbox.setGeometry(QtCore.QRect(10, 452, 40, 22))
        self.point_scale_sbox.setObjectName(_fromUtf8("point_scale_sbox"))
        self.print_button = QtGui.QPushButton(self.groupBox_3)
        self.print_button.setGeometry(QtCore.QRect(231, 452, 91, 23))
        self.print_button.setObjectName(_fromUtf8("print_button"))
        self.otor_find_chbox = QtGui.QCheckBox(self.groupBox_3)
        self.otor_find_chbox.setGeometry(QtCore.QRect(10, 20, 211, 17))
        self.otor_find_chbox.setObjectName(_fromUtf8("otor_find_chbox"))
        self.help_button = QtGui.QPushButton(PastureMonitoringValueDialog)
        self.help_button.setGeometry(QtCore.QRect(549, 510, 101, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.apply_button = QtGui.QPushButton(PastureMonitoringValueDialog)
        self.apply_button.setGeometry(QtCore.QRect(670, 510, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.status_label = QtGui.QLabel(PastureMonitoringValueDialog)
        self.status_label.setGeometry(QtCore.QRect(10, 510, 511, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.close_button = QtGui.QPushButton(PastureMonitoringValueDialog)
        self.close_button.setGeometry(QtCore.QRect(760, 510, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.end_year_sbox = QtGui.QSpinBox(PastureMonitoringValueDialog)
        self.end_year_sbox.setGeometry(QtCore.QRect(666, 41, 68, 20))
        self.end_year_sbox.setMaximum(2200)
        self.end_year_sbox.setProperty("value", 2018)
        self.end_year_sbox.setObjectName(_fromUtf8("end_year_sbox"))
        self.begin_year_sbox = QtGui.QSpinBox(PastureMonitoringValueDialog)
        self.begin_year_sbox.setGeometry(QtCore.QRect(590, 41, 68, 20))
        self.begin_year_sbox.setMaximum(2200)
        self.begin_year_sbox.setProperty("value", 2017)
        self.begin_year_sbox.setObjectName(_fromUtf8("begin_year_sbox"))
        self.plant_value_load_button = QtGui.QPushButton(PastureMonitoringValueDialog)
        self.plant_value_load_button.setGeometry(QtCore.QRect(740, 40, 81, 23))
        self.plant_value_load_button.setObjectName(_fromUtf8("plant_value_load_button"))
        self.label_18 = QtGui.QLabel(PastureMonitoringValueDialog)
        self.label_18.setGeometry(QtCore.QRect(590, 25, 71, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(PastureMonitoringValueDialog)
        self.label_19.setGeometry(QtCore.QRect(670, 25, 61, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.print_year_sbox = QtGui.QSpinBox(PastureMonitoringValueDialog)
        self.print_year_sbox.setGeometry(QtCore.QRect(350, 41, 68, 20))
        self.print_year_sbox.setMaximum(2200)
        self.print_year_sbox.setProperty("value", 2017)
        self.print_year_sbox.setObjectName(_fromUtf8("print_year_sbox"))
        self.label_53 = QtGui.QLabel(PastureMonitoringValueDialog)
        self.label_53.setGeometry(QtCore.QRect(350, 24, 151, 16))
        self.label_53.setObjectName(_fromUtf8("label_53"))

        self.retranslateUi(PastureMonitoringValueDialog)
        self.pasture_value_tab.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(PastureMonitoringValueDialog)
        PastureMonitoringValueDialog.setTabOrder(self.value_load_button, self.point_detail_twidget)
        PastureMonitoringValueDialog.setTabOrder(self.point_detail_twidget, self.plant_value_load_button)
        PastureMonitoringValueDialog.setTabOrder(self.plant_value_load_button, self.x_gradus_edit)
        PastureMonitoringValueDialog.setTabOrder(self.x_gradus_edit, self.x_minute_edit)
        PastureMonitoringValueDialog.setTabOrder(self.x_minute_edit, self.x_second_edit)
        PastureMonitoringValueDialog.setTabOrder(self.x_second_edit, self.y_gradus_edit)
        PastureMonitoringValueDialog.setTabOrder(self.y_gradus_edit, self.y_minute_edit)
        PastureMonitoringValueDialog.setTabOrder(self.y_minute_edit, self.y_second_edit)
        PastureMonitoringValueDialog.setTabOrder(self.y_second_edit, self.add_point_button)
        PastureMonitoringValueDialog.setTabOrder(self.add_point_button, self.apply_button)
        PastureMonitoringValueDialog.setTabOrder(self.apply_button, self.elevation_sbox)
        PastureMonitoringValueDialog.setTabOrder(self.elevation_sbox, self.point_detail_date)
        PastureMonitoringValueDialog.setTabOrder(self.point_detail_date, self.delete_detail_button)
        PastureMonitoringValueDialog.setTabOrder(self.delete_detail_button, self.new_detail_button)
        PastureMonitoringValueDialog.setTabOrder(self.new_detail_button, self.add_detail_button)
        PastureMonitoringValueDialog.setTabOrder(self.add_detail_button, self.edit_detail_button)
        PastureMonitoringValueDialog.setTabOrder(self.edit_detail_button, self.all_point_details_chbox)
        PastureMonitoringValueDialog.setTabOrder(self.all_point_details_chbox, self.pug_boundary_cbox)
        PastureMonitoringValueDialog.setTabOrder(self.pug_boundary_cbox, self.parcel_cbox)
        PastureMonitoringValueDialog.setTabOrder(self.parcel_cbox, self.pasture_value_tab)
        PastureMonitoringValueDialog.setTabOrder(self.pasture_value_tab, self.land_name_text_edit)
        PastureMonitoringValueDialog.setTabOrder(self.land_name_text_edit, self.point_detail_id_edit)
        PastureMonitoringValueDialog.setTabOrder(self.point_detail_id_edit, self.point_zoom_button)
        PastureMonitoringValueDialog.setTabOrder(self.point_zoom_button, self.point_scale_sbox)
        PastureMonitoringValueDialog.setTabOrder(self.point_scale_sbox, self.print_button)
        PastureMonitoringValueDialog.setTabOrder(self.print_button, self.print_year_sbox)
        PastureMonitoringValueDialog.setTabOrder(self.print_year_sbox, self.otor_find_chbox)
        PastureMonitoringValueDialog.setTabOrder(self.otor_find_chbox, self.close_button)
        PastureMonitoringValueDialog.setTabOrder(self.close_button, self.parcel_id_edit)
        PastureMonitoringValueDialog.setTabOrder(self.parcel_id_edit, self.point_twidget)
        PastureMonitoringValueDialog.setTabOrder(self.point_twidget, self.edit_point_button)
        PastureMonitoringValueDialog.setTabOrder(self.edit_point_button, self.land_form_cbox)
        PastureMonitoringValueDialog.setTabOrder(self.land_form_cbox, self.delet_point_button)
        PastureMonitoringValueDialog.setTabOrder(self.delet_point_button, self.end_year_sbox)
        PastureMonitoringValueDialog.setTabOrder(self.end_year_sbox, self.begin_year_sbox)
        PastureMonitoringValueDialog.setTabOrder(self.begin_year_sbox, self.help_button)
        PastureMonitoringValueDialog.setTabOrder(self.help_button, self.area_ga_edit)
        PastureMonitoringValueDialog.setTabOrder(self.area_ga_edit, self.all_point_chbox)
        PastureMonitoringValueDialog.setTabOrder(self.all_point_chbox, self.new_point_button)
        PastureMonitoringValueDialog.setTabOrder(self.new_point_button, self.point_id_edit)
        PastureMonitoringValueDialog.setTabOrder(self.point_id_edit, self.x_utm_edit)
        PastureMonitoringValueDialog.setTabOrder(self.x_utm_edit, self.y_utm_edit)
        PastureMonitoringValueDialog.setTabOrder(self.y_utm_edit, self.single_point_scale_sbox)
        PastureMonitoringValueDialog.setTabOrder(self.single_point_scale_sbox, self.single_point_zoom_button)
        PastureMonitoringValueDialog.setTabOrder(self.single_point_zoom_button, self.natural_zone_edit)
        PastureMonitoringValueDialog.setTabOrder(self.natural_zone_edit, self.pasture_values_twidget)
        PastureMonitoringValueDialog.setTabOrder(self.pasture_values_twidget, self.pushButton)
        PastureMonitoringValueDialog.setTabOrder(self.pushButton, self.pasture_value_save_button)
        PastureMonitoringValueDialog.setTabOrder(self.pasture_value_save_button, self.cover_calc_button)
        PastureMonitoringValueDialog.setTabOrder(self.cover_calc_button, self.live_stock_twidget)
        PastureMonitoringValueDialog.setTabOrder(self.live_stock_twidget, self.sheep_unit_button)
        PastureMonitoringValueDialog.setTabOrder(self.sheep_unit_button, self.sheep_unit_twidget)
        PastureMonitoringValueDialog.setTabOrder(self.sheep_unit_twidget, self.urgats_twidget)
        PastureMonitoringValueDialog.setTabOrder(self.urgats_twidget, self.biomass_type_cbox)
        PastureMonitoringValueDialog.setTabOrder(self.biomass_type_cbox, self.m_1_sbox)
        PastureMonitoringValueDialog.setTabOrder(self.m_1_sbox, self.m_2_sbox)
        PastureMonitoringValueDialog.setTabOrder(self.m_2_sbox, self.m_3_sbox)
        PastureMonitoringValueDialog.setTabOrder(self.m_3_sbox, self.delete_biomass_button)
        PastureMonitoringValueDialog.setTabOrder(self.delete_biomass_button, self.add_biomass_button)
        PastureMonitoringValueDialog.setTabOrder(self.add_biomass_button, self.edit_biomass_button)

    def retranslateUi(self, PastureMonitoringValueDialog):
        PastureMonitoringValueDialog.setWindowTitle(_translate("PastureMonitoringValueDialog", "Dialog", None))
        self.groupBox_5.setTitle(_translate("PastureMonitoringValueDialog", "Point", None))
        self.label_27.setText(_translate("PastureMonitoringValueDialog", "x °", None))
        self.label_28.setText(_translate("PastureMonitoringValueDialog", "y °", None))
        item = self.point_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureMonitoringValueDialog", "Point ID", None))
        item = self.point_twidget.horizontalHeaderItem(1)
        item.setText(_translate("PastureMonitoringValueDialog", "X", None))
        item = self.point_twidget.horizontalHeaderItem(2)
        item.setText(_translate("PastureMonitoringValueDialog", "Y", None))
        self.edit_point_button.setText(_translate("PastureMonitoringValueDialog", "Edit", None))
        self.add_point_button.setText(_translate("PastureMonitoringValueDialog", "Add", None))
        self.delet_point_button.setText(_translate("PastureMonitoringValueDialog", "Delete", None))
        self.label_35.setText(_translate("PastureMonitoringValueDialog", "x \'", None))
        self.label_36.setText(_translate("PastureMonitoringValueDialog", "x \'\'", None))
        self.label_38.setText(_translate("PastureMonitoringValueDialog", "y \'", None))
        self.label_39.setText(_translate("PastureMonitoringValueDialog", "y \'\'", None))
        self.all_point_chbox.setText(_translate("PastureMonitoringValueDialog", "All Points(Only working soum and without register)", None))
        self.new_point_button.setText(_translate("PastureMonitoringValueDialog", "New", None))
        self.label_42.setText(_translate("PastureMonitoringValueDialog", "Point ID", None))
        self.label_43.setText(_translate("PastureMonitoringValueDialog", "UTM", None))
        self.label_44.setText(_translate("PastureMonitoringValueDialog", "UTM", None))
        self.single_point_zoom_button.setText(_translate("PastureMonitoringValueDialog", "Zoom To Selected Point", None))
        self.label_46.setText(_translate("PastureMonitoringValueDialog", "Natural zone", None))
        self.area_ga_edit.setText(_translate("PastureMonitoringValueDialog", "0", None))
        self.label_17.setText(_translate("PastureMonitoringValueDialog", "Parcel ID", None))
        self.input_area_chbox.setText(_translate("PastureMonitoringValueDialog", "Input Area", None))
        self.duration_days_edit.setText(_translate("PastureMonitoringValueDialog", "0", None))
        self.input_duration_chbox.setText(_translate("PastureMonitoringValueDialog", "Input Duration", None))
        self.label_29.setText(_translate("PastureMonitoringValueDialog", "Land Form", None))
        self.label_57.setText(_translate("PastureMonitoringValueDialog", "Land neighbourhood", None))
        self.pasture_value_tab.setTabText(self.pasture_value_tab.indexOf(self.tab_6), _translate("PastureMonitoringValueDialog", "Monitoring Point", None))
        self.photos_group_box.setTitle(_translate("PastureMonitoringValueDialog", "Photos", None))
        self.photo_load_button.setText(_translate("PastureMonitoringValueDialog", "Photo Load", None))
        self.around_photo_rbutton.setText(_translate("PastureMonitoringValueDialog", "Around photo", None))
        self.cover_photo_rbutton.setText(_translate("PastureMonitoringValueDialog", "Cover photo", None))
        item = self.photos_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureMonitoringValueDialog", "Provided", None))
        item = self.photos_twidget.horizontalHeaderItem(1)
        item.setText(_translate("PastureMonitoringValueDialog", "Description", None))
        item = self.photos_twidget.horizontalHeaderItem(2)
        item.setText(_translate("PastureMonitoringValueDialog", "Name", None))
        item = self.photos_twidget.horizontalHeaderItem(3)
        item.setText(_translate("PastureMonitoringValueDialog", "Open", None))
        item = self.photos_twidget.horizontalHeaderItem(4)
        item.setText(_translate("PastureMonitoringValueDialog", "Remove", None))
        item = self.photos_twidget.horizontalHeaderItem(5)
        item.setText(_translate("PastureMonitoringValueDialog", "View", None))
        self.pasture_value_tab.setTabText(self.pasture_value_tab.indexOf(self.tab), _translate("PastureMonitoringValueDialog", "Photo", None))
        self.pushButton.setText(_translate("PastureMonitoringValueDialog", "Print", None))
        self.pasture_value_save_button.setText(_translate("PastureMonitoringValueDialog", "Save", None))
        self.label_2.setText(_translate("PastureMonitoringValueDialog", "Is check pasture plants cover", None))
        self.cover_calc_button.setText(_translate("PastureMonitoringValueDialog", "Cover Calc", None))
        self.pasture_value_tab.setTabText(self.pasture_value_tab.indexOf(self.tab_5), _translate("PastureMonitoringValueDialog", "Land Cover", None))
        self.label_6.setText(_translate("PastureMonitoringValueDialog", "Live Stock values", None))
        self.sheep_unit_button.setText(_translate("PastureMonitoringValueDialog", "Sheep Unit Calc", None))
        self.pasture_value_tab.setTabText(self.pasture_value_tab.indexOf(self.tab_2), _translate("PastureMonitoringValueDialog", "Live Stock/Urgats", None))
        item = self.urgats_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureMonitoringValueDialog", "Year", None))
        item = self.urgats_twidget.horizontalHeaderItem(1)
        item.setText(_translate("PastureMonitoringValueDialog", "Type", None))
        item = self.urgats_twidget.horizontalHeaderItem(2)
        item.setText(_translate("PastureMonitoringValueDialog", "Bio mass kg/ga", None))
        item = self.urgats_twidget.horizontalHeaderItem(3)
        item.setText(_translate("PastureMonitoringValueDialog", "1-M", None))
        item = self.urgats_twidget.horizontalHeaderItem(4)
        item.setText(_translate("PastureMonitoringValueDialog", "1-M Value", None))
        item = self.urgats_twidget.horizontalHeaderItem(5)
        item.setText(_translate("PastureMonitoringValueDialog", "2-M", None))
        item = self.urgats_twidget.horizontalHeaderItem(6)
        item.setText(_translate("PastureMonitoringValueDialog", "2-M Value", None))
        item = self.urgats_twidget.horizontalHeaderItem(7)
        item.setText(_translate("PastureMonitoringValueDialog", "3-M", None))
        item = self.urgats_twidget.horizontalHeaderItem(8)
        item.setText(_translate("PastureMonitoringValueDialog", "3-M Value", None))
        self.label_7.setText(_translate("PastureMonitoringValueDialog", "Urgats values", None))
        self.label_9.setText(_translate("PastureMonitoringValueDialog", "BioMass Type", None))
        self.label_10.setText(_translate("PastureMonitoringValueDialog", "1-M", None))
        self.label_11.setText(_translate("PastureMonitoringValueDialog", "2-M", None))
        self.label_12.setText(_translate("PastureMonitoringValueDialog", "2-M", None))
        self.label_13.setText(_translate("PastureMonitoringValueDialog", "1-M Value", None))
        self.label_14.setText(_translate("PastureMonitoringValueDialog", "2-M Value", None))
        self.label_15.setText(_translate("PastureMonitoringValueDialog", "3-M Value", None))
        self.delete_biomass_button.setText(_translate("PastureMonitoringValueDialog", "Delete", None))
        self.add_biomass_button.setText(_translate("PastureMonitoringValueDialog", "Add", None))
        self.edit_biomass_button.setText(_translate("PastureMonitoringValueDialog", "edit", None))
        self.label_55.setText(_translate("PastureMonitoringValueDialog", "Pasture missed Evaluation", None))
        self.label_56.setText(_translate("PastureMonitoringValueDialog", "Pasture soil Evaluation", None))
        self.pasture_value_tab.setTabText(self.pasture_value_tab.indexOf(self.tab_3), _translate("PastureMonitoringValueDialog", "Bio Mass", None))
        self.groupBox.setTitle(_translate("PastureMonitoringValueDialog", "Calculate Values", None))
        self.label_49.setText(_translate("PastureMonitoringValueDialog", "Боломжит даац", None))
        self.label_40.setText(_translate("PastureMonitoringValueDialog", "1 га-д бэлчиж болох хонин толгой", None))
        self.label_31.setText(_translate("PastureMonitoringValueDialog", "D-2:", None))
        self.label_47.setText(_translate("PastureMonitoringValueDialog", "100 га-д бэлчиж болох хонин толгой", None))
        self.label_32.setText(_translate("PastureMonitoringValueDialog", "D-3:", None))
        self.label_37.setText(_translate("PastureMonitoringValueDialog", "Unelgee:", None))
        self.label_51.setText(_translate("PastureMonitoringValueDialog", "Боломжит ХТ- Одоо байгаа ХТ = Үнэлгээ", None))
        self.label_26.setText(_translate("PastureMonitoringValueDialog", "D-1:", None))
        self.label_48.setText(_translate("PastureMonitoringValueDialog", "1 хонин толгойд шаардлагатай талбай", None))
        self.label_30.setText(_translate("PastureMonitoringValueDialog", "D-1-100ga:", None))
        self.groupBox_2.setTitle(_translate("PastureMonitoringValueDialog", "Basic Values", None))
        self.label_52.setText(_translate("PastureMonitoringValueDialog", "Monitoring Date", None))
        self.label_20.setText(_translate("PastureMonitoringValueDialog", "Area", None))
        self.label_54.setText(_translate("PastureMonitoringValueDialog", "Duration", None))
        self.label_21.setText(_translate("PastureMonitoringValueDialog", "Bio mass", None))
        self.label_23.setText(_translate("PastureMonitoringValueDialog", "RC Precent", None))
        self.label_22.setText(_translate("PastureMonitoringValueDialog", "RC", None))
        self.label_58.setText(_translate("PastureMonitoringValueDialog", "BioMass Pre", None))
        self.label_24.setText(_translate("PastureMonitoringValueDialog", "SHU plant", None))
        self.label_25.setText(_translate("PastureMonitoringValueDialog", "Sheep Unit", None))
        self.calc_refresh_button.setText(_translate("PastureMonitoringValueDialog", "Refresh", None))
        self.label_8.setText(_translate("PastureMonitoringValueDialog", "Begin Month", None))
        self.label_16.setText(_translate("PastureMonitoringValueDialog", "End Month", None))
        self.calc_load_button.setText(_translate("PastureMonitoringValueDialog", "Load", None))
        self.calc_present_rbutton.setText(_translate("PastureMonitoringValueDialog", "Present calculate", None))
        self.calc_comparison_rbutton.setText(_translate("PastureMonitoringValueDialog", "Comparison calculate", None))
        self.pasture_value_tab.setTabText(self.pasture_value_tab.indexOf(self.tab_4), _translate("PastureMonitoringValueDialog", "Calculate", None))
        self.label.setText(_translate("PastureMonitoringValueDialog", "Contract", None))
        self.groupBox_3.setTitle(_translate("PastureMonitoringValueDialog", "Point Detail", None))
        self.label_33.setText(_translate("PastureMonitoringValueDialog", "Elevation", None))
        item = self.point_detail_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureMonitoringValueDialog", "ID", None))
        item = self.point_detail_twidget.horizontalHeaderItem(1)
        item.setText(_translate("PastureMonitoringValueDialog", "Date", None))
        item = self.point_detail_twidget.horizontalHeaderItem(2)
        item.setText(_translate("PastureMonitoringValueDialog", "Land Name", None))
        item = self.point_detail_twidget.horizontalHeaderItem(3)
        item.setText(_translate("PastureMonitoringValueDialog", "Land Form", None))
        item = self.point_detail_twidget.horizontalHeaderItem(4)
        item.setText(_translate("PastureMonitoringValueDialog", "Elevation", None))
        self.label_4.setText(_translate("PastureMonitoringValueDialog", "Date", None))
        self.delete_detail_button.setText(_translate("PastureMonitoringValueDialog", "Delete", None))
        self.new_detail_button.setText(_translate("PastureMonitoringValueDialog", "New", None))
        self.add_detail_button.setText(_translate("PastureMonitoringValueDialog", "Add", None))
        self.edit_detail_button.setText(_translate("PastureMonitoringValueDialog", "edit", None))
        self.all_point_details_chbox.setText(_translate("PastureMonitoringValueDialog", "All Point Information(Only working aimag)", None))
        self.label_41.setText(_translate("PastureMonitoringValueDialog", "Land Name", None))
        self.label_5.setText(_translate("PastureMonitoringValueDialog", "PUG/Otor Zone", None))
        self.label_3.setText(_translate("PastureMonitoringValueDialog", "Parcel", None))
        self.value_load_button.setText(_translate("PastureMonitoringValueDialog", "Find", None))
        self.label_45.setText(_translate("PastureMonitoringValueDialog", "ID", None))
        self.point_zoom_button.setText(_translate("PastureMonitoringValueDialog", "Zoom To Point", None))
        self.print_button.setText(_translate("PastureMonitoringValueDialog", "Print", None))
        self.otor_find_chbox.setText(_translate("PastureMonitoringValueDialog", "Reserve zone", None))
        self.help_button.setText(_translate("PastureMonitoringValueDialog", "?", None))
        self.apply_button.setText(_translate("PastureMonitoringValueDialog", "Apply", None))
        self.status_label.setText(_translate("PastureMonitoringValueDialog", "Messages", None))
        self.close_button.setText(_translate("PastureMonitoringValueDialog", "Close", None))
        self.plant_value_load_button.setText(_translate("PastureMonitoringValueDialog", "Load", None))
        self.label_18.setText(_translate("PastureMonitoringValueDialog", "Begin", None))
        self.label_19.setText(_translate("PastureMonitoringValueDialog", "End", None))
        self.label_53.setText(_translate("PastureMonitoringValueDialog", "Current year", None))

