# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PastureSettings.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PastureSettings(object):
    def setupUi(self, PastureSettings):
        PastureSettings.setObjectName(_fromUtf8("PastureSettings"))
        PastureSettings.resize(808, 538)
        self.tabWidget = QtGui.QTabWidget(PastureSettings)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 786, 487))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.documents_tab = QtGui.QWidget()
        self.documents_tab.setObjectName(_fromUtf8("documents_tab"))
        self.groupBox_12 = QtGui.QGroupBox(self.documents_tab)
        self.groupBox_12.setGeometry(QtCore.QRect(5, 10, 766, 356))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.doc_twidget = QtGui.QTableWidget(self.groupBox_12)
        self.doc_twidget.setGeometry(QtCore.QRect(20, 40, 701, 301))
        self.doc_twidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.doc_twidget.setObjectName(_fromUtf8("doc_twidget"))
        self.doc_twidget.setColumnCount(5)
        self.doc_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(4, item)
        self.doc_twidget.horizontalHeader().setCascadingSectionResizes(False)
        self.doc_twidget.horizontalHeader().setDefaultSectionSize(120)
        self.doc_twidget.horizontalHeader().setHighlightSections(False)
        self.doc_twidget.verticalHeader().setCascadingSectionResizes(False)
        self.add_document_button = QtGui.QPushButton(self.groupBox_12)
        self.add_document_button.setGeometry(QtCore.QRect(730, 150, 31, 31))
        self.add_document_button.setObjectName(_fromUtf8("add_document_button"))
        self.remove_document_button = QtGui.QPushButton(self.groupBox_12)
        self.remove_document_button.setGeometry(QtCore.QRect(730, 190, 31, 31))
        self.remove_document_button.setObjectName(_fromUtf8("remove_document_button"))
        self.load_off_document_button = QtGui.QPushButton(self.groupBox_12)
        self.load_off_document_button.setGeometry(QtCore.QRect(730, 110, 31, 31))
        self.load_off_document_button.setObjectName(_fromUtf8("load_off_document_button"))
        self.tabWidget.addTab(self.documents_tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_10.setGeometry(QtCore.QRect(6, 3, 766, 451))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_10)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 300, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.select_codelist_cbox = QtGui.QComboBox(self.groupBox_10)
        self.select_codelist_cbox.setGeometry(QtCore.QRect(20, 40, 691, 22))
        self.select_codelist_cbox.setObjectName(_fromUtf8("select_codelist_cbox"))
        self.label_12 = QtGui.QLabel(self.groupBox_10)
        self.label_12.setGeometry(QtCore.QRect(20, 70, 300, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.delete_button = QtGui.QPushButton(self.groupBox_10)
        self.delete_button.setGeometry(QtCore.QRect(725, 230, 31, 31))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.add_button = QtGui.QPushButton(self.groupBox_10)
        self.add_button.setGeometry(QtCore.QRect(725, 190, 31, 31))
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.table_widget = QtGui.QTableWidget(self.groupBox_10)
        self.table_widget.setGeometry(QtCore.QRect(20, 95, 691, 341))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_widget.sizePolicy().hasHeightForWidth())
        self.table_widget.setSizePolicy(sizePolicy)
        self.table_widget.setObjectName(_fromUtf8("table_widget"))
        self.table_widget.setColumnCount(2)
        self.table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_widget.setHorizontalHeaderItem(1, item)
        self.table_widget.horizontalHeader().setDefaultSectionSize(80)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(370, 0, 401, 441))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.base_type = QtGui.QComboBox(self.groupBox)
        self.base_type.setGeometry(QtCore.QRect(10, 40, 381, 22))
        self.base_type.setObjectName(_fromUtf8("base_type"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 341, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.connect_type_twidget = QtGui.QTableWidget(self.groupBox)
        self.connect_type_twidget.setGeometry(QtCore.QRect(10, 90, 381, 341))
        self.connect_type_twidget.setObjectName(_fromUtf8("connect_type_twidget"))
        self.connect_type_twidget.setColumnCount(2)
        self.connect_type_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.connect_type_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.connect_type_twidget.setHorizontalHeaderItem(1, item)
        self.all_types_chbox = QtGui.QCheckBox(self.groupBox)
        self.all_types_chbox.setGeometry(QtCore.QRect(10, 70, 181, 17))
        self.all_types_chbox.setObjectName(_fromUtf8("all_types_chbox"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 351, 441))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.live_stock_convert_twidget = QtGui.QTableWidget(self.groupBox_2)
        self.live_stock_convert_twidget.setEnabled(False)
        self.live_stock_convert_twidget.setGeometry(QtCore.QRect(10, 240, 331, 192))
        self.live_stock_convert_twidget.setObjectName(_fromUtf8("live_stock_convert_twidget"))
        self.live_stock_convert_twidget.setColumnCount(2)
        self.live_stock_convert_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.live_stock_convert_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.live_stock_convert_twidget.setHorizontalHeaderItem(1, item)
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 17, 199, 171))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.app_type_pasture_type_rbutton = QtGui.QRadioButton(self.layoutWidget)
        self.app_type_pasture_type_rbutton.setObjectName(_fromUtf8("app_type_pasture_type_rbutton"))
        self.verticalLayout.addWidget(self.app_type_pasture_type_rbutton)
        self.app_type_doc_type_rbutton = QtGui.QRadioButton(self.layoutWidget)
        self.app_type_doc_type_rbutton.setObjectName(_fromUtf8("app_type_doc_type_rbutton"))
        self.verticalLayout.addWidget(self.app_type_doc_type_rbutton)
        self.contract_doc_type_rbutton = QtGui.QRadioButton(self.layoutWidget)
        self.contract_doc_type_rbutton.setObjectName(_fromUtf8("contract_doc_type_rbutton"))
        self.verticalLayout.addWidget(self.contract_doc_type_rbutton)
        self.natural_zone_land_form_rbutton = QtGui.QRadioButton(self.layoutWidget)
        self.natural_zone_land_form_rbutton.setObjectName(_fromUtf8("natural_zone_land_form_rbutton"))
        self.verticalLayout.addWidget(self.natural_zone_land_form_rbutton)
        self.natural_zone_land_plants_rbutton = QtGui.QRadioButton(self.layoutWidget)
        self.natural_zone_land_plants_rbutton.setObjectName(_fromUtf8("natural_zone_land_plants_rbutton"))
        self.verticalLayout.addWidget(self.natural_zone_land_plants_rbutton)
        self.formula_type_land_form_rbutton = QtGui.QRadioButton(self.layoutWidget)
        self.formula_type_land_form_rbutton.setObjectName(_fromUtf8("formula_type_land_form_rbutton"))
        self.verticalLayout.addWidget(self.formula_type_land_form_rbutton)
        self.live_stock_convert_rbutton = QtGui.QRadioButton(self.layoutWidget)
        self.live_stock_convert_rbutton.setObjectName(_fromUtf8("live_stock_convert_rbutton"))
        self.verticalLayout.addWidget(self.live_stock_convert_rbutton)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 10, 341, 361))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.recovery_class_twidget = QtGui.QTableWidget(self.groupBox_3)
        self.recovery_class_twidget.setGeometry(QtCore.QRect(10, 30, 321, 321))
        self.recovery_class_twidget.setObjectName(_fromUtf8("recovery_class_twidget"))
        self.recovery_class_twidget.setColumnCount(2)
        self.recovery_class_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.recovery_class_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.recovery_class_twidget.setHorizontalHeaderItem(1, item)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(380, 10, 341, 361))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.sheep_food_twidget = QtGui.QTableWidget(self.groupBox_4)
        self.sheep_food_twidget.setGeometry(QtCore.QRect(10, 30, 321, 321))
        self.sheep_food_twidget.setObjectName(_fromUtf8("sheep_food_twidget"))
        self.sheep_food_twidget.setColumnCount(2)
        self.sheep_food_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.sheep_food_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sheep_food_twidget.setHorizontalHeaderItem(1, item)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 341, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.natural_zone_cbox = QtGui.QComboBox(self.tab_3)
        self.natural_zone_cbox.setGeometry(QtCore.QRect(10, 30, 381, 22))
        self.natural_zone_cbox.setObjectName(_fromUtf8("natural_zone_cbox"))
        self.land_form_twidget = QtGui.QTableWidget(self.tab_3)
        self.land_form_twidget.setGeometry(QtCore.QRect(10, 60, 761, 211))
        self.land_form_twidget.setObjectName(_fromUtf8("land_form_twidget"))
        self.land_form_twidget.setColumnCount(1)
        self.land_form_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.land_form_twidget.setHorizontalHeaderItem(0, item)
        self.land_form_twidget.horizontalHeader().setDefaultSectionSize(800)
        self.formula_tab_widget = QtGui.QTabWidget(self.tab_3)
        self.formula_tab_widget.setGeometry(QtCore.QRect(0, 280, 781, 180))
        self.formula_tab_widget.setObjectName(_fromUtf8("formula_tab_widget"))
        self.formula_precent_tab = QtGui.QWidget()
        self.formula_precent_tab.setObjectName(_fromUtf8("formula_precent_tab"))
        self.label_4 = QtGui.QLabel(self.formula_precent_tab)
        self.label_4.setGeometry(QtCore.QRect(10, 47, 221, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.recovery_class_cbox = QtGui.QComboBox(self.formula_precent_tab)
        self.recovery_class_cbox.setGeometry(QtCore.QRect(10, 22, 231, 22))
        self.recovery_class_cbox.setObjectName(_fromUtf8("recovery_class_cbox"))
        self.label_5 = QtGui.QLabel(self.formula_precent_tab)
        self.label_5.setGeometry(QtCore.QRect(10, 92, 111, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formula_add_button = QtGui.QPushButton(self.formula_precent_tab)
        self.formula_add_button.setGeometry(QtCore.QRect(250, 32, 75, 23))
        self.formula_add_button.setObjectName(_fromUtf8("formula_add_button"))
        self.formula_twidget = QtGui.QTableWidget(self.formula_precent_tab)
        self.formula_twidget.setGeometry(QtCore.QRect(330, 12, 438, 131))
        self.formula_twidget.setObjectName(_fromUtf8("formula_twidget"))
        self.formula_twidget.setColumnCount(4)
        self.formula_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.formula_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.formula_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.formula_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.formula_twidget.setHorizontalHeaderItem(3, item)
        self.plants_cbox = QtGui.QComboBox(self.formula_precent_tab)
        self.plants_cbox.setGeometry(QtCore.QRect(10, 67, 231, 22))
        self.plants_cbox.setObjectName(_fromUtf8("plants_cbox"))
        self.label_6 = QtGui.QLabel(self.formula_precent_tab)
        self.label_6.setGeometry(QtCore.QRect(160, 92, 81, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_3 = QtGui.QLabel(self.formula_precent_tab)
        self.label_3.setGeometry(QtCore.QRect(10, 2, 221, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.less_symbol_cbox = QtGui.QComboBox(self.formula_precent_tab)
        self.less_symbol_cbox.setGeometry(QtCore.QRect(10, 112, 121, 22))
        self.less_symbol_cbox.setObjectName(_fromUtf8("less_symbol_cbox"))
        self.precent_value_sbox = QtGui.QSpinBox(self.formula_precent_tab)
        self.precent_value_sbox.setGeometry(QtCore.QRect(160, 112, 81, 22))
        self.precent_value_sbox.setObjectName(_fromUtf8("precent_value_sbox"))
        self.formula_delete_button = QtGui.QPushButton(self.formula_precent_tab)
        self.formula_delete_button.setGeometry(QtCore.QRect(250, 92, 75, 23))
        self.formula_delete_button.setObjectName(_fromUtf8("formula_delete_button"))
        self.formula_update_button = QtGui.QPushButton(self.formula_precent_tab)
        self.formula_update_button.setGeometry(QtCore.QRect(250, 62, 75, 23))
        self.formula_update_button.setObjectName(_fromUtf8("formula_update_button"))
        self.formula_tab_widget.addTab(self.formula_precent_tab, _fromUtf8(""))
        self.formula_comparison_tab = QtGui.QWidget()
        self.formula_comparison_tab.setObjectName(_fromUtf8("formula_comparison_tab"))
        self.label_7 = QtGui.QLabel(self.formula_comparison_tab)
        self.label_7.setGeometry(QtCore.QRect(10, 2, 91, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.formula_comparison_tab)
        self.label_8.setGeometry(QtCore.QRect(10, 47, 221, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.recovery_class_comp_cbox = QtGui.QComboBox(self.formula_comparison_tab)
        self.recovery_class_comp_cbox.setGeometry(QtCore.QRect(10, 22, 121, 22))
        self.recovery_class_comp_cbox.setObjectName(_fromUtf8("recovery_class_comp_cbox"))
        self.plants_comp_cbox = QtGui.QComboBox(self.formula_comparison_tab)
        self.plants_comp_cbox.setGeometry(QtCore.QRect(10, 67, 251, 22))
        self.plants_comp_cbox.setObjectName(_fromUtf8("plants_comp_cbox"))
        self.add_comparison_button = QtGui.QPushButton(self.formula_comparison_tab)
        self.add_comparison_button.setGeometry(QtCore.QRect(280, 66, 75, 23))
        self.add_comparison_button.setObjectName(_fromUtf8("add_comparison_button"))
        self.more_delete_button = QtGui.QPushButton(self.formula_comparison_tab)
        self.more_delete_button.setGeometry(QtCore.QRect(410, 128, 75, 23))
        self.more_delete_button.setObjectName(_fromUtf8("more_delete_button"))
        self.formula_more_twidget = QtGui.QTableWidget(self.formula_comparison_tab)
        self.formula_more_twidget.setGeometry(QtCore.QRect(360, 24, 181, 101))
        self.formula_more_twidget.setObjectName(_fromUtf8("formula_more_twidget"))
        self.formula_more_twidget.setColumnCount(1)
        self.formula_more_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.formula_more_twidget.setHorizontalHeaderItem(0, item)
        self.formula_more_twidget.horizontalHeader().setDefaultSectionSize(180)
        self.formula_less_twidget = QtGui.QTableWidget(self.formula_comparison_tab)
        self.formula_less_twidget.setGeometry(QtCore.QRect(588, 24, 181, 101))
        self.formula_less_twidget.setObjectName(_fromUtf8("formula_less_twidget"))
        self.formula_less_twidget.setColumnCount(1)
        self.formula_less_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.formula_less_twidget.setHorizontalHeaderItem(0, item)
        self.formula_less_twidget.horizontalHeader().setDefaultSectionSize(180)
        self.label_9 = QtGui.QLabel(self.formula_comparison_tab)
        self.label_9.setGeometry(QtCore.QRect(550, 40, 29, 48))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.soil_evaluation_cbox = QtGui.QComboBox(self.formula_comparison_tab)
        self.soil_evaluation_cbox.setEnabled(False)
        self.soil_evaluation_cbox.setGeometry(QtCore.QRect(10, 112, 331, 22))
        self.soil_evaluation_cbox.setObjectName(_fromUtf8("soil_evaluation_cbox"))
        self.soil_evaluation_chbox = QtGui.QCheckBox(self.formula_comparison_tab)
        self.soil_evaluation_chbox.setGeometry(QtCore.QRect(10, 92, 231, 17))
        self.soil_evaluation_chbox.setObjectName(_fromUtf8("soil_evaluation_chbox"))
        self.less_delete_button = QtGui.QPushButton(self.formula_comparison_tab)
        self.less_delete_button.setGeometry(QtCore.QRect(640, 128, 75, 23))
        self.less_delete_button.setObjectName(_fromUtf8("less_delete_button"))
        self.label_10 = QtGui.QLabel(self.formula_comparison_tab)
        self.label_10.setGeometry(QtCore.QRect(360, 7, 161, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_13 = QtGui.QLabel(self.formula_comparison_tab)
        self.label_13.setGeometry(QtCore.QRect(588, 7, 161, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.formula_comparison_tab)
        self.label_14.setGeometry(QtCore.QRect(140, 2, 111, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.less_symbol_comp_cbox = QtGui.QComboBox(self.formula_comparison_tab)
        self.less_symbol_comp_cbox.setGeometry(QtCore.QRect(140, 22, 121, 22))
        self.less_symbol_comp_cbox.setObjectName(_fromUtf8("less_symbol_comp_cbox"))
        self.formula_tab_widget.addTab(self.formula_comparison_tab, _fromUtf8(""))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.nz_pasture_type_twidget = QtGui.QTableWidget(self.tab_4)
        self.nz_pasture_type_twidget.setGeometry(QtCore.QRect(10, 60, 761, 371))
        self.nz_pasture_type_twidget.setObjectName(_fromUtf8("nz_pasture_type_twidget"))
        self.nz_pasture_type_twidget.setColumnCount(7)
        self.nz_pasture_type_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.nz_pasture_type_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.nz_pasture_type_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.nz_pasture_type_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.nz_pasture_type_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.nz_pasture_type_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.nz_pasture_type_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.nz_pasture_type_twidget.setHorizontalHeaderItem(6, item)
        self.nz_pasture_type_twidget.horizontalHeader().setDefaultSectionSize(120)
        self.nz_pasture_type_twidget.horizontalHeader().setMinimumSectionSize(35)
        self.nz_pasture_type_twidget.verticalHeader().setDefaultSectionSize(35)
        self.nz_pasture_type_twidget.verticalHeader().setMinimumSectionSize(19)
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 341, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.natural_zone_set_cbox = QtGui.QComboBox(self.tab_4)
        self.natural_zone_set_cbox.setGeometry(QtCore.QRect(10, 30, 381, 22))
        self.natural_zone_set_cbox.setObjectName(_fromUtf8("natural_zone_set_cbox"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.help_button = QtGui.QPushButton(PastureSettings)
        self.help_button.setGeometry(QtCore.QRect(540, 500, 91, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.close_button = QtGui.QPushButton(PastureSettings)
        self.close_button.setGeometry(QtCore.QRect(720, 500, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.status_label = QtGui.QLabel(PastureSettings)
        self.status_label.setGeometry(QtCore.QRect(20, 500, 486, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.apply_button = QtGui.QPushButton(PastureSettings)
        self.apply_button.setGeometry(QtCore.QRect(640, 500, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))

        self.retranslateUi(PastureSettings)
        self.tabWidget.setCurrentIndex(5)
        self.formula_tab_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(PastureSettings)

    def retranslateUi(self, PastureSettings):
        PastureSettings.setWindowTitle(_translate("PastureSettings", "Dialog", None))
        self.groupBox_12.setTitle(_translate("PastureSettings", "Official documents", None))
        item = self.doc_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureSettings", "Visible", None))
        item = self.doc_twidget.horizontalHeaderItem(1)
        item.setText(_translate("PastureSettings", "Name", None))
        item = self.doc_twidget.horizontalHeaderItem(2)
        item.setText(_translate("PastureSettings", "Description", None))
        item = self.doc_twidget.horizontalHeaderItem(3)
        item.setText(_translate("PastureSettings", "Open", None))
        item = self.doc_twidget.horizontalHeaderItem(4)
        item.setText(_translate("PastureSettings", "View", None))
        self.add_document_button.setToolTip(_translate("PastureSettings", "Add Row", None))
        self.add_document_button.setText(_translate("PastureSettings", "+", None))
        self.remove_document_button.setToolTip(_translate("PastureSettings", "Delete Row", None))
        self.remove_document_button.setText(_translate("PastureSettings", "-", None))
        self.load_off_document_button.setToolTip(_translate("PastureSettings", "Add Row", None))
        self.load_off_document_button.setText(_translate("PastureSettings", "Load", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documents_tab), _translate("PastureSettings", "Official Documents", None))
        self.groupBox_10.setTitle(_translate("PastureSettings", "Codelists", None))
        self.label_11.setText(_translate("PastureSettings", "Select Codelist", None))
        self.label_12.setText(_translate("PastureSettings", "Entries", None))
        self.delete_button.setToolTip(_translate("PastureSettings", "Delete Row", None))
        self.delete_button.setText(_translate("PastureSettings", "-", None))
        self.add_button.setToolTip(_translate("PastureSettings", "Add Row", None))
        self.add_button.setText(_translate("PastureSettings", "+", None))
        item = self.table_widget.horizontalHeaderItem(0)
        item.setText(_translate("PastureSettings", "Code", None))
        item = self.table_widget.horizontalHeaderItem(1)
        item.setText(_translate("PastureSettings", "Description", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("PastureSettings", "Codelists", None))
        self.groupBox.setTitle(_translate("PastureSettings", "Connect", None))
        self.label.setText(_translate("PastureSettings", "Base Type", None))
        self.connect_type_twidget.setSortingEnabled(True)
        item = self.connect_type_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureSettings", "Check", None))
        item = self.connect_type_twidget.horizontalHeaderItem(1)
        item.setText(_translate("PastureSettings", "Type", None))
        self.all_types_chbox.setText(_translate("PastureSettings", "All Types", None))
        self.groupBox_2.setTitle(_translate("PastureSettings", "Connect Type", None))
        item = self.live_stock_convert_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureSettings", "Live Stock Type", None))
        item = self.live_stock_convert_twidget.horizontalHeaderItem(1)
        item.setText(_translate("PastureSettings", "Convert Value", None))
        self.app_type_pasture_type_rbutton.setText(_translate("PastureSettings", "Application type and Pasture type", None))
        self.app_type_doc_type_rbutton.setText(_translate("PastureSettings", "Application type and Document type", None))
        self.contract_doc_type_rbutton.setText(_translate("PastureSettings", "Contract and Document type", None))
        self.natural_zone_land_form_rbutton.setText(_translate("PastureSettings", "Natural zone and Land form", None))
        self.natural_zone_land_plants_rbutton.setText(_translate("PastureSettings", "Natural zone and Land plants", None))
        self.formula_type_land_form_rbutton.setText(_translate("PastureSettings", "Formula Type and Land form", None))
        self.live_stock_convert_rbutton.setText(_translate("PastureSettings", "Live Stock convert value", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PastureSettings", "Codelists Settings", None))
        self.groupBox_3.setTitle(_translate("PastureSettings", "Recovery Class", None))
        item = self.recovery_class_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureSettings", "RC code", None))
        item = self.recovery_class_twidget.horizontalHeaderItem(1)
        item.setText(_translate("PastureSettings", "RC %", None))
        self.groupBox_4.setTitle(_translate("PastureSettings", "Natural zone Sheep unit food", None))
        item = self.sheep_food_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureSettings", "Natural Zone", None))
        item = self.sheep_food_twidget.horizontalHeaderItem(1)
        item.setText(_translate("PastureSettings", "Unit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PastureSettings", "Recovery Class", None))
        self.label_2.setText(_translate("PastureSettings", "Natural Zone ", None))
        item = self.land_form_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureSettings", "Land Form name", None))
        self.label_4.setText(_translate("PastureSettings", "Plants cover", None))
        self.label_5.setText(_translate("PastureSettings", "Symbol type", None))
        self.formula_add_button.setText(_translate("PastureSettings", "add", None))
        item = self.formula_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureSettings", "RC", None))
        item = self.formula_twidget.horizontalHeaderItem(1)
        item.setText(_translate("PastureSettings", "Pasture Value(plants cover)", None))
        item = self.formula_twidget.horizontalHeaderItem(2)
        item.setText(_translate("PastureSettings", "Symbol type", None))
        item = self.formula_twidget.horizontalHeaderItem(3)
        item.setText(_translate("PastureSettings", "Precent Value", None))
        self.label_6.setText(_translate("PastureSettings", "Precent value", None))
        self.label_3.setText(_translate("PastureSettings", "Recovery Class", None))
        self.formula_delete_button.setText(_translate("PastureSettings", "delete", None))
        self.formula_update_button.setText(_translate("PastureSettings", "update", None))
        self.formula_tab_widget.setTabText(self.formula_tab_widget.indexOf(self.formula_precent_tab), _translate("PastureSettings", "Precent", None))
        self.label_7.setText(_translate("PastureSettings", "Recovery Class", None))
        self.label_8.setText(_translate("PastureSettings", "Plants cover", None))
        self.add_comparison_button.setText(_translate("PastureSettings", "add", None))
        self.more_delete_button.setText(_translate("PastureSettings", "delete", None))
        item = self.formula_more_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureSettings", "Plants name", None))
        item = self.formula_less_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureSettings", "Plants name", None))
        self.label_9.setText(_translate("PastureSettings", ">", None))
        self.soil_evaluation_chbox.setText(_translate("PastureSettings", "Pasture soil Evaluation", None))
        self.less_delete_button.setText(_translate("PastureSettings", "delete", None))
        self.label_10.setText(_translate("PastureSettings", "More", None))
        self.label_13.setText(_translate("PastureSettings", "Less", None))
        self.label_14.setText(_translate("PastureSettings", "Symbol type", None))
        self.formula_tab_widget.setTabText(self.formula_tab_widget.indexOf(self.formula_comparison_tab), _translate("PastureSettings", "Comparison", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PastureSettings", "Pasture Status", None))
        item = self.nz_pasture_type_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PastureSettings", "Улирлын төрөл", None))
        item = self.nz_pasture_type_twidget.horizontalHeaderItem(1)
        item.setText(_translate("PastureSettings", "Ургац шилжүүлэлт", None))
        item = self.nz_pasture_type_twidget.horizontalHeaderItem(2)
        item.setText(_translate("PastureSettings", "Бэлчээр ашиглалт/%/", None))
        item = self.nz_pasture_type_twidget.horizontalHeaderItem(3)
        item.setText(_translate("PastureSettings", "Эхлэх хугацаа", None))
        item = self.nz_pasture_type_twidget.horizontalHeaderItem(4)
        item.setText(_translate("PastureSettings", "Дуусах хугацаа", None))
        item = self.nz_pasture_type_twidget.horizontalHeaderItem(5)
        item.setText(_translate("PastureSettings", "Үргэлжлэх хугацаа", None))
        item = self.nz_pasture_type_twidget.horizontalHeaderItem(6)
        item.setText(_translate("PastureSettings", "Хонин толгойн идэх өвс", None))
        self.label_15.setText(_translate("PastureSettings", "Natural Zone", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("PastureSettings", "Natural Zone Settings", None))
        self.help_button.setText(_translate("PastureSettings", "?", None))
        self.close_button.setText(_translate("PastureSettings", "Close", None))
        self.status_label.setText(_translate("PastureSettings", "Messages", None))
        self.apply_button.setText(_translate("PastureSettings", "Apply", None))

