# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ParcelMpaDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ParcelMpaDialog(object):
    def setupUi(self, ParcelMpaDialog):
        ParcelMpaDialog.setObjectName(_fromUtf8("ParcelMpaDialog"))
        ParcelMpaDialog.resize(415, 726)
        ParcelMpaDialog.setMinimumSize(QtCore.QSize(415, 700))
        ParcelMpaDialog.setMaximumSize(QtCore.QSize(415, 790))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setGeometry(QtCore.QRect(2, 0, 411, 681))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 600))
        self.scrollArea.setMaximumSize(QtCore.QSize(435, 800))
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setAcceptDrops(False)
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 739))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.parcel_tab_widget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.parcel_tab_widget.setGeometry(QtCore.QRect(6, 220, 383, 401))
        self.parcel_tab_widget.setObjectName(_fromUtf8("parcel_tab_widget"))
        self.parcel_person_tab = QtGui.QWidget()
        self.parcel_person_tab.setObjectName(_fromUtf8("parcel_person_tab"))
        self.parcel_gbox = QtGui.QGroupBox(self.parcel_person_tab)
        self.parcel_gbox.setGeometry(QtCore.QRect(3, 0, 371, 183))
        self.parcel_gbox.setObjectName(_fromUtf8("parcel_gbox"))
        self.parcel_id_edit = QtGui.QLineEdit(self.parcel_gbox)
        self.parcel_id_edit.setEnabled(True)
        self.parcel_id_edit.setGeometry(QtCore.QRect(8, 32, 136, 20))
        self.parcel_id_edit.setReadOnly(True)
        self.parcel_id_edit.setObjectName(_fromUtf8("parcel_id_edit"))
        self.label_3 = QtGui.QLabel(self.parcel_gbox)
        self.label_3.setGeometry(QtCore.QRect(8, 15, 136, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.khashaa_edit = QtGui.QLineEdit(self.parcel_gbox)
        self.khashaa_edit.setEnabled(False)
        self.khashaa_edit.setGeometry(QtCore.QRect(8, 74, 136, 20))
        self.khashaa_edit.setObjectName(_fromUtf8("khashaa_edit"))
        self.old_parcel_id_edit = QtGui.QLineEdit(self.parcel_gbox)
        self.old_parcel_id_edit.setEnabled(True)
        self.old_parcel_id_edit.setGeometry(QtCore.QRect(150, 32, 211, 20))
        self.old_parcel_id_edit.setReadOnly(True)
        self.old_parcel_id_edit.setObjectName(_fromUtf8("old_parcel_id_edit"))
        self.streetname_edit = QtGui.QLineEdit(self.parcel_gbox)
        self.streetname_edit.setEnabled(False)
        self.streetname_edit.setGeometry(QtCore.QRect(150, 74, 211, 20))
        self.streetname_edit.setObjectName(_fromUtf8("streetname_edit"))
        self.khashaa_chbox = QtGui.QCheckBox(self.parcel_gbox)
        self.khashaa_chbox.setGeometry(QtCore.QRect(8, 55, 131, 17))
        self.khashaa_chbox.setObjectName(_fromUtf8("khashaa_chbox"))
        self.street_chbox = QtGui.QCheckBox(self.parcel_gbox)
        self.street_chbox.setGeometry(QtCore.QRect(151, 55, 211, 17))
        self.street_chbox.setObjectName(_fromUtf8("street_chbox"))
        self.label_5 = QtGui.QLabel(self.parcel_gbox)
        self.label_5.setGeometry(QtCore.QRect(150, 15, 211, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.zoriulalt_edit = QtGui.QLineEdit(self.parcel_gbox)
        self.zoriulalt_edit.setEnabled(False)
        self.zoriulalt_edit.setGeometry(QtCore.QRect(10, 114, 45, 20))
        self.zoriulalt_edit.setObjectName(_fromUtf8("zoriulalt_edit"))
        self.zoriulalt_chbox = QtGui.QCheckBox(self.parcel_gbox)
        self.zoriulalt_chbox.setGeometry(QtCore.QRect(10, 96, 61, 17))
        self.zoriulalt_chbox.setObjectName(_fromUtf8("zoriulalt_chbox"))
        self.edit_status_cbox = QtGui.QComboBox(self.parcel_gbox)
        self.edit_status_cbox.setGeometry(QtCore.QRect(200, 160, 161, 22))
        self.edit_status_cbox.setObjectName(_fromUtf8("edit_status_cbox"))
        self.neighbourhood_edit = QtGui.QLineEdit(self.parcel_person_tab)
        self.neighbourhood_edit.setEnabled(False)
        self.neighbourhood_edit.setGeometry(QtCore.QRect(11, 160, 181, 20))
        self.neighbourhood_edit.setObjectName(_fromUtf8("neighbourhood_edit"))
        self.neighbourhood_chbox = QtGui.QCheckBox(self.parcel_person_tab)
        self.neighbourhood_chbox.setGeometry(QtCore.QRect(11, 141, 361, 17))
        self.neighbourhood_chbox.setObjectName(_fromUtf8("neighbourhood_chbox"))
        self.parcel_landuse_cbox = QtGui.QComboBox(self.parcel_person_tab)
        self.parcel_landuse_cbox.setEnabled(False)
        self.parcel_landuse_cbox.setGeometry(QtCore.QRect(71, 114, 291, 20))
        self.parcel_landuse_cbox.setObjectName(_fromUtf8("parcel_landuse_cbox"))
        self.landuse_chbox = QtGui.QCheckBox(self.parcel_person_tab)
        self.landuse_chbox.setGeometry(QtCore.QRect(90, 96, 261, 17))
        self.landuse_chbox.setObjectName(_fromUtf8("landuse_chbox"))
        self.person_tabwidget = QtGui.QTabWidget(self.parcel_person_tab)
        self.person_tabwidget.setGeometry(QtCore.QRect(3, 184, 371, 188))
        self.person_tabwidget.setObjectName(_fromUtf8("person_tabwidget"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.phone_edit = QtGui.QLineEdit(self.tab_8)
        self.phone_edit.setEnabled(False)
        self.phone_edit.setGeometry(QtCore.QRect(8, 140, 261, 20))
        self.phone_edit.setObjectName(_fromUtf8("phone_edit"))
        self.phone_chbox = QtGui.QCheckBox(self.tab_8)
        self.phone_chbox.setGeometry(QtCore.QRect(8, 121, 136, 17))
        self.phone_chbox.setObjectName(_fromUtf8("phone_chbox"))
        self.person_type_cbox = QtGui.QComboBox(self.tab_8)
        self.person_type_cbox.setEnabled(False)
        self.person_type_cbox.setGeometry(QtCore.QRect(8, 19, 351, 20))
        self.person_type_cbox.setObjectName(_fromUtf8("person_type_cbox"))
        self.firstname_chbox = QtGui.QCheckBox(self.tab_8)
        self.firstname_chbox.setGeometry(QtCore.QRect(165, 39, 191, 17))
        self.firstname_chbox.setObjectName(_fromUtf8("firstname_chbox"))
        self.lastname_chbox = QtGui.QCheckBox(self.tab_8)
        self.lastname_chbox.setGeometry(QtCore.QRect(207, 80, 151, 17))
        self.lastname_chbox.setObjectName(_fromUtf8("lastname_chbox"))
        self.middlename_chbox = QtGui.QCheckBox(self.tab_8)
        self.middlename_chbox.setGeometry(QtCore.QRect(9, 80, 191, 17))
        self.middlename_chbox.setObjectName(_fromUtf8("middlename_chbox"))
        self.name_edit = QtGui.QLineEdit(self.tab_8)
        self.name_edit.setEnabled(False)
        self.name_edit.setGeometry(QtCore.QRect(207, 98, 151, 20))
        self.name_edit.setObjectName(_fromUtf8("name_edit"))
        self.person_type_chbox = QtGui.QCheckBox(self.tab_8)
        self.person_type_chbox.setGeometry(QtCore.QRect(9, 0, 271, 17))
        self.person_type_chbox.setObjectName(_fromUtf8("person_type_chbox"))
        self.first_name_edit = QtGui.QLineEdit(self.tab_8)
        self.first_name_edit.setEnabled(False)
        self.first_name_edit.setGeometry(QtCore.QRect(165, 57, 191, 20))
        self.first_name_edit.setObjectName(_fromUtf8("first_name_edit"))
        self.personal_id_edit = QtGui.QLineEdit(self.tab_8)
        self.personal_id_edit.setEnabled(False)
        self.personal_id_edit.setGeometry(QtCore.QRect(8, 57, 150, 20))
        self.personal_id_edit.setObjectName(_fromUtf8("personal_id_edit"))
        self.date_of_birth_date = QtGui.QDateEdit(self.tab_8)
        self.date_of_birth_date.setEnabled(False)
        self.date_of_birth_date.setGeometry(QtCore.QRect(274, 140, 91, 20))
        self.date_of_birth_date.setLocale(QtCore.QLocale(QtCore.QLocale.Mongolian, QtCore.QLocale.Mongolia))
        self.date_of_birth_date.setDisplayFormat(_fromUtf8("yyyy-MM-dd"))
        self.date_of_birth_date.setCalendarPopup(True)
        self.date_of_birth_date.setObjectName(_fromUtf8("date_of_birth_date"))
        self.middle_name_edit = QtGui.QLineEdit(self.tab_8)
        self.middle_name_edit.setEnabled(False)
        self.middle_name_edit.setGeometry(QtCore.QRect(9, 98, 191, 20))
        self.middle_name_edit.setObjectName(_fromUtf8("middle_name_edit"))
        self.person_id_chbox = QtGui.QCheckBox(self.tab_8)
        self.person_id_chbox.setGeometry(QtCore.QRect(9, 39, 146, 17))
        self.person_id_chbox.setObjectName(_fromUtf8("person_id_chbox"))
        self.person_tabwidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.label_6 = QtGui.QLabel(self.tab_9)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 171, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.aimag_cbox = QtGui.QComboBox(self.tab_9)
        self.aimag_cbox.setGeometry(QtCore.QRect(10, 16, 170, 20))
        self.aimag_cbox.setObjectName(_fromUtf8("aimag_cbox"))
        self.bag_cbox = QtGui.QComboBox(self.tab_9)
        self.bag_cbox.setGeometry(QtCore.QRect(10, 60, 171, 20))
        self.bag_cbox.setObjectName(_fromUtf8("bag_cbox"))
        self.label_7 = QtGui.QLabel(self.tab_9)
        self.label_7.setGeometry(QtCore.QRect(190, 0, 171, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.soum_cbox = QtGui.QComboBox(self.tab_9)
        self.soum_cbox.setGeometry(QtCore.QRect(190, 16, 170, 20))
        self.soum_cbox.setObjectName(_fromUtf8("soum_cbox"))
        self.label_8 = QtGui.QLabel(self.tab_9)
        self.label_8.setGeometry(QtCore.QRect(10, 44, 220, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.person_khashaa_edit = QtGui.QLineEdit(self.tab_9)
        self.person_khashaa_edit.setGeometry(QtCore.QRect(10, 135, 171, 21))
        self.person_khashaa_edit.setObjectName(_fromUtf8("person_khashaa_edit"))
        self.person_street_name_edit = QtGui.QLineEdit(self.tab_9)
        self.person_street_name_edit.setGeometry(QtCore.QRect(10, 97, 171, 21))
        self.person_street_name_edit.setObjectName(_fromUtf8("person_street_name_edit"))
        self.label_12 = QtGui.QLabel(self.tab_9)
        self.label_12.setGeometry(QtCore.QRect(10, 81, 220, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_19 = QtGui.QLabel(self.tab_9)
        self.label_19.setGeometry(QtCore.QRect(10, 120, 220, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.building_edit = QtGui.QLineEdit(self.tab_9)
        self.building_edit.setGeometry(QtCore.QRect(190, 98, 166, 20))
        self.building_edit.setObjectName(_fromUtf8("building_edit"))
        self.label_35 = QtGui.QLabel(self.tab_9)
        self.label_35.setGeometry(QtCore.QRect(190, 82, 166, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.apartment_edit = QtGui.QLineEdit(self.tab_9)
        self.apartment_edit.setGeometry(QtCore.QRect(190, 137, 166, 20))
        self.apartment_edit.setObjectName(_fromUtf8("apartment_edit"))
        self.label_36 = QtGui.QLabel(self.tab_9)
        self.label_36.setGeometry(QtCore.QRect(190, 121, 166, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.person_tabwidget.addTab(self.tab_9, _fromUtf8(""))
        self.label_38 = QtGui.QLabel(self.parcel_person_tab)
        self.label_38.setGeometry(QtCore.QRect(203, 143, 161, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.parcel_tab_widget.addTab(self.parcel_person_tab, _fromUtf8(""))
        self.decision_contract_tab = QtGui.QWidget()
        self.decision_contract_tab.setObjectName(_fromUtf8("decision_contract_tab"))
        self.groupBox = QtGui.QGroupBox(self.decision_contract_tab)
        self.groupBox.setGeometry(QtCore.QRect(4, 2, 371, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.decision_date = QtGui.QDateEdit(self.groupBox)
        self.decision_date.setEnabled(False)
        self.decision_date.setGeometry(QtCore.QRect(261, 127, 101, 20))
        self.decision_date.setCalendarPopup(True)
        self.decision_date.setObjectName(_fromUtf8("decision_date"))
        self.decision_date_chbox = QtGui.QCheckBox(self.groupBox)
        self.decision_date_chbox.setGeometry(QtCore.QRect(263, 107, 101, 20))
        self.decision_date_chbox.setObjectName(_fromUtf8("decision_date_chbox"))
        self.decision_full_edit = QtGui.QLineEdit(self.groupBox)
        self.decision_full_edit.setEnabled(False)
        self.decision_full_edit.setGeometry(QtCore.QRect(111, 127, 141, 20))
        self.decision_full_edit.setObjectName(_fromUtf8("decision_full_edit"))
        self.rigth_type_cbox = QtGui.QComboBox(self.groupBox)
        self.rigth_type_cbox.setEnabled(False)
        self.rigth_type_cbox.setGeometry(QtCore.QRect(9, 39, 131, 20))
        self.rigth_type_cbox.setObjectName(_fromUtf8("rigth_type_cbox"))
        self.decision_no_edit = QtGui.QLineEdit(self.groupBox)
        self.decision_no_edit.setEnabled(False)
        self.decision_no_edit.setGeometry(QtCore.QRect(9, 127, 91, 20))
        self.decision_no_edit.setObjectName(_fromUtf8("decision_no_edit"))
        self.decision_full_chbox = QtGui.QLabel(self.groupBox)
        self.decision_full_chbox.setGeometry(QtCore.QRect(112, 110, 136, 16))
        self.decision_full_chbox.setObjectName(_fromUtf8("decision_full_chbox"))
        self.decision_level_cbox = QtGui.QComboBox(self.groupBox)
        self.decision_level_cbox.setEnabled(False)
        self.decision_level_cbox.setGeometry(QtCore.QRect(150, 39, 211, 20))
        self.decision_level_cbox.setObjectName(_fromUtf8("decision_level_cbox"))
        self.level_chbox = QtGui.QCheckBox(self.groupBox)
        self.level_chbox.setGeometry(QtCore.QRect(150, 20, 211, 17))
        self.level_chbox.setObjectName(_fromUtf8("level_chbox"))
        self.right_type_chbox = QtGui.QCheckBox(self.groupBox)
        self.right_type_chbox.setGeometry(QtCore.QRect(9, 20, 136, 17))
        self.right_type_chbox.setObjectName(_fromUtf8("right_type_chbox"))
        self.decision_no_chbox = QtGui.QCheckBox(self.groupBox)
        self.decision_no_chbox.setGeometry(QtCore.QRect(9, 108, 91, 17))
        self.decision_no_chbox.setObjectName(_fromUtf8("decision_no_chbox"))
        self.label_37 = QtGui.QLabel(self.groupBox)
        self.label_37.setGeometry(QtCore.QRect(11, 62, 307, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.application_type_cbox = QtGui.QComboBox(self.groupBox)
        self.application_type_cbox.setEnabled(True)
        self.application_type_cbox.setGeometry(QtCore.QRect(10, 81, 351, 20))
        self.application_type_cbox.setObjectName(_fromUtf8("application_type_cbox"))
        self.groupBox_2 = QtGui.QGroupBox(self.decision_contract_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(4, 153, 371, 171))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.contract_status_cbox = QtGui.QComboBox(self.groupBox_2)
        self.contract_status_cbox.setEnabled(False)
        self.contract_status_cbox.setGeometry(QtCore.QRect(4, 39, 101, 20))
        self.contract_status_cbox.setObjectName(_fromUtf8("contract_status_cbox"))
        self.contract_date = QtGui.QDateEdit(self.groupBox_2)
        self.contract_date.setEnabled(False)
        self.contract_date.setGeometry(QtCore.QRect(87, 88, 101, 20))
        self.contract_date.setCalendarPopup(True)
        self.contract_date.setObjectName(_fromUtf8("contract_date"))
        self.contract_cert_edit = QtGui.QLineEdit(self.groupBox_2)
        self.contract_cert_edit.setEnabled(False)
        self.contract_cert_edit.setGeometry(QtCore.QRect(266, 40, 101, 20))
        self.contract_cert_edit.setObjectName(_fromUtf8("contract_cert_edit"))
        self.contract_date_chbox = QtGui.QCheckBox(self.groupBox_2)
        self.contract_date_chbox.setGeometry(QtCore.QRect(76, 69, 101, 17))
        self.contract_date_chbox.setObjectName(_fromUtf8("contract_date_chbox"))
        self.contract_no_chbox = QtGui.QCheckBox(self.groupBox_2)
        self.contract_no_chbox.setGeometry(QtCore.QRect(2, 68, 71, 20))
        self.contract_no_chbox.setObjectName(_fromUtf8("contract_no_chbox"))
        self.contract_full_chbox = QtGui.QLabel(self.groupBox_2)
        self.contract_full_chbox.setGeometry(QtCore.QRect(131, 20, 121, 16))
        self.contract_full_chbox.setObjectName(_fromUtf8("contract_full_chbox"))
        self.end_date_chbox = QtGui.QCheckBox(self.groupBox_2)
        self.end_date_chbox.setGeometry(QtCore.QRect(178, 68, 121, 17))
        self.end_date_chbox.setObjectName(_fromUtf8("end_date_chbox"))
        self.contract_no_edit = QtGui.QLineEdit(self.groupBox_2)
        self.contract_no_edit.setEnabled(False)
        self.contract_no_edit.setGeometry(QtCore.QRect(2, 88, 81, 20))
        self.contract_no_edit.setObjectName(_fromUtf8("contract_no_edit"))
        self.duration_chbox = QtGui.QCheckBox(self.groupBox_2)
        self.duration_chbox.setGeometry(QtCore.QRect(290, 68, 81, 20))
        self.duration_chbox.setObjectName(_fromUtf8("duration_chbox"))
        self.contract_certificate_chbox = QtGui.QCheckBox(self.groupBox_2)
        self.contract_certificate_chbox.setGeometry(QtCore.QRect(276, 20, 91, 17))
        self.contract_certificate_chbox.setObjectName(_fromUtf8("contract_certificate_chbox"))
        self.contract_full_edit = QtGui.QLineEdit(self.groupBox_2)
        self.contract_full_edit.setEnabled(False)
        self.contract_full_edit.setGeometry(QtCore.QRect(109, 39, 151, 20))
        self.contract_full_edit.setObjectName(_fromUtf8("contract_full_edit"))
        self.duration_sbox = QtGui.QSpinBox(self.groupBox_2)
        self.duration_sbox.setEnabled(False)
        self.duration_sbox.setGeometry(QtCore.QRect(285, 88, 81, 20))
        self.duration_sbox.setObjectName(_fromUtf8("duration_sbox"))
        self.end_date = QtGui.QDateEdit(self.groupBox_2)
        self.end_date.setEnabled(False)
        self.end_date.setGeometry(QtCore.QRect(191, 88, 91, 20))
        self.end_date.setCalendarPopup(True)
        self.end_date.setObjectName(_fromUtf8("end_date"))
        self.contract_status_chbox = QtGui.QCheckBox(self.groupBox_2)
        self.contract_status_chbox.setGeometry(QtCore.QRect(4, 19, 111, 17))
        self.contract_status_chbox.setObjectName(_fromUtf8("contract_status_chbox"))
        self.parcel_tab_widget.addTab(self.decision_contract_tab, _fromUtf8(""))
        self.right_holder_twidget = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.right_holder_twidget.setGeometry(QtCore.QRect(6, 103, 381, 111))
        self.right_holder_twidget.setObjectName(_fromUtf8("right_holder_twidget"))
        self.right_holder_twidget.setColumnCount(10)
        self.right_holder_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(9, item)
        self.finish_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.finish_button.setGeometry(QtCore.QRect(10, 630, 75, 28))
        self.finish_button.setStyleSheet(_fromUtf8("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 250, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #60c465; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 174)\n"
"}"))
        self.finish_button.setObjectName(_fromUtf8("finish_button"))
        self.save_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.save_button.setGeometry(QtCore.QRect(300, 630, 84, 28))
        self.save_button.setStyleSheet(_fromUtf8("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 250, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #E6B9E6; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 174)\n"
"}"))
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.clear_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.clear_button.setGeometry(QtCore.QRect(310, 72, 75, 23))
        self.clear_button.setAutoDefault(False)
        self.clear_button.setDefault(False)
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.layer_view_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.layer_view_button.setGeometry(QtCore.QRect(130, 630, 131, 28))
        self.layer_view_button.setStyleSheet(_fromUtf8("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 250, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #C19B93; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 174)\n"
"}"))
        self.layer_view_button.setObjectName(_fromUtf8("layer_view_button"))
        self.error_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.error_label.setGeometry(QtCore.QRect(20, 715, 361, 17))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.find_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.find_button.setEnabled(True)
        self.find_button.setGeometry(QtCore.QRect(310, 19, 75, 50))
        self.find_button.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/zoom.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.find_button.setIcon(icon)
        self.find_button.setAutoDefault(False)
        self.find_button.setDefault(True)
        self.find_button.setObjectName(_fromUtf8("find_button"))
        self.find_tab = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.find_tab.setGeometry(QtCore.QRect(3, 0, 304, 101))
        self.find_tab.setAcceptDrops(False)
        self.find_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.find_tab.setObjectName(_fromUtf8("find_tab"))
        self.tab_17 = QtGui.QWidget()
        self.tab_17.setObjectName(_fromUtf8("tab_17"))
        self.label_33 = QtGui.QLabel(self.tab_17)
        self.label_33.setGeometry(QtCore.QRect(10, 35, 121, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.find_parcel_id_edit = QtGui.QLineEdit(self.tab_17)
        self.find_parcel_id_edit.setEnabled(False)
        self.find_parcel_id_edit.setGeometry(QtCore.QRect(10, 15, 135, 20))
        self.find_parcel_id_edit.setObjectName(_fromUtf8("find_parcel_id_edit"))
        self.label_2 = QtGui.QLabel(self.tab_17)
        self.label_2.setGeometry(QtCore.QRect(150, -2, 136, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.find_person_id_edit = QtGui.QLineEdit(self.tab_17)
        self.find_person_id_edit.setEnabled(False)
        self.find_person_id_edit.setGeometry(QtCore.QRect(150, 15, 135, 20))
        self.find_person_id_edit.setObjectName(_fromUtf8("find_person_id_edit"))
        self.label_34 = QtGui.QLabel(self.tab_17)
        self.label_34.setGeometry(QtCore.QRect(150, 34, 136, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.find_lastname_edit = QtGui.QLineEdit(self.tab_17)
        self.find_lastname_edit.setEnabled(False)
        self.find_lastname_edit.setGeometry(QtCore.QRect(150, 51, 135, 20))
        self.find_lastname_edit.setObjectName(_fromUtf8("find_lastname_edit"))
        self.label = QtGui.QLabel(self.tab_17)
        self.label.setGeometry(QtCore.QRect(10, -1, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.find_firstname_edit = QtGui.QLineEdit(self.tab_17)
        self.find_firstname_edit.setEnabled(False)
        self.find_firstname_edit.setGeometry(QtCore.QRect(10, 51, 135, 20))
        self.find_firstname_edit.setObjectName(_fromUtf8("find_firstname_edit"))
        self.find_tab.addTab(self.tab_17, _fromUtf8(""))
        self.tab_18 = QtGui.QWidget()
        self.tab_18.setObjectName(_fromUtf8("tab_18"))
        self.find_x_coordinate_edit = QtGui.QLineEdit(self.tab_18)
        self.find_x_coordinate_edit.setEnabled(False)
        self.find_x_coordinate_edit.setGeometry(QtCore.QRect(10, 42, 110, 20))
        self.find_x_coordinate_edit.setObjectName(_fromUtf8("find_x_coordinate_edit"))
        self.label_39 = QtGui.QLabel(self.tab_18)
        self.label_39.setGeometry(QtCore.QRect(130, 25, 110, 16))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.find_y_coordinate_edit = QtGui.QLineEdit(self.tab_18)
        self.find_y_coordinate_edit.setEnabled(False)
        self.find_y_coordinate_edit.setGeometry(QtCore.QRect(130, 42, 110, 20))
        self.find_y_coordinate_edit.setObjectName(_fromUtf8("find_y_coordinate_edit"))
        self.label_40 = QtGui.QLabel(self.tab_18)
        self.label_40.setGeometry(QtCore.QRect(10, 26, 110, 16))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.point_scale_sbox = QtGui.QSpinBox(self.tab_18)
        self.point_scale_sbox.setGeometry(QtCore.QRect(250, 42, 45, 22))
        self.point_scale_sbox.setObjectName(_fromUtf8("point_scale_sbox"))
        self.label_41 = QtGui.QLabel(self.tab_18)
        self.label_41.setGeometry(QtCore.QRect(250, 25, 34, 16))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.coordinate_chbox = QtGui.QCheckBox(self.tab_18)
        self.coordinate_chbox.setGeometry(QtCore.QRect(20, 7, 271, 17))
        self.coordinate_chbox.setObjectName(_fromUtf8("coordinate_chbox"))
        self.find_tab.addTab(self.tab_18, _fromUtf8(""))
        self.tab_19 = QtGui.QWidget()
        self.tab_19.setObjectName(_fromUtf8("tab_19"))
        self.label_55 = QtGui.QLabel(self.tab_19)
        self.label_55.setGeometry(QtCore.QRect(148, 2, 136, 16))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_56 = QtGui.QLabel(self.tab_19)
        self.label_56.setGeometry(QtCore.QRect(8, 3, 121, 16))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.find_street_name_edit = QtGui.QLineEdit(self.tab_19)
        self.find_street_name_edit.setEnabled(False)
        self.find_street_name_edit.setGeometry(QtCore.QRect(8, 19, 135, 20))
        self.find_street_name_edit.setObjectName(_fromUtf8("find_street_name_edit"))
        self.find_khashaa_number_edit = QtGui.QLineEdit(self.tab_19)
        self.find_khashaa_number_edit.setEnabled(False)
        self.find_khashaa_number_edit.setGeometry(QtCore.QRect(148, 19, 135, 20))
        self.find_khashaa_number_edit.setObjectName(_fromUtf8("find_khashaa_number_edit"))
        self.find_tab.addTab(self.tab_19, _fromUtf8(""))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        ParcelMpaDialog.setWidget(self.dockWidgetContents)

        self.retranslateUi(ParcelMpaDialog)
        self.parcel_tab_widget.setCurrentIndex(0)
        self.person_tabwidget.setCurrentIndex(0)
        self.find_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ParcelMpaDialog)
        ParcelMpaDialog.setTabOrder(self.landuse_chbox, self.old_parcel_id_edit)
        ParcelMpaDialog.setTabOrder(self.old_parcel_id_edit, self.khashaa_edit)
        ParcelMpaDialog.setTabOrder(self.khashaa_edit, self.khashaa_chbox)
        ParcelMpaDialog.setTabOrder(self.khashaa_chbox, self.streetname_edit)
        ParcelMpaDialog.setTabOrder(self.streetname_edit, self.zoriulalt_edit)
        ParcelMpaDialog.setTabOrder(self.zoriulalt_edit, self.neighbourhood_chbox)
        ParcelMpaDialog.setTabOrder(self.neighbourhood_chbox, self.lastname_chbox)
        ParcelMpaDialog.setTabOrder(self.lastname_chbox, self.zoriulalt_chbox)
        ParcelMpaDialog.setTabOrder(self.zoriulalt_chbox, self.neighbourhood_edit)
        ParcelMpaDialog.setTabOrder(self.neighbourhood_edit, self.find_parcel_id_edit)
        ParcelMpaDialog.setTabOrder(self.find_parcel_id_edit, self.parcel_landuse_cbox)
        ParcelMpaDialog.setTabOrder(self.parcel_landuse_cbox, self.find_person_id_edit)
        ParcelMpaDialog.setTabOrder(self.find_person_id_edit, self.person_tabwidget)
        ParcelMpaDialog.setTabOrder(self.person_tabwidget, self.phone_edit)
        ParcelMpaDialog.setTabOrder(self.phone_edit, self.phone_chbox)
        ParcelMpaDialog.setTabOrder(self.phone_chbox, self.find_firstname_edit)
        ParcelMpaDialog.setTabOrder(self.find_firstname_edit, self.find_lastname_edit)
        ParcelMpaDialog.setTabOrder(self.find_lastname_edit, self.clear_button)
        ParcelMpaDialog.setTabOrder(self.clear_button, self.find_button)
        ParcelMpaDialog.setTabOrder(self.find_button, self.middlename_chbox)
        ParcelMpaDialog.setTabOrder(self.middlename_chbox, self.name_edit)
        ParcelMpaDialog.setTabOrder(self.name_edit, self.person_type_chbox)
        ParcelMpaDialog.setTabOrder(self.person_type_chbox, self.first_name_edit)
        ParcelMpaDialog.setTabOrder(self.first_name_edit, self.personal_id_edit)
        ParcelMpaDialog.setTabOrder(self.personal_id_edit, self.date_of_birth_date)
        ParcelMpaDialog.setTabOrder(self.date_of_birth_date, self.middle_name_edit)
        ParcelMpaDialog.setTabOrder(self.middle_name_edit, self.person_id_chbox)
        ParcelMpaDialog.setTabOrder(self.person_id_chbox, self.aimag_cbox)
        ParcelMpaDialog.setTabOrder(self.aimag_cbox, self.bag_cbox)
        ParcelMpaDialog.setTabOrder(self.bag_cbox, self.soum_cbox)
        ParcelMpaDialog.setTabOrder(self.soum_cbox, self.person_khashaa_edit)
        ParcelMpaDialog.setTabOrder(self.person_khashaa_edit, self.person_street_name_edit)
        ParcelMpaDialog.setTabOrder(self.person_street_name_edit, self.decision_date)
        ParcelMpaDialog.setTabOrder(self.decision_date, self.decision_date_chbox)
        ParcelMpaDialog.setTabOrder(self.decision_date_chbox, self.decision_full_edit)
        ParcelMpaDialog.setTabOrder(self.decision_full_edit, self.rigth_type_cbox)
        ParcelMpaDialog.setTabOrder(self.rigth_type_cbox, self.decision_no_edit)
        ParcelMpaDialog.setTabOrder(self.decision_no_edit, self.decision_level_cbox)
        ParcelMpaDialog.setTabOrder(self.decision_level_cbox, self.level_chbox)
        ParcelMpaDialog.setTabOrder(self.level_chbox, self.right_type_chbox)
        ParcelMpaDialog.setTabOrder(self.right_type_chbox, self.decision_no_chbox)
        ParcelMpaDialog.setTabOrder(self.decision_no_chbox, self.contract_status_cbox)
        ParcelMpaDialog.setTabOrder(self.contract_status_cbox, self.contract_date)
        ParcelMpaDialog.setTabOrder(self.contract_date, self.contract_cert_edit)
        ParcelMpaDialog.setTabOrder(self.contract_cert_edit, self.contract_date_chbox)
        ParcelMpaDialog.setTabOrder(self.contract_date_chbox, self.contract_no_chbox)
        ParcelMpaDialog.setTabOrder(self.contract_no_chbox, self.end_date_chbox)
        ParcelMpaDialog.setTabOrder(self.end_date_chbox, self.contract_no_edit)
        ParcelMpaDialog.setTabOrder(self.contract_no_edit, self.duration_chbox)
        ParcelMpaDialog.setTabOrder(self.duration_chbox, self.contract_certificate_chbox)
        ParcelMpaDialog.setTabOrder(self.contract_certificate_chbox, self.contract_full_edit)
        ParcelMpaDialog.setTabOrder(self.contract_full_edit, self.duration_sbox)
        ParcelMpaDialog.setTabOrder(self.duration_sbox, self.end_date)
        ParcelMpaDialog.setTabOrder(self.end_date, self.contract_status_chbox)
        ParcelMpaDialog.setTabOrder(self.contract_status_chbox, self.right_holder_twidget)
        ParcelMpaDialog.setTabOrder(self.right_holder_twidget, self.finish_button)
        ParcelMpaDialog.setTabOrder(self.finish_button, self.save_button)
        ParcelMpaDialog.setTabOrder(self.save_button, self.layer_view_button)
        ParcelMpaDialog.setTabOrder(self.layer_view_button, self.find_person_id_edit)
        ParcelMpaDialog.setTabOrder(self.find_person_id_edit, self.find_parcel_id_edit)
        ParcelMpaDialog.setTabOrder(self.find_parcel_id_edit, self.street_chbox)
        ParcelMpaDialog.setTabOrder(self.street_chbox, self.person_type_cbox)
        ParcelMpaDialog.setTabOrder(self.person_type_cbox, self.find_firstname_edit)
        ParcelMpaDialog.setTabOrder(self.find_firstname_edit, self.firstname_chbox)
        ParcelMpaDialog.setTabOrder(self.firstname_chbox, self.parcel_tab_widget)
        ParcelMpaDialog.setTabOrder(self.parcel_tab_widget, self.scrollArea)
        ParcelMpaDialog.setTabOrder(self.scrollArea, self.find_lastname_edit)
        ParcelMpaDialog.setTabOrder(self.find_lastname_edit, self.parcel_id_edit)
        ParcelMpaDialog.setTabOrder(self.parcel_id_edit, self.find_button)
        ParcelMpaDialog.setTabOrder(self.find_button, self.find_tab)
        ParcelMpaDialog.setTabOrder(self.find_tab, self.find_x_coordinate_edit)
        ParcelMpaDialog.setTabOrder(self.find_x_coordinate_edit, self.find_y_coordinate_edit)
        ParcelMpaDialog.setTabOrder(self.find_y_coordinate_edit, self.point_scale_sbox)

    def retranslateUi(self, ParcelMpaDialog):
        ParcelMpaDialog.setWindowTitle(_translate("ParcelMpaDialog", "UB Parcel Information", None))
        self.parcel_gbox.setTitle(_translate("ParcelMpaDialog", "Parcel Info", None))
        self.label_3.setText(_translate("ParcelMpaDialog", "Parcel ID", None))
        self.khashaa_chbox.setText(_translate("ParcelMpaDialog", "Khashaa", None))
        self.street_chbox.setText(_translate("ParcelMpaDialog", "Street name", None))
        self.label_5.setText(_translate("ParcelMpaDialog", "Old Parcel ID", None))
        self.zoriulalt_chbox.setText(_translate("ParcelMpaDialog", "gaid", None))
        self.neighbourhood_chbox.setText(_translate("ParcelMpaDialog", "Address neighbourhood change", None))
        self.landuse_chbox.setText(_translate("ParcelMpaDialog", "Landuse type change", None))
        self.phone_chbox.setText(_translate("ParcelMpaDialog", "Phone number", None))
        self.firstname_chbox.setText(_translate("ParcelMpaDialog", "First name/Contact firstname", None))
        self.lastname_chbox.setText(_translate("ParcelMpaDialog", "Last name/Company Name", None))
        self.middlename_chbox.setText(_translate("ParcelMpaDialog", "Middle name/Contact Person name", None))
        self.person_type_chbox.setText(_translate("ParcelMpaDialog", "Person type change", None))
        self.person_id_chbox.setText(_translate("ParcelMpaDialog", "Person ID", None))
        self.person_tabwidget.setTabText(self.person_tabwidget.indexOf(self.tab_8), _translate("ParcelMpaDialog", "Person", None))
        self.label_6.setText(_translate("ParcelMpaDialog", "Aimag / Duureg", None))
        self.label_7.setText(_translate("ParcelMpaDialog", "Soum", None))
        self.label_8.setText(_translate("ParcelMpaDialog", "Bag / Khoroo", None))
        self.label_12.setText(_translate("ParcelMpaDialog", "Street Name", None))
        self.label_19.setText(_translate("ParcelMpaDialog", "Khashaa", None))
        self.label_35.setText(_translate("ParcelMpaDialog", "Building Number", None))
        self.label_36.setText(_translate("ParcelMpaDialog", "Apartment Number", None))
        self.person_tabwidget.setTabText(self.person_tabwidget.indexOf(self.tab_9), _translate("ParcelMpaDialog", "Person Address", None))
        self.label_38.setText(_translate("ParcelMpaDialog", "Edit Status", None))
        self.parcel_tab_widget.setTabText(self.parcel_tab_widget.indexOf(self.parcel_person_tab), _translate("ParcelMpaDialog", "Parcel & Person", None))
        self.groupBox.setTitle(_translate("ParcelMpaDialog", "Decision", None))
        self.decision_date_chbox.setText(_translate("ParcelMpaDialog", "Decision Date", None))
        self.decision_full_chbox.setText(_translate("ParcelMpaDialog", "Decision full number", None))
        self.level_chbox.setText(_translate("ParcelMpaDialog", "Decision level", None))
        self.right_type_chbox.setText(_translate("ParcelMpaDialog", "Right type", None))
        self.decision_no_chbox.setText(_translate("ParcelMpaDialog", "Decision No", None))
        self.label_37.setText(_translate("ParcelMpaDialog", "Application Type", None))
        self.groupBox_2.setTitle(_translate("ParcelMpaDialog", "Possess Contract", None))
        self.contract_date_chbox.setText(_translate("ParcelMpaDialog", "Create Date", None))
        self.contract_no_chbox.setText(_translate("ParcelMpaDialog", "Contract No", None))
        self.contract_full_chbox.setText(_translate("ParcelMpaDialog", "Contract full number", None))
        self.end_date_chbox.setText(_translate("ParcelMpaDialog", "End Date", None))
        self.duration_chbox.setText(_translate("ParcelMpaDialog", "Duration", None))
        self.contract_certificate_chbox.setText(_translate("ParcelMpaDialog", "Certificate", None))
        self.contract_status_chbox.setText(_translate("ParcelMpaDialog", "Contact status", None))
        self.parcel_tab_widget.setTabText(self.parcel_tab_widget.indexOf(self.decision_contract_tab), _translate("ParcelMpaDialog", "Decision/Contract", None))
        item = self.right_holder_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ParcelMpaDialog", "Rigth Type", None))
        item = self.right_holder_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ParcelMpaDialog", "Person / Company ID", None))
        item = self.right_holder_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ParcelMpaDialog", "Person / Company Name", None))
        item = self.right_holder_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ParcelMpaDialog", "First Name", None))
        item = self.right_holder_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ParcelMpaDialog", "Old Parcel ID", None))
        item = self.right_holder_twidget.horizontalHeaderItem(5)
        item.setText(_translate("ParcelMpaDialog", "Parcel ID", None))
        item = self.right_holder_twidget.horizontalHeaderItem(6)
        item.setText(_translate("ParcelMpaDialog", "Decision No", None))
        item = self.right_holder_twidget.horizontalHeaderItem(7)
        item.setText(_translate("ParcelMpaDialog", "Decision Date", None))
        item = self.right_holder_twidget.horizontalHeaderItem(8)
        item.setText(_translate("ParcelMpaDialog", "Contract No", None))
        item = self.right_holder_twidget.horizontalHeaderItem(9)
        item.setText(_translate("ParcelMpaDialog", "Contract Date", None))
        self.finish_button.setText(_translate("ParcelMpaDialog", "Finish", None))
        self.save_button.setText(_translate("ParcelMpaDialog", "Save", None))
        self.clear_button.setText(_translate("ParcelMpaDialog", "New", None))
        self.layer_view_button.setText(_translate("ParcelMpaDialog", "Layer View", None))
        self.find_button.setText(_translate("ParcelMpaDialog", "Find", None))
        self.label_33.setText(_translate("ParcelMpaDialog", "Firstname", None))
        self.label_2.setText(_translate("ParcelMpaDialog", "Person ID", None))
        self.label_34.setText(_translate("ParcelMpaDialog", "Lastname", None))
        self.label.setText(_translate("ParcelMpaDialog", "Parcel ID", None))
        self.find_tab.setTabText(self.find_tab.indexOf(self.tab_17), _translate("ParcelMpaDialog", "Find", None))
        self.label_39.setText(_translate("ParcelMpaDialog", "Y coordinate", None))
        self.label_40.setText(_translate("ParcelMpaDialog", "X coordinate", None))
        self.label_41.setText(_translate("ParcelMpaDialog", "Scale", None))
        self.coordinate_chbox.setText(_translate("ParcelMpaDialog", "Point Coordinate System ITRF", None))
        self.find_tab.setTabText(self.find_tab.indexOf(self.tab_18), _translate("ParcelMpaDialog", "Find Coordinate", None))
        self.label_55.setText(_translate("ParcelMpaDialog", "Khashaa_number", None))
        self.label_56.setText(_translate("ParcelMpaDialog", "Street_name", None))
        self.find_tab.setTabText(self.find_tab.indexOf(self.tab_19), _translate("ParcelMpaDialog", "find_address", None))

import resources_rc
