# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ParcelInfoFeeDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ParcelInfoFeeDialog(object):
    def setupUi(self, ParcelInfoFeeDialog):
        ParcelInfoFeeDialog.setObjectName(_fromUtf8("ParcelInfoFeeDialog"))
        ParcelInfoFeeDialog.resize(867, 504)
        self.close_button = QtGui.QPushButton(ParcelInfoFeeDialog)
        self.close_button.setGeometry(QtCore.QRect(779, 475, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.tabWidget = QtGui.QTabWidget(ParcelInfoFeeDialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 861, 471))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.fee_info_twidget = QtGui.QTableWidget(self.tab)
        self.fee_info_twidget.setGeometry(QtCore.QRect(15, 98, 631, 101))
        self.fee_info_twidget.setObjectName(_fromUtf8("fee_info_twidget"))
        self.fee_info_twidget.setColumnCount(14)
        self.fee_info_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(13, item)
        self.landuse_edit = QtGui.QLineEdit(self.tab)
        self.landuse_edit.setEnabled(False)
        self.landuse_edit.setGeometry(QtCore.QRect(133, 73, 151, 20))
        self.landuse_edit.setObjectName(_fromUtf8("landuse_edit"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(293, 53, 151, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(5, 200, 641, 241))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 11, 141, 220))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.quarterly1_paid_edit = QtGui.QLineEdit(self.groupBox_2)
        self.quarterly1_paid_edit.setEnabled(False)
        self.quarterly1_paid_edit.setGeometry(QtCore.QRect(10, 31, 120, 20))
        self.quarterly1_paid_edit.setObjectName(_fromUtf8("quarterly1_paid_edit"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 11, 120, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 120, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.quarterly2_paid_edit = QtGui.QLineEdit(self.groupBox_2)
        self.quarterly2_paid_edit.setEnabled(False)
        self.quarterly2_paid_edit.setGeometry(QtCore.QRect(10, 70, 120, 20))
        self.quarterly2_paid_edit.setObjectName(_fromUtf8("quarterly2_paid_edit"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 91, 120, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.quarterly4_paid_edit = QtGui.QLineEdit(self.groupBox_2)
        self.quarterly4_paid_edit.setEnabled(False)
        self.quarterly4_paid_edit.setGeometry(QtCore.QRect(10, 150, 120, 20))
        self.quarterly4_paid_edit.setObjectName(_fromUtf8("quarterly4_paid_edit"))
        self.quarterly3_paid_edit = QtGui.QLineEdit(self.groupBox_2)
        self.quarterly3_paid_edit.setEnabled(False)
        self.quarterly3_paid_edit.setGeometry(QtCore.QRect(10, 111, 120, 20))
        self.quarterly3_paid_edit.setObjectName(_fromUtf8("quarterly3_paid_edit"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 130, 120, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.all_paid_edit = QtGui.QLineEdit(self.groupBox_2)
        self.all_paid_edit.setEnabled(False)
        self.all_paid_edit.setGeometry(QtCore.QRect(10, 190, 120, 20))
        self.all_paid_edit.setObjectName(_fromUtf8("all_paid_edit"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 170, 120, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(155, 11, 271, 220))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.left_previous_year_paid_edit = QtGui.QLineEdit(self.groupBox_3)
        self.left_previous_year_paid_edit.setEnabled(False)
        self.left_previous_year_paid_edit.setGeometry(QtCore.QRect(10, 31, 120, 20))
        self.left_previous_year_paid_edit.setObjectName(_fromUtf8("left_previous_year_paid_edit"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 11, 120, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 120, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.payment_year_paid_edit = QtGui.QLineEdit(self.groupBox_3)
        self.payment_year_paid_edit.setEnabled(False)
        self.payment_year_paid_edit.setGeometry(QtCore.QRect(10, 70, 120, 20))
        self.payment_year_paid_edit.setObjectName(_fromUtf8("payment_year_paid_edit"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 91, 120, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.frequency_paid_edit = QtGui.QLineEdit(self.groupBox_3)
        self.frequency_paid_edit.setEnabled(False)
        self.frequency_paid_edit.setGeometry(QtCore.QRect(10, 150, 120, 20))
        self.frequency_paid_edit.setObjectName(_fromUtf8("frequency_paid_edit"))
        self.offset_paid_edit = QtGui.QLineEdit(self.groupBox_3)
        self.offset_paid_edit.setEnabled(False)
        self.offset_paid_edit.setGeometry(QtCore.QRect(10, 111, 120, 20))
        self.offset_paid_edit.setObjectName(_fromUtf8("offset_paid_edit"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 130, 120, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.fine_paid_edit = QtGui.QLineEdit(self.groupBox_3)
        self.fine_paid_edit.setEnabled(False)
        self.fine_paid_edit.setGeometry(QtCore.QRect(10, 190, 120, 20))
        self.fine_paid_edit.setObjectName(_fromUtf8("fine_paid_edit"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 170, 120, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(140, 50, 120, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.district_all_paid_edit = QtGui.QLineEdit(self.groupBox_3)
        self.district_all_paid_edit.setEnabled(False)
        self.district_all_paid_edit.setGeometry(QtCore.QRect(140, 70, 120, 20))
        self.district_all_paid_edit.setObjectName(_fromUtf8("district_all_paid_edit"))
        self.city_all_paid_edit = QtGui.QLineEdit(self.groupBox_3)
        self.city_all_paid_edit.setEnabled(False)
        self.city_all_paid_edit.setGeometry(QtCore.QRect(140, 31, 120, 20))
        self.city_all_paid_edit.setObjectName(_fromUtf8("city_all_paid_edit"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(140, 11, 120, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(140, 130, 120, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.cancel_paid_edit = QtGui.QLineEdit(self.groupBox_3)
        self.cancel_paid_edit.setEnabled(False)
        self.cancel_paid_edit.setGeometry(QtCore.QRect(140, 111, 120, 20))
        self.cancel_paid_edit.setObjectName(_fromUtf8("cancel_paid_edit"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(140, 91, 120, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.cancel_other_paid_edit = QtGui.QLineEdit(self.groupBox_3)
        self.cancel_other_paid_edit.setEnabled(False)
        self.cancel_other_paid_edit.setGeometry(QtCore.QRect(140, 150, 120, 20))
        self.cancel_other_paid_edit.setObjectName(_fromUtf8("cancel_other_paid_edit"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(430, 12, 141, 101))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.left_paid_edit = QtGui.QLineEdit(self.groupBox_5)
        self.left_paid_edit.setEnabled(False)
        self.left_paid_edit.setGeometry(QtCore.QRect(10, 31, 120, 20))
        self.left_paid_edit.setObjectName(_fromUtf8("left_paid_edit"))
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(10, 11, 120, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(10, 50, 120, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.surplus_paid_edit = QtGui.QLineEdit(self.groupBox_5)
        self.surplus_paid_edit.setEnabled(False)
        self.surplus_paid_edit.setGeometry(QtCore.QRect(10, 70, 120, 20))
        self.surplus_paid_edit.setObjectName(_fromUtf8("surplus_paid_edit"))
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(430, 111, 141, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.transfer_decision_txt = QtGui.QTextEdit(self.groupBox)
        self.transfer_decision_txt.setGeometry(QtCore.QRect(430, 130, 141, 41))
        self.transfer_decision_txt.setObjectName(_fromUtf8("transfer_decision_txt"))
        self.decsription_txt = QtGui.QTextEdit(self.groupBox)
        self.decsription_txt.setGeometry(QtCore.QRect(430, 189, 141, 41))
        self.decsription_txt.setObjectName(_fromUtf8("decsription_txt"))
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(430, 170, 141, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(15, 53, 151, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(453, 53, 151, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.decision_no_edit = QtGui.QLineEdit(self.tab)
        self.decision_no_edit.setEnabled(False)
        self.decision_no_edit.setGeometry(QtCore.QRect(293, 73, 151, 20))
        self.decision_no_edit.setObjectName(_fromUtf8("decision_no_edit"))
        self.find_gbox = QtGui.QGroupBox(self.tab)
        self.find_gbox.setEnabled(False)
        self.find_gbox.setGeometry(QtCore.QRect(5, -1, 431, 54))
        self.find_gbox.setObjectName(_fromUtf8("find_gbox"))
        self.find_button = QtGui.QPushButton(self.find_gbox)
        self.find_button.setGeometry(QtCore.QRect(340, 26, 75, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/zoom.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.find_button.setIcon(icon)
        self.find_button.setObjectName(_fromUtf8("find_button"))
        self.old_parcel_id_edit = QtGui.QLineEdit(self.find_gbox)
        self.old_parcel_id_edit.setEnabled(False)
        self.old_parcel_id_edit.setGeometry(QtCore.QRect(170, 29, 151, 20))
        self.old_parcel_id_edit.setObjectName(_fromUtf8("old_parcel_id_edit"))
        self.person_id_edit = QtGui.QLineEdit(self.find_gbox)
        self.person_id_edit.setEnabled(False)
        self.person_id_edit.setGeometry(QtCore.QRect(10, 29, 151, 20))
        self.person_id_edit.setObjectName(_fromUtf8("person_id_edit"))
        self.label_3 = QtGui.QLabel(self.find_gbox)
        self.label_3.setGeometry(QtCore.QRect(10, 9, 151, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.find_gbox)
        self.label_4.setGeometry(QtCore.QRect(170, 9, 151, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.decision_date_edit = QtGui.QLineEdit(self.tab)
        self.decision_date_edit.setEnabled(False)
        self.decision_date_edit.setGeometry(QtCore.QRect(453, 73, 151, 20))
        self.decision_date_edit.setObjectName(_fromUtf8("decision_date_edit"))
        self.area_m2_edit = QtGui.QLineEdit(self.tab)
        self.area_m2_edit.setEnabled(False)
        self.area_m2_edit.setGeometry(QtCore.QRect(15, 73, 111, 20))
        self.area_m2_edit.setObjectName(_fromUtf8("area_m2_edit"))
        self.clear_button = QtGui.QPushButton(self.tab)
        self.clear_button.setGeometry(QtCore.QRect(445, 25, 75, 23))
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(133, 53, 151, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(650, 10, 201, 431))
        self.groupBox_4.setMouseTracking(False)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setStyleSheet(_fromUtf8("QGroupBox {\n"
"    \n"
"    background-color: rgb(190, 204, 255);\n"
"    border-color: rgb(79, 255, 30);\n"
"    color: rgb(6, 22, 255);\n"
"}"))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_25 = QtGui.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(10, 249, 180, 23))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.fee_per_year_edit = QtGui.QLineEdit(self.groupBox_4)
        self.fee_per_year_edit.setGeometry(QtCore.QRect(10, 271, 180, 21))
        self.fee_per_year_edit.setReadOnly(True)
        self.fee_per_year_edit.setObjectName(_fromUtf8("fee_per_year_edit"))
        self.fee_to_pay_edit = QtGui.QLineEdit(self.groupBox_4)
        self.fee_to_pay_edit.setGeometry(QtCore.QRect(10, 393, 180, 21))
        self.fee_to_pay_edit.setReadOnly(True)
        self.fee_to_pay_edit.setObjectName(_fromUtf8("fee_to_pay_edit"))
        self.fee_paid_edit = QtGui.QLineEdit(self.groupBox_4)
        self.fee_paid_edit.setGeometry(QtCore.QRect(10, 311, 180, 21))
        self.fee_paid_edit.setReadOnly(True)
        self.fee_paid_edit.setObjectName(_fromUtf8("fee_paid_edit"))
        self.label_26 = QtGui.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(10, 329, 181, 26))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.surplus_from_last_years_edit = QtGui.QLineEdit(self.groupBox_4)
        self.surplus_from_last_years_edit.setGeometry(QtCore.QRect(10, 352, 180, 21))
        self.surplus_from_last_years_edit.setReadOnly(True)
        self.surplus_from_last_years_edit.setObjectName(_fromUtf8("surplus_from_last_years_edit"))
        self.label_27 = QtGui.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(10, 370, 180, 23))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(10, 290, 180, 23))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.parcel_area_edit = QtGui.QLineEdit(self.groupBox_4)
        self.parcel_area_edit.setGeometry(QtCore.QRect(10, 231, 180, 21))
        self.parcel_area_edit.setReadOnly(True)
        self.parcel_area_edit.setObjectName(_fromUtf8("parcel_area_edit"))
        self.label_29 = QtGui.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(10, 209, 180, 23))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.contract_cbox = QtGui.QComboBox(self.groupBox_4)
        self.contract_cbox.setGeometry(QtCore.QRect(10, 32, 181, 22))
        self.contract_cbox.setObjectName(_fromUtf8("contract_cbox"))
        self.label_30 = QtGui.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(10, 14, 181, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.contract_status_edit = QtGui.QLineEdit(self.groupBox_4)
        self.contract_status_edit.setGeometry(QtCore.QRect(10, 73, 181, 20))
        self.contract_status_edit.setReadOnly(True)
        self.contract_status_edit.setObjectName(_fromUtf8("contract_status_edit"))
        self.label_31 = QtGui.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(10, 56, 181, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.groupBox_4)
        self.label_32.setGeometry(QtCore.QRect(10, 94, 181, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.name_edit = QtGui.QLineEdit(self.groupBox_4)
        self.name_edit.setGeometry(QtCore.QRect(10, 111, 181, 20))
        self.name_edit.setReadOnly(True)
        self.name_edit.setObjectName(_fromUtf8("name_edit"))
        self.label_33 = QtGui.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(10, 134, 181, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.parcel_landuse_edit = QtGui.QLineEdit(self.groupBox_4)
        self.parcel_landuse_edit.setGeometry(QtCore.QRect(10, 151, 181, 20))
        self.parcel_landuse_edit.setReadOnly(True)
        self.parcel_landuse_edit.setObjectName(_fromUtf8("parcel_landuse_edit"))
        self.label_34 = QtGui.QLabel(self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(10, 172, 181, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.parcel_zone_edit = QtGui.QLineEdit(self.groupBox_4)
        self.parcel_zone_edit.setGeometry(QtCore.QRect(10, 189, 181, 20))
        self.parcel_zone_edit.setReadOnly(True)
        self.parcel_zone_edit.setObjectName(_fromUtf8("parcel_zone_edit"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))

        self.retranslateUi(ParcelInfoFeeDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ParcelInfoFeeDialog)

    def retranslateUi(self, ParcelInfoFeeDialog):
        ParcelInfoFeeDialog.setWindowTitle(_translate("ParcelInfoFeeDialog", "Dialog", None))
        self.close_button.setText(_translate("ParcelInfoFeeDialog", "Close", None))
        item = self.fee_info_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ParcelInfoFeeDialog", "year", None))
        item = self.fee_info_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ParcelInfoFeeDialog", "Year Fee", None))
        item = self.fee_info_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ParcelInfoFeeDialog", "Fee m2", None))
        item = self.fee_info_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ParcelInfoFeeDialog", "subsidized fee rate", None))
        item = self.fee_info_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ParcelInfoFeeDialog", "left previous year", None))
        item = self.fee_info_twidget.horizontalHeaderItem(5)
        item.setText(_translate("ParcelInfoFeeDialog", "surplus previous year", None))
        item = self.fee_info_twidget.horizontalHeaderItem(6)
        item.setText(_translate("ParcelInfoFeeDialog", "payable year", None))
        item = self.fee_info_twidget.horizontalHeaderItem(7)
        item.setText(_translate("ParcelInfoFeeDialog", "offset", None))
        item = self.fee_info_twidget.horizontalHeaderItem(8)
        item.setText(_translate("ParcelInfoFeeDialog", "control", None))
        item = self.fee_info_twidget.horizontalHeaderItem(9)
        item.setText(_translate("ParcelInfoFeeDialog", "quarterly1 fee", None))
        item = self.fee_info_twidget.horizontalHeaderItem(10)
        item.setText(_translate("ParcelInfoFeeDialog", "quarterly2 fee", None))
        item = self.fee_info_twidget.horizontalHeaderItem(11)
        item.setText(_translate("ParcelInfoFeeDialog", "quarterly3 fee", None))
        item = self.fee_info_twidget.horizontalHeaderItem(12)
        item.setText(_translate("ParcelInfoFeeDialog", "quarterly4 fee", None))
        item = self.fee_info_twidget.horizontalHeaderItem(13)
        item.setText(_translate("ParcelInfoFeeDialog", "payment year", None))
        self.label.setText(_translate("ParcelInfoFeeDialog", "Decision No", None))
        self.groupBox.setTitle(_translate("ParcelInfoFeeDialog", "GroupBox", None))
        self.groupBox_2.setTitle(_translate("ParcelInfoFeeDialog", "Season", None))
        self.label_7.setText(_translate("ParcelInfoFeeDialog", "Quarterly1 paid", None))
        self.label_8.setText(_translate("ParcelInfoFeeDialog", "Quarterly2 paid", None))
        self.label_9.setText(_translate("ParcelInfoFeeDialog", "Quarterly3 paid", None))
        self.label_10.setText(_translate("ParcelInfoFeeDialog", "Quarterly4 paid", None))
        self.label_11.setText(_translate("ParcelInfoFeeDialog", "all_paid", None))
        self.groupBox_3.setTitle(_translate("ParcelInfoFeeDialog", "Paymend", None))
        self.label_12.setText(_translate("ParcelInfoFeeDialog", "left previous year paid", None))
        self.label_13.setText(_translate("ParcelInfoFeeDialog", "payment year paid", None))
        self.label_14.setText(_translate("ParcelInfoFeeDialog", "offset paid", None))
        self.label_15.setText(_translate("ParcelInfoFeeDialog", "frequency paid", None))
        self.label_16.setText(_translate("ParcelInfoFeeDialog", "fine paid", None))
        self.label_17.setText(_translate("ParcelInfoFeeDialog", "district all paid", None))
        self.label_18.setText(_translate("ParcelInfoFeeDialog", "city all paid", None))
        self.label_19.setText(_translate("ParcelInfoFeeDialog", "cancel other paid", None))
        self.label_20.setText(_translate("ParcelInfoFeeDialog", "cancel paid", None))
        self.groupBox_5.setTitle(_translate("ParcelInfoFeeDialog", "left and Surplus", None))
        self.label_23.setText(_translate("ParcelInfoFeeDialog", "left_paid", None))
        self.label_24.setText(_translate("ParcelInfoFeeDialog", "surplus_paid", None))
        self.label_21.setText(_translate("ParcelInfoFeeDialog", "transfer decision", None))
        self.label_22.setText(_translate("ParcelInfoFeeDialog", "decsription", None))
        self.label_5.setText(_translate("ParcelInfoFeeDialog", "Area /m2/", None))
        self.label_2.setText(_translate("ParcelInfoFeeDialog", "Decision Date", None))
        self.find_gbox.setTitle(_translate("ParcelInfoFeeDialog", "Find", None))
        self.find_button.setText(_translate("ParcelInfoFeeDialog", "Find", None))
        self.label_3.setText(_translate("ParcelInfoFeeDialog", "Person ID", None))
        self.label_4.setText(_translate("ParcelInfoFeeDialog", "Old Parcel ID", None))
        self.clear_button.setText(_translate("ParcelInfoFeeDialog", "New", None))
        self.label_6.setText(_translate("ParcelInfoFeeDialog", "Landuse", None))
        self.groupBox_4.setTitle(_translate("ParcelInfoFeeDialog", "LM2 Fee and Payment", None))
        self.label_25.setText(_translate("ParcelInfoFeeDialog", "Fee To Pay For Year [₮]", None))
        self.label_26.setText(_translate("ParcelInfoFeeDialog", "Surplus From Previous Year(s) [₮]", None))
        self.label_27.setText(_translate("ParcelInfoFeeDialog", "Fee Left To Be Paid [₮]", None))
        self.label_28.setText(_translate("ParcelInfoFeeDialog", "Fee Paid [₮]", None))
        self.label_29.setText(_translate("ParcelInfoFeeDialog", "Parcel Area /m2/", None))
        self.label_30.setText(_translate("ParcelInfoFeeDialog", "Contract / Person id", None))
        self.label_31.setText(_translate("ParcelInfoFeeDialog", "Contract Status", None))
        self.label_32.setText(_translate("ParcelInfoFeeDialog", "Name", None))
        self.label_33.setText(_translate("ParcelInfoFeeDialog", "Parcel Land use type", None))
        self.label_34.setText(_translate("ParcelInfoFeeDialog", "Fee zone id", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ParcelInfoFeeDialog", "Fee", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ParcelInfoFeeDialog", "LandUK", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ParcelInfoFeeDialog", "LPIS", None))

import resources_rc
