# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PrintDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PrintDialog(object):
    def setupUi(self, PrintDialog):
        PrintDialog.setObjectName(_fromUtf8("PrintDialog"))
        PrintDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PrintDialog.resize(650, 665)
        PrintDialog.setMinimumSize(QtCore.QSize(650, 665))
        PrintDialog.setMaximumSize(QtCore.QSize(650, 665))
        PrintDialog.setModal(False)
        self.close_button = QtGui.QPushButton(PrintDialog)
        self.close_button.setGeometry(QtCore.QRect(565, 630, 75, 28))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.help_button = QtGui.QPushButton(PrintDialog)
        self.help_button.setGeometry(QtCore.QRect(455, 630, 28, 28))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_button.sizePolicy().hasHeightForWidth())
        self.help_button.setSizePolicy(sizePolicy)
        self.help_button.setMinimumSize(QtCore.QSize(28, 28))
        self.help_button.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.help_button.setFont(font)
        self.help_button.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/help_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_button.setIcon(icon)
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.right_holder_twidget = QtGui.QTableWidget(PrintDialog)
        self.right_holder_twidget.setGeometry(QtCore.QRect(10, 10, 631, 151))
        self.right_holder_twidget.setObjectName(_fromUtf8("right_holder_twidget"))
        self.right_holder_twidget.setColumnCount(7)
        self.right_holder_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(6, item)
        self.print_button = QtGui.QPushButton(PrintDialog)
        self.print_button.setGeometry(QtCore.QRect(485, 630, 75, 28))
        self.print_button.setObjectName(_fromUtf8("print_button"))
        self.file_name_edit = QtGui.QLineEdit(PrintDialog)
        self.file_name_edit.setGeometry(QtCore.QRect(175, 170, 321, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.file_name_edit.setFont(font)
        self.file_name_edit.setReadOnly(True)
        self.file_name_edit.setObjectName(_fromUtf8("file_name_edit"))
        self.label = QtGui.QLabel(PrintDialog)
        self.label.setGeometry(QtCore.QRect(15, 175, 146, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.choose_file_button = QtGui.QPushButton(PrintDialog)
        self.choose_file_button.setGeometry(QtCore.QRect(505, 170, 136, 28))
        self.choose_file_button.setObjectName(_fromUtf8("choose_file_button"))
        self.dpi_edit = QtGui.QLineEdit(PrintDialog)
        self.dpi_edit.setGeometry(QtCore.QRect(175, 221, 56, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dpi_edit.setFont(font)
        self.dpi_edit.setReadOnly(False)
        self.dpi_edit.setObjectName(_fromUtf8("dpi_edit"))
        self.label_2 = QtGui.QLabel(PrintDialog)
        self.label_2.setGeometry(QtCore.QRect(15, 226, 156, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.northArrowGBox = QtGui.QGroupBox(PrintDialog)
        self.northArrowGBox.setGeometry(QtCore.QRect(240, 205, 391, 71))
        self.northArrowGBox.setObjectName(_fromUtf8("northArrowGBox"))
        self.upper_left_rbutton = QtGui.QRadioButton(self.northArrowGBox)
        self.upper_left_rbutton.setGeometry(QtCore.QRect(20, 20, 121, 17))
        self.upper_left_rbutton.setObjectName(_fromUtf8("upper_left_rbutton"))
        self.upper_right_rbutton = QtGui.QRadioButton(self.northArrowGBox)
        self.upper_right_rbutton.setGeometry(QtCore.QRect(195, 20, 121, 17))
        self.upper_right_rbutton.setObjectName(_fromUtf8("upper_right_rbutton"))
        self.lower_right_rbutton = QtGui.QRadioButton(self.northArrowGBox)
        self.lower_right_rbutton.setGeometry(QtCore.QRect(195, 45, 121, 17))
        self.lower_right_rbutton.setObjectName(_fromUtf8("lower_right_rbutton"))
        self.lower_left_rbutton = QtGui.QRadioButton(self.northArrowGBox)
        self.lower_left_rbutton.setGeometry(QtCore.QRect(20, 45, 121, 17))
        self.lower_left_rbutton.setObjectName(_fromUtf8("lower_left_rbutton"))
        self.map_title_edit = QtGui.QLineEdit(PrintDialog)
        self.map_title_edit.setGeometry(QtCore.QRect(175, 385, 446, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.map_title_edit.setFont(font)
        self.map_title_edit.setReadOnly(False)
        self.map_title_edit.setObjectName(_fromUtf8("map_title_edit"))
        self.label_3 = QtGui.QLabel(PrintDialog)
        self.label_3.setGeometry(QtCore.QRect(15, 390, 146, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.groupBox_2 = QtGui.QGroupBox(PrintDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 415, 631, 196))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.department_edit = QtGui.QLineEdit(self.groupBox_2)
        self.department_edit.setGeometry(QtCore.QRect(165, 51, 446, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.department_edit.setFont(font)
        self.department_edit.setReadOnly(False)
        self.department_edit.setObjectName(_fromUtf8("department_edit"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 56, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.department_head_edit = QtGui.QLineEdit(self.groupBox_2)
        self.department_head_edit.setGeometry(QtCore.QRect(165, 16, 446, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.department_head_edit.setFont(font)
        self.department_head_edit.setReadOnly(False)
        self.department_head_edit.setObjectName(_fromUtf8("department_head_edit"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 21, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.cadastre_checkbox = QtGui.QCheckBox(self.groupBox_2)
        self.cadastre_checkbox.setGeometry(QtCore.QRect(5, 85, 171, 17))
        self.cadastre_checkbox.setObjectName(_fromUtf8("cadastre_checkbox"))
        self.cadastre_page_sbox = QtGui.QSpinBox(self.groupBox_2)
        self.cadastre_page_sbox.setEnabled(False)
        self.cadastre_page_sbox.setGeometry(QtCore.QRect(179, 111, 86, 22))
        self.cadastre_page_sbox.setMaximum(99999999)
        self.cadastre_page_sbox.setObjectName(_fromUtf8("cadastre_page_sbox"))
        self.cpage_save_button = QtGui.QPushButton(self.groupBox_2)
        self.cpage_save_button.setEnabled(False)
        self.cpage_save_button.setGeometry(QtCore.QRect(421, 110, 186, 23))
        self.cpage_save_button.setStyleSheet(_fromUtf8("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 250, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #60c465; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 174)\n"
"}"))
        self.cpage_save_button.setObjectName(_fromUtf8("cpage_save_button"))
        self.cpage_print_date = QtGui.QDateEdit(self.groupBox_2)
        self.cpage_print_date.setEnabled(False)
        self.cpage_print_date.setGeometry(QtCore.QRect(345, 111, 71, 22))
        self.cpage_print_date.setObjectName(_fromUtf8("cpage_print_date"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(274, 115, 81, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.error_label = QtGui.QLabel(self.groupBox_2)
        self.error_label.setGeometry(QtCore.QRect(0, 175, 626, 16))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.cadastre_page_interval_cbox = QtGui.QComboBox(self.groupBox_2)
        self.cadastre_page_interval_cbox.setGeometry(QtCore.QRect(180, 85, 236, 22))
        self.cadastre_page_interval_cbox.setObjectName(_fromUtf8("cadastre_page_interval_cbox"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(420, 85, 196, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.print_parcel_address_button = QtGui.QPushButton(self.groupBox_2)
        self.print_parcel_address_button.setGeometry(QtCore.QRect(5, 145, 146, 28))
        self.print_parcel_address_button.setObjectName(_fromUtf8("print_parcel_address_button"))
        self.save_settings_button = QtGui.QPushButton(PrintDialog)
        self.save_settings_button.setGeometry(QtCore.QRect(15, 630, 146, 28))
        self.save_settings_button.setObjectName(_fromUtf8("save_settings_button"))
        self.load_settings_button = QtGui.QPushButton(PrintDialog)
        self.load_settings_button.setGeometry(QtCore.QRect(165, 630, 136, 28))
        self.load_settings_button.setObjectName(_fromUtf8("load_settings_button"))
        self.load_defaults_button = QtGui.QPushButton(PrintDialog)
        self.load_defaults_button.setGeometry(QtCore.QRect(305, 630, 146, 28))
        self.load_defaults_button.setObjectName(_fromUtf8("load_defaults_button"))
        self.label_7 = QtGui.QLabel(PrintDialog)
        self.label_7.setGeometry(QtCore.QRect(15, 246, 156, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.buffer_edit = QtGui.QLineEdit(PrintDialog)
        self.buffer_edit.setGeometry(QtCore.QRect(175, 251, 56, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buffer_edit.setFont(font)
        self.buffer_edit.setReadOnly(False)
        self.buffer_edit.setObjectName(_fromUtf8("buffer_edit"))
        self.groupBox = QtGui.QGroupBox(PrintDialog)
        self.groupBox.setGeometry(QtCore.QRect(15, 275, 616, 56))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.grid_distance_edit = QtGui.QLineEdit(self.groupBox)
        self.grid_distance_edit.setGeometry(QtCore.QRect(160, 20, 56, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.grid_distance_edit.setFont(font)
        self.grid_distance_edit.setReadOnly(False)
        self.grid_distance_edit.setObjectName(_fromUtf8("grid_distance_edit"))
        self.grid_offset_x_edit = QtGui.QLineEdit(self.groupBox)
        self.grid_offset_x_edit.setGeometry(QtCore.QRect(355, 20, 56, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.grid_offset_x_edit.setFont(font)
        self.grid_offset_x_edit.setReadOnly(False)
        self.grid_offset_x_edit.setObjectName(_fromUtf8("grid_offset_x_edit"))
        self.grid_offset_y_edit = QtGui.QLineEdit(self.groupBox)
        self.grid_offset_y_edit.setGeometry(QtCore.QRect(545, 20, 56, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.grid_offset_y_edit.setFont(font)
        self.grid_offset_y_edit.setReadOnly(False)
        self.grid_offset_y_edit.setObjectName(_fromUtf8("grid_offset_y_edit"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(15, 25, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(245, 25, 106, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(440, 25, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.groupBox_3 = QtGui.QGroupBox(PrintDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(15, 335, 616, 46))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.old_parcel_id_chbox = QtGui.QCheckBox(PrintDialog)
        self.old_parcel_id_chbox.setGeometry(QtCore.QRect(256, 350, 134, 17))
        self.old_parcel_id_chbox.setObjectName(_fromUtf8("old_parcel_id_chbox"))
        self.cadastreid_chbox = QtGui.QCheckBox(PrintDialog)
        self.cadastreid_chbox.setGeometry(QtCore.QRect(33, 350, 176, 17))
        self.cadastreid_chbox.setObjectName(_fromUtf8("cadastreid_chbox"))
        self.geoid_chbox = QtGui.QCheckBox(PrintDialog)
        self.geoid_chbox.setGeometry(QtCore.QRect(480, 350, 133, 17))
        self.geoid_chbox.setObjectName(_fromUtf8("geoid_chbox"))
        self.label.setBuddy(self.file_name_edit)
        self.label_2.setBuddy(self.dpi_edit)
        self.label_3.setBuddy(self.map_title_edit)
        self.label_5.setBuddy(self.department_edit)
        self.label_7.setBuddy(self.buffer_edit)
        self.label_8.setBuddy(self.grid_distance_edit)
        self.label_9.setBuddy(self.grid_offset_x_edit)
        self.label_10.setBuddy(self.grid_offset_y_edit)

        self.retranslateUi(PrintDialog)
        QtCore.QMetaObject.connectSlotsByName(PrintDialog)
        PrintDialog.setTabOrder(self.right_holder_twidget, self.choose_file_button)
        PrintDialog.setTabOrder(self.choose_file_button, self.file_name_edit)
        PrintDialog.setTabOrder(self.file_name_edit, self.dpi_edit)
        PrintDialog.setTabOrder(self.dpi_edit, self.upper_left_rbutton)
        PrintDialog.setTabOrder(self.upper_left_rbutton, self.upper_right_rbutton)
        PrintDialog.setTabOrder(self.upper_right_rbutton, self.lower_left_rbutton)
        PrintDialog.setTabOrder(self.lower_left_rbutton, self.lower_right_rbutton)
        PrintDialog.setTabOrder(self.lower_right_rbutton, self.buffer_edit)
        PrintDialog.setTabOrder(self.buffer_edit, self.grid_distance_edit)
        PrintDialog.setTabOrder(self.grid_distance_edit, self.grid_offset_x_edit)
        PrintDialog.setTabOrder(self.grid_offset_x_edit, self.grid_offset_y_edit)
        PrintDialog.setTabOrder(self.grid_offset_y_edit, self.map_title_edit)
        PrintDialog.setTabOrder(self.map_title_edit, self.department_head_edit)
        PrintDialog.setTabOrder(self.department_head_edit, self.department_edit)
        PrintDialog.setTabOrder(self.department_edit, self.save_settings_button)
        PrintDialog.setTabOrder(self.save_settings_button, self.load_settings_button)
        PrintDialog.setTabOrder(self.load_settings_button, self.load_defaults_button)
        PrintDialog.setTabOrder(self.load_defaults_button, self.help_button)
        PrintDialog.setTabOrder(self.help_button, self.print_button)
        PrintDialog.setTabOrder(self.print_button, self.close_button)

    def retranslateUi(self, PrintDialog):
        PrintDialog.setWindowTitle(_translate("PrintDialog", "Dialog", None))
        self.close_button.setText(_translate("PrintDialog", "Close", None))
        item = self.right_holder_twidget.horizontalHeaderItem(0)
        item.setText(_translate("PrintDialog", "Person / Company ID", None))
        item = self.right_holder_twidget.horizontalHeaderItem(1)
        item.setText(_translate("PrintDialog", "Person / Company Name", None))
        item = self.right_holder_twidget.horizontalHeaderItem(2)
        item.setText(_translate("PrintDialog", "Middle Name", None))
        item = self.right_holder_twidget.horizontalHeaderItem(3)
        item.setText(_translate("PrintDialog", "First Name", None))
        item = self.right_holder_twidget.horizontalHeaderItem(4)
        item.setText(_translate("PrintDialog", "Birthday", None))
        item = self.right_holder_twidget.horizontalHeaderItem(5)
        item.setText(_translate("PrintDialog", "Contract No", None))
        item = self.right_holder_twidget.horizontalHeaderItem(6)
        item.setText(_translate("PrintDialog", "Contract Date", None))
        self.print_button.setText(_translate("PrintDialog", "Print", None))
        self.label.setText(_translate("PrintDialog", "File Name", None))
        self.choose_file_button.setText(_translate("PrintDialog", "Choose File", None))
        self.label_2.setText(_translate("PrintDialog", "Print Resolution [DPI]", None))
        self.northArrowGBox.setTitle(_translate("PrintDialog", "Position of the north arrow on the map", None))
        self.upper_left_rbutton.setText(_translate("PrintDialog", "Upper Left Corner", None))
        self.upper_right_rbutton.setText(_translate("PrintDialog", "Upper Right Corner", None))
        self.lower_right_rbutton.setText(_translate("PrintDialog", "Lower Right Corner", None))
        self.lower_left_rbutton.setText(_translate("PrintDialog", "Lower Left Corner", None))
        self.label_3.setText(_translate("PrintDialog", "Map Title", None))
        self.groupBox_2.setTitle(_translate("PrintDialog", "Map stamp text (lower right corner)", None))
        self.label_5.setText(_translate("PrintDialog", "Department Name", None))
        self.label_11.setText(_translate("PrintDialog", "Head of Department", None))
        self.cadastre_checkbox.setText(_translate("PrintDialog", "Cadastre Page", None))
        self.cpage_save_button.setText(_translate("PrintDialog", "Save Cadastre Page", None))
        self.label_4.setText(_translate("PrintDialog", "Print Date", None))
        self.label_6.setText(_translate("PrintDialog", "cadastre_page_selected", None))
        self.print_parcel_address_button.setText(_translate("PrintDialog", "Print Parcel Specification", None))
        self.save_settings_button.setText(_translate("PrintDialog", "Save Plot Settings", None))
        self.load_settings_button.setText(_translate("PrintDialog", "Load Plot Settings", None))
        self.load_defaults_button.setText(_translate("PrintDialog", "Load Default Values", None))
        self.label_7.setText(_translate("PrintDialog", "Parcel Buffer [1 - 500 m]", None))
        self.buffer_edit.setWhatsThis(_translate("PrintDialog", "The initial buffer around the parcel based on which the appropriate map scale is calculated. The scale denominator is then rounded to be a multiple of 250.", None))
        self.groupBox.setTitle(_translate("PrintDialog", "Grid", None))
        self.grid_distance_edit.setWhatsThis(_translate("PrintDialog", "The initial buffer around the parcel based on which the appropriate map scale is calculated. The scale denominator is then rounded to be a multiple of 250.", None))
        self.grid_offset_x_edit.setWhatsThis(_translate("PrintDialog", "The initial buffer around the parcel based on which the appropriate map scale is calculated. The scale denominator is then rounded to be a multiple of 250.", None))
        self.grid_offset_y_edit.setWhatsThis(_translate("PrintDialog", "The initial buffer around the parcel based on which the appropriate map scale is calculated. The scale denominator is then rounded to be a multiple of 250.", None))
        self.label_8.setText(_translate("PrintDialog", "Distance [10 - 1000 m]", None))
        self.label_9.setText(_translate("PrintDialog", "Offset X [0 - 50 m]", None))
        self.label_10.setText(_translate("PrintDialog", "Offset Y [0 - 50 m]", None))
        self.groupBox_3.setTitle(_translate("PrintDialog", "Parcel identifier in map", None))
        self.old_parcel_id_chbox.setText(_translate("PrintDialog", "Old Parcel ID", None))
        self.cadastreid_chbox.setText(_translate("PrintDialog", "Cadastre ID", None))
        self.geoid_chbox.setText(_translate("PrintDialog", "Geo ID", None))

import resources_rc
