# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ParcelInfoDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ParcelInfoDialog(object):
    def setupUi(self, ParcelInfoDialog):
        ParcelInfoDialog.setObjectName(_fromUtf8("ParcelInfoDialog"))
        ParcelInfoDialog.resize(600, 800)
        ParcelInfoDialog.setMinimumSize(QtCore.QSize(600, 700))
        ParcelInfoDialog.setMaximumSize(QtCore.QSize(600, 800))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setGeometry(QtCore.QRect(10, 0, 581, 761))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(550, 300))
        self.scrollArea.setMaximumSize(QtCore.QSize(600, 1500))
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setAcceptDrops(False)
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 600, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(550, 1000))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(600, 800))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.parcel_tab_widget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.parcel_tab_widget.setGeometry(QtCore.QRect(6, 200, 556, 473))
        self.parcel_tab_widget.setObjectName(_fromUtf8("parcel_tab_widget"))
        self.parcel_person_tab = QtGui.QWidget()
        self.parcel_person_tab.setObjectName(_fromUtf8("parcel_person_tab"))
        self.parcel_gbox = QtGui.QGroupBox(self.parcel_person_tab)
        self.parcel_gbox.setGeometry(QtCore.QRect(3, 1, 541, 101))
        self.parcel_gbox.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: #f5f5ef; border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.parcel_gbox.setObjectName(_fromUtf8("parcel_gbox"))
        self.parcel_id_edit = QtGui.QLineEdit(self.parcel_gbox)
        self.parcel_id_edit.setEnabled(True)
        self.parcel_id_edit.setGeometry(QtCore.QRect(10, 36, 110, 20))
        self.parcel_id_edit.setReadOnly(True)
        self.parcel_id_edit.setObjectName(_fromUtf8("parcel_id_edit"))
        self.label_3 = QtGui.QLabel(self.parcel_gbox)
        self.label_3.setGeometry(QtCore.QRect(10, 12, 121, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.khashaa_edit = QtGui.QLineEdit(self.parcel_gbox)
        self.khashaa_edit.setEnabled(False)
        self.khashaa_edit.setGeometry(QtCore.QRect(250, 36, 100, 20))
        self.khashaa_edit.setObjectName(_fromUtf8("khashaa_edit"))
        self.old_parcel_id_edit = QtGui.QLineEdit(self.parcel_gbox)
        self.old_parcel_id_edit.setEnabled(True)
        self.old_parcel_id_edit.setGeometry(QtCore.QRect(130, 36, 110, 20))
        self.old_parcel_id_edit.setReadOnly(True)
        self.old_parcel_id_edit.setObjectName(_fromUtf8("old_parcel_id_edit"))
        self.streetname_edit = QtGui.QLineEdit(self.parcel_gbox)
        self.streetname_edit.setEnabled(False)
        self.streetname_edit.setGeometry(QtCore.QRect(360, 36, 170, 20))
        self.streetname_edit.setObjectName(_fromUtf8("streetname_edit"))
        self.khashaa_chbox = QtGui.QCheckBox(self.parcel_gbox)
        self.khashaa_chbox.setGeometry(QtCore.QRect(250, 10, 111, 17))
        self.khashaa_chbox.setObjectName(_fromUtf8("khashaa_chbox"))
        self.street_chbox = QtGui.QCheckBox(self.parcel_gbox)
        self.street_chbox.setGeometry(QtCore.QRect(360, 10, 171, 17))
        self.street_chbox.setObjectName(_fromUtf8("street_chbox"))
        self.label_5 = QtGui.QLabel(self.parcel_gbox)
        self.label_5.setGeometry(QtCore.QRect(130, 12, 121, 16))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.zoriulalt_edit = QtGui.QLineEdit(self.parcel_gbox)
        self.zoriulalt_edit.setEnabled(False)
        self.zoriulalt_edit.setGeometry(QtCore.QRect(10, 76, 45, 20))
        self.zoriulalt_edit.setObjectName(_fromUtf8("zoriulalt_edit"))
        self.zoriulalt_chbox = QtGui.QCheckBox(self.parcel_gbox)
        self.zoriulalt_chbox.setGeometry(QtCore.QRect(10, 57, 61, 17))
        self.zoriulalt_chbox.setObjectName(_fromUtf8("zoriulalt_chbox"))
        self.neighbourhood_edit = QtGui.QLineEdit(self.parcel_gbox)
        self.neighbourhood_edit.setEnabled(False)
        self.neighbourhood_edit.setGeometry(QtCore.QRect(360, 76, 170, 20))
        self.neighbourhood_edit.setObjectName(_fromUtf8("neighbourhood_edit"))
        self.neighbourhood_chbox = QtGui.QCheckBox(self.parcel_gbox)
        self.neighbourhood_chbox.setGeometry(QtCore.QRect(360, 57, 170, 17))
        self.neighbourhood_chbox.setObjectName(_fromUtf8("neighbourhood_chbox"))
        self.parcel_landuse_cbox = QtGui.QComboBox(self.parcel_person_tab)
        self.parcel_landuse_cbox.setEnabled(False)
        self.parcel_landuse_cbox.setGeometry(QtCore.QRect(70, 76, 280, 20))
        self.parcel_landuse_cbox.setObjectName(_fromUtf8("parcel_landuse_cbox"))
        self.landuse_chbox = QtGui.QCheckBox(self.parcel_person_tab)
        self.landuse_chbox.setGeometry(QtCore.QRect(70, 58, 261, 17))
        self.landuse_chbox.setObjectName(_fromUtf8("landuse_chbox"))
        self.person_tabwidget = QtGui.QTabWidget(self.parcel_person_tab)
        self.person_tabwidget.setGeometry(QtCore.QRect(3, 103, 543, 129))
        self.person_tabwidget.setStyleSheet(_fromUtf8(""))
        self.person_tabwidget.setObjectName(_fromUtf8("person_tabwidget"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.phone_edit = QtGui.QLineEdit(self.tab_8)
        self.phone_edit.setEnabled(False)
        self.phone_edit.setGeometry(QtCore.QRect(107, 80, 261, 20))
        self.phone_edit.setObjectName(_fromUtf8("phone_edit"))
        self.phone_chbox = QtGui.QCheckBox(self.tab_8)
        self.phone_chbox.setGeometry(QtCore.QRect(10, 80, 101, 17))
        self.phone_chbox.setObjectName(_fromUtf8("phone_chbox"))
        self.person_type_cbox = QtGui.QComboBox(self.tab_8)
        self.person_type_cbox.setEnabled(False)
        self.person_type_cbox.setGeometry(QtCore.QRect(10, 19, 260, 20))
        self.person_type_cbox.setObjectName(_fromUtf8("person_type_cbox"))
        self.firstname_chbox = QtGui.QCheckBox(self.tab_8)
        self.firstname_chbox.setGeometry(QtCore.QRect(10, 40, 180, 17))
        self.firstname_chbox.setObjectName(_fromUtf8("firstname_chbox"))
        self.lastname_chbox = QtGui.QCheckBox(self.tab_8)
        self.lastname_chbox.setGeometry(QtCore.QRect(386, 40, 151, 17))
        self.lastname_chbox.setObjectName(_fromUtf8("lastname_chbox"))
        self.middlename_chbox = QtGui.QCheckBox(self.tab_8)
        self.middlename_chbox.setGeometry(QtCore.QRect(193, 40, 191, 17))
        self.middlename_chbox.setObjectName(_fromUtf8("middlename_chbox"))
        self.name_edit = QtGui.QLineEdit(self.tab_8)
        self.name_edit.setEnabled(False)
        self.name_edit.setGeometry(QtCore.QRect(386, 57, 151, 20))
        self.name_edit.setObjectName(_fromUtf8("name_edit"))
        self.person_type_chbox = QtGui.QCheckBox(self.tab_8)
        self.person_type_chbox.setGeometry(QtCore.QRect(10, 0, 271, 17))
        self.person_type_chbox.setObjectName(_fromUtf8("person_type_chbox"))
        self.first_name_edit = QtGui.QLineEdit(self.tab_8)
        self.first_name_edit.setEnabled(False)
        self.first_name_edit.setGeometry(QtCore.QRect(10, 57, 180, 20))
        self.first_name_edit.setObjectName(_fromUtf8("first_name_edit"))
        self.personal_id_edit = QtGui.QLineEdit(self.tab_8)
        self.personal_id_edit.setEnabled(False)
        self.personal_id_edit.setGeometry(QtCore.QRect(277, 19, 150, 20))
        self.personal_id_edit.setObjectName(_fromUtf8("personal_id_edit"))
        self.date_of_birth_date = QtGui.QDateEdit(self.tab_8)
        self.date_of_birth_date.setEnabled(False)
        self.date_of_birth_date.setGeometry(QtCore.QRect(437, 19, 91, 20))
        self.date_of_birth_date.setLocale(QtCore.QLocale(QtCore.QLocale.Mongolian, QtCore.QLocale.Mongolia))
        self.date_of_birth_date.setDisplayFormat(_fromUtf8("yyyy-MM-dd"))
        self.date_of_birth_date.setCalendarPopup(True)
        self.date_of_birth_date.setObjectName(_fromUtf8("date_of_birth_date"))
        self.middle_name_edit = QtGui.QLineEdit(self.tab_8)
        self.middle_name_edit.setEnabled(False)
        self.middle_name_edit.setGeometry(QtCore.QRect(193, 57, 191, 20))
        self.middle_name_edit.setObjectName(_fromUtf8("middle_name_edit"))
        self.person_id_chbox = QtGui.QCheckBox(self.tab_8)
        self.person_id_chbox.setGeometry(QtCore.QRect(277, 1, 146, 17))
        self.person_id_chbox.setObjectName(_fromUtf8("person_id_chbox"))
        self.person_tabwidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.label_6 = QtGui.QLabel(self.tab_9)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 150, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.aimag_cbox = QtGui.QComboBox(self.tab_9)
        self.aimag_cbox.setGeometry(QtCore.QRect(10, 16, 170, 20))
        self.aimag_cbox.setObjectName(_fromUtf8("aimag_cbox"))
        self.bag_cbox = QtGui.QComboBox(self.tab_9)
        self.bag_cbox.setGeometry(QtCore.QRect(360, 16, 170, 20))
        self.bag_cbox.setObjectName(_fromUtf8("bag_cbox"))
        self.label_7 = QtGui.QLabel(self.tab_9)
        self.label_7.setGeometry(QtCore.QRect(184, 0, 150, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.soum_cbox = QtGui.QComboBox(self.tab_9)
        self.soum_cbox.setGeometry(QtCore.QRect(184, 16, 170, 20))
        self.soum_cbox.setObjectName(_fromUtf8("soum_cbox"))
        self.label_8 = QtGui.QLabel(self.tab_9)
        self.label_8.setGeometry(QtCore.QRect(360, 0, 150, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.person_khashaa_edit = QtGui.QLineEdit(self.tab_9)
        self.person_khashaa_edit.setGeometry(QtCore.QRect(187, 55, 150, 21))
        self.person_khashaa_edit.setObjectName(_fromUtf8("person_khashaa_edit"))
        self.person_street_name_edit = QtGui.QLineEdit(self.tab_9)
        self.person_street_name_edit.setGeometry(QtCore.QRect(10, 55, 171, 21))
        self.person_street_name_edit.setObjectName(_fromUtf8("person_street_name_edit"))
        self.label_12 = QtGui.QLabel(self.tab_9)
        self.label_12.setGeometry(QtCore.QRect(10, 39, 170, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_19 = QtGui.QLabel(self.tab_9)
        self.label_19.setGeometry(QtCore.QRect(187, 40, 150, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.building_edit = QtGui.QLineEdit(self.tab_9)
        self.building_edit.setGeometry(QtCore.QRect(450, 55, 80, 21))
        self.building_edit.setObjectName(_fromUtf8("building_edit"))
        self.label_35 = QtGui.QLabel(self.tab_9)
        self.label_35.setGeometry(QtCore.QRect(450, 40, 80, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.apartment_edit = QtGui.QLineEdit(self.tab_9)
        self.apartment_edit.setGeometry(QtCore.QRect(343, 55, 100, 21))
        self.apartment_edit.setObjectName(_fromUtf8("apartment_edit"))
        self.label_36 = QtGui.QLabel(self.tab_9)
        self.label_36.setGeometry(QtCore.QRect(343, 40, 100, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.person_tabwidget.addTab(self.tab_9, _fromUtf8(""))
        self.groupBox_5 = QtGui.QGroupBox(self.parcel_person_tab)
        self.groupBox_5.setGeometry(QtCore.QRect(3, 234, 541, 107))
        self.groupBox_5.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: #f5f5ef; border: 1px solid black;\n"
"     border-radius: 3px;\n"
"}"))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.decision_date = QtGui.QDateEdit(self.groupBox_5)
        self.decision_date.setEnabled(False)
        self.decision_date.setGeometry(QtCore.QRect(438, 35, 101, 20))
        self.decision_date.setCalendarPopup(True)
        self.decision_date.setObjectName(_fromUtf8("decision_date"))
        self.decision_date_chbox = QtGui.QCheckBox(self.groupBox_5)
        self.decision_date_chbox.setGeometry(QtCore.QRect(440, 15, 101, 20))
        self.decision_date_chbox.setObjectName(_fromUtf8("decision_date_chbox"))
        self.decision_full_edit = QtGui.QLineEdit(self.groupBox_5)
        self.decision_full_edit.setEnabled(False)
        self.decision_full_edit.setGeometry(QtCore.QRect(397, 80, 141, 20))
        self.decision_full_edit.setObjectName(_fromUtf8("decision_full_edit"))
        self.rigth_type_cbox = QtGui.QComboBox(self.groupBox_5)
        self.rigth_type_cbox.setEnabled(False)
        self.rigth_type_cbox.setGeometry(QtCore.QRect(9, 35, 110, 20))
        self.rigth_type_cbox.setObjectName(_fromUtf8("rigth_type_cbox"))
        self.decision_no_edit = QtGui.QLineEdit(self.groupBox_5)
        self.decision_no_edit.setEnabled(False)
        self.decision_no_edit.setGeometry(QtCore.QRect(346, 35, 80, 20))
        self.decision_no_edit.setObjectName(_fromUtf8("decision_no_edit"))
        self.decision_full_chbox = QtGui.QLabel(self.groupBox_5)
        self.decision_full_chbox.setGeometry(QtCore.QRect(398, 60, 136, 16))
        self.decision_full_chbox.setObjectName(_fromUtf8("decision_full_chbox"))
        self.decision_level_cbox = QtGui.QComboBox(self.groupBox_5)
        self.decision_level_cbox.setEnabled(False)
        self.decision_level_cbox.setGeometry(QtCore.QRect(126, 35, 211, 20))
        self.decision_level_cbox.setObjectName(_fromUtf8("decision_level_cbox"))
        self.level_chbox = QtGui.QCheckBox(self.groupBox_5)
        self.level_chbox.setGeometry(QtCore.QRect(126, 15, 211, 17))
        self.level_chbox.setObjectName(_fromUtf8("level_chbox"))
        self.right_type_chbox = QtGui.QCheckBox(self.groupBox_5)
        self.right_type_chbox.setGeometry(QtCore.QRect(9, 15, 110, 17))
        self.right_type_chbox.setObjectName(_fromUtf8("right_type_chbox"))
        self.decision_no_chbox = QtGui.QCheckBox(self.groupBox_5)
        self.decision_no_chbox.setGeometry(QtCore.QRect(346, 15, 80, 17))
        self.decision_no_chbox.setObjectName(_fromUtf8("decision_no_chbox"))
        self.label_42 = QtGui.QLabel(self.groupBox_5)
        self.label_42.setGeometry(QtCore.QRect(11, 60, 307, 16))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.application_type_cbox = QtGui.QComboBox(self.groupBox_5)
        self.application_type_cbox.setEnabled(True)
        self.application_type_cbox.setGeometry(QtCore.QRect(10, 80, 340, 20))
        self.application_type_cbox.setObjectName(_fromUtf8("application_type_cbox"))
        self.contract_gbox = QtGui.QGroupBox(self.parcel_person_tab)
        self.contract_gbox.setGeometry(QtCore.QRect(3, 341, 541, 104))
        self.contract_gbox.setObjectName(_fromUtf8("contract_gbox"))
        self.contract_status_cbox = QtGui.QComboBox(self.contract_gbox)
        self.contract_status_cbox.setEnabled(False)
        self.contract_status_cbox.setGeometry(QtCore.QRect(10, 33, 160, 20))
        self.contract_status_cbox.setObjectName(_fromUtf8("contract_status_cbox"))
        self.contract_date = QtGui.QDateEdit(self.contract_gbox)
        self.contract_date.setEnabled(False)
        self.contract_date.setGeometry(QtCore.QRect(10, 77, 101, 20))
        self.contract_date.setCalendarPopup(True)
        self.contract_date.setObjectName(_fromUtf8("contract_date"))
        self.contract_cert_edit = QtGui.QLineEdit(self.contract_gbox)
        self.contract_cert_edit.setEnabled(False)
        self.contract_cert_edit.setGeometry(QtCore.QRect(360, 33, 101, 20))
        self.contract_cert_edit.setObjectName(_fromUtf8("contract_cert_edit"))
        self.contract_date_chbox = QtGui.QCheckBox(self.contract_gbox)
        self.contract_date_chbox.setGeometry(QtCore.QRect(10, 57, 101, 17))
        self.contract_date_chbox.setObjectName(_fromUtf8("contract_date_chbox"))
        self.contract_full_chbox = QtGui.QLabel(self.contract_gbox)
        self.contract_full_chbox.setGeometry(QtCore.QRect(190, 15, 121, 16))
        self.contract_full_chbox.setObjectName(_fromUtf8("contract_full_chbox"))
        self.end_date_chbox = QtGui.QCheckBox(self.contract_gbox)
        self.end_date_chbox.setGeometry(QtCore.QRect(140, 57, 91, 17))
        self.end_date_chbox.setObjectName(_fromUtf8("end_date_chbox"))
        self.duration_chbox = QtGui.QCheckBox(self.contract_gbox)
        self.duration_chbox.setGeometry(QtCore.QRect(260, 57, 81, 20))
        self.duration_chbox.setObjectName(_fromUtf8("duration_chbox"))
        self.contract_certificate_chbox = QtGui.QCheckBox(self.contract_gbox)
        self.contract_certificate_chbox.setGeometry(QtCore.QRect(360, 15, 91, 17))
        self.contract_certificate_chbox.setObjectName(_fromUtf8("contract_certificate_chbox"))
        self.contract_full_edit = QtGui.QLineEdit(self.contract_gbox)
        self.contract_full_edit.setEnabled(False)
        self.contract_full_edit.setGeometry(QtCore.QRect(190, 33, 151, 20))
        self.contract_full_edit.setObjectName(_fromUtf8("contract_full_edit"))
        self.duration_sbox = QtGui.QSpinBox(self.contract_gbox)
        self.duration_sbox.setEnabled(False)
        self.duration_sbox.setGeometry(QtCore.QRect(260, 77, 81, 20))
        self.duration_sbox.setObjectName(_fromUtf8("duration_sbox"))
        self.end_date = QtGui.QDateEdit(self.contract_gbox)
        self.end_date.setEnabled(False)
        self.end_date.setGeometry(QtCore.QRect(140, 77, 91, 20))
        self.end_date.setCalendarPopup(True)
        self.end_date.setObjectName(_fromUtf8("end_date"))
        self.contract_status_chbox = QtGui.QCheckBox(self.contract_gbox)
        self.contract_status_chbox.setGeometry(QtCore.QRect(10, 15, 160, 17))
        self.contract_status_chbox.setObjectName(_fromUtf8("contract_status_chbox"))
        self.parcel_tab_widget.addTab(self.parcel_person_tab, _fromUtf8(""))
        self.document_tab = QtGui.QWidget()
        self.document_tab.setObjectName(_fromUtf8("document_tab"))
        self.load_docs_button = QtGui.QPushButton(self.document_tab)
        self.load_docs_button.setGeometry(QtCore.QRect(271, 30, 101, 23))
        self.load_docs_button.setObjectName(_fromUtf8("load_docs_button"))
        self.documet_cbox = QtGui.QComboBox(self.document_tab)
        self.documet_cbox.setGeometry(QtCore.QRect(10, 31, 251, 22))
        self.documet_cbox.setObjectName(_fromUtf8("documet_cbox"))
        self.doc_twidget = QtGui.QTableWidget(self.document_tab)
        self.doc_twidget.setGeometry(QtCore.QRect(10, 60, 531, 181))
        self.doc_twidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.doc_twidget.setObjectName(_fromUtf8("doc_twidget"))
        self.doc_twidget.setColumnCount(3)
        self.doc_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(2, item)
        self.doc_twidget.horizontalHeader().setCascadingSectionResizes(False)
        self.doc_twidget.horizontalHeader().setDefaultSectionSize(120)
        self.doc_twidget.horizontalHeader().setHighlightSections(False)
        self.doc_twidget.verticalHeader().setCascadingSectionResizes(False)
        self.doc_info_twidget = QtGui.QTableWidget(self.document_tab)
        self.doc_info_twidget.setGeometry(QtCore.QRect(10, 250, 531, 121))
        self.doc_info_twidget.setObjectName(_fromUtf8("doc_info_twidget"))
        self.doc_info_twidget.setColumnCount(8)
        self.doc_info_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.doc_info_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.doc_info_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.doc_info_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.doc_info_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.doc_info_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.doc_info_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.doc_info_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.doc_info_twidget.setHorizontalHeaderItem(7, item)
        self.ftp_connect_button = QtGui.QPushButton(self.document_tab)
        self.ftp_connect_button.setGeometry(QtCore.QRect(271, 3, 101, 23))
        self.ftp_connect_button.setObjectName(_fromUtf8("ftp_connect_button"))
        self.is_ftp_edit_chbox = QtGui.QCheckBox(self.document_tab)
        self.is_ftp_edit_chbox.setGeometry(QtCore.QRect(10, 6, 111, 17))
        self.is_ftp_edit_chbox.setObjectName(_fromUtf8("is_ftp_edit_chbox"))
        self.ftp_host_edit = QtGui.QLineEdit(self.document_tab)
        self.ftp_host_edit.setEnabled(False)
        self.ftp_host_edit.setGeometry(QtCore.QRect(130, 6, 131, 20))
        self.ftp_host_edit.setObjectName(_fromUtf8("ftp_host_edit"))
        self.parcel_tab_widget.addTab(self.document_tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.fee_view_button = QtGui.QPushButton(self.tab_5)
        self.fee_view_button.setGeometry(QtCore.QRect(5, 310, 75, 23))
        self.fee_view_button.setObjectName(_fromUtf8("fee_view_button"))
        self.fee_info_twidget = QtGui.QTableWidget(self.tab_5)
        self.fee_info_twidget.setGeometry(QtCore.QRect(1, 60, 541, 241))
        self.fee_info_twidget.setObjectName(_fromUtf8("fee_info_twidget"))
        self.fee_info_twidget.setColumnCount(8)
        self.fee_info_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.fee_info_twidget.setHorizontalHeaderItem(7, item)
        self.fee_find_button = QtGui.QPushButton(self.tab_5)
        self.fee_find_button.setEnabled(False)
        self.fee_find_button.setGeometry(QtCore.QRect(296, 33, 75, 23))
        self.fee_find_button.setObjectName(_fromUtf8("fee_find_button"))
        self.fee_person_id_edit = QtGui.QLineEdit(self.tab_5)
        self.fee_person_id_edit.setEnabled(False)
        self.fee_person_id_edit.setGeometry(QtCore.QRect(10, 35, 120, 20))
        self.fee_person_id_edit.setObjectName(_fromUtf8("fee_person_id_edit"))
        self.fee_old_parcel_id_edit = QtGui.QLineEdit(self.tab_5)
        self.fee_old_parcel_id_edit.setEnabled(False)
        self.fee_old_parcel_id_edit.setGeometry(QtCore.QRect(140, 35, 141, 20))
        self.fee_old_parcel_id_edit.setObjectName(_fromUtf8("fee_old_parcel_id_edit"))
        self.checkBox_5 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 0, 351, 17))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.label_9 = QtGui.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(10, 18, 121, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(140, 18, 231, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.parcel_tab_widget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.lpis_search_chbox = QtGui.QCheckBox(self.tab_6)
        self.lpis_search_chbox.setGeometry(QtCore.QRect(9, 1, 311, 17))
        self.lpis_search_chbox.setObjectName(_fromUtf8("lpis_search_chbox"))
        self.lpis_find_button = QtGui.QPushButton(self.tab_6)
        self.lpis_find_button.setEnabled(False)
        self.lpis_find_button.setGeometry(QtCore.QRect(296, 33, 75, 23))
        self.lpis_find_button.setObjectName(_fromUtf8("lpis_find_button"))
        self.label_31 = QtGui.QLabel(self.tab_6)
        self.label_31.setGeometry(QtCore.QRect(140, 18, 231, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_48 = QtGui.QLabel(self.tab_6)
        self.label_48.setGeometry(QtCore.QRect(10, 18, 121, 16))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.lpis_old_parcel_id_edit = QtGui.QLineEdit(self.tab_6)
        self.lpis_old_parcel_id_edit.setEnabled(False)
        self.lpis_old_parcel_id_edit.setGeometry(QtCore.QRect(140, 35, 141, 20))
        self.lpis_old_parcel_id_edit.setObjectName(_fromUtf8("lpis_old_parcel_id_edit"))
        self.lpis_info_twidget = QtGui.QTableWidget(self.tab_6)
        self.lpis_info_twidget.setGeometry(QtCore.QRect(10, 59, 531, 151))
        self.lpis_info_twidget.setObjectName(_fromUtf8("lpis_info_twidget"))
        self.lpis_info_twidget.setColumnCount(12)
        self.lpis_info_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.lpis_info_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_info_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_info_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_info_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_info_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_info_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_info_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_info_twidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_info_twidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_info_twidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_info_twidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_info_twidget.setHorizontalHeaderItem(11, item)
        self.lpis_person_id_edit = QtGui.QLineEdit(self.tab_6)
        self.lpis_person_id_edit.setEnabled(False)
        self.lpis_person_id_edit.setGeometry(QtCore.QRect(10, 35, 120, 20))
        self.lpis_person_id_edit.setObjectName(_fromUtf8("lpis_person_id_edit"))
        self.label_32 = QtGui.QLabel(self.tab_6)
        self.label_32.setGeometry(QtCore.QRect(10, 209, 361, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.lpis_co_owner_twidget = QtGui.QTableWidget(self.tab_6)
        self.lpis_co_owner_twidget.setGeometry(QtCore.QRect(10, 229, 531, 161))
        self.lpis_co_owner_twidget.setObjectName(_fromUtf8("lpis_co_owner_twidget"))
        self.lpis_co_owner_twidget.setColumnCount(5)
        self.lpis_co_owner_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.lpis_co_owner_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_co_owner_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_co_owner_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_co_owner_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.lpis_co_owner_twidget.setHorizontalHeaderItem(4, item)
        self.parcel_tab_widget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.landuk_person_id_edit = QtGui.QLineEdit(self.tab_7)
        self.landuk_person_id_edit.setEnabled(False)
        self.landuk_person_id_edit.setGeometry(QtCore.QRect(10, 34, 120, 20))
        self.landuk_person_id_edit.setObjectName(_fromUtf8("landuk_person_id_edit"))
        self.landuk_old_parcel_id_edit = QtGui.QLineEdit(self.tab_7)
        self.landuk_old_parcel_id_edit.setEnabled(False)
        self.landuk_old_parcel_id_edit.setGeometry(QtCore.QRect(140, 34, 141, 20))
        self.landuk_old_parcel_id_edit.setObjectName(_fromUtf8("landuk_old_parcel_id_edit"))
        self.landuk_find_button = QtGui.QPushButton(self.tab_7)
        self.landuk_find_button.setEnabled(False)
        self.landuk_find_button.setGeometry(QtCore.QRect(296, 32, 75, 23))
        self.landuk_find_button.setObjectName(_fromUtf8("landuk_find_button"))
        self.landuk_search_chbox = QtGui.QCheckBox(self.tab_7)
        self.landuk_search_chbox.setGeometry(QtCore.QRect(9, 0, 311, 17))
        self.landuk_search_chbox.setObjectName(_fromUtf8("landuk_search_chbox"))
        self.label_11 = QtGui.QLabel(self.tab_7)
        self.label_11.setGeometry(QtCore.QRect(10, 17, 121, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_13 = QtGui.QLabel(self.tab_7)
        self.label_13.setGeometry(QtCore.QRect(140, 17, 231, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_7)
        self.tabWidget_3.setGeometry(QtCore.QRect(3, 194, 541, 180))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_10)
        self.groupBox_4.setGeometry(QtCore.QRect(5, 83, 360, 91))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 13, 161, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.contact_firstname_edit = QtGui.QLineEdit(self.groupBox_4)
        self.contact_firstname_edit.setGeometry(QtCore.QRect(10, 29, 160, 20))
        self.contact_firstname_edit.setReadOnly(True)
        self.contact_firstname_edit.setObjectName(_fromUtf8("contact_firstname_edit"))
        self.contact_lastname_edit = QtGui.QLineEdit(self.groupBox_4)
        self.contact_lastname_edit.setGeometry(QtCore.QRect(180, 29, 160, 20))
        self.contact_lastname_edit.setReadOnly(True)
        self.contact_lastname_edit.setObjectName(_fromUtf8("contact_lastname_edit"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(180, 13, 161, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.contact_position_edit = QtGui.QLineEdit(self.groupBox_4)
        self.contact_position_edit.setGeometry(QtCore.QRect(10, 66, 331, 20))
        self.contact_position_edit.setReadOnly(True)
        self.contact_position_edit.setObjectName(_fromUtf8("contact_position_edit"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(10, 50, 331, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.landuk_person_type_edit = QtGui.QLineEdit(self.tab_10)
        self.landuk_person_type_edit.setGeometry(QtCore.QRect(15, 19, 201, 20))
        self.landuk_person_type_edit.setReadOnly(True)
        self.landuk_person_type_edit.setObjectName(_fromUtf8("landuk_person_type_edit"))
        self.landuk_country_edit = QtGui.QLineEdit(self.tab_10)
        self.landuk_country_edit.setGeometry(QtCore.QRect(15, 59, 201, 20))
        self.landuk_country_edit.setReadOnly(True)
        self.landuk_country_edit.setObjectName(_fromUtf8("landuk_country_edit"))
        self.label_17 = QtGui.QLabel(self.tab_10)
        self.label_17.setGeometry(QtCore.QRect(16, 40, 161, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab_10)
        self.label_18.setGeometry(QtCore.QRect(16, 0, 161, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.tabWidget_3.addTab(self.tab_10, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.landuk_fee_edit = QtGui.QLineEdit(self.tab_12)
        self.landuk_fee_edit.setGeometry(QtCore.QRect(135, 67, 110, 20))
        self.landuk_fee_edit.setReadOnly(True)
        self.landuk_fee_edit.setObjectName(_fromUtf8("landuk_fee_edit"))
        self.landuk_area_edit = QtGui.QLineEdit(self.tab_12)
        self.landuk_area_edit.setGeometry(QtCore.QRect(20, 67, 110, 20))
        self.landuk_area_edit.setReadOnly(True)
        self.landuk_area_edit.setObjectName(_fromUtf8("landuk_area_edit"))
        self.landuk_parcel_id_edit = QtGui.QLineEdit(self.tab_12)
        self.landuk_parcel_id_edit.setGeometry(QtCore.QRect(20, 24, 151, 20))
        self.landuk_parcel_id_edit.setReadOnly(True)
        self.landuk_parcel_id_edit.setObjectName(_fromUtf8("landuk_parcel_id_edit"))
        self.landuk_landuse_edit = QtGui.QLineEdit(self.tab_12)
        self.landuk_landuse_edit.setGeometry(QtCore.QRect(180, 24, 181, 20))
        self.landuk_landuse_edit.setReadOnly(True)
        self.landuk_landuse_edit.setObjectName(_fromUtf8("landuk_landuse_edit"))
        self.landuk_certificate_edit = QtGui.QLineEdit(self.tab_12)
        self.landuk_certificate_edit.setGeometry(QtCore.QRect(251, 112, 110, 20))
        self.landuk_certificate_edit.setReadOnly(True)
        self.landuk_certificate_edit.setObjectName(_fromUtf8("landuk_certificate_edit"))
        self.landuk_right_type_edit = QtGui.QLineEdit(self.tab_12)
        self.landuk_right_type_edit.setGeometry(QtCore.QRect(135, 154, 110, 20))
        self.landuk_right_type_edit.setReadOnly(True)
        self.landuk_right_type_edit.setObjectName(_fromUtf8("landuk_right_type_edit"))
        self.landuk_deicsion_no_edit = QtGui.QLineEdit(self.tab_12)
        self.landuk_deicsion_no_edit.setGeometry(QtCore.QRect(20, 112, 110, 20))
        self.landuk_deicsion_no_edit.setReadOnly(True)
        self.landuk_deicsion_no_edit.setObjectName(_fromUtf8("landuk_deicsion_no_edit"))
        self.landuk_decision_date = QtGui.QDateEdit(self.tab_12)
        self.landuk_decision_date.setGeometry(QtCore.QRect(136, 112, 110, 20))
        self.landuk_decision_date.setObjectName(_fromUtf8("landuk_decision_date"))
        self.landuk_unit_price_edit = QtGui.QLineEdit(self.tab_12)
        self.landuk_unit_price_edit.setGeometry(QtCore.QRect(251, 67, 110, 20))
        self.landuk_unit_price_edit.setReadOnly(True)
        self.landuk_unit_price_edit.setObjectName(_fromUtf8("landuk_unit_price_edit"))
        self.label_20 = QtGui.QLabel(self.tab_12)
        self.label_20.setGeometry(QtCore.QRect(20, 5, 141, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab_12)
        self.label_21.setGeometry(QtCore.QRect(180, 5, 181, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab_12)
        self.label_22.setGeometry(QtCore.QRect(20, 48, 101, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.tab_12)
        self.label_23.setGeometry(QtCore.QRect(135, 48, 81, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_12)
        self.label_24.setGeometry(QtCore.QRect(253, 48, 110, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_12)
        self.label_25.setGeometry(QtCore.QRect(21, 92, 101, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_12)
        self.label_26.setGeometry(QtCore.QRect(137, 92, 101, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.tab_12)
        self.label_27.setGeometry(QtCore.QRect(250, 92, 101, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_12)
        self.label_28.setGeometry(QtCore.QRect(251, 135, 101, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.tab_12)
        self.label_29.setGeometry(QtCore.QRect(135, 135, 101, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.is_mortgage_edit = QtGui.QLineEdit(self.tab_12)
        self.is_mortgage_edit.setGeometry(QtCore.QRect(251, 154, 110, 20))
        self.is_mortgage_edit.setReadOnly(True)
        self.is_mortgage_edit.setObjectName(_fromUtf8("is_mortgage_edit"))
        self.landuk_duration_edit = QtGui.QLineEdit(self.tab_12)
        self.landuk_duration_edit.setGeometry(QtCore.QRect(20, 154, 110, 20))
        self.landuk_duration_edit.setReadOnly(True)
        self.landuk_duration_edit.setObjectName(_fromUtf8("landuk_duration_edit"))
        self.label_30 = QtGui.QLabel(self.tab_12)
        self.label_30.setGeometry(QtCore.QRect(20, 135, 110, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.tabWidget_3.addTab(self.tab_12, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.landuk_mortgage_twidget = QtGui.QTableWidget(self.tab_11)
        self.landuk_mortgage_twidget.setGeometry(QtCore.QRect(5, 0, 531, 150))
        self.landuk_mortgage_twidget.setObjectName(_fromUtf8("landuk_mortgage_twidget"))
        self.landuk_mortgage_twidget.setColumnCount(7)
        self.landuk_mortgage_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.landuk_mortgage_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.landuk_mortgage_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.landuk_mortgage_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.landuk_mortgage_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.landuk_mortgage_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.landuk_mortgage_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.landuk_mortgage_twidget.setHorizontalHeaderItem(6, item)
        self.tabWidget_3.addTab(self.tab_11, _fromUtf8(""))
        self.landuk_info_twidget = QtGui.QTableWidget(self.tab_7)
        self.landuk_info_twidget.setGeometry(QtCore.QRect(10, 60, 531, 135))
        self.landuk_info_twidget.setObjectName(_fromUtf8("landuk_info_twidget"))
        self.landuk_info_twidget.setColumnCount(6)
        self.landuk_info_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.landuk_info_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.landuk_info_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.landuk_info_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.landuk_info_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.landuk_info_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.landuk_info_twidget.setHorizontalHeaderItem(5, item)
        self.parcel_tab_widget.addTab(self.tab_7, _fromUtf8(""))
        self.right_holder_twidget = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.right_holder_twidget.setGeometry(QtCore.QRect(6, 103, 551, 91))
        self.right_holder_twidget.setObjectName(_fromUtf8("right_holder_twidget"))
        self.right_holder_twidget.setColumnCount(10)
        self.right_holder_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.right_holder_twidget.setHorizontalHeaderItem(9, item)
        self.finish_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.finish_button.setGeometry(QtCore.QRect(10, 680, 75, 28))
        self.finish_button.setStyleSheet(_fromUtf8("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 250, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #34a853; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 174)\n"
"}"))
        self.finish_button.setObjectName(_fromUtf8("finish_button"))
        self.save_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.save_button.setGeometry(QtCore.QRect(260, 680, 84, 28))
        self.save_button.setStyleSheet(_fromUtf8("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 250, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #00b3ca; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 174)\n"
"}"))
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.clear_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.clear_button.setGeometry(QtCore.QRect(480, 72, 75, 23))
        self.clear_button.setAutoDefault(False)
        self.clear_button.setDefault(False)
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.layer_view_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.layer_view_button.setGeometry(QtCore.QRect(105, 680, 131, 28))
        self.layer_view_button.setStyleSheet(_fromUtf8("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 250, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #d2b29b; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 174)\n"
"}"))
        self.layer_view_button.setObjectName(_fromUtf8("layer_view_button"))
        self.error_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.error_label.setGeometry(QtCore.QRect(20, 715, 361, 17))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.find_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.find_button.setEnabled(True)
        self.find_button.setGeometry(QtCore.QRect(480, 19, 75, 50))
        self.find_button.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/zoom.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.find_button.setIcon(icon)
        self.find_button.setAutoDefault(False)
        self.find_button.setDefault(True)
        self.find_button.setObjectName(_fromUtf8("find_button"))
        self.find_tab = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.find_tab.setGeometry(QtCore.QRect(3, 0, 471, 101))
        self.find_tab.setAcceptDrops(False)
        self.find_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.find_tab.setObjectName(_fromUtf8("find_tab"))
        self.tab_17 = QtGui.QWidget()
        self.tab_17.setObjectName(_fromUtf8("tab_17"))
        self.label_33 = QtGui.QLabel(self.tab_17)
        self.label_33.setGeometry(QtCore.QRect(10, 35, 121, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.find_parcel_id_edit = QtGui.QLineEdit(self.tab_17)
        self.find_parcel_id_edit.setEnabled(False)
        self.find_parcel_id_edit.setGeometry(QtCore.QRect(10, 15, 200, 20))
        self.find_parcel_id_edit.setObjectName(_fromUtf8("find_parcel_id_edit"))
        self.label_2 = QtGui.QLabel(self.tab_17)
        self.label_2.setGeometry(QtCore.QRect(240, -3, 136, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.find_person_id_edit = QtGui.QLineEdit(self.tab_17)
        self.find_person_id_edit.setEnabled(False)
        self.find_person_id_edit.setGeometry(QtCore.QRect(240, 14, 200, 20))
        self.find_person_id_edit.setObjectName(_fromUtf8("find_person_id_edit"))
        self.label_34 = QtGui.QLabel(self.tab_17)
        self.label_34.setGeometry(QtCore.QRect(240, 33, 136, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.find_lastname_edit = QtGui.QLineEdit(self.tab_17)
        self.find_lastname_edit.setEnabled(False)
        self.find_lastname_edit.setGeometry(QtCore.QRect(240, 50, 200, 20))
        self.find_lastname_edit.setObjectName(_fromUtf8("find_lastname_edit"))
        self.label = QtGui.QLabel(self.tab_17)
        self.label.setGeometry(QtCore.QRect(10, -1, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.find_firstname_edit = QtGui.QLineEdit(self.tab_17)
        self.find_firstname_edit.setEnabled(False)
        self.find_firstname_edit.setGeometry(QtCore.QRect(10, 51, 200, 20))
        self.find_firstname_edit.setObjectName(_fromUtf8("find_firstname_edit"))
        self.find_tab.addTab(self.tab_17, _fromUtf8(""))
        self.tab_18 = QtGui.QWidget()
        self.tab_18.setObjectName(_fromUtf8("tab_18"))
        self.find_x_coordinate_edit = QtGui.QLineEdit(self.tab_18)
        self.find_x_coordinate_edit.setEnabled(False)
        self.find_x_coordinate_edit.setGeometry(QtCore.QRect(10, 42, 110, 20))
        self.find_x_coordinate_edit.setObjectName(_fromUtf8("find_x_coordinate_edit"))
        self.label_39 = QtGui.QLabel(self.tab_18)
        self.label_39.setGeometry(QtCore.QRect(130, 25, 110, 16))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.find_y_coordinate_edit = QtGui.QLineEdit(self.tab_18)
        self.find_y_coordinate_edit.setEnabled(False)
        self.find_y_coordinate_edit.setGeometry(QtCore.QRect(130, 42, 110, 20))
        self.find_y_coordinate_edit.setObjectName(_fromUtf8("find_y_coordinate_edit"))
        self.label_40 = QtGui.QLabel(self.tab_18)
        self.label_40.setGeometry(QtCore.QRect(10, 26, 110, 16))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.point_scale_sbox = QtGui.QSpinBox(self.tab_18)
        self.point_scale_sbox.setGeometry(QtCore.QRect(250, 42, 45, 22))
        self.point_scale_sbox.setObjectName(_fromUtf8("point_scale_sbox"))
        self.label_41 = QtGui.QLabel(self.tab_18)
        self.label_41.setGeometry(QtCore.QRect(250, 25, 34, 16))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.coordinate_chbox = QtGui.QCheckBox(self.tab_18)
        self.coordinate_chbox.setGeometry(QtCore.QRect(20, 7, 271, 17))
        self.coordinate_chbox.setObjectName(_fromUtf8("coordinate_chbox"))
        self.find_tab.addTab(self.tab_18, _fromUtf8(""))
        self.tab_19 = QtGui.QWidget()
        self.tab_19.setObjectName(_fromUtf8("tab_19"))
        self.label_55 = QtGui.QLabel(self.tab_19)
        self.label_55.setGeometry(QtCore.QRect(148, 2, 136, 16))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_56 = QtGui.QLabel(self.tab_19)
        self.label_56.setGeometry(QtCore.QRect(8, 3, 121, 16))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.find_street_name_edit = QtGui.QLineEdit(self.tab_19)
        self.find_street_name_edit.setEnabled(False)
        self.find_street_name_edit.setGeometry(QtCore.QRect(8, 19, 135, 20))
        self.find_street_name_edit.setObjectName(_fromUtf8("find_street_name_edit"))
        self.find_khashaa_number_edit = QtGui.QLineEdit(self.tab_19)
        self.find_khashaa_number_edit.setEnabled(False)
        self.find_khashaa_number_edit.setGeometry(QtCore.QRect(148, 19, 135, 20))
        self.find_khashaa_number_edit.setObjectName(_fromUtf8("find_khashaa_number_edit"))
        self.find_tab.addTab(self.tab_19, _fromUtf8(""))
        self.edit_status_cbox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.edit_status_cbox.setGeometry(QtCore.QRect(370, 687, 161, 22))
        self.edit_status_cbox.setObjectName(_fromUtf8("edit_status_cbox"))
        self.label_38 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_38.setGeometry(QtCore.QRect(370, 670, 161, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.record_gbox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.record_gbox.setGeometry(QtCore.QRect(11, 562, 541, 71))
        self.record_gbox.setObjectName(_fromUtf8("record_gbox"))
        self.record_full = QtGui.QLabel(self.record_gbox)
        self.record_full.setGeometry(QtCore.QRect(260, 16, 121, 20))
        self.record_full.setObjectName(_fromUtf8("record_full"))
        self.record_cert_edit = QtGui.QLineEdit(self.record_gbox)
        self.record_cert_edit.setEnabled(False)
        self.record_cert_edit.setGeometry(QtCore.QRect(10, 36, 111, 20))
        self.record_cert_edit.setObjectName(_fromUtf8("record_cert_edit"))
        self.own_date = QtGui.QDateEdit(self.record_gbox)
        self.own_date.setEnabled(False)
        self.own_date.setGeometry(QtCore.QRect(140, 36, 111, 20))
        self.own_date.setObjectName(_fromUtf8("own_date"))
        self.record_full_edit = QtGui.QLineEdit(self.record_gbox)
        self.record_full_edit.setEnabled(False)
        self.record_full_edit.setGeometry(QtCore.QRect(260, 36, 131, 20))
        self.record_full_edit.setObjectName(_fromUtf8("record_full_edit"))
        self.record_certificate_chbox = QtGui.QCheckBox(self.record_gbox)
        self.record_certificate_chbox.setGeometry(QtCore.QRect(10, 16, 111, 20))
        self.record_certificate_chbox.setObjectName(_fromUtf8("record_certificate_chbox"))
        self.own_date_chbox = QtGui.QCheckBox(self.record_gbox)
        self.own_date_chbox.setGeometry(QtCore.QRect(140, 16, 110, 17))
        self.own_date_chbox.setObjectName(_fromUtf8("own_date_chbox"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        ParcelInfoDialog.setWidget(self.dockWidgetContents)

        self.retranslateUi(ParcelInfoDialog)
        self.parcel_tab_widget.setCurrentIndex(0)
        self.person_tabwidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(2)
        self.find_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ParcelInfoDialog)
        ParcelInfoDialog.setTabOrder(self.landuse_chbox, self.old_parcel_id_edit)
        ParcelInfoDialog.setTabOrder(self.old_parcel_id_edit, self.khashaa_edit)
        ParcelInfoDialog.setTabOrder(self.khashaa_edit, self.khashaa_chbox)
        ParcelInfoDialog.setTabOrder(self.khashaa_chbox, self.streetname_edit)
        ParcelInfoDialog.setTabOrder(self.streetname_edit, self.zoriulalt_edit)
        ParcelInfoDialog.setTabOrder(self.zoriulalt_edit, self.neighbourhood_chbox)
        ParcelInfoDialog.setTabOrder(self.neighbourhood_chbox, self.lastname_chbox)
        ParcelInfoDialog.setTabOrder(self.lastname_chbox, self.zoriulalt_chbox)
        ParcelInfoDialog.setTabOrder(self.zoriulalt_chbox, self.neighbourhood_edit)
        ParcelInfoDialog.setTabOrder(self.neighbourhood_edit, self.find_parcel_id_edit)
        ParcelInfoDialog.setTabOrder(self.find_parcel_id_edit, self.parcel_landuse_cbox)
        ParcelInfoDialog.setTabOrder(self.parcel_landuse_cbox, self.find_person_id_edit)
        ParcelInfoDialog.setTabOrder(self.find_person_id_edit, self.person_tabwidget)
        ParcelInfoDialog.setTabOrder(self.person_tabwidget, self.phone_edit)
        ParcelInfoDialog.setTabOrder(self.phone_edit, self.phone_chbox)
        ParcelInfoDialog.setTabOrder(self.phone_chbox, self.find_firstname_edit)
        ParcelInfoDialog.setTabOrder(self.find_firstname_edit, self.find_lastname_edit)
        ParcelInfoDialog.setTabOrder(self.find_lastname_edit, self.clear_button)
        ParcelInfoDialog.setTabOrder(self.clear_button, self.find_button)
        ParcelInfoDialog.setTabOrder(self.find_button, self.middlename_chbox)
        ParcelInfoDialog.setTabOrder(self.middlename_chbox, self.name_edit)
        ParcelInfoDialog.setTabOrder(self.name_edit, self.person_type_chbox)
        ParcelInfoDialog.setTabOrder(self.person_type_chbox, self.first_name_edit)
        ParcelInfoDialog.setTabOrder(self.first_name_edit, self.personal_id_edit)
        ParcelInfoDialog.setTabOrder(self.personal_id_edit, self.date_of_birth_date)
        ParcelInfoDialog.setTabOrder(self.date_of_birth_date, self.middle_name_edit)
        ParcelInfoDialog.setTabOrder(self.middle_name_edit, self.person_id_chbox)
        ParcelInfoDialog.setTabOrder(self.person_id_chbox, self.aimag_cbox)
        ParcelInfoDialog.setTabOrder(self.aimag_cbox, self.bag_cbox)
        ParcelInfoDialog.setTabOrder(self.bag_cbox, self.soum_cbox)
        ParcelInfoDialog.setTabOrder(self.soum_cbox, self.person_khashaa_edit)
        ParcelInfoDialog.setTabOrder(self.person_khashaa_edit, self.person_street_name_edit)
        ParcelInfoDialog.setTabOrder(self.person_street_name_edit, self.load_docs_button)
        ParcelInfoDialog.setTabOrder(self.load_docs_button, self.documet_cbox)
        ParcelInfoDialog.setTabOrder(self.documet_cbox, self.doc_twidget)
        ParcelInfoDialog.setTabOrder(self.doc_twidget, self.doc_info_twidget)
        ParcelInfoDialog.setTabOrder(self.doc_info_twidget, self.ftp_connect_button)
        ParcelInfoDialog.setTabOrder(self.ftp_connect_button, self.is_ftp_edit_chbox)
        ParcelInfoDialog.setTabOrder(self.is_ftp_edit_chbox, self.ftp_host_edit)
        ParcelInfoDialog.setTabOrder(self.ftp_host_edit, self.fee_view_button)
        ParcelInfoDialog.setTabOrder(self.fee_view_button, self.fee_info_twidget)
        ParcelInfoDialog.setTabOrder(self.fee_info_twidget, self.fee_find_button)
        ParcelInfoDialog.setTabOrder(self.fee_find_button, self.fee_person_id_edit)
        ParcelInfoDialog.setTabOrder(self.fee_person_id_edit, self.fee_old_parcel_id_edit)
        ParcelInfoDialog.setTabOrder(self.fee_old_parcel_id_edit, self.checkBox_5)
        ParcelInfoDialog.setTabOrder(self.checkBox_5, self.lpis_search_chbox)
        ParcelInfoDialog.setTabOrder(self.lpis_search_chbox, self.lpis_find_button)
        ParcelInfoDialog.setTabOrder(self.lpis_find_button, self.lpis_old_parcel_id_edit)
        ParcelInfoDialog.setTabOrder(self.lpis_old_parcel_id_edit, self.lpis_info_twidget)
        ParcelInfoDialog.setTabOrder(self.lpis_info_twidget, self.lpis_person_id_edit)
        ParcelInfoDialog.setTabOrder(self.lpis_person_id_edit, self.lpis_co_owner_twidget)
        ParcelInfoDialog.setTabOrder(self.lpis_co_owner_twidget, self.landuk_person_id_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_person_id_edit, self.landuk_old_parcel_id_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_old_parcel_id_edit, self.landuk_find_button)
        ParcelInfoDialog.setTabOrder(self.landuk_find_button, self.landuk_search_chbox)
        ParcelInfoDialog.setTabOrder(self.landuk_search_chbox, self.tabWidget_3)
        ParcelInfoDialog.setTabOrder(self.tabWidget_3, self.contact_firstname_edit)
        ParcelInfoDialog.setTabOrder(self.contact_firstname_edit, self.contact_lastname_edit)
        ParcelInfoDialog.setTabOrder(self.contact_lastname_edit, self.contact_position_edit)
        ParcelInfoDialog.setTabOrder(self.contact_position_edit, self.landuk_person_type_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_person_type_edit, self.landuk_country_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_country_edit, self.landuk_fee_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_fee_edit, self.landuk_area_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_area_edit, self.landuk_parcel_id_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_parcel_id_edit, self.landuk_landuse_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_landuse_edit, self.landuk_certificate_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_certificate_edit, self.landuk_right_type_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_right_type_edit, self.landuk_deicsion_no_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_deicsion_no_edit, self.landuk_decision_date)
        ParcelInfoDialog.setTabOrder(self.landuk_decision_date, self.landuk_unit_price_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_unit_price_edit, self.is_mortgage_edit)
        ParcelInfoDialog.setTabOrder(self.is_mortgage_edit, self.landuk_duration_edit)
        ParcelInfoDialog.setTabOrder(self.landuk_duration_edit, self.landuk_mortgage_twidget)
        ParcelInfoDialog.setTabOrder(self.landuk_mortgage_twidget, self.landuk_info_twidget)
        ParcelInfoDialog.setTabOrder(self.landuk_info_twidget, self.right_holder_twidget)
        ParcelInfoDialog.setTabOrder(self.right_holder_twidget, self.finish_button)
        ParcelInfoDialog.setTabOrder(self.finish_button, self.save_button)
        ParcelInfoDialog.setTabOrder(self.save_button, self.layer_view_button)
        ParcelInfoDialog.setTabOrder(self.layer_view_button, self.find_person_id_edit)
        ParcelInfoDialog.setTabOrder(self.find_person_id_edit, self.find_parcel_id_edit)
        ParcelInfoDialog.setTabOrder(self.find_parcel_id_edit, self.street_chbox)
        ParcelInfoDialog.setTabOrder(self.street_chbox, self.person_type_cbox)
        ParcelInfoDialog.setTabOrder(self.person_type_cbox, self.find_firstname_edit)
        ParcelInfoDialog.setTabOrder(self.find_firstname_edit, self.firstname_chbox)
        ParcelInfoDialog.setTabOrder(self.firstname_chbox, self.parcel_tab_widget)
        ParcelInfoDialog.setTabOrder(self.parcel_tab_widget, self.scrollArea)
        ParcelInfoDialog.setTabOrder(self.scrollArea, self.find_lastname_edit)
        ParcelInfoDialog.setTabOrder(self.find_lastname_edit, self.parcel_id_edit)
        ParcelInfoDialog.setTabOrder(self.parcel_id_edit, self.find_button)
        ParcelInfoDialog.setTabOrder(self.find_button, self.find_tab)
        ParcelInfoDialog.setTabOrder(self.find_tab, self.find_x_coordinate_edit)
        ParcelInfoDialog.setTabOrder(self.find_x_coordinate_edit, self.find_y_coordinate_edit)
        ParcelInfoDialog.setTabOrder(self.find_y_coordinate_edit, self.point_scale_sbox)

    def retranslateUi(self, ParcelInfoDialog):
        ParcelInfoDialog.setWindowTitle(_translate("ParcelInfoDialog", "UB Parcel Information", None))
        self.parcel_gbox.setTitle(_translate("ParcelInfoDialog", "Parcel Info", None))
        self.label_3.setText(_translate("ParcelInfoDialog", "Parcel ID", None))
        self.khashaa_chbox.setText(_translate("ParcelInfoDialog", "Khashaa", None))
        self.street_chbox.setText(_translate("ParcelInfoDialog", "Street name", None))
        self.label_5.setText(_translate("ParcelInfoDialog", "Old Parcel ID", None))
        self.zoriulalt_chbox.setText(_translate("ParcelInfoDialog", "gaid", None))
        self.neighbourhood_chbox.setText(_translate("ParcelInfoDialog", "Address neighbourhood change", None))
        self.landuse_chbox.setText(_translate("ParcelInfoDialog", "Landuse type change", None))
        self.phone_chbox.setText(_translate("ParcelInfoDialog", "Phone number", None))
        self.firstname_chbox.setText(_translate("ParcelInfoDialog", "First name/Contact firstname", None))
        self.lastname_chbox.setText(_translate("ParcelInfoDialog", "Last name/Company Name", None))
        self.middlename_chbox.setText(_translate("ParcelInfoDialog", "Middle name/Contact Person name", None))
        self.person_type_chbox.setText(_translate("ParcelInfoDialog", "Person type change", None))
        self.person_id_chbox.setText(_translate("ParcelInfoDialog", "Person ID", None))
        self.person_tabwidget.setTabText(self.person_tabwidget.indexOf(self.tab_8), _translate("ParcelInfoDialog", "Person", None))
        self.label_6.setText(_translate("ParcelInfoDialog", "Aimag / Duureg", None))
        self.label_7.setText(_translate("ParcelInfoDialog", "Soum", None))
        self.label_8.setText(_translate("ParcelInfoDialog", "Bag / Khoroo", None))
        self.label_12.setText(_translate("ParcelInfoDialog", "Street Name", None))
        self.label_19.setText(_translate("ParcelInfoDialog", "Khashaa", None))
        self.label_35.setText(_translate("ParcelInfoDialog", "Building Number", None))
        self.label_36.setText(_translate("ParcelInfoDialog", "Apartment Number", None))
        self.person_tabwidget.setTabText(self.person_tabwidget.indexOf(self.tab_9), _translate("ParcelInfoDialog", "Person Address", None))
        self.groupBox_5.setTitle(_translate("ParcelInfoDialog", "Decision", None))
        self.decision_date_chbox.setText(_translate("ParcelInfoDialog", "Decision Date", None))
        self.decision_full_chbox.setText(_translate("ParcelInfoDialog", "Decision full number", None))
        self.level_chbox.setText(_translate("ParcelInfoDialog", "Decision level", None))
        self.right_type_chbox.setText(_translate("ParcelInfoDialog", "Right type", None))
        self.decision_no_chbox.setText(_translate("ParcelInfoDialog", "Decision No", None))
        self.label_42.setText(_translate("ParcelInfoDialog", "Application Type", None))
        self.contract_gbox.setTitle(_translate("ParcelInfoDialog", "Possess Contract", None))
        self.contract_date_chbox.setText(_translate("ParcelInfoDialog", "Create Date", None))
        self.contract_full_chbox.setText(_translate("ParcelInfoDialog", "Contract full number", None))
        self.end_date_chbox.setText(_translate("ParcelInfoDialog", "End Date", None))
        self.duration_chbox.setText(_translate("ParcelInfoDialog", "Duration", None))
        self.contract_certificate_chbox.setText(_translate("ParcelInfoDialog", "Certificate", None))
        self.contract_status_chbox.setText(_translate("ParcelInfoDialog", "Contact status", None))
        self.parcel_tab_widget.setTabText(self.parcel_tab_widget.indexOf(self.parcel_person_tab), _translate("ParcelInfoDialog", "Parcel & Person", None))
        self.load_docs_button.setText(_translate("ParcelInfoDialog", "Load Documents", None))
        item = self.doc_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ParcelInfoDialog", "Name", None))
        item = self.doc_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ParcelInfoDialog", "Description", None))
        item = self.doc_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ParcelInfoDialog", "View", None))
        item = self.doc_info_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ParcelInfoDialog", "NewPID", None))
        item = self.doc_info_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ParcelInfoDialog", "DecisionLevel", None))
        item = self.doc_info_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ParcelInfoDialog", "DecisionNo", None))
        item = self.doc_info_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ParcelInfoDialog", "DecisionDate", None))
        item = self.doc_info_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ParcelInfoDialog", "Firstname", None))
        item = self.doc_info_twidget.horizontalHeaderItem(5)
        item.setText(_translate("ParcelInfoDialog", "Lastname", None))
        item = self.doc_info_twidget.horizontalHeaderItem(6)
        item.setText(_translate("ParcelInfoDialog", "PersonID", None))
        item = self.doc_info_twidget.horizontalHeaderItem(7)
        item.setText(_translate("ParcelInfoDialog", "Address", None))
        self.ftp_connect_button.setText(_translate("ParcelInfoDialog", "Connect", None))
        self.is_ftp_edit_chbox.setText(_translate("ParcelInfoDialog", "Edit doc host", None))
        self.parcel_tab_widget.setTabText(self.parcel_tab_widget.indexOf(self.document_tab), _translate("ParcelInfoDialog", "Document", None))
        self.fee_view_button.setText(_translate("ParcelInfoDialog", "Fee View", None))
        item = self.fee_info_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ParcelInfoDialog", "PersonID", None))
        item = self.fee_info_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ParcelInfoDialog", "Name", None))
        item = self.fee_info_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ParcelInfoDialog", "phone", None))
        item = self.fee_info_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ParcelInfoDialog", "City/Aimag", None))
        item = self.fee_info_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ParcelInfoDialog", "District/Soum", None))
        item = self.fee_info_twidget.horizontalHeaderItem(5)
        item.setText(_translate("ParcelInfoDialog", "Bag/Khoroo", None))
        item = self.fee_info_twidget.horizontalHeaderItem(6)
        item.setText(_translate("ParcelInfoDialog", "Street", None))
        item = self.fee_info_twidget.horizontalHeaderItem(7)
        item.setText(_translate("ParcelInfoDialog", "Khashaa", None))
        self.fee_find_button.setText(_translate("ParcelInfoDialog", "Find", None))
        self.checkBox_5.setText(_translate("ParcelInfoDialog", "If find in all data for fee", None))
        self.label_9.setText(_translate("ParcelInfoDialog", "Person ID", None))
        self.label_10.setText(_translate("ParcelInfoDialog", "Old Parcel ID", None))
        self.parcel_tab_widget.setTabText(self.parcel_tab_widget.indexOf(self.tab_5), _translate("ParcelInfoDialog", "Fee", None))
        self.lpis_search_chbox.setText(_translate("ParcelInfoDialog", "If find in all data for LPIS", None))
        self.lpis_find_button.setText(_translate("ParcelInfoDialog", "Find", None))
        self.label_31.setText(_translate("ParcelInfoDialog", "Old Parcel ID", None))
        self.label_48.setText(_translate("ParcelInfoDialog", "Person ID", None))
        item = self.lpis_info_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ParcelInfoDialog", "PersonID", None))
        item = self.lpis_info_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ParcelInfoDialog", "Firstname", None))
        item = self.lpis_info_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ParcelInfoDialog", "Lastname", None))
        item = self.lpis_info_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ParcelInfoDialog", "Phone", None))
        item = self.lpis_info_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ParcelInfoDialog", "Note", None))
        item = self.lpis_info_twidget.horizontalHeaderItem(5)
        item.setText(_translate("ParcelInfoDialog", "Address", None))
        item = self.lpis_info_twidget.horizontalHeaderItem(6)
        item.setText(_translate("ParcelInfoDialog", "PID", None))
        item = self.lpis_info_twidget.horizontalHeaderItem(7)
        item.setText(_translate("ParcelInfoDialog", "Decision Area", None))
        item = self.lpis_info_twidget.horizontalHeaderItem(8)
        item.setText(_translate("ParcelInfoDialog", "Land Cost", None))
        item = self.lpis_info_twidget.horizontalHeaderItem(9)
        item.setText(_translate("ParcelInfoDialog", "Decision No", None))
        item = self.lpis_info_twidget.horizontalHeaderItem(10)
        item.setText(_translate("ParcelInfoDialog", "Cert ID", None))
        item = self.lpis_info_twidget.horizontalHeaderItem(11)
        item.setText(_translate("ParcelInfoDialog", "Status", None))
        self.label_32.setText(_translate("ParcelInfoDialog", "Co Owners", None))
        item = self.lpis_co_owner_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ParcelInfoDialog", "Register", None))
        item = self.lpis_co_owner_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ParcelInfoDialog", "Ovog", None))
        item = self.lpis_co_owner_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ParcelInfoDialog", "Ner", None))
        item = self.lpis_co_owner_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ParcelInfoDialog", "Hen", None))
        item = self.lpis_co_owner_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ParcelInfoDialog", "Zahid", None))
        self.parcel_tab_widget.setTabText(self.parcel_tab_widget.indexOf(self.tab_6), _translate("ParcelInfoDialog", "LPIS", None))
        self.landuk_find_button.setText(_translate("ParcelInfoDialog", "Find", None))
        self.landuk_search_chbox.setText(_translate("ParcelInfoDialog", "If find in all data for LANDUK", None))
        self.label_11.setText(_translate("ParcelInfoDialog", "Person ID", None))
        self.label_13.setText(_translate("ParcelInfoDialog", "Old Parcel ID", None))
        self.groupBox_4.setTitle(_translate("ParcelInfoDialog", "Contact Person", None))
        self.label_14.setText(_translate("ParcelInfoDialog", "Contact Firstname", None))
        self.label_15.setText(_translate("ParcelInfoDialog", "Contact Lastname", None))
        self.label_16.setText(_translate("ParcelInfoDialog", "Contact Position", None))
        self.label_17.setText(_translate("ParcelInfoDialog", "Country", None))
        self.label_18.setText(_translate("ParcelInfoDialog", "Person Type", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("ParcelInfoDialog", "LandUK Info", None))
        self.label_20.setText(_translate("ParcelInfoDialog", "Parcel ID", None))
        self.label_21.setText(_translate("ParcelInfoDialog", "Landuse", None))
        self.label_22.setText(_translate("ParcelInfoDialog", "Area /m2/", None))
        self.label_23.setText(_translate("ParcelInfoDialog", "Fee", None))
        self.label_24.setText(_translate("ParcelInfoDialog", "Unit Price", None))
        self.label_25.setText(_translate("ParcelInfoDialog", "Decision No", None))
        self.label_26.setText(_translate("ParcelInfoDialog", "Decision Date", None))
        self.label_27.setText(_translate("ParcelInfoDialog", "Certificate No", None))
        self.label_28.setText(_translate("ParcelInfoDialog", "Is mortgage", None))
        self.label_29.setText(_translate("ParcelInfoDialog", "Right type", None))
        self.label_30.setText(_translate("ParcelInfoDialog", "Duration", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), _translate("ParcelInfoDialog", "Parcel Info", None))
        item = self.landuk_mortgage_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ParcelInfoDialog", "Person name", None))
        item = self.landuk_mortgage_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ParcelInfoDialog", "Bank name", None))
        item = self.landuk_mortgage_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ParcelInfoDialog", "Rent Contract No", None))
        item = self.landuk_mortgage_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ParcelInfoDialog", "Mortgate Contract No", None))
        item = self.landuk_mortgage_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ParcelInfoDialog", "Mortgege Date", None))
        item = self.landuk_mortgage_twidget.horizontalHeaderItem(5)
        item.setText(_translate("ParcelInfoDialog", "Price", None))
        item = self.landuk_mortgage_twidget.horizontalHeaderItem(6)
        item.setText(_translate("ParcelInfoDialog", "Is Mortgage", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("ParcelInfoDialog", "Mortgage", None))
        item = self.landuk_info_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ParcelInfoDialog", "PersonID", None))
        item = self.landuk_info_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ParcelInfoDialog", "Middlename", None))
        item = self.landuk_info_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ParcelInfoDialog", "Firstname", None))
        item = self.landuk_info_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ParcelInfoDialog", "Lastname", None))
        item = self.landuk_info_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ParcelInfoDialog", "Address", None))
        item = self.landuk_info_twidget.horizontalHeaderItem(5)
        item.setText(_translate("ParcelInfoDialog", "phone", None))
        self.parcel_tab_widget.setTabText(self.parcel_tab_widget.indexOf(self.tab_7), _translate("ParcelInfoDialog", "LandUK", None))
        item = self.right_holder_twidget.horizontalHeaderItem(0)
        item.setText(_translate("ParcelInfoDialog", "Rigth Type", None))
        item = self.right_holder_twidget.horizontalHeaderItem(1)
        item.setText(_translate("ParcelInfoDialog", "Person / Company ID", None))
        item = self.right_holder_twidget.horizontalHeaderItem(2)
        item.setText(_translate("ParcelInfoDialog", "Person / Company Name", None))
        item = self.right_holder_twidget.horizontalHeaderItem(3)
        item.setText(_translate("ParcelInfoDialog", "First Name", None))
        item = self.right_holder_twidget.horizontalHeaderItem(4)
        item.setText(_translate("ParcelInfoDialog", "Old Parcel ID", None))
        item = self.right_holder_twidget.horizontalHeaderItem(5)
        item.setText(_translate("ParcelInfoDialog", "Parcel ID", None))
        item = self.right_holder_twidget.horizontalHeaderItem(6)
        item.setText(_translate("ParcelInfoDialog", "Decision No", None))
        item = self.right_holder_twidget.horizontalHeaderItem(7)
        item.setText(_translate("ParcelInfoDialog", "Decision Date", None))
        item = self.right_holder_twidget.horizontalHeaderItem(8)
        item.setText(_translate("ParcelInfoDialog", "Contract No", None))
        item = self.right_holder_twidget.horizontalHeaderItem(9)
        item.setText(_translate("ParcelInfoDialog", "Contract Date", None))
        self.finish_button.setText(_translate("ParcelInfoDialog", "Finish", None))
        self.save_button.setText(_translate("ParcelInfoDialog", "Save", None))
        self.clear_button.setText(_translate("ParcelInfoDialog", "New", None))
        self.layer_view_button.setText(_translate("ParcelInfoDialog", "Layer View", None))
        self.find_button.setText(_translate("ParcelInfoDialog", "Find", None))
        self.label_33.setText(_translate("ParcelInfoDialog", "Firstname", None))
        self.label_2.setText(_translate("ParcelInfoDialog", "Person ID", None))
        self.label_34.setText(_translate("ParcelInfoDialog", "Lastname", None))
        self.label.setText(_translate("ParcelInfoDialog", "Parcel ID", None))
        self.find_tab.setTabText(self.find_tab.indexOf(self.tab_17), _translate("ParcelInfoDialog", "Find", None))
        self.label_39.setText(_translate("ParcelInfoDialog", "Y coordinate", None))
        self.label_40.setText(_translate("ParcelInfoDialog", "X coordinate", None))
        self.label_41.setText(_translate("ParcelInfoDialog", "Scale", None))
        self.coordinate_chbox.setText(_translate("ParcelInfoDialog", "Point Coordinate System ITRF", None))
        self.find_tab.setTabText(self.find_tab.indexOf(self.tab_18), _translate("ParcelInfoDialog", "Find Coordinate", None))
        self.label_55.setText(_translate("ParcelInfoDialog", "Khashaa_number", None))
        self.label_56.setText(_translate("ParcelInfoDialog", "Street_name", None))
        self.find_tab.setTabText(self.find_tab.indexOf(self.tab_19), _translate("ParcelInfoDialog", "find_address", None))
        self.label_38.setText(_translate("ParcelInfoDialog", "Edit Status", None))
        self.record_gbox.setTitle(_translate("ParcelInfoDialog", "Ownership", None))
        self.record_full.setText(_translate("ParcelInfoDialog", "Record full number", None))
        self.record_certificate_chbox.setText(_translate("ParcelInfoDialog", "Certificate", None))
        self.own_date_chbox.setText(_translate("ParcelInfoDialog", "Owner Date", None))

import resources_rc
