# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SParcelPersonDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SParcelPersonDialog(object):
    def setupUi(self, SParcelPersonDialog):
        SParcelPersonDialog.setObjectName(_fromUtf8("SParcelPersonDialog"))
        SParcelPersonDialog.resize(756, 441)
        self.search_person_id_edit = QtGui.QLineEdit(SParcelPersonDialog)
        self.search_person_id_edit.setGeometry(QtCore.QRect(40, 30, 131, 20))
        self.search_person_id_edit.setObjectName(_fromUtf8("search_person_id_edit"))
        self.label = QtGui.QLabel(SParcelPersonDialog)
        self.label.setGeometry(QtCore.QRect(40, 10, 131, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.result_person_twidget = QtGui.QTableWidget(SParcelPersonDialog)
        self.result_person_twidget.setGeometry(QtCore.QRect(40, 80, 341, 131))
        self.result_person_twidget.setObjectName(_fromUtf8("result_person_twidget"))
        self.result_person_twidget.setColumnCount(3)
        self.result_person_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.result_person_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.result_person_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.result_person_twidget.setHorizontalHeaderItem(2, item)
        self.search_person_button = QtGui.QPushButton(SParcelPersonDialog)
        self.search_person_button.setGeometry(QtCore.QRect(310, 30, 75, 23))
        self.search_person_button.setObjectName(_fromUtf8("search_person_button"))
        self.result_parcel_twidget = QtGui.QTableWidget(SParcelPersonDialog)
        self.result_parcel_twidget.setGeometry(QtCore.QRect(400, 80, 311, 131))
        self.result_parcel_twidget.setObjectName(_fromUtf8("result_parcel_twidget"))
        self.result_parcel_twidget.setColumnCount(2)
        self.result_parcel_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.result_parcel_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.result_parcel_twidget.setHorizontalHeaderItem(1, item)
        self.label_2 = QtGui.QLabel(SParcelPersonDialog)
        self.label_2.setGeometry(QtCore.QRect(405, 10, 131, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.search_parcel_id_edit = QtGui.QLineEdit(SParcelPersonDialog)
        self.search_parcel_id_edit.setGeometry(QtCore.QRect(405, 30, 131, 20))
        self.search_parcel_id_edit.setObjectName(_fromUtf8("search_parcel_id_edit"))
        self.search_parcel_button = QtGui.QPushButton(SParcelPersonDialog)
        self.search_parcel_button.setGeometry(QtCore.QRect(650, 29, 75, 23))
        self.search_parcel_button.setObjectName(_fromUtf8("search_parcel_button"))
        self.add_button = QtGui.QPushButton(SParcelPersonDialog)
        self.add_button.setGeometry(QtCore.QRect(130, 260, 75, 23))
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.parcel_person_twidget = QtGui.QTableWidget(SParcelPersonDialog)
        self.parcel_person_twidget.setGeometry(QtCore.QRect(40, 286, 681, 101))
        self.parcel_person_twidget.setObjectName(_fromUtf8("parcel_person_twidget"))
        self.parcel_person_twidget.setColumnCount(3)
        self.parcel_person_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.parcel_person_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.parcel_person_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.parcel_person_twidget.setHorizontalHeaderItem(2, item)
        self.delete_button = QtGui.QPushButton(SParcelPersonDialog)
        self.delete_button.setGeometry(QtCore.QRect(310, 260, 75, 23))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.zoom_button = QtGui.QPushButton(SParcelPersonDialog)
        self.zoom_button.setGeometry(QtCore.QRect(560, 400, 75, 23))
        self.zoom_button.setObjectName(_fromUtf8("zoom_button"))
        self.close_button = QtGui.QPushButton(SParcelPersonDialog)
        self.close_button.setGeometry(QtCore.QRect(670, 400, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.landuse_cbox = QtGui.QComboBox(SParcelPersonDialog)
        self.landuse_cbox.setGeometry(QtCore.QRect(40, 230, 531, 22))
        self.landuse_cbox.setObjectName(_fromUtf8("landuse_cbox"))
        self.label_3 = QtGui.QLabel(SParcelPersonDialog)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 161, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.search_person_name_edit = QtGui.QLineEdit(SParcelPersonDialog)
        self.search_person_name_edit.setGeometry(QtCore.QRect(180, 30, 119, 20))
        self.search_person_name_edit.setObjectName(_fromUtf8("search_person_name_edit"))
        self.person_count_lbl = QtGui.QLabel(SParcelPersonDialog)
        self.person_count_lbl.setGeometry(QtCore.QRect(40, 60, 181, 16))
        self.person_count_lbl.setText(_fromUtf8(""))
        self.person_count_lbl.setObjectName(_fromUtf8("person_count_lbl"))
        self.search_parcel_person_edit = QtGui.QLineEdit(SParcelPersonDialog)
        self.search_parcel_person_edit.setGeometry(QtCore.QRect(480, 260, 119, 20))
        self.search_parcel_person_edit.setObjectName(_fromUtf8("search_parcel_person_edit"))
        self.search_parcel_person_button = QtGui.QPushButton(SParcelPersonDialog)
        self.search_parcel_person_button.setGeometry(QtCore.QRect(610, 260, 75, 23))
        self.search_parcel_person_button.setObjectName(_fromUtf8("search_parcel_person_button"))
        self.edit_button = QtGui.QPushButton(SParcelPersonDialog)
        self.edit_button.setGeometry(QtCore.QRect(220, 260, 75, 23))
        self.edit_button.setObjectName(_fromUtf8("edit_button"))
        self.print_button = QtGui.QPushButton(SParcelPersonDialog)
        self.print_button.setGeometry(QtCore.QRect(50, 400, 75, 23))
        self.print_button.setObjectName(_fromUtf8("print_button"))

        self.retranslateUi(SParcelPersonDialog)
        QtCore.QMetaObject.connectSlotsByName(SParcelPersonDialog)

    def retranslateUi(self, SParcelPersonDialog):
        SParcelPersonDialog.setWindowTitle(_translate("SParcelPersonDialog", "Dialog", None))
        self.label.setText(_translate("SParcelPersonDialog", "Person ID", None))
        item = self.result_person_twidget.horizontalHeaderItem(0)
        item.setText(_translate("SParcelPersonDialog", "Reigster", None))
        item = self.result_person_twidget.horizontalHeaderItem(1)
        item.setText(_translate("SParcelPersonDialog", "Name", None))
        item = self.result_person_twidget.horizontalHeaderItem(2)
        item.setText(_translate("SParcelPersonDialog", "Firstname", None))
        self.search_person_button.setText(_translate("SParcelPersonDialog", "Search", None))
        item = self.result_parcel_twidget.horizontalHeaderItem(0)
        item.setText(_translate("SParcelPersonDialog", "parcel_id", None))
        item = self.result_parcel_twidget.horizontalHeaderItem(1)
        item.setText(_translate("SParcelPersonDialog", "address", None))
        self.label_2.setText(_translate("SParcelPersonDialog", "Parcel ID", None))
        self.search_parcel_button.setText(_translate("SParcelPersonDialog", "Search", None))
        self.add_button.setText(_translate("SParcelPersonDialog", "Add", None))
        item = self.parcel_person_twidget.horizontalHeaderItem(0)
        item.setText(_translate("SParcelPersonDialog", "Person", None))
        item = self.parcel_person_twidget.horizontalHeaderItem(1)
        item.setText(_translate("SParcelPersonDialog", "Parcel", None))
        item = self.parcel_person_twidget.horizontalHeaderItem(2)
        item.setText(_translate("SParcelPersonDialog", "Landuse", None))
        self.delete_button.setText(_translate("SParcelPersonDialog", "Delete", None))
        self.zoom_button.setText(_translate("SParcelPersonDialog", "Zoom  In", None))
        self.close_button.setText(_translate("SParcelPersonDialog", "Close", None))
        self.label_3.setText(_translate("SParcelPersonDialog", "Land Use", None))
        self.search_parcel_person_button.setText(_translate("SParcelPersonDialog", "Search", None))
        self.edit_button.setText(_translate("SParcelPersonDialog", "Edit", None))
        self.print_button.setText(_translate("SParcelPersonDialog", "Print", None))

