# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UserRoleManagementDetialDialog.ui'
#
# Created: Wed Sep 07 15:51:33 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UserRoleManagementDetialDialog(object):
    def setupUi(self, UserRoleManagementDetialDialog):
        UserRoleManagementDetialDialog.setObjectName(_fromUtf8("UserRoleManagementDetialDialog"))
        UserRoleManagementDetialDialog.resize(672, 450)
        self.line = QtGui.QFrame(UserRoleManagementDetialDialog)
        self.line.setGeometry(QtCore.QRect(10, 20, 651, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(UserRoleManagementDetialDialog)
        self.line_2.setGeometry(QtCore.QRect(10, 400, 651, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.user_detial_name_label = QtGui.QLabel(UserRoleManagementDetialDialog)
        self.user_detial_name_label.setGeometry(QtCore.QRect(320, 10, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.user_detial_name_label.setFont(font)
        self.user_detial_name_label.setObjectName(_fromUtf8("user_detial_name_label"))
        self.groupBox = QtGui.QGroupBox(UserRoleManagementDetialDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 651, 125))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 171, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(198, 20, 151, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(360, 20, 141, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(311, 70, 321, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.surname_edit = QtGui.QLineEdit(self.groupBox)
        self.surname_edit.setGeometry(QtCore.QRect(10, 40, 177, 20))
        self.surname_edit.setReadOnly(True)
        self.surname_edit.setObjectName(_fromUtf8("surname_edit"))
        self.firstname_edit = QtGui.QLineEdit(self.groupBox)
        self.firstname_edit.setGeometry(QtCore.QRect(198, 40, 150, 20))
        self.firstname_edit.setReadOnly(True)
        self.firstname_edit.setObjectName(_fromUtf8("firstname_edit"))
        self.employee_type_cbox = QtGui.QComboBox(self.groupBox)
        self.employee_type_cbox.setGeometry(QtCore.QRect(359, 40, 141, 22))
        self.employee_type_cbox.setObjectName(_fromUtf8("employee_type_cbox"))
        self.phone_edit = QtGui.QLineEdit(self.groupBox)
        self.phone_edit.setGeometry(QtCore.QRect(510, 40, 131, 20))
        self.phone_edit.setReadOnly(True)
        self.phone_edit.setObjectName(_fromUtf8("phone_edit"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(510, 20, 131, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.position_edit = QtGui.QLineEdit(self.groupBox)
        self.position_edit.setGeometry(QtCore.QRect(310, 90, 331, 20))
        self.position_edit.setReadOnly(True)
        self.position_edit.setObjectName(_fromUtf8("position_edit"))
        self.end_date = QtGui.QDateEdit(self.groupBox)
        self.end_date.setGeometry(QtCore.QRect(104, 90, 81, 22))
        self.end_date.setReadOnly(True)
        self.end_date.setObjectName(_fromUtf8("end_date"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(104, 70, 91, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.begin_date = QtGui.QDateEdit(self.groupBox)
        self.begin_date.setGeometry(QtCore.QRect(10, 90, 81, 22))
        self.begin_date.setReadOnly(True)
        self.begin_date.setObjectName(_fromUtf8("begin_date"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(198, 70, 111, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.register_edit = QtGui.QLineEdit(self.groupBox)
        self.register_edit.setGeometry(QtCore.QRect(198, 90, 101, 20))
        self.register_edit.setReadOnly(True)
        self.register_edit.setObjectName(_fromUtf8("register_edit"))
        self.extend_groupbox = QtGui.QGroupBox(UserRoleManagementDetialDialog)
        self.extend_groupbox.setGeometry(QtCore.QRect(10, 170, 141, 221))
        self.extend_groupbox.setObjectName(_fromUtf8("extend_groupbox"))
        self.is_extend_checkbox = QtGui.QCheckBox(self.extend_groupbox)
        self.is_extend_checkbox.setGeometry(QtCore.QRect(10, 20, 131, 17))
        self.is_extend_checkbox.setObjectName(_fromUtf8("is_extend_checkbox"))
        self.extend_date = QtGui.QDateEdit(self.extend_groupbox)
        self.extend_date.setEnabled(False)
        self.extend_date.setGeometry(QtCore.QRect(10, 60, 110, 22))
        self.extend_date.setObjectName(_fromUtf8("extend_date"))
        self.label_9 = QtGui.QLabel(self.extend_groupbox)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 131, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.extend_button = QtGui.QPushButton(self.extend_groupbox)
        self.extend_button.setEnabled(False)
        self.extend_button.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.extend_button.setObjectName(_fromUtf8("extend_button"))
        self.termination_groupbox = QtGui.QGroupBox(UserRoleManagementDetialDialog)
        self.termination_groupbox.setGeometry(QtCore.QRect(160, 170, 501, 98))
        self.termination_groupbox.setObjectName(_fromUtf8("termination_groupbox"))
        self.is_cancel_checkbox = QtGui.QCheckBox(self.termination_groupbox)
        self.is_cancel_checkbox.setGeometry(QtCore.QRect(10, 20, 481, 17))
        self.is_cancel_checkbox.setObjectName(_fromUtf8("is_cancel_checkbox"))
        self.cancel_reason_cbox = QtGui.QComboBox(self.termination_groupbox)
        self.cancel_reason_cbox.setEnabled(False)
        self.cancel_reason_cbox.setGeometry(QtCore.QRect(10, 60, 191, 22))
        self.cancel_reason_cbox.setObjectName(_fromUtf8("cancel_reason_cbox"))
        self.label_11 = QtGui.QLabel(self.termination_groupbox)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 191, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.disable_button = QtGui.QPushButton(self.termination_groupbox)
        self.disable_button.setEnabled(False)
        self.disable_button.setGeometry(QtCore.QRect(220, 59, 75, 23))
        self.disable_button.setObjectName(_fromUtf8("disable_button"))
        self.new_employee_gbox = QtGui.QGroupBox(UserRoleManagementDetialDialog)
        self.new_employee_gbox.setEnabled(False)
        self.new_employee_gbox.setGeometry(QtCore.QRect(160, 270, 501, 121))
        self.new_employee_gbox.setObjectName(_fromUtf8("new_employee_gbox"))
        self.label_12 = QtGui.QLabel(self.new_employee_gbox)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 191, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.employee_cbox = QtGui.QComboBox(self.new_employee_gbox)
        self.employee_cbox.setGeometry(QtCore.QRect(10, 40, 191, 22))
        self.employee_cbox.setObjectName(_fromUtf8("employee_cbox"))
        self.employee_select_type = QtGui.QComboBox(self.new_employee_gbox)
        self.employee_select_type.setGeometry(QtCore.QRect(220, 40, 191, 22))
        self.employee_select_type.setObjectName(_fromUtf8("employee_select_type"))
        self.label_13 = QtGui.QLabel(self.new_employee_gbox)
        self.label_13.setGeometry(QtCore.QRect(220, 20, 191, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_7 = QtGui.QLabel(self.new_employee_gbox)
        self.label_7.setGeometry(QtCore.QRect(120, 70, 91, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.end_edit_date = QtGui.QDateEdit(self.new_employee_gbox)
        self.end_edit_date.setGeometry(QtCore.QRect(120, 90, 81, 22))
        self.end_edit_date.setReadOnly(False)
        self.end_edit_date.setObjectName(_fromUtf8("end_edit_date"))
        self.label_6 = QtGui.QLabel(self.new_employee_gbox)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.begin_edit_date = QtGui.QDateEdit(self.new_employee_gbox)
        self.begin_edit_date.setGeometry(QtCore.QRect(10, 90, 81, 22))
        self.begin_edit_date.setReadOnly(False)
        self.begin_edit_date.setObjectName(_fromUtf8("begin_edit_date"))
        self.enable_button = QtGui.QPushButton(self.new_employee_gbox)
        self.enable_button.setGeometry(QtCore.QRect(220, 89, 75, 23))
        self.enable_button.setObjectName(_fromUtf8("enable_button"))
        self.close_button = QtGui.QPushButton(UserRoleManagementDetialDialog)
        self.close_button.setGeometry(QtCore.QRect(587, 420, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.apply_button = QtGui.QPushButton(UserRoleManagementDetialDialog)
        self.apply_button.setGeometry(QtCore.QRect(507, 420, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.help_button = QtGui.QPushButton(UserRoleManagementDetialDialog)
        self.help_button.setGeometry(QtCore.QRect(457, 420, 41, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.user_name_real_lbl = QtGui.QLabel(UserRoleManagementDetialDialog)
        self.user_name_real_lbl.setGeometry(QtCore.QRect(20, 10, 211, 16))
        self.user_name_real_lbl.setObjectName(_fromUtf8("user_name_real_lbl"))

        self.retranslateUi(UserRoleManagementDetialDialog)
        QtCore.QMetaObject.connectSlotsByName(UserRoleManagementDetialDialog)

    def retranslateUi(self, UserRoleManagementDetialDialog):
        UserRoleManagementDetialDialog.setWindowTitle(_translate("UserRoleManagementDetialDialog", "Dialog", None))
        self.user_detial_name_label.setText(_translate("UserRoleManagementDetialDialog", "User Name", None))
        self.groupBox.setTitle(_translate("UserRoleManagementDetialDialog", "Active Employee Detial", None))
        self.label_2.setText(_translate("UserRoleManagementDetialDialog", "Surname", None))
        self.label_3.setText(_translate("UserRoleManagementDetialDialog", "First Name", None))
        self.label_4.setText(_translate("UserRoleManagementDetialDialog", "Employee Type", None))
        self.label_5.setText(_translate("UserRoleManagementDetialDialog", "Position", None))
        self.label_8.setText(_translate("UserRoleManagementDetialDialog", "Phone", None))
        self.label_10.setText(_translate("UserRoleManagementDetialDialog", "End Date", None))
        self.label_14.setText(_translate("UserRoleManagementDetialDialog", "Begin Date", None))
        self.label_15.setText(_translate("UserRoleManagementDetialDialog", "User Register", None))
        self.extend_groupbox.setTitle(_translate("UserRoleManagementDetialDialog", "Date Extend", None))
        self.is_extend_checkbox.setText(_translate("UserRoleManagementDetialDialog", "Is Extend", None))
        self.label_9.setText(_translate("UserRoleManagementDetialDialog", "End Date Edit", None))
        self.extend_button.setText(_translate("UserRoleManagementDetialDialog", "Extend", None))
        self.termination_groupbox.setTitle(_translate("UserRoleManagementDetialDialog", "Termination", None))
        self.is_cancel_checkbox.setText(_translate("UserRoleManagementDetialDialog", "Is Cancel", None))
        self.label_11.setText(_translate("UserRoleManagementDetialDialog", "Cancel Reason", None))
        self.disable_button.setText(_translate("UserRoleManagementDetialDialog", "Disable", None))
        self.new_employee_gbox.setTitle(_translate("UserRoleManagementDetialDialog", "Select New Employee", None))
        self.label_12.setText(_translate("UserRoleManagementDetialDialog", "Select Employee", None))
        self.label_13.setText(_translate("UserRoleManagementDetialDialog", "Employee Type", None))
        self.label_7.setText(_translate("UserRoleManagementDetialDialog", "End Date", None))
        self.label_6.setText(_translate("UserRoleManagementDetialDialog", "Begin Date", None))
        self.enable_button.setText(_translate("UserRoleManagementDetialDialog", "Enable", None))
        self.close_button.setText(_translate("UserRoleManagementDetialDialog", "close", None))
        self.apply_button.setText(_translate("UserRoleManagementDetialDialog", "Apply", None))
        self.help_button.setText(_translate("UserRoleManagementDetialDialog", "?", None))
        self.user_name_real_lbl.setText(_translate("UserRoleManagementDetialDialog", "TextLabel", None))

