# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UserRoleManagementDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UserRoleManagementDialog(object):
    def setupUi(self, UserRoleManagementDialog):
        UserRoleManagementDialog.setObjectName(_fromUtf8("UserRoleManagementDialog"))
        UserRoleManagementDialog.resize(850, 550)
        UserRoleManagementDialog.setMinimumSize(QtCore.QSize(850, 550))
        UserRoleManagementDialog.setMaximumSize(QtCore.QSize(850, 550))
        UserRoleManagementDialog.setBaseSize(QtCore.QSize(860, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/user_role_management.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserRoleManagementDialog.setWindowIcon(icon)
        self.line = QtGui.QFrame(UserRoleManagementDialog)
        self.line.setGeometry(QtCore.QRect(0, 10, 841, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_9 = QtGui.QLabel(UserRoleManagementDialog)
        self.label_9.setGeometry(QtCore.QRect(10, 1, 231, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.close_button = QtGui.QPushButton(UserRoleManagementDialog)
        self.close_button.setGeometry(QtCore.QRect(730, 510, 70, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.help_button = QtGui.QPushButton(UserRoleManagementDialog)
        self.help_button.setGeometry(QtCore.QRect(10, 510, 81, 23))
        self.help_button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/help_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_button.setIcon(icon1)
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.line_2 = QtGui.QFrame(UserRoleManagementDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 530, 841, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.username_real_lbl = QtGui.QLabel(UserRoleManagementDialog)
        self.username_real_lbl.setGeometry(QtCore.QRect(220, 0, 121, 16))
        self.username_real_lbl.setText(_fromUtf8(""))
        self.username_real_lbl.setObjectName(_fromUtf8("username_real_lbl"))
        self.tabWidget = QtGui.QTabWidget(UserRoleManagementDialog)
        self.tabWidget.setGeometry(QtCore.QRect(3, 21, 846, 489))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.user_register_tab = QtGui.QWidget()
        self.user_register_tab.setObjectName(_fromUtf8("user_register_tab"))
        self.groupBox = QtGui.QGroupBox(self.user_register_tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 2, 326, 461))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.username_edit = QtGui.QLineEdit(self.groupBox)
        self.username_edit.setGeometry(QtCore.QRect(10, 122, 150, 20))
        self.username_edit.setObjectName(_fromUtf8("username_edit"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 103, 151, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.password_edit = QtGui.QLineEdit(self.groupBox)
        self.password_edit.setGeometry(QtCore.QRect(10, 206, 150, 20))
        self.password_edit.setEchoMode(QtGui.QLineEdit.Password)
        self.password_edit.setObjectName(_fromUtf8("password_edit"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 187, 151, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(170, 187, 151, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.retype_password_edit = QtGui.QLineEdit(self.groupBox)
        self.retype_password_edit.setGeometry(QtCore.QRect(170, 206, 150, 20))
        self.retype_password_edit.setEchoMode(QtGui.QLineEdit.Password)
        self.retype_password_edit.setObjectName(_fromUtf8("retype_password_edit"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(170, 103, 151, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.surname_edit = QtGui.QLineEdit(self.groupBox)
        self.surname_edit.setGeometry(QtCore.QRect(170, 122, 150, 20))
        self.surname_edit.setObjectName(_fromUtf8("surname_edit"))
        self.firstname_edit = QtGui.QLineEdit(self.groupBox)
        self.firstname_edit.setGeometry(QtCore.QRect(170, 164, 150, 20))
        self.firstname_edit.setObjectName(_fromUtf8("firstname_edit"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(170, 145, 151, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 230, 151, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.phone_edit = QtGui.QLineEdit(self.groupBox)
        self.phone_edit.setGeometry(QtCore.QRect(10, 249, 311, 20))
        self.phone_edit.setText(_fromUtf8(""))
        self.phone_edit.setObjectName(_fromUtf8("phone_edit"))
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(10, 272, 310, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.email_edit = QtGui.QLineEdit(self.groupBox)
        self.email_edit.setGeometry(QtCore.QRect(10, 291, 310, 20))
        self.email_edit.setObjectName(_fromUtf8("email_edit"))
        self.get_mac_checkbox = QtGui.QCheckBox(self.groupBox)
        self.get_mac_checkbox.setGeometry(QtCore.QRect(10, 319, 141, 20))
        self.get_mac_checkbox.setObjectName(_fromUtf8("get_mac_checkbox"))
        self.mac_address_edit = QtGui.QLineEdit(self.groupBox)
        self.mac_address_edit.setGeometry(QtCore.QRect(10, 340, 311, 20))
        self.mac_address_edit.setObjectName(_fromUtf8("mac_address_edit"))
        self.organization_type_cbox = QtGui.QComboBox(self.groupBox)
        self.organization_type_cbox.setGeometry(QtCore.QRect(10, 31, 300, 22))
        self.organization_type_cbox.setObjectName(_fromUtf8("organization_type_cbox"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 57, 300, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 12, 300, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.organization_cbox = QtGui.QComboBox(self.groupBox)
        self.organization_cbox.setGeometry(QtCore.QRect(10, 76, 300, 22))
        self.organization_cbox.setObjectName(_fromUtf8("organization_cbox"))
        self.register_edit = QtGui.QLineEdit(self.groupBox)
        self.register_edit.setGeometry(QtCore.QRect(10, 164, 151, 20))
        self.register_edit.setObjectName(_fromUtf8("register_edit"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(10, 144, 151, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.settings_button = QtGui.QPushButton(self.groupBox)
        self.settings_button.setGeometry(QtCore.QRect(10, 370, 311, 23))
        self.settings_button.setObjectName(_fromUtf8("settings_button"))
        self.groupBox_3 = QtGui.QGroupBox(self.user_register_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(329, 2, 193, 458))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(6, 15, 181, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.down_groups_button = QtGui.QPushButton(self.groupBox_3)
        self.down_groups_button.setGeometry(QtCore.QRect(58, 224, 30, 25))
        self.down_groups_button.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/down_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.down_groups_button.setIcon(icon2)
        self.down_groups_button.setObjectName(_fromUtf8("down_groups_button"))
        self.up_groups_button = QtGui.QPushButton(self.groupBox_3)
        self.up_groups_button.setGeometry(QtCore.QRect(104, 224, 30, 25))
        self.up_groups_button.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/up_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.up_groups_button.setIcon(icon3)
        self.up_groups_button.setObjectName(_fromUtf8("up_groups_button"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(6, 252, 171, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.group_lwidget = QtGui.QListWidget(self.groupBox_3)
        self.group_lwidget.setGeometry(QtCore.QRect(6, 33, 181, 180))
        self.group_lwidget.setObjectName(_fromUtf8("group_lwidget"))
        self.member_lwidget = QtGui.QListWidget(self.groupBox_3)
        self.member_lwidget.setGeometry(QtCore.QRect(6, 270, 181, 180))
        self.member_lwidget.setObjectName(_fromUtf8("member_lwidget"))
        self.groupBox_7 = QtGui.QGroupBox(self.user_register_tab)
        self.groupBox_7.setGeometry(QtCore.QRect(526, 2, 311, 458))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(4, 16, 150, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.aimag_cbox = QtGui.QComboBox(self.groupBox_7)
        self.aimag_cbox.setGeometry(QtCore.QRect(4, 33, 150, 22))
        self.aimag_cbox.setObjectName(_fromUtf8("aimag_cbox"))
        self.aimag_lwidget = QtGui.QListWidget(self.groupBox_7)
        self.aimag_lwidget.setGeometry(QtCore.QRect(4, 109, 150, 101))
        self.aimag_lwidget.setObjectName(_fromUtf8("aimag_lwidget"))
        self.down_aimag_button = QtGui.QPushButton(self.groupBox_7)
        self.down_aimag_button.setGeometry(QtCore.QRect(50, 64, 30, 25))
        self.down_aimag_button.setText(_fromUtf8(""))
        self.down_aimag_button.setIcon(icon2)
        self.down_aimag_button.setObjectName(_fromUtf8("down_aimag_button"))
        self.up_aimag_button = QtGui.QPushButton(self.groupBox_7)
        self.up_aimag_button.setGeometry(QtCore.QRect(96, 64, 30, 25))
        self.up_aimag_button.setText(_fromUtf8(""))
        self.up_aimag_button.setIcon(icon3)
        self.up_aimag_button.setObjectName(_fromUtf8("up_aimag_button"))
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(160, 16, 150, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.soum_cbox = QtGui.QComboBox(self.groupBox_7)
        self.soum_cbox.setGeometry(QtCore.QRect(158, 33, 150, 22))
        self.soum_cbox.setObjectName(_fromUtf8("soum_cbox"))
        self.soum_lwidget = QtGui.QListWidget(self.groupBox_7)
        self.soum_lwidget.setGeometry(QtCore.QRect(158, 109, 150, 101))
        self.soum_lwidget.setObjectName(_fromUtf8("soum_lwidget"))
        self.up_soum_button = QtGui.QPushButton(self.groupBox_7)
        self.up_soum_button.setGeometry(QtCore.QRect(246, 64, 30, 25))
        self.up_soum_button.setText(_fromUtf8(""))
        self.up_soum_button.setIcon(icon3)
        self.up_soum_button.setObjectName(_fromUtf8("up_soum_button"))
        self.down_soum_button = QtGui.QPushButton(self.groupBox_7)
        self.down_soum_button.setGeometry(QtCore.QRect(200, 64, 30, 25))
        self.down_soum_button.setText(_fromUtf8(""))
        self.down_soum_button.setIcon(icon2)
        self.down_soum_button.setObjectName(_fromUtf8("down_soum_button"))
        self.label_30 = QtGui.QLabel(self.groupBox_7)
        self.label_30.setGeometry(QtCore.QRect(6, 90, 146, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_4 = QtGui.QLabel(self.groupBox_7)
        self.label_4.setGeometry(QtCore.QRect(160, 89, 181, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.position_cbox = QtGui.QComboBox(self.groupBox_7)
        self.position_cbox.setGeometry(QtCore.QRect(4, 270, 300, 22))
        self.position_cbox.setObjectName(_fromUtf8("position_cbox"))
        self.label_19 = QtGui.QLabel(self.groupBox_7)
        self.label_19.setGeometry(QtCore.QRect(4, 209, 300, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.department_cbox = QtGui.QComboBox(self.groupBox_7)
        self.department_cbox.setGeometry(QtCore.QRect(4, 228, 300, 22))
        self.department_cbox.setObjectName(_fromUtf8("department_cbox"))
        self.label_7 = QtGui.QLabel(self.groupBox_7)
        self.label_7.setGeometry(QtCore.QRect(4, 251, 300, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.user_role_lwidget = QtGui.QListWidget(self.groupBox_7)
        self.user_role_lwidget.setGeometry(QtCore.QRect(3, 353, 301, 97))
        self.user_role_lwidget.setObjectName(_fromUtf8("user_role_lwidget"))
        self.delete_button = QtGui.QPushButton(self.groupBox_7)
        self.delete_button.setGeometry(QtCore.QRect(210, 300, 70, 23))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.update_button = QtGui.QPushButton(self.groupBox_7)
        self.update_button.setGeometry(QtCore.QRect(120, 300, 70, 23))
        self.update_button.setObjectName(_fromUtf8("update_button"))
        self.add_button = QtGui.QPushButton(self.groupBox_7)
        self.add_button.setGeometry(QtCore.QRect(30, 300, 70, 23))
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.find_update_user_edit = QtGui.QLineEdit(self.groupBox_7)
        self.find_update_user_edit.setGeometry(QtCore.QRect(10, 328, 291, 20))
        self.find_update_user_edit.setObjectName(_fromUtf8("find_update_user_edit"))
        self.tabWidget.addTab(self.user_register_tab, _fromUtf8(""))
        self.user_management_tab = QtGui.QWidget()
        self.user_management_tab.setObjectName(_fromUtf8("user_management_tab"))
        self.user_twidget = QtGui.QTableWidget(self.user_management_tab)
        self.user_twidget.setGeometry(QtCore.QRect(10, 70, 181, 281))
        self.user_twidget.setObjectName(_fromUtf8("user_twidget"))
        self.user_twidget.setColumnCount(1)
        self.user_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.user_twidget.setHorizontalHeaderItem(0, item)
        self.user_twidget.horizontalHeader().setDefaultSectionSize(200)
        self.position_twidget = QtGui.QTableWidget(self.user_management_tab)
        self.position_twidget.setGeometry(QtCore.QRect(210, 40, 201, 311))
        self.position_twidget.setObjectName(_fromUtf8("position_twidget"))
        self.position_twidget.setColumnCount(1)
        self.position_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.position_twidget.setHorizontalHeaderItem(0, item)
        self.position_twidget.horizontalHeader().setDefaultSectionSize(250)
        self.right_grud_twidget = QtGui.QTableWidget(self.user_management_tab)
        self.right_grud_twidget.setGeometry(QtCore.QRect(430, 40, 391, 311))
        self.right_grud_twidget.setObjectName(_fromUtf8("right_grud_twidget"))
        self.right_grud_twidget.setColumnCount(5)
        self.right_grud_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.right_grud_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.right_grud_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.right_grud_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.right_grud_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.right_grud_twidget.setHorizontalHeaderItem(4, item)
        self.groupBox_2 = QtGui.QGroupBox(self.user_management_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 370, 811, 85))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.load_default_settings_button = QtGui.QPushButton(self.user_management_tab)
        self.load_default_settings_button.setGeometry(QtCore.QRect(650, 10, 171, 23))
        self.load_default_settings_button.setObjectName(_fromUtf8("load_default_settings_button"))
        self.load_users_button = QtGui.QPushButton(self.user_management_tab)
        self.load_users_button.setGeometry(QtCore.QRect(10, 10, 181, 21))
        self.load_users_button.setObjectName(_fromUtf8("load_users_button"))
        self.load_position_button = QtGui.QPushButton(self.user_management_tab)
        self.load_position_button.setGeometry(QtCore.QRect(210, 10, 201, 23))
        self.load_position_button.setObjectName(_fromUtf8("load_position_button"))
        self.find_user_edit = QtGui.QLineEdit(self.user_management_tab)
        self.find_user_edit.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.find_user_edit.setObjectName(_fromUtf8("find_user_edit"))
        self.tabWidget.addTab(self.user_management_tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.settings_right_grud_twidget = QtGui.QTableWidget(self.tab)
        self.settings_right_grud_twidget.setGeometry(QtCore.QRect(270, 20, 551, 391))
        self.settings_right_grud_twidget.setObjectName(_fromUtf8("settings_right_grud_twidget"))
        self.settings_right_grud_twidget.setColumnCount(6)
        self.settings_right_grud_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.settings_right_grud_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.settings_right_grud_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.settings_right_grud_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.settings_right_grud_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.settings_right_grud_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.settings_right_grud_twidget.setHorizontalHeaderItem(5, item)
        self.settings_position_twidget = QtGui.QTableWidget(self.tab)
        self.settings_position_twidget.setGeometry(QtCore.QRect(10, 20, 251, 391))
        self.settings_position_twidget.setObjectName(_fromUtf8("settings_position_twidget"))
        self.settings_position_twidget.setColumnCount(1)
        self.settings_position_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.settings_position_twidget.setHorizontalHeaderItem(0, item)
        self.settings_position_twidget.horizontalHeader().setDefaultSectionSize(250)
        self.settings_position_twidget.horizontalHeader().setMinimumSectionSize(33)
        self.settings_position_twidget.verticalHeader().setDefaultSectionSize(30)
        self.settings_position_twidget.verticalHeader().setMinimumSectionSize(19)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.department_twidget = QtGui.QTableWidget(self.tab_2)
        self.department_twidget.setGeometry(QtCore.QRect(10, 258, 821, 191))
        self.department_twidget.setObjectName(_fromUtf8("department_twidget"))
        self.department_twidget.setColumnCount(14)
        self.department_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.department_twidget.setHorizontalHeaderItem(13, item)
        self.department_add_button = QtGui.QPushButton(self.tab_2)
        self.department_add_button.setGeometry(QtCore.QRect(280, 224, 75, 23))
        self.department_add_button.setObjectName(_fromUtf8("department_add_button"))
        self.department_update_button = QtGui.QPushButton(self.tab_2)
        self.department_update_button.setGeometry(QtCore.QRect(370, 224, 75, 23))
        self.department_update_button.setObjectName(_fromUtf8("department_update_button"))
        self.department_delete_button = QtGui.QPushButton(self.tab_2)
        self.department_delete_button.setGeometry(QtCore.QRect(460, 224, 75, 23))
        self.department_delete_button.setObjectName(_fromUtf8("department_delete_button"))
        self.department_load_chbox = QtGui.QCheckBox(self.tab_2)
        self.department_load_chbox.setGeometry(QtCore.QRect(20, 20, 341, 17))
        self.department_load_chbox.setObjectName(_fromUtf8("department_load_chbox"))
        self.department_aimag_cbox = QtGui.QComboBox(self.tab_2)
        self.department_aimag_cbox.setGeometry(QtCore.QRect(20, 68, 161, 22))
        self.department_aimag_cbox.setObjectName(_fromUtf8("department_aimag_cbox"))
        self.department_soum_cbox = QtGui.QComboBox(self.tab_2)
        self.department_soum_cbox.setGeometry(QtCore.QRect(200, 68, 161, 22))
        self.department_soum_cbox.setObjectName(_fromUtf8("department_soum_cbox"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 48, 171, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(200, 48, 161, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.department_name_edit = QtGui.QLineEdit(self.tab_2)
        self.department_name_edit.setGeometry(QtCore.QRect(380, 68, 451, 20))
        self.department_name_edit.setObjectName(_fromUtf8("department_name_edit"))
        self.department_address_edit = QtGui.QTextEdit(self.tab_2)
        self.department_address_edit.setGeometry(QtCore.QRect(20, 108, 341, 103))
        self.department_address_edit.setObjectName(_fromUtf8("department_address_edit"))
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(20, 89, 171, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(380, 48, 431, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.department_phone_edit = QtGui.QLineEdit(self.tab_2)
        self.department_phone_edit.setGeometry(QtCore.QRect(380, 108, 140, 20))
        self.department_phone_edit.setObjectName(_fromUtf8("department_phone_edit"))
        self.department_fax_edit = QtGui.QLineEdit(self.tab_2)
        self.department_fax_edit.setGeometry(QtCore.QRect(536, 108, 140, 20))
        self.department_fax_edit.setObjectName(_fromUtf8("department_fax_edit"))
        self.department_email_edit = QtGui.QLineEdit(self.tab_2)
        self.department_email_edit.setGeometry(QtCore.QRect(691, 108, 140, 20))
        self.department_email_edit.setObjectName(_fromUtf8("department_email_edit"))
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(380, 129, 141, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(380, 88, 141, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(540, 88, 141, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(690, 88, 141, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(537, 129, 141, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.department_account_edit = QtGui.QLineEdit(self.tab_2)
        self.department_account_edit.setGeometry(QtCore.QRect(536, 149, 140, 20))
        self.department_account_edit.setObjectName(_fromUtf8("department_account_edit"))
        self.department_web_edit = QtGui.QLineEdit(self.tab_2)
        self.department_web_edit.setGeometry(QtCore.QRect(691, 149, 140, 20))
        self.department_web_edit.setObjectName(_fromUtf8("department_web_edit"))
        self.label_28 = QtGui.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(690, 129, 141, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.department_headsurname_edit = QtGui.QLineEdit(self.tab_2)
        self.department_headsurname_edit.setGeometry(QtCore.QRect(379, 190, 140, 20))
        self.department_headsurname_edit.setObjectName(_fromUtf8("department_headsurname_edit"))
        self.label_29 = QtGui.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(380, 170, 141, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.department_head_firstname_edit = QtGui.QLineEdit(self.tab_2)
        self.department_head_firstname_edit.setGeometry(QtCore.QRect(539, 190, 140, 20))
        self.department_head_firstname_edit.setObjectName(_fromUtf8("department_head_firstname_edit"))
        self.label_31 = QtGui.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(540, 170, 141, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.department_bank_edit = QtGui.QLineEdit(self.tab_2)
        self.department_bank_edit.setGeometry(QtCore.QRect(380, 149, 140, 20))
        self.department_bank_edit.setObjectName(_fromUtf8("department_bank_edit"))
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(380, 5, 161, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.department_organization_cbox = QtGui.QComboBox(self.tab_2)
        self.department_organization_cbox.setGeometry(QtCore.QRect(380, 25, 451, 22))
        self.department_organization_cbox.setObjectName(_fromUtf8("department_organization_cbox"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.refresh_button = QtGui.QPushButton(UserRoleManagementDialog)
        self.refresh_button.setGeometry(QtCore.QRect(550, 510, 70, 23))
        self.refresh_button.setObjectName(_fromUtf8("refresh_button"))
        self.apply_button = QtGui.QPushButton(UserRoleManagementDialog)
        self.apply_button.setGeometry(QtCore.QRect(640, 510, 70, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.status_label = QtGui.QLabel(UserRoleManagementDialog)
        self.status_label.setGeometry(QtCore.QRect(100, 510, 440, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setObjectName(_fromUtf8("status_label"))

        self.retranslateUi(UserRoleManagementDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UserRoleManagementDialog)
        UserRoleManagementDialog.setTabOrder(self.group_lwidget, self.close_button)
        UserRoleManagementDialog.setTabOrder(self.close_button, self.tabWidget)
        UserRoleManagementDialog.setTabOrder(self.tabWidget, self.refresh_button)
        UserRoleManagementDialog.setTabOrder(self.refresh_button, self.apply_button)
        UserRoleManagementDialog.setTabOrder(self.apply_button, self.username_edit)
        UserRoleManagementDialog.setTabOrder(self.username_edit, self.password_edit)
        UserRoleManagementDialog.setTabOrder(self.password_edit, self.retype_password_edit)
        UserRoleManagementDialog.setTabOrder(self.retype_password_edit, self.surname_edit)
        UserRoleManagementDialog.setTabOrder(self.surname_edit, self.firstname_edit)
        UserRoleManagementDialog.setTabOrder(self.firstname_edit, self.add_button)
        UserRoleManagementDialog.setTabOrder(self.add_button, self.update_button)
        UserRoleManagementDialog.setTabOrder(self.update_button, self.delete_button)
        UserRoleManagementDialog.setTabOrder(self.delete_button, self.phone_edit)
        UserRoleManagementDialog.setTabOrder(self.phone_edit, self.user_role_lwidget)
        UserRoleManagementDialog.setTabOrder(self.user_role_lwidget, self.position_cbox)
        UserRoleManagementDialog.setTabOrder(self.position_cbox, self.settings_button)
        UserRoleManagementDialog.setTabOrder(self.settings_button, self.email_edit)
        UserRoleManagementDialog.setTabOrder(self.email_edit, self.down_groups_button)
        UserRoleManagementDialog.setTabOrder(self.down_groups_button, self.up_groups_button)
        UserRoleManagementDialog.setTabOrder(self.up_groups_button, self.help_button)
        UserRoleManagementDialog.setTabOrder(self.help_button, self.member_lwidget)
        UserRoleManagementDialog.setTabOrder(self.member_lwidget, self.aimag_cbox)
        UserRoleManagementDialog.setTabOrder(self.aimag_cbox, self.aimag_lwidget)
        UserRoleManagementDialog.setTabOrder(self.aimag_lwidget, self.down_aimag_button)
        UserRoleManagementDialog.setTabOrder(self.down_aimag_button, self.up_aimag_button)
        UserRoleManagementDialog.setTabOrder(self.up_aimag_button, self.soum_cbox)
        UserRoleManagementDialog.setTabOrder(self.soum_cbox, self.soum_lwidget)
        UserRoleManagementDialog.setTabOrder(self.soum_lwidget, self.up_soum_button)
        UserRoleManagementDialog.setTabOrder(self.up_soum_button, self.down_soum_button)
        UserRoleManagementDialog.setTabOrder(self.down_soum_button, self.user_twidget)
        UserRoleManagementDialog.setTabOrder(self.user_twidget, self.position_twidget)
        UserRoleManagementDialog.setTabOrder(self.position_twidget, self.right_grud_twidget)
        UserRoleManagementDialog.setTabOrder(self.right_grud_twidget, self.load_default_settings_button)
        UserRoleManagementDialog.setTabOrder(self.load_default_settings_button, self.load_users_button)
        UserRoleManagementDialog.setTabOrder(self.load_users_button, self.load_position_button)
        UserRoleManagementDialog.setTabOrder(self.load_position_button, self.settings_right_grud_twidget)
        UserRoleManagementDialog.setTabOrder(self.settings_right_grud_twidget, self.settings_position_twidget)
        UserRoleManagementDialog.setTabOrder(self.settings_position_twidget, self.department_cbox)
        UserRoleManagementDialog.setTabOrder(self.department_cbox, self.get_mac_checkbox)
        UserRoleManagementDialog.setTabOrder(self.get_mac_checkbox, self.mac_address_edit)
        UserRoleManagementDialog.setTabOrder(self.mac_address_edit, self.organization_type_cbox)
        UserRoleManagementDialog.setTabOrder(self.organization_type_cbox, self.organization_cbox)
        UserRoleManagementDialog.setTabOrder(self.organization_cbox, self.register_edit)

    def retranslateUi(self, UserRoleManagementDialog):
        UserRoleManagementDialog.setWindowTitle(_translate("UserRoleManagementDialog", "User Role Management", None))
        self.label_9.setText(_translate("UserRoleManagementDialog", "User Role Management", None))
        self.close_button.setText(_translate("UserRoleManagementDialog", "Close", None))
        self.groupBox.setTitle(_translate("UserRoleManagementDialog", "User Roles", None))
        self.label.setText(_translate("UserRoleManagementDialog", "User Name", None))
        self.label_2.setText(_translate("UserRoleManagementDialog", "Password", None))
        self.label_3.setText(_translate("UserRoleManagementDialog", "Retype Password", None))
        self.label_5.setText(_translate("UserRoleManagementDialog", "Surname", None))
        self.label_6.setText(_translate("UserRoleManagementDialog", "First Name", None))
        self.label_15.setText(_translate("UserRoleManagementDialog", "Phone", None))
        self.label_18.setText(_translate("UserRoleManagementDialog", "Email", None))
        self.get_mac_checkbox.setText(_translate("UserRoleManagementDialog", "MAC Address(es)", None))
        self.label_11.setText(_translate("UserRoleManagementDialog", "Organization", None))
        self.label_10.setText(_translate("UserRoleManagementDialog", "Organization Type", None))
        self.label_17.setText(_translate("UserRoleManagementDialog", "Register", None))
        self.settings_button.setText(_translate("UserRoleManagementDialog", "User Settings", None))
        self.groupBox_3.setTitle(_translate("UserRoleManagementDialog", "Groups", None))
        self.label_12.setText(_translate("UserRoleManagementDialog", "Groups Available", None))
        self.label_13.setText(_translate("UserRoleManagementDialog", "Groups the user is a member of", None))
        self.groupBox_7.setTitle(_translate("UserRoleManagementDialog", "Spatial Restrictions", None))
        self.label_14.setText(_translate("UserRoleManagementDialog", "Aimag / Duureg", None))
        self.label_16.setText(_translate("UserRoleManagementDialog", "Soum", None))
        self.label_30.setText(_translate("UserRoleManagementDialog", "Granted Aimags / Duuregs", None))
        self.label_4.setText(_translate("UserRoleManagementDialog", "Granted Soums", None))
        self.label_19.setText(_translate("UserRoleManagementDialog", "Department", None))
        self.label_7.setText(_translate("UserRoleManagementDialog", "Position", None))
        self.delete_button.setText(_translate("UserRoleManagementDialog", "Delete", None))
        self.update_button.setText(_translate("UserRoleManagementDialog", "Update", None))
        self.add_button.setText(_translate("UserRoleManagementDialog", "Add", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.user_register_tab), _translate("UserRoleManagementDialog", "User Register", None))
        item = self.user_twidget.horizontalHeaderItem(0)
        item.setText(_translate("UserRoleManagementDialog", "Employeer", None))
        item = self.position_twidget.horizontalHeaderItem(0)
        item.setText(_translate("UserRoleManagementDialog", "Position", None))
        item = self.right_grud_twidget.horizontalHeaderItem(0)
        item.setText(_translate("UserRoleManagementDialog", "Rigth type", None))
        item = self.right_grud_twidget.horizontalHeaderItem(1)
        item.setText(_translate("UserRoleManagementDialog", "View", None))
        item = self.right_grud_twidget.horizontalHeaderItem(2)
        item.setText(_translate("UserRoleManagementDialog", "Add", None))
        item = self.right_grud_twidget.horizontalHeaderItem(3)
        item.setText(_translate("UserRoleManagementDialog", "Delete", None))
        item = self.right_grud_twidget.horizontalHeaderItem(4)
        item.setText(_translate("UserRoleManagementDialog", "Edit", None))
        self.groupBox_2.setTitle(_translate("UserRoleManagementDialog", "Employeer Details", None))
        self.load_default_settings_button.setText(_translate("UserRoleManagementDialog", "Load Default Settings", None))
        self.load_users_button.setText(_translate("UserRoleManagementDialog", "Load All Users", None))
        self.load_position_button.setText(_translate("UserRoleManagementDialog", "Load All Position", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.user_management_tab), _translate("UserRoleManagementDialog", "User Management", None))
        item = self.settings_right_grud_twidget.horizontalHeaderItem(0)
        item.setText(_translate("UserRoleManagementDialog", "Right Type English", None))
        item = self.settings_right_grud_twidget.horizontalHeaderItem(1)
        item.setText(_translate("UserRoleManagementDialog", "Right Type Mongolia", None))
        item = self.settings_right_grud_twidget.horizontalHeaderItem(2)
        item.setText(_translate("UserRoleManagementDialog", "View", None))
        item = self.settings_right_grud_twidget.horizontalHeaderItem(3)
        item.setText(_translate("UserRoleManagementDialog", "Add", None))
        item = self.settings_right_grud_twidget.horizontalHeaderItem(4)
        item.setText(_translate("UserRoleManagementDialog", "Delete", None))
        item = self.settings_right_grud_twidget.horizontalHeaderItem(5)
        item.setText(_translate("UserRoleManagementDialog", "Edit", None))
        item = self.settings_position_twidget.horizontalHeaderItem(0)
        item.setText(_translate("UserRoleManagementDialog", "Position", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UserRoleManagementDialog", "Right Settings", None))
        item = self.department_twidget.horizontalHeaderItem(0)
        item.setText(_translate("UserRoleManagementDialog", "id", None))
        item = self.department_twidget.horizontalHeaderItem(1)
        item.setText(_translate("UserRoleManagementDialog", "name", None))
        item = self.department_twidget.horizontalHeaderItem(2)
        item.setText(_translate("UserRoleManagementDialog", "address", None))
        item = self.department_twidget.horizontalHeaderItem(3)
        item.setText(_translate("UserRoleManagementDialog", "phone", None))
        item = self.department_twidget.horizontalHeaderItem(4)
        item.setText(_translate("UserRoleManagementDialog", "fax", None))
        item = self.department_twidget.horizontalHeaderItem(5)
        item.setText(_translate("UserRoleManagementDialog", "bank", None))
        item = self.department_twidget.horizontalHeaderItem(6)
        item.setText(_translate("UserRoleManagementDialog", "account", None))
        item = self.department_twidget.horizontalHeaderItem(7)
        item.setText(_translate("UserRoleManagementDialog", "email", None))
        item = self.department_twidget.horizontalHeaderItem(8)
        item.setText(_translate("UserRoleManagementDialog", "web site", None))
        item = self.department_twidget.horizontalHeaderItem(9)
        item.setText(_translate("UserRoleManagementDialog", "head surname", None))
        item = self.department_twidget.horizontalHeaderItem(10)
        item.setText(_translate("UserRoleManagementDialog", "head firstname", None))
        item = self.department_twidget.horizontalHeaderItem(11)
        item.setText(_translate("UserRoleManagementDialog", "organization", None))
        item = self.department_twidget.horizontalHeaderItem(12)
        item.setText(_translate("UserRoleManagementDialog", "aimag", None))
        item = self.department_twidget.horizontalHeaderItem(13)
        item.setText(_translate("UserRoleManagementDialog", "soum", None))
        self.department_add_button.setText(_translate("UserRoleManagementDialog", "add", None))
        self.department_update_button.setText(_translate("UserRoleManagementDialog", "update", None))
        self.department_delete_button.setText(_translate("UserRoleManagementDialog", "delete", None))
        self.department_load_chbox.setText(_translate("UserRoleManagementDialog", "Load and find", None))
        self.label_8.setText(_translate("UserRoleManagementDialog", "Aimag", None))
        self.label_20.setText(_translate("UserRoleManagementDialog", "Soum", None))
        self.label_21.setText(_translate("UserRoleManagementDialog", "Address", None))
        self.label_22.setText(_translate("UserRoleManagementDialog", "Name", None))
        self.label_23.setText(_translate("UserRoleManagementDialog", "Bank(Төрийн сан банк)", None))
        self.label_24.setText(_translate("UserRoleManagementDialog", "Phone", None))
        self.label_25.setText(_translate("UserRoleManagementDialog", "Fax", None))
        self.label_26.setText(_translate("UserRoleManagementDialog", "email", None))
        self.label_27.setText(_translate("UserRoleManagementDialog", "Account", None))
        self.label_28.setText(_translate("UserRoleManagementDialog", "web site", None))
        self.label_29.setText(_translate("UserRoleManagementDialog", "Head surname", None))
        self.label_31.setText(_translate("UserRoleManagementDialog", "Head firstname", None))
        self.label_32.setText(_translate("UserRoleManagementDialog", "Oragnization", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("UserRoleManagementDialog", "Department", None))
        self.refresh_button.setText(_translate("UserRoleManagementDialog", "Refresh", None))
        self.apply_button.setText(_translate("UserRoleManagementDialog", "Save", None))
        self.status_label.setText(_translate("UserRoleManagementDialog", "Messages", None))

import resources_rc
